# Supabase Configuration
project_id = "wehouse"

[functions.provider-password-recovery]
verify_jwt = true

[functions.private-call-ice]
verify_jwt = true

[functions.turn-credentials]
verify_jwt = true
