import { supabase } from './client';
import type { Profile } from '@/types';
import { compressImageFile } from './utils';

export type SafeProfileUpdates = Pick<Partial<Profile>,
  | 'username' | 'full_name' | 'avatar_url' | 'bio' | 'phone' | 'occupation'
  | 'gender' | 'is_student' | 'school' | 'state' | 'local_government'
  | 'city' | 'area' | 'profile_complete' | 'country'
  | 'precise_latitude' | 'precise_longitude' | 'precise_address' | 'precise_location_accuracy_m'
  | 'worker_occupation' | 'worker_skills' | 'worker_price' | 'worker_bio' | 'worker_experience'
>;
export type SafePrivacyUpdates = Pick<Partial<Profile>, 'privacy_profile_visible'|'privacy_search_visible'|'privacy_activity_visible'|'privacy_email_visible'|'privacy_phone_visible'>;
type ProfileError = { message: string };
type PublicAgent = Pick<Profile, 'user_id'|'username'|'avatar_url'|'role'>;
export async function getProfile(userId:string){const{data,error}=await supabase.from('profiles').select('*').eq('user_id',userId).maybeSingle();return{profile:data as Profile|null,error};}
export async function getProfileByAuthId(authId:string,email?:string){void email;const{data,error}=await supabase.from('profiles').select('*').eq('auth_id',authId).maybeSingle();return{profile:data as Profile|null,error};}
export async function getPublicAgentInfo(authId:string){const{data,error}=await supabase.from('profiles').select('user_id, username, avatar_url, role').eq('auth_id',authId).maybeSingle();return{agent:data as PublicAgent|null,error};}
export async function getPublicAgentByUserId(userId:string){const{data,error}=await supabase.from('profiles').select('user_id, username, avatar_url, role, phone, privacy_phone_visible').eq('user_id',userId).maybeSingle();const agent=data?{user_id:data.user_id,username:data.username,avatar_url:data.avatar_url,role:data.role,phone:data.privacy_phone_visible?data.phone:null}:null;return{agent,error};}
export async function getProfileByEmail(email:string){const{data,error}=await supabase.from('profiles').select('*').eq('email',email).maybeSingle();return{profile:data as Profile|null,error};}
export async function linkProfileToAuth(userId:string,authId:string){void userId;void authId;return{profile:null as Profile|null,error:{message:'This account needs secure identity repair. Contact WeHouse Support.'}};}
export async function createProfile(authId:string,email:string,role?:'user'|'worker'|'property_partner'):Promise<{profile:Profile|null;error:ProfileError|null}>;
export async function createProfile(userId:string,email:string,username:string,authId:string):Promise<{profile:Profile|null;error:ProfileError|null}>;
export async function createProfile(a:string,b:string,c?:string,d?:string){void a;const legacy=c!==undefined&&d!==undefined;const requestedRole=!legacy&&c;const role:'user'|'worker'|'property_partner'=requestedRole==='worker'||requestedRole==='property_partner'?requestedRole:'user';const{data,error}=await supabase.rpc('create_my_profile',{p_email:b,p_role:role});if(error||!data)return{profile:null,error};let profile=data as Profile;if(legacy&&c){const r=await updateProfile(profile.user_id,{username:c});if(r.error)return{profile:null,error:r.error};profile=r.profile||profile;}return{profile,error:null};}
export async function uploadAvatar(file:File,userId:string){void userId;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return{url:null,error:{message:'Choose a JPG, PNG or WebP image'}};if(file.size>10*1024*1024)return{url:null,error:{message:'Profile photo must be under 10MB'}};try{const{data:{user}}=await supabase.auth.getUser();if(!user)return{url:null,error:{message:'Authentication required'}};const compressed=await compressImageFile(file,1200,0.9,1.5*1024*1024);const fileName=`${user.id}/avatar-${Date.now()}.jpg`;const{error}=await supabase.storage.from('avatars').upload(fileName,compressed,{contentType:'image/jpeg',upsert:true});if(error)return{url:null,error};const{data}=supabase.storage.from('avatars').getPublicUrl(fileName);return{url:data.publicUrl,error:null};}catch(err:unknown){return{url:null,error:{message:err instanceof Error?err.message:'Upload failed'}};}}
const RESERVED_USERNAMES=['admin','creator','support','system','api','wehouse','mod','moderator','owner','staff','help','info','null','undefined'];
export function validateUsername(username:string){const t=username.trim().toLowerCase();if(!t)return{valid:false,error:'Username is required'};if(t.length<3)return{valid:false,error:'Minimum 3 characters'};if(t.length>20)return{valid:false,error:'Maximum 20 characters'};if(!/^[a-z0-9_]+$/.test(t))return{valid:false,error:'Letters, numbers, underscores only'};if(RESERVED_USERNAMES.includes(t))return{valid:false,error:'This username is reserved'};return{valid:true};}
export async function checkUsernameAvailable(username:string,currentUserId?:string){void currentUserId;const t=username.trim().toLowerCase();const{data,error}=await supabase.rpc('is_username_available',{p_username:t});if(error)return{available:false,taken:false,error};const available=data===true;return{available,taken:!available,error:null};}
export async function removeAvatar(userId:string){void userId;const{data,error}=await supabase.rpc('update_my_profile',{p_updates:{avatar_url:null}});return{profile:data as Profile|null,error};}
export async function updateProfile(userId:string,updates:SafeProfileUpdates){void userId;const normalized:Record<string,unknown>={...updates};const hasPrecise=['precise_latitude','precise_longitude','precise_address','precise_location_accuracy_m'].some(key=>key in normalized);const latitude=normalized.precise_latitude as number|null|undefined,longitude=normalized.precise_longitude as number|null|undefined,address=normalized.precise_address as string|null|undefined,accuracy=normalized.precise_location_accuracy_m as number|null|undefined;delete normalized.precise_latitude;delete normalized.precise_longitude;delete normalized.precise_address;delete normalized.precise_location_accuracy_m;if('city'in normalized&&!('local_government'in normalized))normalized.local_government=normalized.city;const{data,error}=await supabase.rpc('update_my_profile',{p_updates:normalized});if(error||!hasPrecise)return{profile:data as Profile|null,error};const location=await supabase.rpc('update_my_precise_location',{p_latitude:latitude??null,p_longitude:longitude??null,p_address:address??null,p_accuracy_m:accuracy??null});return{profile:location.data as Profile|null,error:location.error};}
export async function updatePrivacySettings(userId:string,settings:SafePrivacyUpdates){void userId;const{data,error}=await supabase.rpc('update_my_privacy',{p_updates:settings});return{profile:data as Profile|null,error};}
