import { supabase } from './client';

export function parseDeviceInfo(ua:string=typeof navigator!=='undefined'?navigator.userAgent:''){let device='Desktop',os='Unknown',browser='Unknown';if(/Android/.test(ua)){const m=ua.match(/Android\s([\d.]+)/);os=m?`Android ${m[1]}`:'Android';const d=ua.match(/;\s*([^)]+)\s*Build/);device=d?d[1].trim():'Android Device'}else if(/iPhone/.test(ua)){os='iOS';device='iPhone'}else if(/iPad/.test(ua)){os='iPadOS';device='iPad'}else if(/Windows NT/.test(ua))os='Windows';else if(/Mac OS/.test(ua))os='macOS';else if(/Linux/.test(ua))os='Linux';if(/Chrome/.test(ua)&&!/Edg|OPR/.test(ua)){const m=ua.match(/Chrome\/([\d.]+)/);browser=m?`Chrome ${m[1].split('.')[0]}`:'Chrome'}else if(/Edg/.test(ua))browser='Edge';else if(/Firefox/.test(ua))browser='Firefox';else if(/Safari/.test(ua)&&!/Chrome/.test(ua))browser='Safari';else if(/OPR/.test(ua))browser='Opera';return{device,os,browser}}
export async function trackSession(userId:string,authId:string){const{device,os,browser}=parseDeviceInfo();const{error}=await supabase.from('user_activity').insert({user_id:userId,auth_id:authId,action_type:'session_start',details:{device,os,browser,source:'login'}});return{error}}
export async function endSession(userId:string,authId:string){const{error}=await supabase.from('user_activity').insert({user_id:userId,auth_id:authId,action_type:'session_end',details:{source:'logout'}});return{error}}
export async function getSessionHistory(userId:string,limit=20){const{data,error}=await supabase.from('user_activity').select('*').eq('user_id',userId).or('action_type.eq.session_start,action_type.eq.session_end').order('created_at',{ascending:false}).limit(limit);return{sessions:data||[],error}}
const SESSION_STORAGE_KEY='wh_session_id';
export function getStoredSessionId(){try{return localStorage.getItem(SESSION_STORAGE_KEY)}catch{return null}}
export function clearStoredSessionId(){try{localStorage.removeItem(SESSION_STORAGE_KEY)}catch{}}
export async function getUserSessionState(sessionId:string,userId:string,authId:string):Promise<{state:'active'|'inactive'|'missing'|'foreign'|'error';error:any}>{const{data,error}=await supabase.from('user_sessions').select('id,user_id,auth_id,is_active,is_current').eq('id',sessionId).maybeSingle();if(error)return{state:'error',error};if(!data)return{state:'missing',error:null};if(data.user_id!==userId||data.auth_id!==authId)return{state:'foreign',error:null};return{state:data.is_active?'active':'inactive',error:null}}
export async function createUserSession(userId:string,authId:string):Promise<string|null>{const existing=getStoredSessionId();if(existing){const{state}=await getUserSessionState(existing,userId,authId);if(state==='active'){await updateSessionLastSeen(existing);return existing}if(state==='foreign'||state==='missing')clearStoredSessionId();if(state==='inactive')return null}const{device,os,browser}=parseDeviceInfo();const{data,error}=await supabase.from('user_sessions').insert({user_id:userId,auth_id:authId,device,os,browser,is_active:true,is_current:true,last_seen:new Date().toISOString()}).select('id').maybeSingle();if(error||!data){console.error('[Session] Failed to create session:',error?.message);return null}localStorage.setItem(SESSION_STORAGE_KEY,data.id);return data.id}
export async function deactivateUserSession(sessionId:string){await supabase.from('user_sessions').update({is_active:false,is_current:false,logout_time:new Date().toISOString()}).eq('id',sessionId);if(getStoredSessionId()===sessionId)clearStoredSessionId()}
export async function isSessionActive(sessionId:string){const{data}=await supabase.from('user_sessions').select('is_active').eq('id',sessionId).maybeSingle();return Boolean(data?.is_active)}
export async function updateSessionLastSeen(sessionId:string){await supabase.from('user_sessions').update({last_seen:new Date().toISOString()}).eq('id',sessionId).eq('is_active',true)}
