import { supabase } from './client';
import { compressImageFile } from './utils';

export async function createBookingRequest(workerId:string,serviceType:string,description:string,address:string,scheduledDate:string,customerMessage?:string){const{data,error}=await supabase.rpc('create_booking_request',{p_worker_id:workerId,p_service_type:serviceType,p_description:description,p_address:address,p_scheduled_date:scheduledDate,p_customer_message:customerMessage||null});return{booking:error?null:data||null,error}}
export async function getMyBookingConversations(userId:string){const{data,error}=await supabase.rpc('get_my_booking_conversations',{p_user_id:userId});return{conversations:(data||[]).map((row:any)=>({conversation_id:row.conversation_id,booking_id:row.booking_id,booking_code:row.booking_code,booking_status:row.booking_status,service_type:row.service_type,negotiated_amount:row.negotiated_amount||0,other_person_name:row.other_person_name||'Unknown',other_person_username:'',updated_at:row.updated_at,unread_count:row.unread_count||0})),error}}

async function signChatPath(path:string){if(!path||path.startsWith('http'))return path;const{data}=await supabase.storage.from('chat-files').createSignedUrl(path,3600);return data?.signedUrl||path}
export async function getBookingMessages(conversationId:string){const{data,error}=await supabase.rpc('get_booking_messages',{p_conversation_id:conversationId});if(error||!data)return{messages:data||[],error};const messages=await Promise.all((data as any[]).map(async msg=>{const raw=String(msg.content||''),legacyFile=/\.(jpg|jpeg|png|gif|webp|pdf|mp3|wav|webm|m4a|mp4)(\?.*)?$/i.test(raw)&&!raw.startsWith('http')?await signChatPath(raw):raw;const attachments=await Promise.all(((msg.attachments||[]) as string[]).map(signChatPath));return{...msg,content:legacyFile,attachments}}));return{messages,error}}
export async function sendBookingMessage(conversationId:string,content:string,attachments:string[]=[]){const{data,error}=await supabase.rpc('send_booking_message_v2',{p_conversation_id:conversationId,p_content:content,p_attachments:attachments});return{messageId:data,error}}

export async function uploadBookingChatAttachment(file:File,conversationId:string){try{let upload:Blob|File=file;let contentType=file.type||'application/octet-stream';let extension=(file.name.split('.').pop()||'bin').replace(/[^a-zA-Z0-9]/g,'').toLowerCase()||'bin';if(file.type.startsWith('image/')){upload=await compressImageFile(file,1920,.85);contentType='image/jpeg';extension='jpg'}const safeBase=file.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,48)||'file';const path=`${conversationId}/${Date.now()}-${Math.random().toString(36).slice(2)}-${safeBase}.${extension}`;const{error}=await supabase.storage.from('chat-files').upload(path,upload,{contentType,upsert:false});if(error)return{path:null,signedUrl:null,error};const{data:signed,error:signedError}=await supabase.storage.from('chat-files').createSignedUrl(path,3600);return{path,signedUrl:signed?.signedUrl||null,error:signedError}}catch(e:any){return{path:null,signedUrl:null,error:{message:e?.message||'Upload failed'} as any}}}
export async function uploadBookingChatImage(file:File,conversationId:string){return uploadBookingChatAttachment(file,conversationId)}
export async function sendBookingImageMessage(conversationId:string,imagePath:string){return sendBookingMessage(conversationId,'',[imagePath])}

export async function workerAcceptBooking(bookingId:string,negotiatedAmount:number,scheduledDate?:string){const{data,error}=await supabase.rpc('worker_accept_booking',{p_booking_id:bookingId,p_negotiated_amount:negotiatedAmount,p_scheduled_date:scheduledDate||null});return{success:data,error}}
export async function createWorkerBookingPayment(bookingId:string){const{data,error}=await supabase.rpc('create_worker_booking_payment',{p_booking_id:bookingId});return{result:data,error}}
export async function workerStartJob(bookingId:string){const{data,error}=await supabase.rpc('worker_start_job',{p_booking_id:bookingId});return{success:data,error}}
export async function workerMarkComplete(bookingId:string){const{data,error}=await supabase.rpc('worker_mark_complete',{p_booking_id:bookingId});return{success:data,error}}
export async function customerConfirmCompletion(bookingId:string){const{data,error}=await supabase.rpc('customer_confirm_completion',{p_booking_id:bookingId});return{success:data,error}}
export async function customerRaiseDispute(bookingId:string,reason:string){const{data,error}=await supabase.rpc('customer_raise_dispute',{p_booking_id:bookingId,p_reason:reason});return{success:data,error}}
export async function cancelBooking(bookingId:string,reason:string){const{data,error}=await supabase.rpc('cancel_booking',{p_booking_id:bookingId,p_reason:reason});return{success:data,error}}
export async function getBookingDetails(bookingId:string){const{data:booking,error}=await supabase.from('worker_bookings').select('id,booking_code,status,service_type,description,address,negotiated_amount,agreed_amount,scheduled_date,created_at,updated_at,user_id,worker_id').eq('id',bookingId).single();if(error||!booking)return{booking:null,error};const[{data:customer},{data:worker}]=await Promise.all([supabase.from('profiles').select('user_id,username,full_name,avatar_url,phone').eq('user_id',booking.user_id).single(),supabase.from('profiles').select('user_id,username,full_name,avatar_url').eq('user_id',booking.worker_id).single()]);return{booking:{...booking,user_name:customer?.full_name||customer?.username||'Customer',customer_username:customer?.username||'',customer_phone:customer?.phone||'',worker_name:worker?.full_name||worker?.username||'Worker'},error:null}}
export async function getWorkerBookings(workerId:string){const{data,error}=await supabase.from('worker_bookings').select('*, profiles!worker_bookings_user_id_fkey(full_name, phone)').eq('worker_id',workerId).order('created_at',{ascending:false});return{bookings:data||[],error}}
export async function deleteBooking(bookingId:string,userId:string){const{data:booking,error:fetchErr}=await supabase.from('worker_bookings').select('user_id,worker_id').eq('id',bookingId).single();if(fetchErr)return{success:false,error:fetchErr};if(booking.user_id!==userId&&booking.worker_id!==userId)return{success:false,error:{message:'Not authorized to cancel this booking'} as any};const{error}=await supabase.from('worker_bookings').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',bookingId);return{success:!error,error}}
export async function getUserActiveBookings(userId:string){const{data,error}=await supabase.from('worker_bookings').select('id,worker_id,status').eq('user_id',userId).not('status','in','(cancelled,refunded,approved_released)');return{bookings:data||[],error}}

export const BOOKING_STATUS_LABELS:Record<string,{label:string;color:string;description:string}>={booking_requested:{label:'Booking Requested',color:'bg-amber-500/10 text-amber-400',description:'Waiting for the Worker to respond'},negotiating:{label:'Negotiating',color:'bg-blue-500/10 text-blue-400',description:'Discussing the job, schedule and price'},waiting_payment:{label:'Waiting for Payment',color:'bg-purple-500/10 text-purple-400',description:'Worker accepted; customer needs to pay'},confirmed:{label:'Confirmed',color:'bg-emerald-500/10 text-emerald-400',description:'Payment received; ready to start'},in_progress:{label:'In Progress',color:'bg-indigo-500/10 text-indigo-400',description:'The job is underway'},completed_pending_approval:{label:'Pending Approval',color:'bg-orange-500/10 text-orange-400',description:'Worker marked complete; customer confirmation is pending'},approved_released:{label:'Completed',color:'bg-emerald-500/10 text-emerald-400',description:'Job completed and payment released'},disputed:{label:'Disputed',color:'bg-red-500/10 text-red-400',description:'WeHouse is reviewing the dispute'},cancelled:{label:'Cancelled',color:'bg-gray-500/10 text-gray-400',description:'Booking cancelled'},refunded:{label:'Refunded',color:'bg-gray-500/10 text-gray-400',description:'Payment refunded'}};
