import { useState,useEffect,useCallback,useRef } from 'react';
import { supabase,getProfileByAuthId,createProfile,trackSession,endSession,createUserSession,deactivateUserSession,getStoredSessionId,clearStoredSessionId,getUserSessionState,updateSessionLastSeen } from '@/lib/supabase';
import type { Profile,Page } from '@/types';

interface AuthState{page:Page;profile:Profile|null;isLoading:boolean;error:string;kickedOut?:boolean}
type PublicRole='user'|'worker'|'property_partner';
type LandingMode='all'|'operational'|false;
const PUBLIC_ROLES=['user','worker','property_partner'] as const;

async function wipeOnLogout(){try{const keys:string[]=[];for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k&&(k.includes('sb-')||k.includes('supabase')||k.startsWith('wh_')))keys.push(k)}keys.forEach(k=>localStorage.removeItem(k));sessionStorage.clear()}catch{}}
function validPublicRole(value:unknown):PublicRole|undefined{return typeof value==='string'&&(PUBLIC_ROLES as readonly string[]).includes(value)?value as PublicRole:undefined}
function landingForProfile(p:Profile){if(p.role==='creator')return'creator';if(p.role==='admin')return'admin';if(p.role==='staff')return'staff_dashboard';if(p.role==='worker')return'worker_dashboard';if(p.role==='property_partner')return'property_partner';return'home'}
function routeToLanding(p:Profile,mode:LandingMode){if(!mode||(mode==='operational'&&p.role==='user'))return;const page=landingForProfile(p);try{localStorage.setItem('wh_navpage',page);window.history.replaceState({page},'',`#${page}`);window.dispatchEvent(new PopStateEvent('popstate',{state:{page}}))}catch{}}

const ADMIN_ROLES=new Set(['creator','admin']);export const hasAdminAccess=(r:string)=>ADMIN_ROLES.has(r);export const isStaff=(r:string)=>r==='staff';export const canCreateListings=(r:string)=>['staff','admin','creator'].includes(r);export const isAdmin=(r:string)=>r==='admin';export const isCreator=(r:string)=>r==='creator';export const canSendAnnouncements=(r:string)=>isCreator(r)||isAdmin(r);export function getScope(r:string):'global'|'local'|null{return isCreator(r)||isAdmin(r)?'global':r==='staff'?'local':null}export const isGlobal=(r:string)=>getScope(r)==='global';export function canModifyRole(m:string,t:string){if(isCreator(m))return!isCreator(t);if(isAdmin(m))return!isCreator(t)&&!isAdmin(t);return false}export function validateRoleTransition(m:string,c:string,n:string):{allowed:boolean;reason?:string}{if(isCreator(c))return{allowed:false,reason:'Creator role cannot be modified'};if(isCreator(n))return{allowed:false,reason:'Creator role cannot be assigned'};if(c==='worker'||n==='worker')return{allowed:false,reason:'Worker role is managed through worker registration.'};if(c==='property_partner'||n==='property_partner')return{allowed:false,reason:'Property Partner role is managed through partner registration.'};if(isCreator(m)&&['user','staff','admin'].includes(c)&&['user','staff','admin'].includes(n))return{allowed:true};if(isAdmin(m)&&['user','staff'].includes(c)&&['user','staff'].includes(n))return{allowed:true};return{allowed:false,reason:'You cannot make that role change'}}
async function setting(key:string){try{const{data}=await supabase.from('platform_settings').select('value').eq('key',key).maybeSingle();return data?.value==null?null:String(data.value)}catch{return null}}
async function maintenance(){const v=await setting('maintenance_mode');return v==='true'||v==='on'||v==='1'}
async function registrationClosed(){const v=await setting('registration_open');return v==='false'||v==='closed'||v==='0'}

export function useAuth(){
 const[state,setState]=useState<AuthState>({page:'loading',profile:null,isLoading:true,error:'',kickedOut:false});
 const explicitSignOutRef=useRef(false),aliveRef=useRef(true),initializingRef=useRef(true),loadVersionRef=useRef(0),kickoutBusyRef=useRef(false);
 const determinePage=useCallback((p:Profile|null):Page=>{if(!p)return'login';if(!p.profile_complete&&p.role==='worker')return'worker_setup';if(!p.profile_complete)return'setup';if(p.role==='worker')return'worker_dashboard';if(isCreator(p.role))return'creator';if(p.role==='admin')return'admin';if(p.role==='staff')return'staff_dashboard';if(p.role==='property_partner')return'property_partner';return'dashboard'},[]);

 const forceSignedOut=useCallback(async(error='',kickedOut=false)=>{loadVersionRef.current++;explicitSignOutRef.current=true;try{await supabase.auth.signOut({scope:'local'})}catch{}await wipeOnLogout();if(aliveRef.current)setState({page:'login',profile:null,isLoading:false,error,kickedOut})},[]);
 const allowEntry=useCallback(async(p:Profile)=>{if(p.banned||p.suspended||p.deleted){await forceSignedOut(p.banned?'Your account has been permanently banned. Contact support for assistance.':p.suspended?'Your account has been suspended. Contact support for assistance.':'This account has been deleted.');return false}if(!isCreator(p.role)&&!(p as any).maintenance_exempt&&await maintenance()){await forceSignedOut('WeHouse is currently under maintenance. Please check back later.');return false}return true},[forceSignedOut]);

 const ensurePartnerRecord=useCallback(async(p:Profile)=>{if(p.role!=='property_partner')return;const{data,error}=await supabase.from('property_partners').select('id').eq('profile_id',p.user_id).limit(1);if(error||data?.length)return;await supabase.from('property_partners').insert({profile_id:p.user_id,partner_code:`WHP-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,status:'pending_verification'})},[]);

 const ensureSession=useCallback(async(p:Profile)=>{const existing=getStoredSessionId();if(existing){const current=await getUserSessionState(existing,p.user_id,p.auth_id);if(current.state==='active'){await updateSessionLastSeen(existing);return true}if(current.state==='inactive'){if(!kickoutBusyRef.current){kickoutBusyRef.current=true;await forceSignedOut('',true);kickoutBusyRef.current=false}return false}if(current.state==='foreign'||current.state==='missing')clearStoredSessionId();if(current.state==='error')return true}
   const sid=await createUserSession(p.user_id,p.auth_id);if(sid){void trackSession(p.user_id,p.auth_id);return true}return false},[forceSignedOut]);

 const loadProfile=useCallback(async(authId:string,options:{preferredRole?:PublicRole;preserveOnFailure?:boolean;landing?:LandingMode}={})=>{const version=++loadVersionRef.current;const preserve=Boolean(options.preserveOnFailure);try{const{data:userResult,error:userError}=await supabase.auth.getUser();if(userError)throw userError;const user=userResult.user;if(!user||user.id!==authId)throw new Error('Authenticated session could not be verified.');const{profile:existing,error:profileError}=await getProfileByAuthId(authId);if(profileError)throw profileError;let profile=existing;
   if(!profile){const role=options.preferredRole||validPublicRole(user.user_metadata?.signup_role);if(!role){if(await maintenance()){await forceSignedOut('WeHouse is currently under maintenance. Please check back later.');return}if(await registrationClosed()){await forceSignedOut('New registrations are currently closed.');return}if(version===loadVersionRef.current&&aliveRef.current)setState({page:'login',profile:null,isLoading:false,error:'',kickedOut:false});return}if(await maintenance()){await forceSignedOut('WeHouse is currently under maintenance. Please check back later.');return}if(await registrationClosed()){await forceSignedOut('New registrations are currently closed.');return}const created=await createProfile(authId,user.email||'',role);if(created.error||!created.profile)throw created.error||new Error('Could not create account');profile=created.profile;await ensurePartnerRecord(profile)}
   if(!await allowEntry(profile))return;if(!await ensureSession(profile))return;if(version!==loadVersionRef.current||!aliveRef.current)return;routeToLanding(profile,options.landing||false);setState({profile,page:determinePage(profile),isLoading:false,error:'',kickedOut:false})
  }catch(e:any){if(version!==loadVersionRef.current||!aliveRef.current)return;if(preserve)setState(s=>s.profile?{...s,isLoading:false}:{...s,isLoading:false,error:'Connection interrupted. Your session is still being restored.'});else setState({page:'login',profile:null,isLoading:false,error:e?.message||'We could not complete sign in. Please try again.',kickedOut:false})}},[allowEntry,determinePage,ensurePartnerRecord,ensureSession,forceSignedOut]);

 useEffect(()=>{aliveRef.current=true;let alive=true;async function restore(){try{const{data,error}=await supabase.auth.getSession();if(error)throw error;if(!alive)return;if(data.session?.user)await loadProfile(data.session.user.id,{landing:'operational'});else setState({page:'login',profile:null,isLoading:false,error:'',kickedOut:false})}catch(e:any){if(alive)setState({page:'login',profile:null,isLoading:false,error:e?.message||'Unable to restore your session. Please sign in again.',kickedOut:false})}finally{initializingRef.current=false}}void restore();
   const{data:listener}=supabase.auth.onAuthStateChange((event,session)=>{if(!alive)return;if(event==='INITIAL_SESSION')return;if(event==='SIGNED_IN'&&initializingRef.current)return;if(['SIGNED_IN','TOKEN_REFRESHED','USER_UPDATED','PASSWORD_RECOVERY'].includes(event)&&session?.user){void loadProfile(session.user.id,{preserveOnFailure:event==='TOKEN_REFRESHED'||event==='USER_UPDATED',landing:event==='SIGNED_IN'?'all':false});return}if(event==='SIGNED_OUT'){if(explicitSignOutRef.current){explicitSignOutRef.current=false;return}loadVersionRef.current++;void wipeOnLogout().then(()=>{if(alive)setState({page:'login',profile:null,isLoading:false,error:'',kickedOut:false})})}});
   const refresh=()=>{if(document.visibilityState==='hidden'&&!navigator.onLine)return;void supabase.auth.getSession().then(({data})=>{if(data.session?.user)void loadProfile(data.session.user.id,{preserveOnFailure:true})}).catch(()=>{})};const visible=()=>{if(document.visibilityState==='visible')refresh()};window.addEventListener('online',refresh);document.addEventListener('visibilitychange',visible);return()=>{alive=false;aliveRef.current=false;listener.subscription.unsubscribe();window.removeEventListener('online',refresh);document.removeEventListener('visibilitychange',visible)}},[loadProfile]);

 const handleLoginSuccess=useCallback(async(authId:string,_email:string,role?:PublicRole)=>{setState(s=>({...s,isLoading:true,error:''}));await loadProfile(authId,{preferredRole:role,landing:'all'})},[loadProfile]);
 const handleSetupComplete=useCallback((p:Profile)=>{routeToLanding(p,'all');setState({profile:p,page:determinePage(p),isLoading:false,error:'',kickedOut:false})},[determinePage]);
 const logout=useCallback(async()=>{loadVersionRef.current++;const userId=state.profile?.user_id,authId=state.profile?.auth_id,sid=getStoredSessionId();if(sid)await deactivateUserSession(sid).catch(()=>{});if(userId&&authId)await endSession(userId,authId).catch(()=>{});explicitSignOutRef.current=true;try{await supabase.auth.signOut({scope:'local'})}catch{}await wipeOnLogout();setState({page:'login',profile:null,isLoading:false,error:'',kickedOut:false})},[state.profile]);

 useEffect(()=>{const p=state.profile;if(!p)return;let cancelled=false,running=false;async function heartbeat(){if(cancelled||running)return;if(document.visibilityState==='hidden'&&!navigator.onLine)return;running=true;try{await ensureSession(p)}finally{running=false}}void heartbeat();const timer=window.setInterval(()=>void heartbeat(),30000);const visible=()=>{if(document.visibilityState==='visible')void heartbeat()};window.addEventListener('online',heartbeat);document.addEventListener('visibilitychange',visible);return()=>{cancelled=true;window.clearInterval(timer);window.removeEventListener('online',heartbeat);document.removeEventListener('visibilitychange',visible)}},[state.profile?.user_id,state.profile?.auth_id,ensureSession]);

 const clearError=useCallback(()=>setState(s=>({...s,error:''})),[]);return{...state,handleLoginSuccess,handleSetupComplete,logout,clearError,kickedOut:state.kickedOut}
}
