export type NavPage =
  // Customer navigation
  | 'home'
  | 'search'
  | 'saved'
  | 'messages'
  | 'profile'
  | 'roommate'
  | 'activity'
  | 'detail'
  | 'chat'
  | 'profile_edit'
  | 'account'
  | 'privacy'
  | 'security'
  | 'hotels'
  | 'hotel_detail'
  | 'hotel_booking'
  | 'hotel_reservation'
  | 'worker_discovery'
  | 'worker_categories'
  | 'my_bookings'
  | 'my_reservations'
  // Canonical role workspaces
  | 'creator'
  | 'analytics'
  | 'admin'
  | 'staff_dashboard'
  | 'worker_dashboard'
  | 'worker_setup'
  | 'worker_verification'
  | 'wallet'
  | 'property_partner'
  | 'new_listing'
  // Public pages
  | 'privacy_policy'
  | 'terms_of_service';
