export type NavPage =
  | 'home'
  | 'search'
  | 'saved'
  | 'roommate'
  | 'profile'
  | 'detail'
  | 'creator'
  | 'chat'
  | 'profile_edit'
  | 'account'
  | 'privacy'
  | 'security'
  | 'new_listing'
  | 'worker_setup'
  | 'worker_dashboard'
  | 'worker_discovery';
