export type NavPage =
  // ── Primary Bottom Nav Tabs ──
  | 'home'
  | 'explore'
  | 'saved'
  | 'messages'
  | 'profile'
  // ── Role-specific primary tabs ──
  | 'jobs'
  | 'calendar'
  | 'properties'
  | 'management'
  | 'analytics'
  | 'wallet'
  // ── Legacy / internal ──
  | 'search'
  | 'roommate'
  | 'activity'
  | 'detail'
  | 'creator'
  | 'chat'
  | 'profile_edit'
  | 'account'
  | 'privacy'
  | 'security'
  | 'new_listing'
  | 'worker_setup'
  | 'worker_dashboard'
  | 'worker_discovery'
  | 'worker_categories'
  | 'admin'
  | 'staff_dashboard'
  | 'hotels'
  | 'hotel_detail'
  | 'hotel_booking'
  | 'operations'
  | 'worker_verification'
  | 'finance'
  | 'finance_dashboard'
  | 'worker_wallet'
  | 'field_officer'
  | 'property_owner'
  | 'property_partner'
  | 'my_bookings'
  | 'my_reservations';
