import { useEffect,useState } from 'react';
import { Toaster,toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import CommunicationInbox from '@/components/CommunicationInbox';
import type { Profile } from '@/types';

type Props={profile:Profile;onBack?:()=>void;onGoToPrivacy:()=>void;onGoToSecurity:()=>void;onGoToProfileEdit:()=>void;onLogout?:()=>void};
type Legal={privacy_accepted:boolean;terms_accepted:boolean;privacy_accepted_at?:string|null;terms_accepted_at?:string|null;legal_version?:string|null};
type Published={privacy:boolean;terms:boolean};

export default function AccountCenter({profile,onBack,onGoToPrivacy,onGoToSecurity,onGoToProfileEdit,onLogout}:Props){
 const p=profile as any;
 const[panel,setPanel]=useState<'notifications'|'legal'|'communication'|null>(null),[emailNotifs,setEmailNotifs]=useState(p.pref_email_notif!==false),[pushNotifs,setPushNotifs]=useState(p.pref_push_notif!==false),[legal,setLegal]=useState<Legal>({privacy_accepted:false,terms_accepted:false}),[published,setPublished]=useState<Published>({privacy:false,terms:false}),[acceptPrivacy,setAcceptPrivacy]=useState(false),[acceptTerms,setAcceptTerms]=useState(false),[saving,setSaving]=useState(false);
 const role=profile.role,isUser=role==='user',isWorker=role==='worker',canEditProfile=role!=='staff';
 const roleLabel=role==='property_partner'?'Property Partner':role.charAt(0).toUpperCase()+role.slice(1).replace(/_/g,' ');
 const initials=(profile.full_name||profile.username||profile.email||'U')[0].toUpperCase();
 useEffect(()=>{void(async()=>{const[{data:status},{data:docs}]=await Promise.all([supabase.rpc('get_my_legal_status'),supabase.from('platform_settings').select('key,value').in('key',['privacy_policy','terms_of_service'])]);if(status)setLegal(status as Legal);const next={privacy:false,terms:false};for(const row of docs||[]){if(row.key==='privacy_policy')next.privacy=Boolean(row.value?.trim());if(row.key==='terms_of_service')next.terms=Boolean(row.value?.trim())}setPublished(next)})()},[]);
 async function saveNotifications(){setSaving(true);const{error}=await supabase.from('profiles').update({pref_email_notif:emailNotifs,pref_push_notif:pushNotifs,updated_at:new Date().toISOString()}).eq('auth_id',profile.auth_id);setSaving(false);if(error)return toast.error(error.message);toast.success('Notifications updated');setPanel(null)}
 async function acceptLegal(){if((published.privacy&&!legal.privacy_accepted&&!acceptPrivacy)||(published.terms&&!legal.terms_accepted&&!acceptTerms))return toast.error('Read and accept each published document');setSaving(true);let next=legal;if(published.privacy&&!legal.privacy_accepted){const{data,error}=await supabase.rpc('accept_current_legal',{p_document:'privacy'});if(error){setSaving(false);return toast.error(error.message)}if(data)next=data as Legal}if(published.terms&&!legal.terms_accepted){const{data,error}=await supabase.rpc('accept_current_legal',{p_document:'terms'});if(error){setSaving(false);return toast.error(error.message)}if(data)next=data as Legal}setSaving(false);setLegal(next);setAcceptPrivacy(false);setAcceptTerms(false);toast.success('Legal documents accepted')}
 async function logout(){if(onLogout){onLogout();return}await supabase.auth.signOut({scope:'local'});window.location.reload()}
 function openLegal(page:'privacy_policy'|'terms_of_service'){window.history.pushState({page},'',`#${page}`);window.dispatchEvent(new PopStateEvent('popstate',{state:{page}}))}
 if(panel==='communication')return <SubPage title="Communication" onBack={()=>setPanel(null)}><CommunicationInbox profile={profile} title="Messages" description="WeHouse Official updates and one continuous human-support conversation."/></SubPage>;
 if(panel==='notifications')return <SubPage title="Notifications" onBack={()=>setPanel(null)}><Card><Toggle label="Email notifications" detail="Account and service updates by email." value={emailNotifs} onChange={setEmailNotifs}/><Divider/><Toggle label="Push notifications" detail="Time-sensitive alerts on supported devices." value={pushNotifs} onChange={setPushNotifs}/></Card><button onClick={()=>void saveNotifications()} disabled={saving} className="h-12 w-full rounded-2xl bg-blue-500 text-xs font-semibold disabled:opacity-50">{saving?'Saving…':'Save changes'}</button></SubPage>;
 if(panel==='legal'){const any=published.privacy||published.terms,done=(!published.privacy||legal.privacy_accepted)&&(!published.terms||legal.terms_accepted);return <SubPage title="Legal & consent" onBack={()=>setPanel(null)}><Card><p className="text-sm font-semibold">Published WeHouse documents</p><p className="mt-1 text-[10px] leading-relaxed text-[#747889]">Only documents actually published by Creator can be accepted.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><LegalCard title="Privacy Policy" published={published.privacy} accepted={legal.privacy_accepted} onClick={()=>openLegal('privacy_policy')}/><LegalCard title="Terms & Conditions" published={published.terms} accepted={legal.terms_accepted} onClick={()=>openLegal('terms_of_service')}/></div></Card>{!any?<Empty title="Nothing to accept yet" text="Privacy Policy and Terms & Conditions have not been published."/>:<>{!done&&<Card>{published.privacy&&!legal.privacy_accepted&&<Check label="I have read and accept the published Privacy Policy" value={acceptPrivacy} set={setAcceptPrivacy}/>} {published.privacy&&!legal.privacy_accepted&&published.terms&&!legal.terms_accepted&&<Divider/>}{published.terms&&!legal.terms_accepted&&<Check label="I have read and accept the published Terms & Conditions" value={acceptTerms} set={setAcceptTerms}/>}</Card>}{done?<div className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.05] p-4 text-xs text-emerald-300">Current published documents accepted.</div>:<button onClick={()=>void acceptLegal()} disabled={saving||(published.privacy&&!legal.privacy_accepted&&!acceptPrivacy)||(published.terms&&!legal.terms_accepted&&!acceptTerms)} className="h-12 w-full rounded-2xl bg-blue-500 text-xs font-semibold disabled:opacity-40">{saving?'Saving…':'Accept published documents'}</button>}</>}</SubPage>}
 const anyPublished=published.privacy||published.terms,legalDone=anyPublished&&(!published.privacy||legal.privacy_accepted)&&(!published.terms||legal.terms_accepted);
 const items=[...(canEditProfile?[{title:'Profile',detail:'Photo, name, phone and personal information',action:onGoToProfileEdit}]:[]),...(isUser?[{title:'Privacy',detail:'Roommate discovery and profile visibility',action:onGoToPrivacy}]:[]),...(isWorker?[{title:'Communication',detail:'WeHouse Official updates and human support',action:()=>setPanel('communication' as const)}]:[]),{title:'Notifications',detail:'Email and push preferences',action:()=>setPanel('notifications' as const)},{title:'Security',detail:'Password, devices and account protection',action:onGoToSecurity},{title:'Legal & consent',detail:!anyPublished?'No legal documents published yet':legalDone?'Current documents accepted':'Review current published documents',action:()=>setPanel('legal' as const)}];
 return <div className="min-h-[100dvh] overflow-x-hidden bg-[#090A0F] pb-10 text-white"><Toaster position="top-center" richColors/><header className="border-b border-white/[.06] bg-[#0D1017] px-4 py-4 sm:px-5"><div className="mx-auto flex max-w-4xl items-center gap-3">{onBack&&<button onClick={onBack} aria-label="Back" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/[.07] bg-white/[.03] text-[#9A9EAD]">←</button>}<div className="min-w-0"><p className="text-[9px] font-bold tracking-[.2em] text-blue-400">ACCOUNT</p><h1 className="mt-1 text-lg font-bold sm:text-xl">Your WeHouse account</h1></div></div></header><main className="mx-auto max-w-4xl space-y-4 px-4 py-5 sm:px-5 lg:py-7"><section className="rounded-3xl border border-blue-500/15 bg-gradient-to-br from-blue-500/[.08] via-[#12151D] to-[#0F1118] p-5 sm:p-6"><div className="flex items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-blue-500 text-xl font-bold">{profile.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:initials}</div><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-semibold">{profile.full_name||`@${profile.username||'user'}`}</h2><p className="mt-1 truncate text-[10px] text-[#777B8C]">@{profile.username||'not-set'}</p><div className="mt-3 flex flex-wrap gap-2"><Chip text={roleLabel}/>{profile.id_verified&&<Chip text="Identity verified" good/>}</div></div></div></section><section className="overflow-hidden rounded-2xl border border-white/[.06] bg-[#11141C]">{items.map((item,i)=><div key={item.title}>{i>0&&<Divider/>}<button onClick={item.action} className="flex w-full items-center gap-3 px-4 py-4 text-left hover:bg-white/[.025] sm:px-5"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.title}</p><p className="mt-0.5 text-[10px] leading-relaxed text-[#696D7D]">{item.detail}</p></div><span className="text-[#55596A]">›</span></button></div>)}</section><section className="grid gap-3 sm:grid-cols-3"><Info label="Email" value={profile.email_verified?'Verified':'Not verified'}/><Info label="Location" value={[profile.state,profile.local_government||profile.city].filter(Boolean).join(' / ')||'Not set'}/><Info label="Member since" value={new Date(profile.created_at).toLocaleDateString()}/></section>{!canEditProfile&&<div className="rounded-2xl border border-amber-500/15 bg-amber-500/[.05] p-4 text-[10px] leading-relaxed text-amber-200/80">Staff identity, branch and permissions are controlled by authorized Admin/Creator workflows.</div>}<button onClick={()=>void logout()} className="w-full rounded-2xl border border-red-500/15 bg-red-500/[.05] p-4 text-left"><p className="text-sm font-medium text-red-300">Log out</p><p className="mt-1 text-[10px] text-red-300/60">Sign out of this device</p></button></main></div>
}
function SubPage({title,onBack,children}:{title:string;onBack:()=>void;children:React.ReactNode}){return <div className="min-h-[100dvh] bg-[#090A0F] text-white"><Toaster position="top-center" richColors/><header className="border-b border-white/[.06] bg-[#0D1017] px-4 py-4"><div className="mx-auto flex max-w-4xl items-center gap-3"><button onClick={onBack} className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.07] bg-white/[.03]">←</button><h1 className="text-base font-semibold">{title}</h1></div></header><main className="mx-auto max-w-4xl space-y-4 px-4 py-5 sm:px-5">{children}</main></div>}
function Card({children}:{children:React.ReactNode}){return <section className="overflow-hidden rounded-2xl border border-white/[.06] bg-[#11141C] p-4 sm:p-5">{children}</section>}
function Divider(){return <div className="h-px bg-white/[.05]"/>}
function Toggle({label,detail,value,onChange}:{label:string;detail:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between gap-4 py-1"><div><p className="text-sm font-medium">{label}</p><p className="mt-1 text-[10px] text-[#696D7D]">{detail}</p></div><button onClick={()=>onChange(!value)} className={`relative h-6 w-11 shrink-0 rounded-full ${value?'bg-blue-500':'bg-[#2A2D38]'}`}><span className={`absolute left-0.5 top-0.5 h-5 w-5 rounded-full bg-white transition-transform ${value?'translate-x-5':''}`}/></button></div>}
function LegalCard({title,published,accepted,onClick}:{title:string;published:boolean;accepted:boolean;onClick:()=>void}){return <button onClick={onClick} className="rounded-xl border border-white/[.08] p-3 text-left"><p className="text-xs font-medium">{title}</p><p className={`mt-1 text-[9px] ${!published?'text-[#727687]':accepted?'text-emerald-300':'text-amber-300'}`}>{!published?'Not published yet':accepted?'Current version accepted':'Published · review required'}</p></button>}
function Check({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <button onClick={()=>set(!value)} className="flex w-full items-center gap-3 py-2 text-left"><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-lg border text-xs ${value?'border-blue-500 bg-blue-500':'border-white/[.15]'}`}>{value?'✓':''}</span><span className="text-xs">{label}</span></button>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[.06] bg-[#11141C] p-4"><p className="text-[9px] uppercase tracking-wide text-[#606475]">{label}</p><p className="mt-2 break-words text-xs font-medium text-[#D1D3DC]">{value}</p></div>}
function Chip({text,good=false}:{text:string;good?:boolean}){return <span className={`rounded-full px-2.5 py-1 text-[9px] font-semibold ${good?'border border-emerald-500/15 bg-emerald-500/[.07] text-emerald-300':'border border-blue-400/20 bg-blue-400/10 text-blue-300'}`}>{text}</span>}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] p-6 text-center"><p className="text-sm font-semibold">{title}</p><p className="mt-2 text-[10px] text-[#6D7182]">{text}</p></div>}
