import type { Profile } from '@/types';

type Props={profile:Profile;onBack?:()=>void;onGoToPrivacy:()=>void;onGoToSecurity:()=>void;onGoToNotifications:()=>void;onGoToProfileEdit:()=>void;onLogout:()=>void};
export default function AccountCenter({profile,onGoToPrivacy,onGoToSecurity,onGoToNotifications,onGoToProfileEdit,onLogout}:Props){
  const initials=(profile.full_name||profile.username||profile.email||'U')[0].toUpperCase();
  const roleLabel=profile.role==='property_partner'?'Property Partner':profile.role.charAt(0).toUpperCase()+profile.role.slice(1);
  const isUser=profile.role==='user';
  const canEditProfile=profile.role!=='staff';
  const items=[
    ...(canEditProfile?[{title:'Profile',description:'Photo, name, phone and personal information',action:onGoToProfileEdit}]:[]),
    ...(isUser?[{title:'Privacy',description:'Roommate profile and discovery visibility',action:onGoToPrivacy}]:[]),
    {title:'Notifications',description:'Email and push notification preferences',action:onGoToNotifications},
    {title:'Security',description:'Password, sessions and account protection',action:onGoToSecurity},
    ...(isUser?[{title:'Help & Support',description:'Contact the WeHouse support team',action:()=>window.dispatchEvent(new CustomEvent('openSupportChat'))}]:[]),
  ];
  return <div className="role-workspace min-h-[100dvh] bg-[#09090D] pb-24 text-white"><header className="border-b border-white/[0.06] bg-[#0D0E14] px-4 py-5 sm:px-5"><div className="mx-auto max-w-4xl"><p className="text-[9px] font-bold tracking-[.2em] text-blue-400">ACCOUNT</p><h1 className="mt-2 text-xl font-bold">Your WeHouse account</h1></div></header><main className="mx-auto max-w-4xl space-y-5 px-4 py-5 sm:px-5 lg:py-7"><section className="rounded-3xl border border-blue-500/15 bg-gradient-to-br from-blue-500/[0.09] via-[#12141C] to-[#0F1118] p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-blue-500 text-xl font-bold">{profile.avatar_url?<img src={profile.avatar_url} alt="Profile" className="h-full w-full object-cover"/>:initials}</div><div className="min-w-0 flex-1"><h2 className="break-words text-lg font-semibold">{profile.full_name||`@${profile.username||'user'}`}</h2><p className="mt-1 break-all text-[11px] text-[#7C8091]">@{profile.username||'not-set'} · {profile.email}</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full border border-blue-400/20 bg-blue-400/10 px-2.5 py-1 text-[9px] font-semibold text-blue-300">{roleLabel}</span><span className="rounded-full bg-white/[0.04] px-2.5 py-1 text-[9px] text-[#858999]">{profile.user_id}</span>{profile.id_verified&&<span className="rounded-full border border-emerald-500/15 bg-emerald-500/[0.07] px-2.5 py-1 text-[9px] text-emerald-300">Identity verified</span>}</div></div></div></section><section className="overflow-hidden rounded-2xl border border-white/[0.06] bg-[#11131B] divide-y divide-white/[0.05]">{items.map(item=><button key={item.title} onClick={item.action} className="flex w-full items-center gap-3 px-4 py-4 text-left hover:bg-white/[0.025] sm:px-5"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.title}</p><p className="mt-0.5 text-[10px] leading-relaxed text-[#686C7D]">{item.description}</p></div><span className="text-[#55596A]">›</span></button>)}</section><section className="grid gap-3 sm:grid-cols-3"><Info label="Email" value={profile.email_verified?'Verified':'Not verified'}/><Info label="Location" value={[profile.state,profile.local_government||profile.city].filter(Boolean).join(' / ')||'Not set'}/><Info label="Member since" value={new Date(profile.created_at).toLocaleDateString()}/></section>{!canEditProfile&&<div className="rounded-2xl border border-amber-500/15 bg-amber-500/[0.05] p-4 text-[10px] leading-relaxed text-amber-200/80">Staff identity and branch information are managed by authorized Admin/Creator workflows.</div>}<button onClick={onLogout} className="w-full rounded-2xl border border-red-500/15 bg-red-500/[0.05] p-4 text-left hover:bg-red-500/[0.08]"><p className="text-sm font-medium text-red-300">Log out</p><p className="mt-1 text-[10px] text-red-300/60">Sign out of this device</p></button></main></div>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[0.06] bg-[#11131B] p-4"><p className="text-[9px] uppercase tracking-wide text-[#606475]">{label}</p><p className="mt-2 break-words text-xs font-medium text-[#D1D3DC]">{value}</p></div>}
