import { useEffect, useMemo, useState } from 'react';
import { Toaster, toast } from 'sonner';
import WorkspaceFrameV2 from '@/components/WorkspaceFrameV2';
import CommunicationsWorkspace from '@/components/CommunicationsWorkspace';
import PropertyPipelineWorkspace from '@/components/PropertyPipelineWorkspace';
import CreatorWorkerOversight from '@/components/CreatorWorkerOversight';
import ServiceBookingOversight from '@/components/ServiceBookingOversight';
import UserProfileModal from '@/components/UserProfileModal';
import StaffListTab from './StaffListTab';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';

type Tab='overview'|'operations'|'communications'|'reports';
type Operation='people'|'staff'|'properties'|'workers'|'bookings';
type PersonRole='user'|'property_partner';
type Props={profile:Profile;onLogout:()=>void;onNavigate?:(page:string)=>void;onGoToChat?:(id?:string)=>void};
const NAV=[{id:'overview',label:'Overview'},{id:'operations',label:'Operations'},{id:'communications',label:'Communications'},{id:'reports',label:'Reports'}];
const OPS:Array<{id:Operation;label:string;note:string}>=[
 {id:'people',label:'People',note:'Regular Users and Property Partners in this branch.'},
 {id:'staff',label:'Staff',note:'Branch Staff, appointment capacity, modules and trust.'},
 {id:'properties',label:'Properties',note:'Property requests, inspections, preparation and publication.'},
 {id:'workers',label:'Workers',note:'Worker lifecycle oversight. Verification Staff own routine review.'},
 {id:'bookings',label:'Service Bookings',note:'Worker-service booking oversight for this branch.'},
];

export default function AdminDashboardModernV2({profile,onLogout,onNavigate,onGoToChat}:Props){
 const[tab,setTab]=useState<Tab>('overview'),[operation,setOperation]=useState<Operation>('people'),[stats,setStats]=useState<any>({}),[viewing,setViewing]=useState<Profile|null>(null);
 const branchReady=Boolean(profile.assigned_state&&profile.assigned_lga);
 async function loadStats(){if(!branchReady)return;const{data,error}=await supabase.rpc('admin_get_my_branch_stats');if(error)toast.error(error.message);else setStats(data||{})}
 useEffect(()=>{void loadStats()},[branchReady,profile.assigned_state,profile.assigned_lga]);
 function openOperation(next:Operation){setOperation(next);setTab('operations')}
 const description=!branchReady?'Branch assignment required before Admin operations can begin.':tab==='overview'?`Branch health and priority work · ${profile.assigned_lga}, ${profile.assigned_state}`:tab==='operations'?`People, Staff, properties, Workers and bookings · ${profile.assigned_lga}, ${profile.assigned_state}`:tab==='communications'?`Branch inbox and announcements · ${profile.assigned_lga}, ${profile.assigned_state}`:`Listing reports and moderation · ${profile.assigned_lga}, ${profile.assigned_state}`;
 return <><Toaster position="top-center" richColors/><WorkspaceFrameV2 label={`WEHOUSE · ADMIN · ${profile.assigned_lga||'UNASSIGNED'}`} title={NAV.find(item=>item.id===tab)?.label||'Admin'} description={description} items={NAV} active={tab} setActive={id=>setTab(id as Tab)} onAccount={onNavigate?()=>onNavigate('profile'):undefined} onLogout={onLogout}>{!branchReady?<Empty title="Branch assignment required" text="Creator must assign this Admin to a State and LGA before branch operations are available."/>:<>{tab==='overview'&&<Overview stats={stats} profile={profile} openOperation={openOperation} openCommunications={()=>setTab('communications')} openReports={()=>setTab('reports')}/>} {tab==='operations'&&<Operations profile={profile} active={operation} setActive={setOperation} onView={setViewing}/>} {tab==='communications'&&<CommunicationsWorkspace profile={profile} scope={{state:profile.assigned_state!,lga:profile.assigned_lga!}}/>} {tab==='reports'&&<Reports/>}</>}</WorkspaceFrameV2>{viewing&&<UserProfileModal user={viewing} adminProfile={profile} onClose={()=>setViewing(null)} onPromote={()=>{setViewing(null);openOperation('staff');void loadStats()}} onNavigate={onNavigate} onGoToChat={onGoToChat}/>}</>;
}

function Overview({stats,profile,openOperation,openCommunications,openReports}:{stats:any;profile:Profile;openOperation:(tab:Operation)=>void;openCommunications:()=>void;openReports:()=>void}){const cards:Array<[string,number,Operation,string]>=[['Users',stats.users||0,'people','Regular Users'],['Property Partners',stats.partners||0,'people','Property owners'],['Staff',stats.staff||0,'staff','Branch Staff'],['Properties',stats.listings||0,'properties','Published inventory'],['Workers',stats.workers||0,'workers',`${stats.pending_verifications||0} in verification`]];return <div className="space-y-5"><section className="rounded-3xl border border-indigo-500/15 bg-gradient-to-br from-indigo-500/[.12] via-[#111522] to-[#0D1018] p-5"><p className="text-[8px] font-bold uppercase tracking-[.18em] text-indigo-300">BRANCH AUTHORITY</p><h2 className="mt-3 text-2xl font-bold">{profile.assigned_lga}, {profile.assigned_state}</h2><p className="mt-2 text-[10px] text-[#858B9B]">Admin manages this branch. Verification Staff make routine Worker review decisions.</p></section><section className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-5">{cards.map(([label,value,target,note])=><button key={label} onClick={()=>openOperation(target)} className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4 text-left"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-[10px] font-semibold">{label}</p><p className="mt-1 text-[8px] text-[#626879]">{note}</p></button>)}</section><div className="grid gap-2 sm:grid-cols-2"><button onClick={openCommunications} className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4 text-left text-xs font-semibold">Communications</button><button onClick={openReports} className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4 text-left text-xs font-semibold">Reports & moderation</button></div></div>}

function Operations({profile,active,setActive,onView}:{profile:Profile;active:Operation;setActive:(value:Operation)=>void;onView:(p:Profile)=>void}){const current=OPS.find(item=>item.id===active)!;return <div className="space-y-4"><div><h2 className="text-lg font-bold">Branch operations</h2><p className="mt-1 text-[10px] text-[#707687]">Each branch responsibility has one home.</p></div><div className="flex gap-2 overflow-x-auto scrollbar-hide">{OPS.map(item=><Chip key={item.id} active={active===item.id} onClick={()=>setActive(item.id)}>{item.label}</Chip>)}</div><div className="rounded-xl border border-indigo-500/10 bg-indigo-500/[.03] p-3"><p className="text-xs font-semibold">{current.label}</p><p className="mt-1 text-[9px] text-[#676E7F]">{current.note}</p></div>{active==='people'&&<People onView={onView}/>} {active==='staff'&&<StaffListTab profile={profile}/>} {active==='properties'&&<PropertyPipelineWorkspace profile={profile}/>} {active==='workers'&&<CreatorWorkerOversight actorLabel="Admin"/>} {active==='bookings'&&<Bookings/>}</div>}

function People({onView}:{onView:(p:Profile)=>void}){const[role,setRole]=useState<PersonRole>('user'),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState('');useEffect(()=>{void load()},[role]);async function load(){setLoading(true);const{data,error}=await supabase.rpc('admin_get_my_branch_profiles',{p_role:role});if(error)toast.error(error.message);setRows(Array.isArray(data)?data:[]);setLoading(false)}const shown=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(row=>!q||[row.full_name,row.username,row.email,row.user_id].filter(Boolean).join(' ').toLowerCase().includes(q))},[rows,search]);return <Section title="People" note="Regular Users and Property Partners in this branch."><div className="flex gap-2"><Chip active={role==='user'} onClick={()=>setRole('user')}>Users</Chip><Chip active={role==='property_partner'} onClick={()=>setRole('property_partner')}>Property Partners</Chip></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search this branch" className="h-11 w-full rounded-xl border border-white/[.08] bg-[#141720] px-3 text-xs"/>{loading?<Loading/>:shown.length===0?<Empty title="No matching accounts" text="Nothing in this branch matches the filter."/>:<div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{shown.map(person=><button key={person.user_id} onClick={()=>onView(person)} className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4 text-left"><p className="truncate text-sm font-semibold">{person.full_name||person.username||'WeHouse account'}</p><p className="mt-1 truncate text-[9px] text-[#666D7E]">{person.email}</p></button>)}</div>}</Section>}

function Bookings(){return <ServiceBookingOversight title="Service bookings" note="This branch only. Participants control each job; Admin monitors lifecycle and exceptions."/>}

function Reports(){const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);async function load(){setLoading(true);const{data,error}=await supabase.rpc('admin_get_my_branch_reports');if(error)toast.error(error.message);setRows(Array.isArray(data)?data:[]);setLoading(false)}useEffect(()=>{void load()},[]);async function act(id:string,action:'resolved'|'dismissed'){const{error}=await supabase.rpc('admin_resolve_my_branch_report',{p_report_id:id,p_action:action});if(error)return toast.error(error.message);toast.success(action==='resolved'?'Report resolved':'Report dismissed');void load()}return <Section title="Reports & moderation" note="Listing reports only. Support stays in Communications.">{loading?<Loading/>:rows.length===0?<Empty title="No reports" text="No listing reports are waiting for moderation."/>:<div className="space-y-2">{rows.map(row=><div key={row.id} className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><p className="text-sm font-semibold">{row.reason||'Listing report'}</p><p className="mt-1 text-[9px] text-[#666D7E]">{row.listing_id||'Listing'} · {row.status||'pending'}</p>{row.status==='pending'&&<div className="mt-3 flex gap-2"><button onClick={()=>void act(row.id,'resolved')} className="h-10 flex-1 rounded-xl bg-indigo-500 text-[10px] font-semibold">Resolve</button><button onClick={()=>void act(row.id,'dismissed')} className="h-10 flex-1 rounded-xl border border-white/[.08] text-[10px] font-semibold">Dismiss</button></div>}</div>)}</div>}</Section>}

function Section({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <div className="space-y-4"><div><h2 className="text-lg font-bold">{title}</h2><p className="mt-1 text-[10px] text-[#707687]">{note}</p></div>{children}</div>}
function Chip({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`shrink-0 rounded-xl px-3 py-2 text-[9px] font-semibold ${active?'bg-indigo-500 text-white':'border border-white/[.06] text-[#777D8D]'}`}>{children}</button>}
function Loading(){return <div className="grid min-h-40 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-indigo-500 border-t-transparent"/></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] px-5 py-12 text-center"><p className="text-sm font-semibold">{title}</p><p className="mt-2 text-[10px] text-[#666C7D]">{text}</p></div>}
