import { useEffect,useMemo,useState } from 'react';
import { supabase } from '@/lib/supabase';
import { invalidateSettingsCache } from '@/hooks/usePlatformSettings';
import type { Profile } from '@/types';
import { toast } from 'sonner';

type Type='text'|'toggle'|'textarea'|'email';
type Def={key:string;label:string;description:string;type:Type;defaultValue:string};
type Db={key:string;value:string;is_active:boolean};
const GROUPS:Array<{id:string;label:string;description:string;settings:Def[]}>= [
 {id:'identity',label:'Platform identity',description:'Public WeHouse contact and identity information.',settings:[{key:'company_name',label:'Company name',description:'Name shown across the platform.',type:'text',defaultValue:'WeHouse'},{key:'support_email',label:'Support email',description:'Primary public support email.',type:'email',defaultValue:''},{key:'support_phone',label:'Support phone',description:'Primary public support phone number.',type:'text',defaultValue:''}]},
 {id:'access',label:'Platform access',description:'High-level switches that affect access to WeHouse.',settings:[{key:'maintenance_mode',label:'Maintenance mode',description:'Temporarily block normal platform access while maintenance is active.',type:'toggle',defaultValue:'false'},{key:'registration_open',label:'Registration open',description:'Allow new accounts to register.',type:'toggle',defaultValue:'true'}]},
 {id:'legal',label:'Legal documents',description:'Published Privacy Policy and Terms & Conditions. Users can read and accept the current versions.',settings:[{key:'privacy_policy',label:'Privacy Policy',description:'The public Privacy Policy shown in WeHouse.',type:'textarea',defaultValue:''},{key:'terms_of_service',label:'Terms & Conditions',description:'The public Terms & Conditions shown in WeHouse.',type:'textarea',defaultValue:''}]}
];

export default function CreatorSettingsTab({profile}:{profile?:Profile}){
 const[settings,setSettings]=useState<Db[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState<Record<string,boolean>>({}),[drafts,setDrafts]=useState<Record<string,string>>({}),[aiConfigured,setAiConfigured]=useState(false),[aiKey,setAiKey]=useState(''),[aiSaving,setAiSaving]=useState(false),[aiTesting,setAiTesting]=useState(false);
 const defs=useMemo(()=>GROUPS.flatMap(g=>g.settings),[]),keys=useMemo(()=>defs.map(d=>d.key),[defs]);
 useEffect(()=>{let cancel=false;void(async()=>{setLoading(true);const[{data,error},{data:secret,error:secretError}]=await Promise.all([supabase.from('platform_settings').select('key,value,is_active').in('key',keys),supabase.rpc('get_secret_v2',{p_key:'openai_api_key'})]);if(cancel)return;if(error)toast.error(`Could not load platform settings: ${error.message}`);else setSettings((data||[]) as Db[]);if(secretError)toast.error('Could not read Assistant connection status');else setAiConfigured(Boolean(Array.isArray(secret)&&secret[0]?.value));setLoading(false)})();return()=>{cancel=true}},[keys]);
 const stored=(d:Def)=>settings.find(s=>s.key===d.key&&s.is_active!==false)?.value??d.defaultValue,current=(d:Def)=>drafts[d.key]!==undefined?drafts[d.key]:stored(d),setDraft=(k:string,v:string)=>setDrafts(x=>({...x,[k]:v}));
 async function save(d:Def,value:string){setSaving(x=>({...x,[d.key]:true}));const{data:existing}=await supabase.from('platform_settings').select('key').eq('key',d.key).maybeSingle();let error:any=null;if(existing){({error}=await supabase.from('platform_settings').update({value,label:d.label,description:d.description,data_type:d.type==='toggle'?'boolean':'text',is_active:true,updated_at:new Date().toISOString()}).eq('key',d.key))}else{({error}=await supabase.from('platform_settings').insert({key:d.key,value,label:d.label,description:d.description,category:'platform',data_type:d.type==='toggle'?'boolean':'text',is_active:true,updated_at:new Date().toISOString()}))}if(error){setSaving(x=>({...x,[d.key]:false}));toast.error(`Could not save ${d.label}: ${error.message}`);return false}const{data:verify,error:ve}=await supabase.from('platform_settings').select('key,value,is_active').eq('key',d.key).maybeSingle();if(ve||!verify||String(verify.value)!==String(value)){setSaving(x=>({...x,[d.key]:false}));toast.error(`${d.label} could not be verified after saving`);return false}setSettings(x=>[...x.filter(s=>s.key!==d.key),verify as Db]);setDrafts(x=>{const n={...x};delete n[d.key];return n});invalidateSettingsCache();setSaving(x=>({...x,[d.key]:false}));if(d.key==='privacy_policy'||d.key==='terms_of_service')toast.success(`${d.label} published`);return true}
 async function saveAll(){const changed=defs.filter(d=>drafts[d.key]!==undefined);let n=0;for(const d of changed)if(await save(d,drafts[d.key]))n++;if(n)toast.success(`${n} setting${n===1?'':'s'} saved`)}
 async function saveAssistantKey(){const key=aiKey.trim();if(!key)return toast.error('Paste the OpenAI API key first');if(!key.startsWith('sk-'))return toast.error('That does not look like an OpenAI API key');setAiSaving(true);const{data,error}=await supabase.rpc('set_secret_v2',{p_key:'openai_api_key',p_value:key});setAiSaving(false);if(error||data!==true)return toast.error(error?.message||'Could not save Assistant connection');setAiKey('');setAiConfigured(true);toast.success('WeHouse Assistant connection saved securely')}
 async function testAssistant(){if(!profile)return;setAiTesting(true);const{data,error}=await supabase.functions.invoke('wehouse-assistant',{body:{message:'Confirm that WeHouse Assistant is connected. Keep the answer under 12 words.',messages:[]}});setAiTesting(false);if(error||!data?.message)return toast.error(data?.message||'Assistant connection test failed');toast.success('WeHouse Assistant is connected')}
 if(loading)return <div className="grid min-h-40 place-items-center"><div className="h-6 w-6 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>;
 const changed=Object.keys(drafts).length;
 return <section className="min-w-0 space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><h2 className="text-base font-bold text-white">Platform settings</h2><p className="mt-1 max-w-2xl text-[10px] leading-relaxed text-[#686C7E]">Identity, access, Assistant connection and published legal documents.</p></div>{changed>0&&<button onClick={()=>void saveAll()} disabled={Object.values(saving).some(Boolean)} className="min-h-10 w-full rounded-xl bg-violet-500 px-4 text-[10px] font-semibold text-white disabled:opacity-40 sm:w-auto">{Object.values(saving).some(Boolean)?'Saving…':`Save changes (${changed})`}</button>}</div>
 <section className="overflow-hidden rounded-3xl border border-blue-500/15 bg-gradient-to-br from-blue-500/[.09] via-[#10131B] to-[#0D1017]"><div className="flex flex-col gap-4 border-b border-white/[.05] p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div><div className="flex items-center gap-2"><h3 className="text-sm font-semibold">WeHouse Assistant</h3><span className={`rounded-full px-2 py-1 text-[8px] font-semibold ${aiConfigured?'bg-emerald-500/10 text-emerald-300':'bg-amber-500/10 text-amber-300'}`}>{aiConfigured?'CONNECTED':'NOT CONNECTED'}</span></div><p className="mt-1 max-w-xl text-[10px] leading-relaxed text-[#6D7284]">Connect the AI that powers product guidance. Human Support remains a separate real-person conversation.</p></div>{aiConfigured&&<button onClick={()=>void testAssistant()} disabled={aiTesting} className="h-10 rounded-xl border border-blue-500/20 bg-blue-500/10 px-4 text-[10px] font-semibold text-blue-300 disabled:opacity-40">{aiTesting?'Testing…':'Test connection'}</button>}</div><div className="p-4 sm:p-5"><label className="block"><span className="mb-1.5 block text-[9px] font-semibold uppercase tracking-[.12em] text-[#6A7082]">{aiConfigured?'Replace API key':'OpenAI API key'}</span><div className="flex flex-col gap-2 sm:flex-row"><input type="password" autoComplete="off" value={aiKey} onChange={e=>setAiKey(e.target.value)} placeholder={aiConfigured?'Paste a new key only if you want to replace the current one':'sk-…'} className="h-11 min-w-0 flex-1 rounded-xl border border-white/[.08] bg-[#171A23] px-3 text-xs outline-none focus:border-blue-500/40"/><button onClick={()=>void saveAssistantKey()} disabled={aiSaving||!aiKey.trim()} className="h-11 shrink-0 rounded-xl bg-blue-500 px-4 text-[10px] font-semibold disabled:opacity-40">{aiSaving?'Saving…':aiConfigured?'Replace key':'Connect Assistant'}</button></div></label><p className="mt-2 text-[9px] leading-relaxed text-[#5F6476]">The saved key is never shown again on this screen.</p></div></section>
 <div className="grid min-w-0 gap-4 xl:grid-cols-2">{GROUPS.map(g=><section key={g.id} className={`${g.id==='legal'?'xl:col-span-2':''} min-w-0 rounded-2xl border border-white/[.06] bg-[#10131B] p-4 sm:p-5`}><div className="mb-4"><h3 className="text-sm font-semibold">{g.label}</h3><p className="mt-1 text-[10px] leading-relaxed text-[#666A7C]">{g.description}</p></div>{g.id==='legal'&&<div className="mb-4 rounded-xl border border-violet-500/15 bg-violet-500/[.05] p-3 text-[10px] leading-relaxed text-violet-200/80">Publishing a changed legal document creates the current version users can read and accept.</div>}<div className="space-y-4">{g.settings.map(d=>{const value=current(d),busy=saving[d.key],dirty=drafts[d.key]!==undefined;if(d.type==='textarea')return <div key={d.key} className="min-w-0 rounded-2xl border border-white/[.05] bg-[#0D1017] p-3 sm:p-4"><div className="mb-3"><p className="text-xs font-semibold">{d.label}</p><p className="mt-1 text-[10px] text-[#666A7C]">{d.description}</p></div><textarea rows={10} value={value} onChange={e=>setDraft(d.key,e.target.value)} className="w-full min-w-0 resize-y rounded-xl border border-white/[.08] bg-[#171A23] px-3 py-3 text-xs leading-6 text-white outline-none focus:border-violet-500/40"/><button onClick={()=>void save(d,value)} disabled={busy||!dirty} className="mt-3 min-h-10 w-full rounded-xl bg-violet-500 px-4 text-[10px] font-semibold disabled:opacity-30 sm:w-auto">{busy?'Publishing…':`Publish ${d.label}`}</button></div>;return <div key={d.key} className="grid min-w-0 gap-3 border-b border-white/[.05] pb-4 last:border-0 last:pb-0 sm:grid-cols-[minmax(0,1fr)_minmax(180px,280px)] sm:items-center"><div className="min-w-0"><p className="text-[11px] font-medium">{d.label}</p><p className="mt-1 text-[10px] leading-relaxed text-[#666A7C]">{d.description}</p></div>{d.type==='toggle'?<button disabled={busy} aria-pressed={value==='true'} onClick={()=>{const next=value==='true'?'false':'true';setDraft(d.key,next);void save(d,next)}} className={`relative h-6 w-11 rounded-full disabled:opacity-50 sm:justify-self-end ${value==='true'?'bg-violet-500':'border border-white/[.08] bg-[#252936]'}`}><span className={`absolute left-0.5 top-0.5 h-5 w-5 rounded-full bg-white transition-transform ${value==='true'?'translate-x-5':''}`}/></button>:<div className="flex min-w-0 flex-col gap-2 sm:flex-row"><input type={d.type} value={value} onChange={e=>setDraft(d.key,e.target.value)} className="h-10 min-w-0 flex-1 rounded-xl border border-white/[.08] bg-[#171A23] px-3 text-xs outline-none focus:border-violet-500/40"/><button disabled={busy||!dirty} onClick={()=>void save(d,value)} className="h-10 rounded-xl bg-violet-500 px-3 text-[10px] font-semibold disabled:opacity-30">{busy?'Saving…':'Save'}</button></div>}</div>})}</div></section>)}</div></section>
}
