import { useEffect, useState } from 'react';
import { getHotelById, getHotelReviews, addHotelReview } from '@/lib/supabase';
import type { Hotel, HotelRoom, HotelReview } from '@/types';
import { Toaster, toast } from 'sonner';
import { useHotelReservationSettings, calculateReservationFee } from '@/hooks/useHotelReservationSettings';

type ReviewRow=HotelReview&{profiles:{username:string|null;avatar_url:string|null}};
type Props={hotelId:number;onBack:()=>void;onBook:(hotelId:number,roomId:number,checkIn:string,checkOut:string)=>void;onReserve:(hotelId:number,roomId:number)=>void;profile:{user_id:string;username:string|null}};

export default function HotelDetail({hotelId,onBack,onBook,onReserve,profile}:Props){
 const[hotel,setHotel]=useState<(Hotel&{hotel_rooms:HotelRoom[]})|null>(null),[reviews,setReviews]=useState<ReviewRow[]>([]),[loading,setLoading]=useState(true),[currentImage,setCurrentImage]=useState(0),[showAllAmenities,setShowAllAmenities]=useState(false),[showReviewForm,setShowReviewForm]=useState(false),[reviewRating,setReviewRating]=useState(5),[reviewComment,setReviewComment]=useState(''),[submittingReview,setSubmittingReview]=useState(false),[selectedRoom,setSelectedRoom]=useState<HotelRoom|null>(null),[checkIn,setCheckIn]=useState(''),[checkOut,setCheckOut]=useState('');
 const reservationSettings=useHotelReservationSettings();
 useEffect(()=>{void load()},[hotelId]);
 async function load(){setLoading(true);const{hotel:h,error}=await getHotelById(hotelId);if(error||!h){toast.error('Hotel could not be loaded');setLoading(false);return}setHotel(h);setSelectedRoom(h.hotel_rooms?.[0]||null);const{reviews:r}=await getHotelReviews(hotelId);setReviews((r||[]) as ReviewRow[]);setLoading(false)}
 async function submitReview(){if(!profile.user_id)return;setSubmittingReview(true);const{error}=await addHotelReview(hotelId,profile.user_id,reviewRating,reviewComment||undefined);setSubmittingReview(false);if(error)return toast.error('Review could not be submitted');toast.success('Review submitted');setShowReviewForm(false);setReviewComment('');const{reviews:r}=await getHotelReviews(hotelId);setReviews((r||[]) as ReviewRow[]);const{hotel:h}=await getHotelById(hotelId);if(h)setHotel(h)}
 const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const tomorrowStr=tomorrow.toISOString().split('T')[0];
 function minCheckout(){if(!checkIn)return tomorrowStr;const next=new Date(checkIn);next.setDate(next.getDate()+1);return next.toISOString().split('T')[0]}
 const nights=checkIn&&checkOut?Math.ceil((new Date(checkOut).getTime()-new Date(checkIn).getTime())/86400000):0;
 const totalPrice=selectedRoom&&nights>0?nights*selectedRoom.price_per_night:0;
 const reservationFee=reservationSettings.enabled?calculateReservationFee(reservationSettings,nights):0;
 function proceed(){if(!selectedRoom)return toast.error('Choose a room first');if(reservationSettings.enabled){onReserve(hotelId,selectedRoom.room_id);return}if(!checkIn||!checkOut)return toast.error('Select check-in and check-out');if(nights<=0)return toast.error('Check-out must be after check-in');onBook(hotelId,selectedRoom.room_id,checkIn,checkOut)}
 if(loading)return <div className="grid min-h-[70dvh] place-items-center bg-[#0A0A0F]"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>;
 if(!hotel)return <div className="grid min-h-[70dvh] place-items-center bg-[#0A0A0F] px-5 text-white"><div className="text-center"><p className="text-sm font-semibold">Hotel not found</p><button onClick={onBack} className="mt-4 rounded-xl bg-violet-500 px-4 py-2 text-xs font-semibold">Back to hotels</button></div></div>;
 const images=hotel.images?.length?hotel.images:[],allAmenities=hotel.amenities||[],displayedAmenities=showAllAmenities?allAmenities:allAmenities.slice(0,8);
 return <div className="min-h-[100dvh] bg-[#0A0A0F] pb-28 text-white"><Toaster position="top-center" richColors/>
  <header className="sticky top-0 z-40 border-b border-white/[.06] bg-[#0A0A0F]/95 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-5xl items-center gap-3"><button onClick={onBack} className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.08] bg-white/[.03] text-[#9DA3B2]">←</button><div className="min-w-0"><p className="text-[8px] font-bold uppercase tracking-[.18em] text-violet-400">WEHOUSE · HOTELS</p><p className="mt-1 truncate text-sm font-semibold">{hotel.name}</p></div></div></header>
  <main className="mx-auto max-w-5xl space-y-5 px-4 py-5 sm:px-6">
   <section className="overflow-hidden rounded-3xl border border-white/[.07] bg-[#10141C]">
    <div className="relative aspect-[16/9] bg-[#171B24]">{images.length?<img src={images[currentImage]} alt={hotel.name} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-[10px] text-[#62697A]">No hotel image yet</div>}<div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/>{images.length>1&&<div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 gap-1.5">{images.map((_,index)=><button key={index} onClick={()=>setCurrentImage(index)} className={`h-1.5 rounded-full ${index===currentImage?'w-5 bg-violet-400':'w-1.5 bg-white/45'}`}/>)}</div>}</div>
    <div className="p-4 sm:p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h1 className="text-xl font-bold">{hotel.name}</h1><p className="mt-1 text-[10px] text-[#747B8B]">{[hotel.area,hotel.city,hotel.state].filter(Boolean).join(', ')}</p></div>{Number(hotel.rating||0)>0&&<span className="rounded-full border border-amber-500/20 bg-amber-500/[.08] px-2.5 py-1 text-[9px] font-semibold text-amber-300">★ {Number(hotel.rating).toFixed(1)}</span>}</div>{hotel.description&&<p className="mt-4 text-[11px] leading-5 text-[#9399A8]">{hotel.description}</p>}{hotel.address&&<div className="mt-4 rounded-xl border border-white/[.06] bg-black/10 p-3 text-[10px] text-[#7D8494]">{hotel.address}</div>}</div>
   </section>

   {allAmenities.length>0&&<section className="rounded-2xl border border-white/[.06] bg-[#10141C] p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Amenities</h2>{allAmenities.length>8&&<button onClick={()=>setShowAllAmenities(value=>!value)} className="text-[9px] font-semibold text-violet-300">{showAllAmenities?'Show less':`+${allAmenities.length-8} more`}</button>}</div><div className="mt-3 flex flex-wrap gap-2">{displayedAmenities.map(item=><span key={item} className="rounded-xl border border-white/[.06] bg-white/[.025] px-2.5 py-1.5 text-[9px] text-[#A0A6B4]">{item}</span>)}</div></section>}

   <section><div className="mb-3"><h2 className="text-base font-bold">Choose a room</h2><p className="mt-1 text-[9px] text-[#666D7E]">Select the room you want before continuing.</p></div>{hotel.hotel_rooms?.length?<div className="grid gap-3 sm:grid-cols-2">{hotel.hotel_rooms.map(room=><button key={room.room_id} onClick={()=>setSelectedRoom(room)} className={`rounded-2xl border p-4 text-left transition ${selectedRoom?.room_id===room.room_id?'border-violet-500/35 bg-violet-500/[.07]':'border-white/[.07] bg-[#11141C] hover:border-white/[.12]'}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-semibold">{room.room_type}</h3>{selectedRoom?.room_id===room.room_id&&<span className="rounded-full bg-violet-500 px-2 py-0.5 text-[7px] font-bold">SELECTED</span>}</div>{room.description&&<p className="mt-1 line-clamp-2 text-[9px] leading-relaxed text-[#6F7585]">{room.description}</p>}<p className="mt-2 text-[9px] text-[#858B9A]">Up to {room.max_guests} guest{room.max_guests===1?'':'s'}{room.bed_type?` · ${room.bed_type}`:''}</p></div><div className="shrink-0 text-right"><p className="text-sm font-bold text-violet-200">₦{Number(room.price_per_night).toLocaleString()}</p><p className="text-[8px] text-[#62697A]">per night</p></div></div>{room.amenities?.length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{room.amenities.slice(0,4).map(item=><span key={item} className="rounded-lg border border-white/[.05] px-2 py-1 text-[8px] text-[#777E8E]">{item}</span>)}</div>}</button>)}</div>:<div className="rounded-2xl border border-dashed border-white/[.08] p-10 text-center text-[10px] text-[#666D7E]">No rooms are currently available.</div>}</section>

   {!reservationSettings.enabled&&selectedRoom&&<section className="rounded-2xl border border-white/[.06] bg-[#10141C] p-4"><h2 className="text-sm font-semibold">Stay dates</h2><div className="mt-4 grid grid-cols-2 gap-3"><DateField label="Check-in" value={checkIn} min={tomorrowStr} onChange={value=>{setCheckIn(value);if(checkOut&&checkOut<=value)setCheckOut('')}}/><DateField label="Check-out" value={checkOut} min={minCheckout()} onChange={setCheckOut}/></div>{nights>0&&<div className="mt-4 grid grid-cols-2 gap-2"><Fact label="Nights" value={String(nights)}/><Fact label="Stay total" value={`₦${totalPrice.toLocaleString()}`}/></div>}</section>}

   {reservationSettings.enabled&&selectedRoom&&<section className="rounded-2xl border border-violet-500/15 bg-violet-500/[.05] p-4"><p className="text-sm font-semibold">Reservation mode</p><p className="mt-1 text-[10px] leading-relaxed text-[#858B9A]">Continue to the current WeHouse hotel reservation flow for this room.</p>{reservationFee>0&&<p className="mt-3 text-[10px] font-semibold text-violet-200">Reservation fee: ₦{reservationFee.toLocaleString()}</p>}</section>}

   <section className="rounded-2xl border border-white/[.06] bg-[#10141C] p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Guest reviews</h2><p className="mt-1 text-[9px] text-[#666D7E]">{reviews.length} review{reviews.length===1?'':'s'}</p></div><button onClick={()=>setShowReviewForm(value=>!value)} className="rounded-xl border border-white/[.08] px-3 py-2 text-[9px] font-semibold text-violet-300">{showReviewForm?'Cancel':'Write review'}</button></div>{showReviewForm&&<div className="mt-4 space-y-3 rounded-2xl border border-white/[.06] bg-black/10 p-3"><div className="flex gap-1">{[1,2,3,4,5].map(value=><button key={value} onClick={()=>setReviewRating(value)} className={`text-lg ${value<=reviewRating?'text-amber-300':'text-[#444A58]'}`}>★</button>)}</div><textarea value={reviewComment} onChange={event=>setReviewComment(event.target.value)} rows={3} placeholder="Share your experience" className="w-full resize-none rounded-xl border border-white/[.08] bg-[#171B24] p-3 text-xs outline-none focus:border-violet-500/40"/><button onClick={()=>void submitReview()} disabled={submittingReview} className="h-11 w-full rounded-xl bg-violet-500 text-[10px] font-semibold disabled:opacity-50">{submittingReview?'Submitting…':'Submit review'}</button></div>}<div className="mt-4 space-y-2">{reviews.length?reviews.slice(0,6).map(review=><div key={review.review_id} className="rounded-xl border border-white/[.05] bg-black/10 p-3"><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-semibold">@{review.profiles?.username||'guest'}</p><p className="text-[9px] text-amber-300">{'★'.repeat(Number(review.rating||0))}</p></div>{review.comment&&<p className="mt-2 text-[10px] leading-relaxed text-[#858B9A]">{review.comment}</p>}</div>):<p className="py-5 text-center text-[10px] text-[#666D7E]">No reviews yet.</p>}</div></section>
  </main>
  <div className="fixed inset-x-0 bottom-0 z-50 border-t border-white/[.08] bg-[#090B12]/96 p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] backdrop-blur-xl"><div className="mx-auto max-w-5xl"><button onClick={proceed} disabled={!selectedRoom} className="h-12 w-full rounded-2xl bg-violet-500 text-xs font-semibold disabled:opacity-40">{reservationSettings.enabled?'Continue reservation':'Continue booking'}</button></div></div>
 </div>
}

function DateField({label,value,min,onChange}:{label:string;value:string;min:string;onChange:(value:string)=>void}){return <label><span className="mb-1.5 block text-[9px] text-[#777E8E]">{label}</span><input type="date" value={value} min={min} onChange={event=>onChange(event.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#171B24] px-3 text-xs outline-none focus:border-violet-500/40"/></label>}
function Fact({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.05] bg-black/10 p-3"><p className="text-[8px] uppercase tracking-wide text-[#62697A]">{label}</p><p className="mt-1 text-[11px] font-semibold">{value}</p></div>}
