import { useEffect,useRef,useState } from 'react';
import {
  createInspectionRequest,
  createReservation,
  getInspectionRequestForReservation,
  getListing,
  getReservationForListing,
  supabase,
  updateReservationPlan,
} from '@/lib/supabase';
import { LISTING_STATUS_COLORS,LISTING_STATUS_LABELS } from '@/types';
import { usePlatformSettings } from '@/hooks/usePlatformSettings';
import type { Listing,ListingStatus,Profile,RentalDuration } from '@/types';
import RentalPlanSelector from '@/components/RentalPlanSelector';
import { Toaster,toast } from 'sonner';

type Props={listingId:string;onNavigate:()=>void;isSaved:boolean;onToggleSave:()=>void;profile:Profile;onGoToChat:(convId:string)=>void};
type Popup='plans'|'confirmed'|'inspection_requested'|'edit_plan';
type Plan={durationYears:RentalDuration;year1Upfront:number;monthlyInstallment:number};

export default function ListingDetail({listingId,onNavigate,profile}:Props){
 const[listing,setListing]=useState<Listing|null>(null),[loading,setLoading]=useState(true),[imageIndex,setImageIndex]=useState(0),[reservation,setReservation]=useState<any>(null),[inspection,setInspection]=useState<any>(null),[popup,setPopup]=useState<Popup>('plans'),[showPopup,setShowPopup]=useState(false),[plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[paystackReady,setPaystackReady]=useState(false);
 const{getNumber}=usePlatformSettings();const reservationFee=getNumber('reservation_fee',5000);
 useEffect(()=>{void(async()=>{setLoading(true);const[{listing:data},{data:pk}]=await Promise.all([getListing(listingId),supabase.rpc('get_setting_v2',{p_key:'paystack_public_key'})]);setListing(data);setPaystackReady(Boolean(pk));if(data&&profile){const{reservation:r}=await getReservationForListing(listingId,profile.user_id);if(r){setReservation(r);if(r.rental_plan_years)setPlan({durationYears:r.rental_plan_years as RentalDuration,year1Upfront:0,monthlyInstallment:0});const{inspection:i}=await getInspectionRequestForReservation(r.id);if(i)setInspection(i)}}setLoading(false)})()},[listingId,profile.user_id]);
 function support(kind:'property'|'reservation'|'inspection'|'payment'='property'){
  if(!listing)return;
  const contextId=kind==='inspection'?(inspection?.id||reservation?.id||listing.listing_id):kind==='reservation'||kind==='payment'?(reservation?.id||listing.listing_id):listing.listing_id;
  const contextType=kind==='inspection'?'property_inspection':kind==='reservation'?'apartment_reservation':kind==='payment'?'apartment_payment':'property_listing';
  const subject=kind==='inspection'?`Inspection help · ${listing.title}`:kind==='reservation'?`Reservation help · ${listing.title}`:kind==='payment'?`Rent payment help · ${listing.title}`:`Question about ${listing.title}`;
  window.dispatchEvent(new CustomEvent('openSupportChat',{detail:{category:kind==='inspection'?'property_inspection':kind==='payment'?'payment':'apartment_booking',subject,contextType,contextId,contextSnapshot:{listing_id:listing.listing_id,listing_title:listing.title,location:[listing.city,listing.state].filter(Boolean).join(', '),price:listing.price,property_type:listing.property_type||listing.sub_type||null,reservation_id:reservation?.id||null,reservation_status:reservation?.status||null,inspection_id:inspection?.id||null,inspection_status:inspection?.status||null}}}));
 }
 function openReservation(){setPopup(reservation?(inspection?'inspection_requested':'confirmed'):'plans');setShowPopup(true)}
 async function reserve(){if(!listing||!plan)return;setBusy(true);const{reservation:r,error}=await createReservation(listingId,profile.user_id,{title:listing.title,price:listing.price,location:[listing.city,listing.state].filter(Boolean).join(', ')});if(error||!r){setBusy(false);return toast.error(error?.message||'Could not reserve this property')}const{reservation:updated,error:planError}=await updateReservationPlan(r.id,plan.durationYears);setBusy(false);if(planError)return toast.error(planError.message);const next=updated||{...r,rental_plan_years:plan.durationYears};setReservation(next);setPopup('confirmed');toast.success('Property reserved')}
 async function savePlan(){if(!reservation||!plan)return;setBusy(true);const{reservation:updated,error}=await updateReservationPlan(reservation.id,plan.durationYears);setBusy(false);if(error)return toast.error(error.message);setReservation(updated||{...reservation,rental_plan_years:plan.durationYears});setPopup('confirmed');toast.success('Rental plan updated')}
 async function requestInspection(){if(!listing||!reservation)return;setBusy(true);const{inspection:i,error}=await createInspectionRequest(reservation.id,listingId,profile.user_id,`Inspection requested for ${listing.title}`);setBusy(false);if(error)return toast.error(error.message);if(i)setInspection(i);setPopup('inspection_requested');toast.success('Inspection requested')}
 if(loading)return <div className="grid min-h-[70dvh] place-items-center bg-[#090A0F]"><div className="h-7 w-7 animate-spin rounded-full border-2 border-blue-500 border-t-transparent"/></div>;
 if(!listing)return <div className="grid min-h-[70dvh] place-items-center bg-[#090A0F] px-4 text-center text-white"><div><p className="text-sm font-semibold">Property unavailable</p><button onClick={onNavigate} className="mt-4 text-xs text-blue-400">← Go back</button></div></div>;
 const images=listing.images?.length?listing.images:['https://placehold.co/900x650/171922/666A7A?text=No+Image'];const status=(listing.status||'available') as ListingStatus;const color=(LISTING_STATUS_COLORS as Record<string,string>)[status]||LISTING_STATUS_COLORS.available;const label=(LISTING_STATUS_LABELS as Record<string,string>)[status]||'Available';const available=status==='available';
 return <div className="min-h-[100dvh] overflow-x-hidden bg-[#090A0F] pb-10 text-white"><Toaster position="top-center" richColors/><div className="mx-auto max-w-6xl"><section className="relative overflow-hidden bg-[#11141C] sm:m-4 sm:rounded-3xl"><img src={images[imageIndex]} alt={listing.title} className="aspect-[4/3] w-full object-cover sm:aspect-[16/9]"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-black/20"/><button onClick={onNavigate} className="absolute left-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-black/50 backdrop-blur">←</button><span className={`absolute bottom-4 left-4 rounded-full border px-3 py-1.5 text-[9px] font-bold uppercase ${color}`}>{label}</span>{images.length>1&&<div className="absolute bottom-4 right-4 flex gap-1.5">{images.map((_,i)=><button key={i} onClick={()=>setImageIndex(i)} className={`h-2 rounded-full ${i===imageIndex?'w-5 bg-white':'w-2 bg-white/40'}`}/>)}</div>}</section>
 <main className="px-4 py-5 sm:px-6 lg:px-8"><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="min-w-0 space-y-5"><section><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><h1 className="break-words text-2xl font-bold">{listing.title}</h1><p className="mt-1 text-xs text-[#777B8B]">{[listing.address,listing.city,listing.state].filter(Boolean).join(', ')}</p></div><p className="shrink-0 text-xl font-bold text-blue-400">₦{Number(listing.price||0).toLocaleString()}<span className="ml-1 text-[10px] font-normal text-[#686C7D]">/year</span></p></div></section>
 <section className="grid grid-cols-3 gap-2"><Fact label="Type" value={listing.sub_type?listing.sub_type.replace(/_/g,' '):listing.property_type||'Apartment'}/><Fact label="Bathrooms" value={listing.bathrooms||'—'}/><Fact label="Availability" value={(listing.availability_status||status).replace(/_/g,' ')}/></section>
 {listing.description&&<section className="rounded-2xl border border-white/[.06] bg-[#11141C] p-4 sm:p-5"><h2 className="text-sm font-semibold">About this property</h2><p className="mt-2 whitespace-pre-wrap text-xs leading-6 text-[#9599A8]">{listing.description}</p></section>}
 {listing.videos?.length>0&&<section><h2 className="mb-3 text-sm font-semibold">Property videos</h2><div className="grid gap-3 sm:grid-cols-2">{listing.videos.map((url,i)=><Video key={url} url={url} index={i}/>)}</div></section>}
 <section className="rounded-2xl border border-blue-500/12 bg-blue-500/[.035] p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-blue-500/10 font-bold text-blue-300">W</div><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">Questions about this property?</h2><p className="mt-1 text-[11px] leading-relaxed text-[#7C8191]">Message WeHouse Support. This property is linked to the conversation automatically, and you can send photos, documents or a voice note.</p></div></div><button onClick={()=>support('property')} className="mt-4 h-11 w-full rounded-xl border border-blue-500/20 bg-blue-500/10 text-xs font-semibold text-blue-300">Message WeHouse Support</button></section></div>
 <aside className="space-y-3 lg:sticky lg:top-20 lg:self-start">{available?<section className="rounded-3xl border border-white/[.07] bg-[#11141C] p-5">{reservation?<><p className="text-[10px] font-semibold uppercase tracking-wide text-emerald-300">Reservation active</p><h2 className="mt-2 text-lg font-bold">Your property reservation</h2><p className="mt-2 text-[11px] leading-relaxed text-[#777B8B]">{inspection?'Inspection is linked to this reservation.':'Review your rental plan or request an inspection.'}</p>{inspection&&<div className="mt-3 rounded-xl bg-blue-500/[.06] p-3 text-[10px] text-blue-300">Inspection · <span className="capitalize">{String(inspection.status||'pending').replace(/_/g,' ')}</span></div>}<button onClick={openReservation} className="mt-4 h-12 w-full rounded-xl bg-blue-500 text-sm font-semibold">{inspection?'View inspection':'Reservation options'}</button><button onClick={()=>support(inspection?'inspection':'reservation')} className="mt-2 h-11 w-full rounded-xl border border-white/[.08] text-xs font-semibold text-[#B7BAC5]">Get help</button></>:<><p className="text-[10px] font-semibold uppercase tracking-wide text-blue-300">Available</p><h2 className="mt-2 text-lg font-bold">Reserve this property</h2><p className="mt-2 text-[11px] leading-relaxed text-[#777B8B]">Choose a rental plan, reserve the property and decide whether you want an inspection before proceeding.</p>{paystackReady&&<div className="mt-3 flex items-center justify-between rounded-xl bg-white/[.035] p-3 text-xs"><span className="text-[#747889]">Reservation fee</span><span className="font-semibold">₦{reservationFee.toLocaleString()}</span></div>}<button onClick={openReservation} className="mt-4 h-12 w-full rounded-xl bg-blue-500 text-sm font-semibold">View rental plans</button></>}</section>:<section className="rounded-3xl border border-amber-500/15 bg-amber-500/[.04] p-5"><h2 className="text-sm font-semibold">Currently unavailable</h2><p className="mt-2 text-[11px] text-[#8A8E9D]">This property is not open for a new reservation right now.</p></section>}</aside></div></main></div>
 {showPopup&&<div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/65 p-0 sm:items-center sm:p-4" onClick={()=>setShowPopup(false)}><section className="max-h-[92dvh] w-full max-w-lg overflow-y-auto rounded-t-3xl border border-white/[.08] bg-[#11141C] p-5 text-white sm:rounded-3xl" onClick={e=>e.stopPropagation()}>{(popup==='plans'||popup==='edit_plan')&&<><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{popup==='edit_plan'?'Change rental plan':'Choose your rental plan'}</h2><p className="mt-1 text-[10px] text-[#747889]">{listing.title}</p></div><button onClick={()=>setShowPopup(false)} className="text-[#777B8B]">×</button></div><div className="mt-5"><RentalPlanSelector annualRent={listing.price||0} subType={listing.sub_type||'long_stay'} securityDepositAmount={listing.security_deposit_amount} onSelectPlan={setPlan}/></div><button onClick={()=>void (popup==='edit_plan'?savePlan():reserve())} disabled={!plan||busy} className="mt-5 h-12 w-full rounded-xl bg-blue-500 text-sm font-semibold disabled:opacity-40">{busy?'Saving…':popup==='edit_plan'?'Save plan':'Reserve property'}</button>{popup==='edit_plan'&&<button onClick={()=>setPopup('confirmed')} className="mt-2 h-10 w-full text-xs text-[#777B8B]">Cancel</button>}</>}
 {popup==='confirmed'&&reservation&&<><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase text-emerald-300">Reservation confirmed</p><h2 className="mt-2 text-lg font-bold">Choose what happens next</h2></div><button onClick={()=>setShowPopup(false)} className="text-[#777B8B]">×</button></div><div className="mt-4 rounded-2xl bg-white/[.035] p-4 text-xs"><Row label="Property" value={listing.title}/><Row label="Plan" value={`${reservation.rental_plan_years||plan?.durationYears||1} year`}/>{paystackReady&&<Row label="Reservation fee" value={`₦${reservationFee.toLocaleString()}`}/>}</div><div className="mt-4 grid gap-2"><button onClick={()=>setPopup('edit_plan')} className="h-11 rounded-xl border border-white/[.08] text-xs font-semibold">Edit rental plan</button><button onClick={()=>void requestInspection()} disabled={busy} className="h-11 rounded-xl bg-blue-500 text-xs font-semibold disabled:opacity-40">{busy?'Requesting…':'Request inspection'}</button><button onClick={()=>{setShowPopup(false);support('payment')}} className="h-11 rounded-xl bg-emerald-600 text-xs font-semibold">Proceed with rent / payment help</button><button onClick={()=>{setShowPopup(false);support('reservation')}} className="h-10 text-xs text-blue-300">Message WeHouse about this reservation</button></div></>}
 {popup==='inspection_requested'&&<><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase text-blue-300">Inspection requested</p><h2 className="mt-2 text-lg font-bold">WeHouse is handling your inspection</h2></div><button onClick={()=>setShowPopup(false)} className="text-[#777B8B]">×</button></div><div className="mt-4 rounded-2xl border border-blue-500/10 bg-blue-500/[.04] p-4"><p className="text-xs font-semibold">Current status</p><p className="mt-1 text-[11px] capitalize text-blue-300">{String(inspection?.status||'pending').replace(/_/g,' ')}</p><p className="mt-3 text-[10px] leading-relaxed text-[#858A9A]">The inspection request is already linked to your account and property. Support can see that context when you contact them.</p></div><button onClick={()=>{setShowPopup(false);support('inspection')}} className="mt-4 h-12 w-full rounded-xl bg-blue-500 text-sm font-semibold">Message Support about inspection</button><button onClick={()=>setShowPopup(false)} className="mt-2 h-10 w-full text-xs text-[#777B8B]">Close</button></>}</section></div>}
 </div>
}
function Fact({label,value}:{label:string;value:string|number}){return <div className="min-w-0 rounded-2xl border border-white/[.06] bg-[#11141C] p-3 text-center"><p className="truncate text-xs font-semibold capitalize">{String(value).replace(/_/g,' ')}</p><p className="mt-1 text-[9px] text-[#626678]">{label}</p></div>}
function Row({label,value}:{label:string;value:string}){return <div className="flex items-start justify-between gap-3 border-b border-white/[.05] py-2 last:border-0"><span className="text-[#747889]">{label}</span><span className="max-w-[65%] text-right font-medium">{value}</span></div>}
function Video({url,index}:{url:string;index:number}){const ref=useRef<HTMLVideoElement>(null);const[playing,setPlaying]=useState(false);return <div className="relative overflow-hidden rounded-2xl bg-[#11141C]"><video ref={ref} src={url} className="aspect-video w-full object-cover" controls onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)}/>{!playing&&<span className="pointer-events-none absolute left-3 top-3 rounded-lg bg-black/50 px-2 py-1 text-[9px]">Video {index+1}</span>}</div>}
