import { useEffect,useState } from 'react';
import { getMyBookingConversations,BOOKING_STATUS_LABELS } from '@/lib/supabase/worker-bookings';
import BookingNegotiationChat from '@/components/BookingNegotiationChat';
import type { Profile } from '@/types';
import { Toaster } from 'sonner';

type Props={profile:Profile;onBack:()=>void};

export default function MyBookings({profile,onBack}:Props){
 const[conversations,setConversations]=useState<any[]>([]),[loading,setLoading]=useState(true),[activeChat,setActiveChat]=useState<{conversationId:string;bookingId:string}|null>(null),[filter,setFilter]=useState('all');
 useEffect(()=>{void loadConversations()},[profile.user_id]);
 async function loadConversations(){setLoading(true);const{conversations:rows}=await getMyBookingConversations(profile.user_id);setConversations(rows||[]);setLoading(false)}
 const filtered=filter==='all'?conversations:conversations.filter((c:any)=>c.booking_status===filter);
 const filters=[['all','All'],['booking_requested','Pending'],['negotiating','Negotiating'],['waiting_payment','Pay'],['confirmed','Confirmed'],['in_progress','Active'],['completed_pending_approval','Done'],['approved_released','Paid'],['cancelled','Cancelled'],['refunded','Refunded']];
 if(activeChat)return <BookingNegotiationChat conversationId={activeChat.conversationId} bookingId={activeChat.bookingId} profile={profile} isWorker={false} onClose={()=>{setActiveChat(null);void loadConversations()}}/>;
 return <div className="min-h-[100dvh] bg-[#0A0A0F] pb-6 text-white"><Toaster position="top-center" richColors/><header className="sticky top-0 z-40 border-b border-white/[.06] bg-[#0A0A0F]/95 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-3xl items-center gap-3"><button onClick={onBack} className="grid h-9 w-9 place-items-center rounded-xl border border-white/[.07] bg-white/[.04] text-[#8A8B9C]">←</button><div><h1 className="text-base font-bold">My Worker Bookings</h1><p className="mt-0.5 text-[10px] text-[#5C5E72]">{conversations.length} booking{conversations.length===1?'':'s'} · completed records are retained</p></div></div></header><main className="mx-auto max-w-3xl space-y-4 px-4 py-4"><div className="flex gap-1.5 overflow-x-auto pb-1 scrollbar-hide">{filters.map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[10px] font-medium ${filter===key?'bg-blue-500/15 text-blue-400':'bg-[#12121A] text-[#66697B]'}`}>{label}</button>)}</div>{loading?<Loading/>:filtered.length===0?<Empty onBack={onBack}/>:<div className="space-y-2">{filtered.map(conv=>{const status=BOOKING_STATUS_LABELS[conv.booking_status];return <button key={conv.conversation_id} onClick={()=>setActiveChat({conversationId:conv.conversation_id,bookingId:conv.booking_id})} className="w-full rounded-2xl border border-white/[.06] bg-[#12121A] p-4 text-left transition hover:border-blue-500/25"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><span className="text-[9px] text-[#5C5E72]">#{conv.booking_code}</span>{Number(conv.unread_count||0)>0&&<span className="grid h-4 min-w-4 place-items-center rounded-full bg-red-500 px-1 text-[8px] font-bold">{conv.unread_count}</span>}</div><p className="mt-1 text-xs font-semibold">{conv.service_type||'Service booking'}</p><p className="mt-1 truncate text-[10px] text-[#66697B]">{conv.other_person_name||'Worker'}</p></div>{status&&<span className={`shrink-0 rounded-full px-2 py-1 text-[8px] ${status.color}`}>{status.label}</span>}</div>{conv.last_message&&<p className="mt-3 truncate text-[10px] text-[#858A9B]">{conv.last_message}</p>}<div className="mt-3 flex items-end justify-between gap-3 border-t border-white/[.05] pt-3">{Number(conv.negotiated_amount||0)>0?<p className="text-xs font-semibold text-emerald-300">₦{Number(conv.negotiated_amount).toLocaleString()}</p>:<span/>}<p className="text-[9px] text-[#565A6B]">{conv.updated_at?new Date(conv.updated_at).toLocaleDateString():''}</p></div></button>})}</div>}</main></div>;
}

function Loading(){return <div className="grid min-h-56 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-blue-500 border-t-transparent"/></div>}
function Empty({onBack}:{onBack:()=>void}){return <div className="rounded-3xl border border-dashed border-white/[.08] px-5 py-14 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-500/10 text-blue-300">⌂</div><p className="mt-4 text-sm font-semibold">No bookings in this section</p><p className="mx-auto mt-2 max-w-sm text-[10px] leading-relaxed text-[#66697B]">Worker requests and job history will appear here.</p><button onClick={onBack} className="mt-4 rounded-xl bg-blue-500 px-4 py-2.5 text-[10px] font-semibold">Find workers</button></div>}
