import { useEffect,useMemo,useState } from 'react';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';
import { toast,Toaster } from 'sonner';

type Props={profile:Profile;onNavigate:(page:string,id?:string)=>void};
type Activity={id:string;type:string;title:string;message:string|null;read:boolean;created_at:string;source_type?:string|null;source_id?:string|null;destination_route?:string|null;destination_params?:Record<string,unknown>|null};
export default function Notifications({profile,onNavigate}:Props){
 const[rows,setRows]=useState<Activity[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(quiet=false){if(!quiet)setLoading(true);const{data,error}=await supabase.from('notifications').select('id,type,title,message,read,created_at,source_type,source_id,destination_route,destination_params').eq('recipient_id',profile.user_id).order('created_at',{ascending:false}).limit(100);if(error){setError(error.message)}else{setRows((data||[]) as Activity[]);setError('')}if(!quiet)setLoading(false)}
 useEffect(()=>{void load();const channel=supabase.channel(`user-activity:${profile.user_id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`recipient_id=eq.${profile.user_id}`},()=>void load(true)).subscribe();return()=>{void supabase.removeChannel(channel)}},[profile.user_id]);
 const groups=useMemo(()=>{const result=new Map<string,Activity[]>();for(const row of rows){const day=dayLabel(row.created_at);result.set(day,[...(result.get(day)||[]),row])}return [...result]},[rows]);
 async function open(row:Activity){if(!row.read){await supabase.rpc('mark_my_notification_read',{p_notification_id:row.id});setRows(current=>current.map(item=>item.id===row.id?{...item,read:true}:item))}const route=row.destination_route||legacyRoute(row.type);const params=row.destination_params||{};const id=String(params.listing_id||params.listingId||params.conversation_id||params.conversationId||params.contextId||params.booking_id||params.bookingId||params.sharedGroupId||row.source_id||'');if(route)onNavigate(route,id||undefined)}
 async function markAll(){const{error}=await supabase.rpc('mark_all_my_notifications_read');if(error)return toast.error(error.message);setRows(current=>current.map(row=>({...row,read:true})));toast.success('Activity marked as read')}
 const unread=rows.filter(row=>!row.read).length;
 return <div className="min-h-[100dvh] bg-[#090B10] pb-28 text-white"><Toaster position="top-center" richColors/><header className="sticky top-0 z-40 border-b border-white/[.06] bg-[#090B10]/95 px-4 py-4 backdrop-blur-xl"><div className="mx-auto flex max-w-4xl items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.24em] text-violet-400">WEHOUSE</p><h1 className="mt-1 text-xl font-bold">Notifications</h1><p className="mt-1 text-[10px] text-[#747A8B]">Updates that need your attention, linked to the exact place they happened.</p></div>{unread>0&&<button onClick={()=>void markAll()} className="shrink-0 rounded-full border border-white/[.08] px-3 py-2 text-[9px] font-semibold text-violet-300">Mark all read</button>}</div></header><main className="mx-auto max-w-4xl px-4 py-5">{loading?<Skeleton/>:error?<ErrorState text={error} retry={()=>void load()}/>:rows.length===0?<Empty/>:<div className="space-y-7">{groups.map(([day,items])=><section key={day}><h2 className="mb-2 text-[9px] font-bold uppercase tracking-[.15em] text-[#656B7C]">{day}</h2><div className="divide-y divide-white/[.055] border-y border-white/[.06]">{items.map(row=><button key={row.id} onClick={()=>void open(row)} className="flex min-h-20 w-full items-start gap-3 py-3 text-left"><span className={`mt-1 grid h-9 w-9 shrink-0 place-items-center rounded-full ${row.read?'bg-white/[.035] text-[#73798A]':'bg-violet-500/12 text-violet-300'}`}>{icon(row.type)}</span><span className="min-w-0 flex-1"><span className={`block text-xs ${row.read?'font-medium text-[#A3A7B3]':'font-semibold text-white'}`}>{row.title}</span>{row.message&&<span className="mt-1 line-clamp-2 block text-[10px] leading-4 text-[#717788]">{row.message}</span>}<span className="mt-1.5 block text-[8px] text-[#555C6D]">{new Date(row.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></span>{!row.read&&<span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-violet-400"/>}</button>)}</div></section>)}</div>}</main></div>;
}
function legacyRoute(type:string){if(type==='roommate_interest'||type==='shared_home_invite'||type==='shared_home_response')return'roommate';if(type.includes('message')||type==='roommate_match'||type==='missed_call')return'messages';if(type.includes('booking')||type.includes('payment')||type.includes('inspection')||type.includes('shared_home'))return'my_reservations';return''}
function dayLabel(value:string){const date=new Date(value),today=new Date(),yesterday=new Date();yesterday.setDate(today.getDate()-1);if(date.toDateString()===today.toDateString())return'Today';if(date.toDateString()===yesterday.toDateString())return'Yesterday';return date.toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'})}
function icon(type:string){if(type.includes('message'))return'↗';if(type.includes('payment'))return'₦';if(type.includes('roommate'))return'◉';if(type.includes('security'))return'⌾';if(type.includes('booking')||type.includes('reservation'))return'✓';return'•'}
function Skeleton(){return <div className="space-y-3">{[1,2,3,4].map(i=><div key={i} className="h-20 animate-pulse border-b border-white/[.06] bg-white/[.015]"/>)}</div>}
function Empty(){return <div className="grid min-h-[55dvh] place-items-center text-center"><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-violet-500/10 text-violet-300">✓</div><p className="mt-4 text-sm font-semibold">You’re up to date</p><p className="mt-2 max-w-xs text-[10px] leading-5 text-[#6C7282]">Booking actions, relevant saved-search matches, messages and account updates will appear here.</p></div></div>}
function ErrorState({text,retry}:{text:string;retry:()=>void}){return <div className="rounded-2xl border border-red-500/15 p-5 text-center"><p className="text-xs font-semibold">Notifications could not be loaded</p><p className="mt-1 text-[9px] text-[#757B8A]">{text}</p><button onClick={retry} className="mt-3 text-[10px] font-semibold text-violet-300">Try again</button></div>}
