import { useEffect,useState } from 'react';
import { updatePrivacySettings } from '@/lib/supabase';
import { getCallPreferences,setCallPreferences } from '@/lib/private-calls';
import { Toaster,toast } from 'sonner';
import AccountShell from '@/components/AccountShell';
import type { Profile } from '@/types';

type Props={profile:Profile;onUpdate:(p:Profile)=>void;onBack:()=>void};
type PrivacyKey='privacy_profile_visible'|'privacy_search_visible';
export default function PrivacySettingsPhase10({profile,onUpdate,onBack}:Props){
 const[privacy,setPrivacy]=useState<Record<PrivacyKey,boolean>>({privacy_profile_visible:profile.privacy_profile_visible!==false,privacy_search_visible:profile.privacy_search_visible!==false});
 const[savingPrivacy,setSavingPrivacy]=useState<PrivacyKey|null>(null),[audio,setAudio]=useState(true),[video,setVideo]=useState(false),[callLoading,setCallLoading]=useState(true),[callSaving,setCallSaving]=useState(false);
 const canCall=['user','worker'].includes(profile.role),isUser=profile.role==='user';
 useEffect(()=>{if(!canCall){setCallLoading(false);return}void(async()=>{const result=await getCallPreferences();if(result.error)toast.error(result.error.message);if(result.preferences){setAudio(result.preferences.allow_audio_calls);setVideo(result.preferences.allow_video_calls)}setCallLoading(false)})()},[profile.user_id,canCall]);
 async function togglePrivacy(key:PrivacyKey,value:boolean){const previous=privacy;setPrivacy(current=>({...current,[key]:value}));setSavingPrivacy(key);const{profile:updated,error}=await updatePrivacySettings(profile.user_id,{[key]:value} as any);setSavingPrivacy(null);if(error||!updated){setPrivacy(previous);toast.error(error?.message||'Could not save privacy setting');return}onUpdate(updated);toast.success('Privacy updated')}
 async function saveCalls(nextAudio:boolean,nextVideo:boolean){if(callSaving)return;const prevAudio=audio,prevVideo=video;setAudio(nextAudio);setVideo(nextVideo);setCallSaving(true);const result=await setCallPreferences(nextAudio,nextVideo);setCallSaving(false);if(result.error||!result.preferences){setAudio(prevAudio);setVideo(prevVideo);toast.error(result.error?.message||'Could not save call preference');return}setAudio(result.preferences.allow_audio_calls);setVideo(result.preferences.allow_video_calls);toast.success('Call privacy updated')}
 return <AccountShell profile={profile} title="Privacy" description="Control discovery and who may call you inside private WeHouse conversations." onBack={onBack}><Toaster position="top-center" richColors/>
  {isUser&&<section className="overflow-hidden rounded-2xl border border-white/[.06] bg-[#11141C]"><SectionTitle title="Roommate discovery" text="Controls used by Roommate matching only."/><Row label="Roommate profile visibility" text="Allow compatible roommate candidates to see your roommate profile while matching is active." value={privacy.privacy_profile_visible} disabled={savingPrivacy==='privacy_profile_visible'} onChange={v=>void togglePrivacy('privacy_profile_visible',v)}/><Row label="Roommate discovery" text="Allow your profile to participate in roommate matching when you turn matching on." value={privacy.privacy_search_visible} disabled={savingPrivacy==='privacy_search_visible'} onChange={v=>void togglePrivacy('privacy_search_visible',v)}/></section>}
  {canCall&&<section className="mt-4 overflow-hidden rounded-2xl border border-white/[.06] bg-[#11141C]"><SectionTitle title="Private calls" text="Calls can only come from someone who already has an eligible private Roommate or Worker-booking conversation with you."/>{callLoading?<div className="grid min-h-24 place-items-center"><div className="h-6 w-6 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>:<><Row label="Allow audio calls" text="Let eligible private chat participants ring you for an audio call. Enabled by default." value={audio} disabled={callSaving} onChange={v=>void saveCalls(v,video)}/><Row label="Allow video calls" text="Let eligible private chat participants ring your camera. Off by default until you choose to enable it." value={video} disabled={callSaving} onChange={v=>void saveCalls(audio,v)}/></>}</section>}
  {!isUser&&!canCall&&<div className="rounded-2xl border border-white/[.06] bg-[#11141C] p-6 text-center"><p className="text-sm font-semibold">No personal discovery controls for this role</p><p className="mx-auto mt-2 max-w-md text-[10px] leading-relaxed text-[#6F7585]">Operational visibility is controlled by role permissions and workflow rules.</p></div>}
 </AccountShell>
}
function SectionTitle({title,text}:{title:string;text:string}){return <div className="border-b border-white/[.05] p-4 sm:p-5"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-[9px] leading-relaxed text-[#6F7585]">{text}</p></div>}
function Row({label,text,value,onChange,disabled}:{label:string;text:string;value:boolean;onChange:(v:boolean)=>void;disabled:boolean}){return <div className="flex min-h-[5rem] items-center justify-between gap-4 border-b border-white/[.05] p-4 last:border-b-0 sm:p-5"><div><p className="text-[12px] font-semibold">{label}</p><p className="mt-1 max-w-xl text-[9px] leading-relaxed text-[#6F7585]">{text}</p></div><button onClick={()=>onChange(!value)} disabled={disabled} aria-pressed={value} className={`relative h-6 w-11 shrink-0 rounded-full ${value?'bg-violet-500':'bg-[#2A2D38]'} disabled:opacity-50`}><span className={`absolute left-0.5 top-0.5 h-5 w-5 rounded-full bg-white transition-transform ${value?'translate-x-5':''}`}/></button></div>}
