import { useEffect,useMemo,useState } from 'react';
import { Toaster,toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import PropertyInspectionRequestPanel from '@/components/PropertyInspectionRequestPanel';
import PropertyPartnerFinancePanel from '@/components/PropertyPartnerFinancePanel';
import CommunicationInbox from '@/components/CommunicationInbox';
import type { Profile } from '@/types';

type PartnerTab='overview'|'requests'|'properties'|'finance'|'communication';
type FinanceView='wallet'|'earnings';
type Props={profile:Profile;onLogout:()=>void;onNavigate:(page:string)=>void;onGoToChat?:(convId?:string)=>void};
type Overview={properties:number;available:number;pendingRequests:number;inspections:number};
type EarningRelease={id:string;earning_type:string;status:'pending'|'available'|'held'|'reversed';net_amount:number;release_event:string|null;created_at:string};
const TABS:Array<{key:PartnerTab;label:string;description:string}>=[
 {key:'overview',label:'Overview',description:'Properties, requests and inspections at a glance'},
 {key:'requests',label:'Property Requests',description:'Submit properties and follow inspection progress'},
 {key:'properties',label:'My Properties',description:'Published properties managed by WeHouse'},
 {key:'finance',label:'Finance',description:'Wallet, earnings and withdrawals'},
 {key:'communication',label:'Communication',description:'Official WeHouse updates and human support'},
];
const money=(value:number)=>`₦${Number(value||0).toLocaleString('en-NG',{minimumFractionDigits:2})}`;

export default function PropertyOwnerDashboard({profile,onLogout,onNavigate}:Props){
 const[tab,setTab]=useState<PartnerTab>('overview');
 const current=useMemo(()=>TABS.find(item=>item.key===tab)!,[tab]);
 return <div className="min-h-[100dvh] bg-[#09090D] text-white"><Toaster position="top-center" richColors/><header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#09090D]/94 backdrop-blur-xl"><div className="mx-auto max-w-7xl px-4 pt-4 sm:px-5 lg:px-8 lg:pt-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-[9px] font-bold tracking-[.22em] text-violet-400">PROPERTY PARTNER</p><h1 className="mt-1 text-lg font-bold lg:text-xl">{current.label}</h1><p className="mt-1 max-w-xl text-[10px] leading-relaxed text-[#686A7D] lg:text-[11px]">{current.description}</p></div><div className="grid grid-cols-2 gap-2 sm:flex sm:shrink-0"><button onClick={()=>onNavigate('profile')} className="rounded-xl border border-white/[.08] bg-white/[.04] px-3 py-2 text-[10px] text-[#A5A6B5]">Account</button><button onClick={onLogout} className="rounded-xl border border-red-500/15 bg-red-500/[.05] px-3 py-2 text-[10px] text-red-300">Log out</button></div></div><div className="mt-4 overflow-x-auto pb-3 scrollbar-hide"><div className="flex min-w-max gap-1">{TABS.map(item=><button key={item.key} onClick={()=>setTab(item.key)} className={`rounded-xl px-3 py-2 text-[10px] font-semibold transition ${tab===item.key?'bg-violet-500 text-white':'text-[#6F7184] hover:bg-white/[.04] hover:text-white'}`}>{item.label}</button>)}</div></div></div></header><main className="mx-auto max-w-7xl px-4 py-5 pb-24 sm:px-5 lg:px-8 lg:py-8">{tab==='overview'&&<OverviewTab profile={profile} onTab={setTab}/>} {tab==='requests'&&<RequestsTab profile={profile}/>} {tab==='properties'&&<PropertiesTab profile={profile}/>} {tab==='finance'&&<FinanceTab profile={profile}/>} {tab==='communication'&&<CommunicationInbox profile={profile} title="Communication" description="Your WeHouse Official channel and one continuous human-support conversation."/>}</main></div>
}

function OverviewTab({profile,onTab}:{profile:Profile;onTab:(tab:PartnerTab)=>void}){
 const[data,setData]=useState<Overview|null>(null);
 useEffect(()=>{let active=true;(async()=>{const[listingsResult,requestsResult]=await Promise.all([supabase.from('listings').select('id,status,availability_status').or(`owner_id.eq.${profile.user_id},partner_id.eq.${profile.user_id}`),supabase.from('inspection_requests').select('id,status').eq('owner_id',profile.user_id)]);if(!active)return;const listings=listingsResult.data||[],requests=requestsResult.data||[];setData({properties:listings.length,available:listings.filter((row:any)=>row.availability_status==='available'||row.status==='approved').length,pendingRequests:requests.filter((row:any)=>['pending','scheduled'].includes(row.status)).length,inspections:requests.filter((row:any)=>row.status==='in_progress').length})})();return()=>{active=false}},[profile.user_id]);
 if(!data)return <Loading/>;
 return <div className="space-y-5"><section className="overflow-hidden rounded-3xl border border-violet-500/15 bg-gradient-to-br from-violet-500/[.13] via-[#151520] to-[#101018] p-5 sm:p-6 lg:p-7"><div className="grid gap-5 lg:grid-cols-[1.4fr_1fr] lg:items-end"><div><span className="rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1 text-[10px] font-semibold text-violet-300">YOUR PARTNERSHIP</span><h2 className="mt-4 max-w-2xl text-2xl font-bold leading-tight lg:text-3xl">Submit properties. Follow inspection. See what WeHouse publishes.</h2><p className="mt-2 max-w-xl text-xs leading-relaxed text-[#9395A8]">Home is for property activity. Earnings, withdrawals and bank details stay inside Finance.</p></div><div className="grid gap-2 sm:grid-cols-2 lg:flex lg:justify-end"><button onClick={()=>onTab('requests')} className="rounded-xl bg-violet-500 px-4 py-3 text-xs font-semibold hover:bg-violet-400">Submit property</button><button onClick={()=>onTab('properties')} className="rounded-xl border border-white/[.08] bg-white/[.04] px-4 py-3 text-xs font-semibold text-[#C4C5D0]">My properties</button></div></div></section><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Published properties" value={data.properties}/><Metric label="Available" value={data.available}/><Metric label="Pending requests" value={data.pendingRequests}/><Metric label="Inspections in progress" value={data.inspections}/></section></div>
}

function RequestsTab({profile}:{profile:Profile}){
 const[requests,setRequests]=useState<any[]>([]),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const{data,error}=await supabase.from('inspection_requests').select('id,request_code,property_address,property_type,property_state,property_city,expected_rent,status,created_at,scheduled_date,completed_at,notes,rejection_reason,gps_latitude,gps_longitude').eq('owner_id',profile.user_id).order('created_at',{ascending:false});if(error){toast.error(error.message||'Unable to load property requests');setRequests([])}else setRequests(data||[]);setLoading(false)}
 useEffect(()=>{void load()},[profile.user_id]);
 function contact(request:any){window.dispatchEvent(new CustomEvent('openSupportChat',{detail:{category:'property_inspection',subject:`Property inspection ${request.request_code||''}`.trim(),contextType:'property_inspection',contextId:request.id,contextSnapshot:{request_code:request.request_code,property_address:request.property_address,property_type:request.property_type,city:request.property_city,state:request.property_state,status:request.status}}}))}
 return <div className="space-y-6"><PropertyInspectionRequestPanel profile={profile}/><section><div className="mb-3 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold">Request & inspection history</h2><p className="mt-1 text-[10px] text-[#66687B]">Follow each submission from review through inspection and listing preparation.</p></div><button onClick={()=>void load()} className="w-fit rounded-lg border border-white/[.07] px-3 py-2 text-[9px] text-[#888A9B]">Refresh</button></div>{loading?<Loading/>:requests.length===0?<Empty title="No property requests yet" text="Use the form above to send your first property to WeHouse for review and inspection."/>:<div className="space-y-3">{requests.map(request=><section key={request.id} className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words text-xs font-semibold">{request.property_address||request.property_type||'Property request'}</p><p className="mt-1 break-words text-[10px] text-[#66687B]">{[request.property_city,request.property_state].filter(Boolean).join(', ')} {request.request_code?`· ${request.request_code}`:''}</p></div><Status value={request.status||'pending'}/></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4"><Info label="Property type" value={request.property_type||'Not specified'}/><Info label="Expected rent" value={request.expected_rent?money(Number(request.expected_rent)):'—'}/><Info label="Submitted" value={request.created_at?new Date(request.created_at).toLocaleDateString():'—'}/><Info label="Inspection date" value={request.scheduled_date?new Date(request.scheduled_date).toLocaleDateString():request.completed_at?new Date(request.completed_at).toLocaleDateString():'Not scheduled'}/></div>{(request.notes||request.rejection_reason)&&<div className="mt-3 rounded-xl border border-white/[.05] bg-white/[.02] p-3"><p className="text-[9px] uppercase tracking-wide text-[#66687B]">Latest update</p><p className="mt-1 text-[10px] leading-relaxed text-[#A4A5B2]">{request.rejection_reason||request.notes}</p></div>}<button onClick={()=>contact(request)} className="mt-3 rounded-xl border border-violet-500/15 bg-violet-500/[.06] px-3 py-2 text-[10px] font-semibold text-violet-300">Message Support about this request</button></section>)}</div>}</section></div>
}

function PropertiesTab({profile}:{profile:Profile}){
 const[properties,setProperties]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;(async()=>{const{data,error}=await supabase.from('listings').select('*').or(`owner_id.eq.${profile.user_id},partner_id.eq.${profile.user_id}`).order('created_at',{ascending:false});if(!active)return;if(error)toast.error('Unable to load your properties');setProperties(data||[]);setLoading(false)})();return()=>{active=false}},[profile.user_id]);
 if(selected)return <PropertyDetails property={selected} onBack={()=>setSelected(null)}/>;
 return <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Properties published by WeHouse</h2><p className="mt-1 text-[10px] text-[#66687B]">Read-only public listings connected to your Property Partner account.</p></div><span className="rounded-full bg-white/[.04] px-3 py-1 text-[10px] text-[#888A9B]">{properties.length}</span></div>{loading?<Loading/>:properties.length===0?<Empty title="No published properties yet" text="Your approved property will appear here after WeHouse completes inspection and publishes the listing."/>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{properties.map(property=><button key={property.id} onClick={()=>setSelected(property)} className="overflow-hidden rounded-2xl border border-white/[.06] bg-[#111119] text-left transition hover:-translate-y-0.5 hover:border-violet-500/25"><div className="h-40 bg-[#171722]">{property.images?.[0]?<img src={property.images[0]} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-[#46485A]">No image</div>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{property.title||'Property'}</p><p className="mt-1 truncate text-[10px] text-[#66687B]">{[property.city,property.state].filter(Boolean).join(', ')}</p></div><Status value={property.availability_status||property.status||'pending'}/></div><p className="mt-3 text-xs font-bold">{money(Number(property.price||0))}</p></div></button>)}</div>}</section>
}

function PropertyDetails({property,onBack}:{property:any;onBack:()=>void}){
 function contact(){window.dispatchEvent(new CustomEvent('openSupportChat',{detail:{category:'property_inspection',subject:`Listing help: ${property.title||'Property'}`,contextType:'listing',contextId:String(property.id),contextSnapshot:{property_name:property.title,address:property.address,city:property.city,state:property.state,status:property.status}}}))}
 return <div className="space-y-5"><button onClick={onBack} className="text-xs text-[#888A9B] hover:text-white">← Back to properties</button><section className="overflow-hidden rounded-3xl border border-white/[.06] bg-[#111119]">{property.images?.[0]&&<img src={property.images[0]} alt="" className="h-56 w-full object-cover lg:h-72"/>}<div className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="break-words text-xl font-bold">{property.title||'Property'}</h2><p className="mt-1 break-words text-xs text-[#747689]">{[property.address,property.city,property.state].filter(Boolean).join(', ')}</p></div><Status value={property.availability_status||property.status||'pending'}/></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Info label="Group" value={property.property_type||'Apartment'}/><Info label="Type" value={property.sub_type||'Not specified'}/><Info label="Bedrooms" value={property.bedrooms??'—'}/><Info label="Bathrooms" value={property.bathrooms??'—'}/></div><button onClick={contact} className="mt-4 rounded-xl border border-violet-500/15 bg-violet-500/[.06] px-4 py-3 text-xs font-semibold text-violet-300">Message Support about this property</button></div></section></div>
}

function FinanceTab({profile}:{profile:Profile}){const[view,setView]=useState<FinanceView>('wallet');return <div className="space-y-5"><div className="grid grid-cols-2 gap-2 rounded-xl border border-white/[.06] bg-[#101018] p-1"><button onClick={()=>setView('wallet')} className={`rounded-lg px-4 py-2.5 text-[10px] font-semibold ${view==='wallet'?'bg-violet-500 text-white':'text-[#747689]'}`}>Wallet</button><button onClick={()=>setView('earnings')} className={`rounded-lg px-4 py-2.5 text-[10px] font-semibold ${view==='earnings'?'bg-violet-500 text-white':'text-[#747689]'}`}>Earnings</button></div>{view==='wallet'?<PropertyPartnerFinancePanel profile={profile}/>:<EarningsTab profile={profile}/>}</div>}

function EarningsTab({profile}:{profile:Profile}){
 const[rows,setRows]=useState<EarningRelease[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;(async()=>{const{data,error}=await supabase.from('property_partner_earning_releases').select('id,earning_type,status,net_amount,release_event,created_at').eq('partner_id',profile.user_id).order('created_at',{ascending:false});if(!active)return;if(error)toast.error('Unable to load earnings');setRows((data||[]) as EarningRelease[]);setLoading(false)})();return()=>{active=false}},[profile.user_id]);
 const totals=rows.reduce((result,row)=>{result[row.status]+=Number(row.net_amount||0);return result},{pending:0,available:0,held:0,reversed:0});
 return <div className="space-y-5"><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Money label="Released" value={totals.available}/><Money label="Pending" value={totals.pending}/><Money label="Held" value={totals.held}/><Money label="Reversed" value={totals.reversed}/></section><section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><h2 className="text-sm font-semibold">Earning history</h2><p className="mt-1 text-[10px] text-[#66687B]">Net eligible property income after WeHouse commission.</p>{loading?<Loading/>:rows.length===0?<Empty title="No property earnings yet" text="Eligible verified payments will appear here after WeHouse records them."/>:<div className="mt-4 divide-y divide-white/[.05]">{rows.map(row=><div key={row.id} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="break-words text-xs font-medium capitalize">{row.earning_type.replace(/_/g,' ')}</p><p className="mt-1 break-words text-[9px] text-[#626477]">{new Date(row.created_at).toLocaleDateString()} {row.release_event?`· ${row.release_event.replace(/_/g,' ')}`:''}</p></div><div className="shrink-0 text-right"><p className="text-xs font-semibold">{money(row.net_amount)}</p><Status value={row.status}/></div></div>)}</div>}</section></div>
}

function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><p className="text-[9px] text-[#66687B]">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>}
function Money({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.05] p-4"><p className="text-[9px] text-emerald-300/70">{label}</p><p className="mt-2 text-lg font-bold">{money(value)}</p></div>}
function Info({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-white/[.06] bg-[#111119] p-4"><p className="text-[9px] uppercase tracking-wide text-[#616375]">{label}</p><p className="mt-1 break-words text-xs font-medium capitalize text-[#D3D4DC]">{value}</p></div>}
function Status({value}:{value:string}){const normalized=value.toLowerCase();const style=normalized==='available'||normalized==='approved'||normalized==='completed'?'bg-emerald-500/10 text-emerald-300':normalized==='rejected'||normalized==='reversed'?'bg-red-500/10 text-red-300':normalized==='held'?'bg-orange-500/10 text-orange-300':'bg-amber-500/10 text-amber-300';return <span className={`inline-flex shrink-0 rounded-full px-2 py-1 text-[8px] font-semibold capitalize ${style}`}>{value.replace(/_/g,' ')}</span>}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] bg-white/[.015] px-5 py-12 text-center"><p className="text-sm font-semibold">{title}</p><p className="mx-auto mt-2 max-w-md text-[10px] leading-relaxed text-[#626477]">{text}</p></div>}
function Loading(){return <div className="grid min-h-40 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>}
