import { useCallback,useEffect,useState } from 'react';
import { Toaster,toast } from 'sonner';
import { checkSearchExpiry,getSavedMatchResults,refreshRoommateSearch,saveRoommatePreferences,startRoommateSearch,stopRoommateSearch,updateMatchStatus } from '@/lib/supabase';
import { RoommateInfo } from '@/components/RoommateChoices';
import RoommatePreferencesPanel from '@/components/RoommatePreferencesPanel';
import DiscoveryShell from '@/components/DiscoveryShell';
import type { Profile,RoommatePreferences } from '@/types';

type Props={profile:Profile;onGoToChat?:(id:string)=>void;onEditProfile?:()=>void};
type Form={gender_preference:string;budget_min:number;budget_max:number;cleanliness:string;noise_level:string;visitors:string;stay_duration:string;area_preference:string;school_name:string;school_match:boolean};
const EMPTY:Form={gender_preference:'no_preference',budget_min:180000,budget_max:500000,cleanliness:'moderate',noise_level:'moderate',visitors:'sometimes',stay_duration:'1_year',area_preference:'',school_name:'',school_match:false};

export default function RoommateWorkspace({profile,onGoToChat,onEditProfile}:Props){
 const[prefs,setPrefs]=useState<RoommatePreferences|null>(null),[matches,setMatches]=useState<any[]>([]),[form,setForm]=useState<Form>({...EMPTY,school_name:profile.school||''}),[editing,setEditing]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const basics=Boolean(profile.gender&&profile.state)&&profile.role==='user',canMatch=basics&&Boolean(profile.id_verified),location=[profile.local_government||profile.city,profile.state].filter(Boolean).join(', ');
 const load=useCallback(async()=>{setLoading(true);const{prefs:p}=await checkSearchExpiry();const result=await getSavedMatchResults().catch(()=>({matches:[],error:null}));setPrefs(p);setMatches(result.matches||[]);if(p)setForm({gender_preference:p.gender_preference||'no_preference',budget_min:Number(p.budget_min||180000),budget_max:Number(p.budget_max||500000),cleanliness:p.cleanliness||'moderate',noise_level:p.noise_level||'moderate',visitors:p.visitors||'sometimes',stay_duration:p.stay_duration||'1_year',area_preference:p.area_preference||'',school_name:p.school_name||profile.school||'',school_match:Boolean(p.school_match)});setLoading(false)},[profile.school]);
 useEffect(()=>{void load()},[load]);
 async function save(){if(!basics)return toast.error('Add your gender and State first');if(form.school_match&&!form.school_name.trim())return toast.error('Enter your school first');setBusy(true);const{prefs:p,error}=await saveRoommatePreferences({...form,gender:profile.gender,active:true} as any);setBusy(false);if(error||!p)return toast.error(error?.message||'Could not save preferences');setPrefs(p);setEditing(false)}
 async function start(){if(!canMatch)return toast.error('Complete the required account checks first');setBusy(true);const{prefs:p,error}=await startRoommateSearch();if(error||!p){setBusy(false);return toast.error(error?.message||'Could not start matching')}const result=await refreshRoommateSearch();setBusy(false);setPrefs(p);if(result.error)return toast.error(result.error.message);setMatches(result.matches||[])}
 async function refresh(){setBusy(true);const result=await refreshRoommateSearch();setBusy(false);if(result.error)return toast.error(result.error.message);setMatches(result.matches||[])}
 async function stop(){const{prefs:p,error}=await stopRoommateSearch();if(error)return toast.error(error.message);setPrefs(p)}
 async function interest(match:any,status:'accepted'|'declined'){const{conversationId,error}=await updateMatchStatus(match.id,status);if(error)return toast.error(error.message);await load();if(conversationId)onGoToChat?.(conversationId)}
 function navigate(page:string){try{localStorage.setItem('wh_navpage',page);window.history.pushState({page},'',`#${page}`);window.dispatchEvent(new PopStateEvent('popstate',{state:{page}}))}catch{window.location.hash=page}}
 if(loading)return <div className="grid min-h-[70dvh] place-items-center bg-[#0A0A0F] text-xs text-[#777B8D]">Loading roommates…</div>;
 return <DiscoveryShell active="roommates" title="Roommates" description="Compatibility matching uses your saved preferences, not the normal property/service filters." onNavigate={navigate}>
  <Toaster position="top-center" richColors/>
  <main className="mx-auto max-w-6xl space-y-4 px-4 py-5 sm:px-6 lg:px-8">
   <div className="grid gap-3 sm:grid-cols-3"><RoommateInfo label="Location" value={location||'Not set'}/><RoommateInfo label="Account check" value={profile.id_verified?'Ready':'Required'}/><RoommateInfo label="Matching" value={prefs?.search_status==='active'?'Active':'Off'}/></div>
   {!canMatch&&<section className="rounded-2xl border border-amber-500/15 bg-amber-500/[.05] p-4"><p className="text-sm font-semibold">Complete the matching requirements</p><p className="mt-1 text-[10px] text-[#9A9EAD]">Your required account/profile checks must be complete before matches are shown.</p>{onEditProfile&&<button onClick={onEditProfile} className="mt-3 rounded-xl bg-violet-500 px-4 py-2 text-xs font-semibold text-white">Open personal details</button>}</section>}
   {(!prefs||editing)?<RoommatePreferencesPanel form={form} setForm={setForm} profileSchool={profile.school} areaHint={profile.local_government?`Area within ${profile.local_government}`:undefined} busy={busy} onSave={save} onCancel={prefs?()=>setEditing(false):undefined}/>:<><section className="rounded-2xl border border-white/[.07] bg-[#11141C] p-4"><p className="text-lg font-bold">₦{Number(prefs.budget_min).toLocaleString()} – ₦{Number(prefs.budget_max).toLocaleString()}</p>{prefs.school_match&&<p className="mt-2 text-[10px] text-violet-300">Same school only · {prefs.school_name}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>setEditing(true)} className="rounded-xl border border-white/[.08] px-4 py-2 text-xs">Edit</button>{prefs.search_status==='active'?<><button onClick={()=>void refresh()} disabled={busy} className="rounded-xl bg-violet-500 px-4 py-2 text-xs disabled:opacity-40">Refresh</button><button onClick={()=>void stop()} className="rounded-xl border border-white/[.08] px-4 py-2 text-xs">Pause</button></>:<button onClick={()=>void start()} disabled={!canMatch||busy} className="rounded-xl bg-violet-500 px-4 py-2 text-xs disabled:opacity-40">Start matching</button>}</div></section><Matches rows={matches} onChat={onGoToChat} onInterest={interest}/></>}
  </main>
 </DiscoveryShell>
}

function Matches({rows,onChat,onInterest}:{rows:any[];onChat?:((id:string)=>void);onInterest:(row:any,status:'accepted'|'declined')=>void}){const visible=rows.filter(row=>row.status!=='declined');return <section><h2 className="mb-3 text-lg font-bold">Matches</h2>{visible.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map(row=>{const p=row.matched_profile||{};return <article key={row.id} className="rounded-2xl border border-white/[.07] bg-[#11141C] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{p.full_name||`@${p.username||'user'}`}</p><p className="mt-1 text-[10px] text-[#737889]">{p.city||p.state||'Nigeria'}</p>{p.school&&<p className="mt-1 text-[9px] text-violet-300/80">{p.school}</p>}</div><span className="rounded-full bg-violet-500/10 px-2 py-1 text-[10px] text-violet-300">{row.match_score}%</span></div><div className="mt-4 flex gap-2">{row.conversation_id?<button onClick={()=>onChat?.(row.conversation_id)} className="flex-1 rounded-xl bg-violet-500 py-2 text-xs">Chat</button>:<button onClick={()=>void onInterest(row,'accepted')} className="flex-1 rounded-xl bg-violet-500 py-2 text-xs">Interested</button>}<button onClick={()=>void onInterest(row,'declined')} className="rounded-xl border border-white/[.08] px-4 text-xs">Skip</button></div></article>})}</div>:<div className="rounded-2xl border border-dashed border-white/[.08] p-10 text-center text-[10px] text-[#686D7E]">No matches yet.</div>}</section>}
