import { useEffect, useMemo, useState } from 'react';
import { getAllListings } from '@/lib/supabase';
import { NIGERIA_STATES, getCitiesForState } from '@/data/nigeria-locations';
import ListingCard from '@/components/ListingCard';
import PropertyMapExplorer from '@/components/PropertyMapExplorer';
import type { Listing } from '@/types';

interface SearchProps { onNavigate:(page:string,listingId?:string)=>void;savedIds:Set<string>;onToggleSave:(listingId:string)=>void; }
type UserLocation={lat:number;lng:number};
type View='list'|'map';
function normalize(value:unknown){return String(value||'').trim().toLowerCase()}
function typeValue(listing:Listing){return String(listing.sub_type||listing.property_type||'').trim()}
function typeLabel(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function coords(listing:Listing){const r=listing as Listing&{gps_latitude?:number|null;gps_longitude?:number|null};const lat=Number(r.gps_latitude),lng=Number(r.gps_longitude);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null}
function distanceKm(a:UserLocation,b:{lat:number;lng:number}){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,q=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(q))}

export default function Search({onNavigate,savedIds,onToggleSave}:SearchProps){
 const [listings,setListings]=useState<Listing[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[priceMax,setPriceMax]=useState<number|''>(''),[bedrooms,setBedrooms]=useState<number|''>(''),[filterState,setFilterState]=useState(''),[filterCity,setFilterCity]=useState(''),[propertyType,setPropertyType]=useState(''),[showFilters,setShowFilters]=useState(false),[userLocation,setUserLocation]=useState<UserLocation|null>(null),[locating,setLocating]=useState(false),[radius,setRadius]=useState<number|''>(''),[view,setView]=useState<View>('list');
 useEffect(()=>{const saved=sessionStorage.getItem('search_property_type');if(saved&&saved!=='hotel')setPropertyType(saved);sessionStorage.removeItem('search_property_type')},[]);
 useEffect(()=>{let active=true;void(async()=>{const {listings:data}=await getAllListings();if(active){setListings(data||[]);setLoading(false)}})();return()=>{active=false}},[]);
 const citiesForState=useMemo(()=>getCitiesForState(filterState),[filterState]);
 const types=useMemo(()=>{const m=new Map<string,number>();listings.forEach(l=>{const v=typeValue(l);if(v)m.set(v,(m.get(v)||0)+1)});return[...m.entries()].sort((a,b)=>b[1]-a[1]).map(([value,count])=>({value,label:typeLabel(value),count}))},[listings]);
 const stateCounts=useMemo(()=>{const m=new Map<string,number>();listings.forEach(l=>{if(l.state)m.set(l.state,(m.get(l.state)||0)+1)});return m},[listings]);
 const filtered=useMemo(()=>listings.map(listing=>{const c=coords(listing);return{listing,distance:userLocation&&c?distanceKm(userLocation,c):null}}).filter(({listing,distance})=>{const needle=normalize(query),hay=[listing.title,listing.address,listing.city,listing.state,listing.property_type,listing.sub_type].map(normalize).join(' ');if(needle&&!hay.includes(needle))return false;if(priceMax&&Number(listing.price||0)>priceMax)return false;if(bedrooms&&Number(listing.bedrooms||0)<bedrooms)return false;if(filterState&&normalize(listing.state)!==normalize(filterState))return false;if(filterCity&&normalize(listing.city)!==normalize(filterCity))return false;if(propertyType&&normalize(typeValue(listing))!==normalize(propertyType))return false;if(radius&&(distance==null||distance>radius))return false;return true}).sort((a,b)=>userLocation?(a.distance??Infinity)-(b.distance??Infinity):0),[listings,query,priceMax,bedrooms,filterState,filterCity,propertyType,userLocation,radius]);
 const hasFilters=Boolean(query||priceMax||bedrooms||filterState||filterCity||propertyType||radius);
 function clearFilters(){setQuery('');setPriceMax('');setBedrooms('');setFilterState('');setFilterCity('');setPropertyType('');setRadius('')}
 function useLocation(){if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(p=>{setUserLocation({lat:p.coords.latitude,lng:p.coords.longitude});setLocating(false)},()=>setLocating(false),{enableHighAccuracy:true,timeout:15000,maximumAge:60000});setLocating(true)}
 return <div className="min-h-screen bg-[#09090D] pb-24 text-white">
  <header className="sticky top-0 z-20 border-b border-white/[0.06] bg-[#09090D]/95 px-4 pb-4 pt-5 backdrop-blur-xl lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-center gap-3"><button onClick={()=>onNavigate('home')} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-white/[0.06] bg-white/[0.03] text-[#85879A]">←</button><div className="min-w-0 flex-1"><h1 className="text-lg font-bold">Find a home</h1><p className="text-[10px] text-[#686A7D]">Browse verified available properties by list or map.</p></div><button onClick={()=>onNavigate('hotels')} className="rounded-xl border border-rose-500/20 bg-rose-500/[0.08] px-3 py-2 text-[10px] font-semibold text-rose-300">Hotels</button></div>
   <div className="mt-4 flex gap-2"><div className="relative flex-1"><svg className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#5C5E72]" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search home, area or location" className="h-11 w-full rounded-xl border border-white/[0.07] bg-[#14141D] pl-10 pr-4 text-sm outline-none placeholder:text-[#55576A] focus:border-violet-500/35"/></div><button onClick={()=>setShowFilters(v=>!v)} className={`h-11 rounded-xl border px-4 text-xs font-medium ${showFilters?'border-violet-500/30 bg-violet-500/15 text-violet-300':'border-white/[0.07] bg-[#14141D] text-[#85879A]'}`}>Filters</button></div>
   <div className="mt-3 grid grid-cols-2 gap-2"><select value={filterState} onChange={e=>{setFilterState(e.target.value);setFilterCity('')}} className="h-10 rounded-xl border border-white/[0.07] bg-[#14141D] px-3 text-xs"><option value="">All states</option>{NIGERIA_STATES.map(i=><option key={i.state} value={i.state}>{i.state}{stateCounts.get(i.state)?` (${stateCounts.get(i.state)})`:''}</option>)}</select><select value={filterCity} onChange={e=>setFilterCity(e.target.value)} disabled={!filterState} className="h-10 rounded-xl border border-white/[0.07] bg-[#14141D] px-3 text-xs disabled:opacity-40"><option value="">All LGAs</option>{citiesForState.map(city=><option key={city} value={city}>{city}</option>)}</select></div>
   <div className="mt-3 flex flex-wrap items-center gap-2"><button onClick={useLocation} disabled={locating} className="rounded-xl border border-blue-500/20 bg-blue-500/[0.08] px-3 py-2 text-[10px] font-semibold text-blue-300 disabled:opacity-50">{locating?'Finding location…':userLocation?'Refresh my location':'Use my location'}</button>{userLocation&&<select value={radius} onChange={e=>setRadius(e.target.value?Number(e.target.value):'')} className="h-9 rounded-xl border border-white/[0.07] bg-[#14141D] px-3 text-[10px]"><option value="">Any distance</option><option value="2">Within 2 km</option><option value="5">Within 5 km</option><option value="10">Within 10 km</option><option value="20">Within 20 km</option></select>}<div className="ml-auto flex rounded-xl border border-white/[0.07] bg-[#14141D] p-1"><button onClick={()=>setView('list')} className={`rounded-lg px-3 py-1.5 text-[9px] font-semibold ${view==='list'?'bg-violet-500 text-white':'text-[#737789]'}`}>List</button><button onClick={()=>setView('map')} className={`rounded-lg px-3 py-1.5 text-[9px] font-semibold ${view==='map'?'bg-violet-500 text-white':'text-[#737789]'}`}>Map</button></div></div>
   {showFilters&&<div className="mt-3 grid gap-3 rounded-2xl border border-white/[0.06] bg-[#111119] p-4 md:grid-cols-3"><div><label className="mb-1 block text-[9px] uppercase text-[#66687B]">Property type</label><select value={propertyType} onChange={e=>setPropertyType(e.target.value)} className="h-10 w-full rounded-xl border border-white/[0.07] bg-[#181822] px-3 text-xs"><option value="">All types</option>{types.map(i=><option key={i.value} value={i.value}>{i.label} ({i.count})</option>)}</select></div><div><label className="mb-1 block text-[9px] uppercase text-[#66687B]">Maximum price</label><input inputMode="numeric" value={priceMax} onChange={e=>setPriceMax(e.target.value?Number(e.target.value.replace(/[^0-9]/g,'')):'')} placeholder="Any price" className="h-10 w-full rounded-xl border border-white/[0.07] bg-[#181822] px-3 text-xs"/></div><div><label className="mb-1 block text-[9px] uppercase text-[#66687B]">Minimum bedrooms</label><select value={bedrooms} onChange={e=>setBedrooms(e.target.value?Number(e.target.value):'')} className="h-10 w-full rounded-xl border border-white/[0.07] bg-[#181822] px-3 text-xs"><option value="">Any</option><option value="1">1+</option><option value="2">2+</option><option value="3">3+</option><option value="4">4+</option></select></div></div>}
  </div></header>
  <main className="mx-auto max-w-7xl px-4 py-5 lg:px-8"><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">{loading?'Loading homes…':`${filtered.length} ${filtered.length===1?'home':'homes'}`}</p><p className="mt-1 text-[10px] text-[#66687B]">{view==='map'?'Tap a price pin to preview a property.':userLocation?'Nearest properties are shown first.':'Use your location to see real distance.'}</p></div>{hasFilters&&<button onClick={clearFilters} className="text-[10px] font-medium text-violet-300">Clear filters</button>}</div>
   {loading?<div className="grid min-h-56 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>:filtered.length===0?<section className="rounded-3xl border border-dashed border-white/[0.08] bg-white/[0.015] px-6 py-16 text-center"><h2 className="text-sm font-semibold">No available homes match this search</h2><p className="mx-auto mt-2 max-w-md text-[10px] leading-relaxed text-[#66687B]">Change the location, distance or filters.</p>{hasFilters&&<button onClick={clearFilters} className="mt-5 rounded-xl bg-violet-500 px-4 py-2.5 text-xs font-semibold">Show all homes</button>}</section>:view==='map'?<PropertyMapExplorer items={filtered} userLocation={userLocation} radius={radius} onOpen={listing=>onNavigate('detail',listing.id)}/>:<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map(({listing,distance})=><ListingCard key={listing.id} listing={listing} distanceKm={distance} onClick={()=>onNavigate('detail',listing.id)} isSaved={savedIds.has(listing.id)} onToggleSave={event=>{event.stopPropagation();onToggleSave(listing.id)}}/>)}</div>}
  </main>
 </div>
}
