import { useEffect, useMemo, useState } from 'react';
import { Toaster, toast } from 'sonner';
import type { Listing, Profile } from '@/types';
import { usePlatformSettings } from '@/hooks/usePlatformSettings';
import { createInspectionRequest } from '@/lib/supabase/reservations';
import { createShortStayReservation, getMyShortStayReservations, initializeShortStayPayment, initializeShortStayReservationFee } from '@/lib/short-stay';

type Props={listing:Listing;profile:Profile;onNavigate:()=>void;isSaved:boolean;onToggleSave:()=>void};
const ACTIVE=new Set(['payment_pending','reserved','inspection_pending','ready_for_move_in','occupied']);
function today(){return new Date().toISOString().slice(0,10)}
function money(value:unknown){return `₦${Number(value||0).toLocaleString()}`}
function nights(a:string,b:string){if(!a||!b)return 0;const n=Math.round((new Date(`${b}T00:00:00`).getTime()-new Date(`${a}T00:00:00`).getTime())/86400000);return Math.max(0,n)}

export default function ShortStayListingDetail({listing,profile,onNavigate,isSaved,onToggleSave}:Props){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[imageIndex,setImageIndex]=useState(0),[checkIn,setCheckIn]=useState(''),[checkOut,setCheckOut]=useState('');
 const{getNumber}=usePlatformSettings();const reservationFee=getNumber('reservation_fee',5000);const minNights=getNumber('short_stay_min_nights',1);const maxNights=getNumber('short_stay_max_nights',90);
 const stayNights=useMemo(()=>nights(checkIn,checkOut),[checkIn,checkOut]);const rent=stayNights*Number(listing.price||0);const deposit=Number(listing.security_deposit_amount||0);const total=rent+deposit;
 async function load(){setLoading(true);const{reservations,error}=await getMyShortStayReservations(String(listing.id));if(error)toast.error(error.message);setRows((reservations||[]).filter(row=>ACTIVE.has(String(row.status))));setLoading(false)}
 useEffect(()=>{void load()},[listing.id,profile.user_id]);
 function support(row?:any){window.dispatchEvent(new CustomEvent('openSupportChat',{detail:{category:row?.rent_payment_status==='payment_pending'||row?.status==='payment_pending'?'payment':'apartment_booking',subject:`Short Let · ${listing.title}`,contextType:row?'apartment_reservation':'listing',contextId:row?.id||listing.id,contextSnapshot:{listing_id:listing.id,listing_title:listing.title,stay_type:'short_let',reservation_id:row?.id,check_in:row?.stay_check_in,check_out:row?.stay_check_out,status:row?.status}}}))}
 async function reserve(){if(!checkIn||!checkOut)return toast.error('Choose check-in and check-out');if(checkIn<today()||checkOut<=checkIn)return toast.error('Choose valid stay dates');if(stayNights<minNights||stayNights>maxNights)return toast.error(`Choose between ${minNights} and ${maxNights} nights`);setBusy('new');try{const{reservation,error}=await createShortStayReservation(String(listing.id),checkIn,checkOut);if(error)throw error;if(!reservation?.payment_reference)throw new Error('Reservation payment reference is missing');const{result,error:payError}=await initializeShortStayReservationFee(String(reservation.payment_reference));if(payError)throw payError;if(result?.already_paid){await load();setBusy(null);return}if(!result?.success||!result.authorization_url)throw new Error(result?.error||'Could not open Paystack');window.location.assign(result.authorization_url)}catch(error:any){toast.error(error?.message||'Could not reserve these dates');setBusy(null)}}
 async function resumeFee(row:any){setBusy(row.id);try{const{result,error}=await initializeShortStayReservationFee(String(row.payment_reference||''));if(error)throw error;if(result?.already_paid){await load();setBusy(null);return}if(!result?.success||!result.authorization_url)throw new Error(result?.error||'Could not open Paystack');window.location.assign(result.authorization_url)}catch(error:any){toast.error(error?.message||'Could not continue payment');setBusy(null)}}
 async function payStay(row:any){setBusy(row.id);try{const{result,error}=await initializeShortStayPayment(row.id);if(error)throw error;if(result?.already_paid){toast.success('Short Let payment is already confirmed');await load();setBusy(null);return}if(!result?.success||!result.authorization_url)throw new Error(result?.error||'Could not open Paystack');window.location.assign(result.authorization_url)}catch(error:any){toast.error(error?.message||'Could not start Short Let payment');setBusy(null)}}
 async function inspect(row:any){setBusy(row.id);const{error}=await createInspectionRequest(row.id,String(listing.id),profile.user_id,`Inspection requested for Short Let ${listing.title}`);setBusy(null);if(error)return toast.error(error.message);toast.success('Inspection requested');await load()}
 const images=listing.images?.length?listing.images:['https://placehold.co/900x650/171922/666A7A?text=No+Image'];const bookable=!['maintenance','closed','rejected','pending_approval'].includes(String(listing.status));
 return <div className="min-h-[100dvh] bg-[#090A0F] pb-12 text-white"><Toaster position="top-center" richColors/><div className="mx-auto max-w-6xl"><section className="relative overflow-hidden bg-[#11141C] sm:m-4 sm:rounded-3xl"><img src={images[imageIndex]} alt={listing.title} className="aspect-[4/3] w-full object-cover sm:aspect-[16/9]"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-black/20"/><button onClick={onNavigate} className="absolute left-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-black/50">←</button><button onClick={onToggleSave} aria-label={isSaved?'Remove from saved properties':'Save property'} aria-pressed={isSaved} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-black/50"><Heart filled={isSaved}/></button><span className="absolute bottom-4 left-4 rounded-full border border-violet-400/20 bg-violet-500/20 px-3 py-1.5 text-[9px] font-bold text-violet-100">SHORT LET</span>{images.length>1&&<div className="absolute bottom-4 right-4 flex gap-1.5">{images.map((_,i)=><button key={i} onClick={()=>setImageIndex(i)} className={`h-2 rounded-full ${i===imageIndex?'w-5 bg-white':'w-2 bg-white/40'}`}/>)}</div>}</section>
 <main className="grid gap-6 px-4 py-5 sm:px-6 lg:grid-cols-[minmax(0,1fr)_380px] lg:px-8"><div className="space-y-5"><section><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{listing.title}</h1><p className="mt-1 text-xs text-[#777B8B]">{[listing.address,listing.city,listing.state].filter(Boolean).join(', ')}</p></div><p className="text-xl font-bold text-violet-300">{money(listing.price)}<span className="ml-1 text-[10px] font-normal text-[#6F7484]">/night</span></p></div></section><section className="grid grid-cols-3 gap-2"><Fact label="Stay" value="Short Let"/><Fact label="Bedrooms" value={listing.bedrooms||'—'}/><Fact label="Bathrooms" value={listing.bathrooms||'—'}/></section><section className="rounded-2xl border border-violet-500/12 bg-violet-500/[.035] p-4"><div className="flex flex-wrap gap-2"><Pill>Furnished</Pill><Pill>Refundable deposit · {money(deposit)}</Pill></div><p className="mt-3 text-[10px] leading-5 text-[#858A9A]">The security deposit is held separately from Property Partner earnings and becomes refund-due after checkout, subject to the property condition review.</p></section>{listing.description&&<section className="rounded-2xl border border-white/[.06] bg-[#11141C] p-4"><h2 className="text-sm font-semibold">About this stay</h2><p className="mt-2 whitespace-pre-wrap text-xs leading-6 text-[#9599A8]">{listing.description}</p></section>}<button onClick={()=>support()} className="h-11 w-full rounded-xl border border-blue-500/20 bg-blue-500/[.05] text-xs font-semibold text-blue-300">Message WeHouse Support</button></div>
 <aside className="space-y-3 lg:sticky lg:top-20 lg:self-start"><section className="rounded-3xl border border-white/[.07] bg-[#11141C] p-5"><p className="text-[10px] font-semibold uppercase tracking-wide text-violet-300">Choose dates</p><div className="mt-4 grid grid-cols-2 gap-2"><DateField label="Check-in" value={checkIn} min={today()} set={value=>{setCheckIn(value);if(checkOut&&value>=checkOut)setCheckOut('')}}/><DateField label="Check-out" value={checkOut} min={checkIn||today()} set={setCheckOut}/></div>{stayNights>0&&<div className="mt-4 space-y-2 rounded-2xl bg-white/[.035] p-3"><Row label={`${stayNights} night${stayNights===1?'':'s'}`} value={money(rent)}/><Row label="Refundable security deposit" value={money(deposit)}/><div className="border-t border-white/[.06] pt-2"><Row label="Stay + deposit" value={money(total)}/></div><p className="pt-1 text-[8px] text-[#656B7C]">Reservation fee: {money(reservationFee)} paid first to reserve these dates.</p></div>}<button disabled={!bookable||stayNights<minNights||stayNights>maxNights||busy==='new'} onClick={()=>void reserve()} className="mt-4 h-12 w-full rounded-xl bg-violet-500 text-sm font-semibold disabled:opacity-40">{busy==='new'?'Opening Paystack…':'Reserve these dates'}</button>{!bookable&&<p className="mt-2 text-center text-[9px] text-amber-300">This property is not taking new bookings right now.</p>}</section>
 {loading?<Loading/>:rows.length>0&&<section className="rounded-3xl border border-white/[.07] bg-[#11141C] p-4"><h2 className="text-sm font-semibold">Your Short Let bookings</h2><div className="mt-3 space-y-3">{rows.map(row=><Booking key={row.id} row={row} busy={busy===row.id} onResume={()=>void resumeFee(row)} onPay={()=>void payStay(row)} onInspect={()=>void inspect(row)} onSupport={()=>support(row)}/>)}</div></section>}</aside></main></div></div>
}
function Heart({filled}:{filled:boolean}){return <svg width="18" height="18" viewBox="0 0 24 24" fill={filled?'#A78BFA':'none'} stroke={filled?'#A78BFA':'white'} strokeWidth="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>}

function Booking({row,busy,onResume,onPay,onInspect,onSupport}:{row:any;busy:boolean;onResume:()=>void;onPay:()=>void;onInspect:()=>void;onSupport:()=>void}){const feePaid=['paid','completed'].includes(String(row.manual_payment_status||''));const stayPaid=row.rent_payment_status==='paid';return <div className="rounded-2xl border border-white/[.06] bg-[#0D1017] p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-[10px] font-semibold">{row.stay_check_in} → {row.stay_check_out}</p><p className="mt-1 text-[8px] text-[#676D7E]">{row.stay_nights} night{Number(row.stay_nights)===1?'':'s'} · {String(row.status).replace(/_/g,' ')}</p></div><span className="rounded-full border border-white/[.07] px-2 py-1 text-[8px] text-[#8E93A2]">{row.booking_code||'Reserved'}</span></div>{row.status==='payment_pending'&&<button disabled={busy} onClick={onResume} className="mt-3 h-10 w-full rounded-xl bg-violet-500 text-[10px] font-semibold disabled:opacity-40">{busy?'Opening…':'Pay reservation fee'}</button>}{feePaid&&row.status==='reserved'&&!stayPaid&&<div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy} onClick={onPay} className="h-10 rounded-xl bg-emerald-500 text-[9px] font-semibold text-[#04120C] disabled:opacity-40">Pay stay + deposit</button><button disabled={busy} onClick={onInspect} className="h-10 rounded-xl border border-blue-500/20 text-[9px] font-semibold text-blue-300 disabled:opacity-40">Request inspection</button></div>}{row.status==='inspection_pending'&&<p className="mt-3 rounded-xl bg-blue-500/[.06] p-2.5 text-[9px] text-blue-300">Inspection is in progress. Stay payment becomes available after the inspection result.</p>}{row.status==='ready_for_move_in'&&!stayPaid&&<button disabled={busy} onClick={onPay} className="mt-3 h-10 w-full rounded-xl bg-emerald-500 text-[10px] font-semibold text-[#04120C] disabled:opacity-40">Pay stay + refundable deposit</button>}{stayPaid&&row.status==='ready_for_move_in'&&<p className="mt-3 rounded-xl bg-emerald-500/[.06] p-2.5 text-[9px] text-emerald-300">Payment verified. WeHouse Operations can confirm check-in on your reserved date.</p>}{row.status==='occupied'&&<p className="mt-3 rounded-xl bg-violet-500/[.06] p-2.5 text-[9px] text-violet-200">Checked in · deposit status: {String(row.security_deposit_status||'held').replace(/_/g,' ')}</p>}<button onClick={onSupport} className="mt-2 h-8 w-full text-[9px] text-blue-300">Support</button></div>}
function DateField({label,value,min,set}:{label:string;value:string;min:string;set:(v:string)=>void}){return <label><span className="mb-1.5 block text-[9px] text-[#73798A]">{label}</span><input type="date" min={min} value={value} onChange={event=>set(event.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#171A23] px-2 text-[9px] outline-none focus:border-violet-500/40"/></label>}
function Fact({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/[.06] bg-[#11141C] p-3 text-center"><p className="text-[8px] uppercase text-[#5F6474]">{label}</p><p className="mt-1 truncate text-xs font-semibold">{value}</p></div>}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full border border-violet-500/15 bg-violet-500/[.06] px-3 py-1.5 text-[9px] text-violet-200">{children}</span>}
function Row({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between gap-3 text-[9px]"><span className="text-[#73798A]">{label}</span><span className="font-semibold">{value}</span></div>}
function Loading(){return <div className="grid min-h-24 place-items-center"><div className="h-5 w-5 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>}
