import { useEffect, useMemo, useState } from 'react';
import { Toaster, toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import { useStaffPermissions } from '@/hooks/useStaffPermissions';
import type { Profile, StaffPermission } from '@/types';

type Props = { profile: Profile; onLogout: () => void };
type ModuleKey = 'operations' | 'finance' | 'support' | 'verification' | 'field_officer';
const MODULE_INFO: Record<ModuleKey,{title:string;description:string;sections:Array<[string,string]>}> = {
 operations:{title:'Property Operations',description:'Manage the branch property pipeline from inspection handoff to listing publication.',sections:[['overview','Overview'],['review','Listing Review'],['live','Live Listings'],['rejected','Rejected']]},
 finance:{title:'Finance',description:'Monitor canonical WeHouse finance records.',sections:[['overview','Overview'],['payments','Payments'],['commissions','Commissions'],['withdrawals','Withdrawals'],['escrow','Escrow'],['refunds','Refunds'],['audit','Audit']]},
 support:{title:'Support',description:'Resolve branch support cases.',sections:[['overview','Overview'],['open','Open'],['in_progress','In Progress'],['resolved','Resolved']]},
 verification:{title:'Worker Verification',description:'Review worker verification evidence.',sections:[['overview','Overview'],['verification_paid','Ready'],['profile_under_review','Under Review'],['verified','Verified'],['rejected','Rejected'],['suspended','Suspended']]},
 field_officer:{title:'Field Work',description:'Handle only inspections assigned to you.',sections:[['overview','Overview'],['scheduled','Scheduled'],['in_progress','In Progress'],['completed','Completed']]}
};
const STAFF_MODULES=new Set<StaffPermission>(['operations','finance','support','verification','field_officer']);
export default function StaffDashboard({profile,onLogout}:Props){const {permissions,loading}=useStaffPermissions(profile.user_id);const assigned=useMemo(()=>permissions.filter((p):p is ModuleKey=>STAFF_MODULES.has(p)&&p in MODULE_INFO),[permissions]);if(loading)return <Loading/>;if(assigned.length!==1)return <Shell profile={profile} onLogout={onLogout} title="Staff Workspace"><Empty text={assigned.length?'Conflicting staff assignments. Admin or Creator must assign one module.':'No operational module has been assigned.'}/></Shell>;return <Workspace profile={profile} onLogout={onLogout} module={assigned[0]}/>}
function Workspace({profile,onLogout,module}:{profile:Profile;onLogout:()=>void;module:ModuleKey}){const info=MODULE_INFO[module];const [section,setSection]=useState('overview');return <Shell profile={profile} onLogout={onLogout} title={info.title} tabs={info.sections} section={section} setSection={setSection}>{module==='finance'?<Finance section={section}/>:<ExistingModule module={module} section={section} profile={profile}/>}</Shell>}
function Finance({section}:{section:string}){const [d,setD]=useState<any>({}),[loading,setLoading]=useState(true);useEffect(()=>{void(async()=>{const {data,error}=await supabase.rpc('get_my_staff_finance_queue');if(error)toast.error(error.message);else setD(data||{});setLoading(false)})()},[]);if(loading)return <Loading/>;const rows=section==='overview'?[]:(d[section]||[]);if(section==='overview')return <div className="space-y-5"><Stats items={[['Payments',(d.payments||[]).length],['Commissions',(d.commissions||[]).length],['Withdrawals',(d.withdrawals||[]).length],['Escrow',(d.escrow||[]).length]]}/><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{['Payments','Commissions','Withdrawals','Escrow','Refunds','Audit'].map(x=><Card key={x}><h3 className="text-sm font-semibold">{x}</h3><p className="mt-2 text-[10px] text-[#73798B]">Canonical {x.toLowerCase()} records live here.</p></Card>)}</div></div>;return <div className="space-y-4"><Stats items={[['Records',rows.length]]}/>{rows.length?<div className="space-y-3">{rows.map((r:any)=><Card key={r.id}><div className="flex justify-between gap-3"><div><h3 className="text-sm font-semibold">{r.purpose||r.booking_type||r.action||r.snapshot_bank_account_name||section}</h3><p className="mt-1 text-[10px] text-[#73798B]">{r.description||r.refund_reason||r.paystack_reference||r.payment_reference||new Date(r.created_at).toLocaleString()}</p></div><span className="text-[9px] uppercase text-[#9297A8]">{String(r.status||r.status_after||'recorded').replace(/_/g,' ')}</span></div></Card>)}</div>:<Empty text={`No ${section} records.`}/>}</div>}
function ExistingModule({module,section,profile}:{module:ModuleKey;section:string;profile:Profile}){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{void(async()=>{let res:any;if(module==='operations')res=await supabase.rpc('get_my_staff_operations_listings',{p_status:section==='review'?'pending_approval':section==='live'?'available':section==='rejected'?'rejected':'all'});else if(module==='support')res=await supabase.rpc('get_my_staff_support_tickets',{p_status:section==='overview'?'all':section});else if(module==='verification')res=await supabase.rpc('get_my_staff_worker_reviews',{p_status:section==='overview'?'all':section});else res=await supabase.rpc('get_my_inspections',{p_field_officer_id:profile.user_id});if(res.error)toast.error(res.error.message);setRows(res.data||[]);setLoading(false)})()},[module,section,profile.user_id]);if(loading)return <Loading/>;const shown=module==='field_officer'&&section!=='overview'?rows.filter(r=>section==='completed'?['completed','approved'].includes(r.status):r.status===section):rows;return <div className="space-y-5"><Stats items={[['Records',shown.length]]}/>{shown.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{shown.map((r:any)=><Card key={r.id||r.user_id}><h3 className="text-sm font-semibold">{r.title||r.subject||r.full_name||r.username||r.property_address||'Record'}</h3><p className="mt-2 text-[10px] text-[#73798B]">{r.message||r.worker_occupation||r.property_type||[r.city,r.state].filter(Boolean).join(', ')}</p><p className="mt-3 text-[9px] uppercase text-blue-400">{String(r.status||r.worker_status||'active').replace(/_/g,' ')}</p></Card>)}</div>:<Empty text="Nothing matches this stage."/>}</div>}
function Shell({profile,onLogout,title,tabs,section,setSection,children}:{profile:Profile;onLogout:()=>void;title:string;tabs?:Array<[string,string]>;section?:string;setSection?:(v:string)=>void;children:React.ReactNode}){return <div className="min-h-[100dvh] bg-[#070A10] text-white"><Toaster position="top-center" richColors/><header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#090D14]/95"><div className="mx-auto max-w-7xl px-4 pt-5 lg:px-8"><div className="flex justify-between"><div><p className="text-[9px] font-bold tracking-[.24em] text-blue-400">WEHOUSE STAFF</p><h1 className="mt-2 text-xl font-bold">{title}</h1><p className="mt-1 text-[9px] text-[#555B6C]">{[profile.assigned_lga,profile.assigned_state].filter(Boolean).join(', ')||'Branch assignment required'}</p></div><button onClick={onLogout} className="rounded-xl border border-white/[.08] px-3 text-[10px]">Log out</button></div>{tabs&&<div className="mt-4 flex gap-1 overflow-x-auto pb-3">{tabs.map(([id,label])=><button key={id} onClick={()=>setSection?.(id)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-[10px] ${section===id?'bg-blue-500':'text-[#777D8E]'}`}>{label}</button>)}</div>}</div></header><main className="mx-auto max-w-7xl px-4 py-6 lg:px-8">{children}</main></div>}
function Stats({items}:{items:Array<[string,string|number]>}){return <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{items.map(([a,b])=><Card key={a}><p className="text-[9px] text-[#656B7D]">{a}</p><p className="mt-2 text-xl font-bold">{b}</p></Card>)}</div>}function Card({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4">{children}</div>}function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] p-10 text-center text-[11px] text-[#6D7284]">{text}</div>}function Loading(){return <div className="grid min-h-[60vh] place-items-center bg-[#070A10] text-xs text-[#777D8E]">Loading…</div>}
