import { Toaster } from 'sonner';
import { useStaffPermissions } from '@/hooks/useStaffPermissions';
import PropertyPipelineWorkspace from '@/components/PropertyPipelineWorkspace';
import CommunicationsWorkspace from '@/components/CommunicationsWorkspace';
import StaffVerificationPanel from '@/components/StaffVerificationPanel';
import StaffFieldPanel from '@/components/StaffFieldPanel';
import StaffDashboardLegacy from './StaffDashboardLegacy';
import type { Profile } from '@/types';

type Props={profile:Profile;onLogout:()=>void;onGoToChat?:(convId?:string)=>void;onNavigate?:(page:string)=>void};
type Module='operations'|'finance'|'support'|'verification'|'field_officer';
const MODULES:Module[]=['operations','finance','support','verification','field_officer'];
const TITLES:Record<Exclude<Module,'finance'>,[string,string]>={operations:['Property Operations','Move assigned-branch property requests through inspection, preparation and publication.'],support:['Support','Handle human support conversations for your assigned branch.'],verification:['Worker Verification','Review workers from one list; each worker carries its own current status.'],field_officer:['Field Work','Handle assigned inspections from one list; each inspection carries its own current status.']};

export default function StaffWorkspace(props:Props){const{profile,onLogout}=props;const{permissions,loading}=useStaffPermissions(profile.user_id);const assigned=permissions.filter((value):value is Module=>MODULES.includes(value as Module));if(loading)return <Empty text="Loading staff workspace…"/>;if(assigned.length!==1)return <Shell profile={profile} onLogout={onLogout} title="Staff Workspace" note="Your account must have exactly one Staff responsibility."><Empty text={assigned.length?'This account has conflicting module assignments.':'No Staff module has been assigned yet.'}/></Shell>;const mod=assigned[0];if(mod==='finance')return <StaffDashboardLegacy {...props}/>;const[title,note]=TITLES[mod];const supportScope={state:profile.assigned_state||profile.state||'',lga:profile.assigned_lga||profile.local_government||profile.city||''};return <Shell profile={profile} onLogout={onLogout} title={title} note={note}>{mod==='operations'?<PropertyPipelineWorkspace profile={profile}/>:mod==='support'?<CommunicationsWorkspace profile={profile} scope={supportScope} forcedView="inbox" hideViewTabs/>:mod==='verification'?<StaffVerificationPanel/>:<StaffFieldPanel profile={profile}/>}</Shell>}

function Shell({profile,onLogout,title,note,children}:{profile:Profile;onLogout:()=>void;title:string;note:string;children:React.ReactNode}){return <div className="min-h-[100dvh] bg-[#070A10] text-white"><Toaster position="top-center" richColors/><header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#090D14]/95 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-start justify-between gap-3 px-4 py-4 sm:px-5 lg:px-8"><div><p className="text-[9px] font-bold tracking-[.24em] text-blue-400">WEHOUSE STAFF</p><h1 className="mt-2 text-xl font-bold">{title}</h1><p className="mt-1 max-w-2xl text-[10px] leading-relaxed text-[#7A8091]">{note}</p><p className="mt-2 text-[9px] text-[#555B6C]">{[profile.assigned_lga,profile.assigned_state].filter(Boolean).join(', ')||'Branch assignment required'}</p></div><button onClick={onLogout} className="rounded-xl border border-white/[.08] px-3 py-2 text-[10px] text-[#A3A7B5]">Log out</button></div></header><main className="mx-auto max-w-7xl px-4 py-5 pb-24 sm:px-5 lg:px-8">{children}</main></div>}
function Empty({text}:{text:string}){return <div className="grid min-h-[50vh] place-items-center bg-[#070A10] px-4 text-center text-xs text-[#777D8E]">{text}</div>}
