import { useEffect, useMemo, useState } from 'react';
import { Toaster, toast } from 'sonner';
import { supabase, setWorkerAvailability } from '@/lib/supabase';
import { getMyBookingConversations, BOOKING_STATUS_LABELS } from '@/lib/supabase/worker-bookings';
import BookingNegotiationChat from '@/components/BookingNegotiationChat';
import WorkerWallet from '@/pages/WorkerWallet';
import type { Profile } from '@/types';
import { WORKER_OCCUPATION_LABELS } from '@/types';

type WorkerTab = 'overview' | 'jobs' | 'schedule' | 'earnings' | 'services' | 'reviews' | 'verification';
type Props = { profile: Profile; onGoToSetup: () => void; onLogout: () => void; onNavigate?: (page: string) => void; onGoToChat?: (convId: string) => void; onGoToMessages?: () => void };
type Stats = { views: number; activeJobs: number; completedJobs: number; rating: number; reviewCount: number; availableBalance: number; pendingBalance: number };

const TABS: Array<{ key: WorkerTab; label: string; description: string }> = [
  { key: 'overview', label: 'Overview', description: 'Availability, job status, earnings and performance' },
  { key: 'jobs', label: 'Jobs', description: 'Requests, customer chat, negotiation, active work and completion' },
  { key: 'schedule', label: 'Schedule', description: 'Confirmed jobs with agreed dates and locations' },
  { key: 'earnings', label: 'Earnings & Wallet', description: 'Balances, payouts, withdrawals and transaction history' },
  { key: 'services', label: 'Service Profile', description: 'What customers see when they discover your service' },
  { key: 'reviews', label: 'Reviews', description: 'Customer feedback from completed jobs' },
  { key: 'verification', label: 'Verification', description: 'Verification progress and public eligibility' },
];
const STATUS: Record<string,{label:string;text:string;style:string}> = {
  pending:{label:'Pending',text:'WeHouse has not opened professional verification for this profile yet.',style:'border-amber-500/20 bg-amber-500/[0.07] text-amber-300'},
  verification_paid:{label:'Verification ready',text:'Your verification stage is ready for evidence review.',style:'border-blue-500/20 bg-blue-500/[0.07] text-blue-300'},
  profile_under_review:{label:'Under review',text:'WeHouse is reviewing your identity and skill evidence.',style:'border-violet-500/20 bg-violet-500/[0.07] text-violet-300'},
  verified:{label:'Verified and public',text:'Customers can discover and book you while availability is enabled.',style:'border-emerald-500/20 bg-emerald-500/[0.07] text-emerald-300'},
  rejected:{label:'Changes required',text:'Your review was not approved. Correct the requested information before another review.',style:'border-red-500/20 bg-red-500/[0.07] text-red-300'},
  suspended:{label:'Suspended',text:'Your worker profile is not public. Contact WeHouse support if you need help.',style:'border-red-500/20 bg-red-500/[0.07] text-red-300'},
};

export default function WorkerDashboard({ profile, onGoToSetup, onLogout, onNavigate }: Props) {
  const [tab,setTab]=useState<WorkerTab>('overview'); const current=useMemo(()=>TABS.find(t=>t.key===tab)!,[tab]);
  return <div className="min-h-[100dvh] bg-[#080B11] text-white"><Toaster position="top-center" richColors/>
    <header className="sticky top-0 z-30 border-b border-white/[0.06] bg-[#080B11]/95 backdrop-blur-xl"><div className="mx-auto max-w-7xl px-4 pt-5 lg:px-8"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-[9px] font-bold tracking-[.22em] text-cyan-400">WORKER WORKSPACE</p><h1 className="mt-1 text-lg font-bold">{current.label}</h1><p className="mt-1 text-[10px] text-[#707588]">{current.description}</p></div><div className="flex shrink-0 gap-2">{onNavigate&&<button onClick={()=>onNavigate('profile')} className="rounded-xl border border-white/[0.08] bg-white/[0.04] px-3 py-2 text-[10px] text-[#A3A8B7]">Account</button>}<button onClick={onLogout} className="rounded-xl border border-red-500/15 bg-red-500/[0.05] px-3 py-2 text-[10px] text-red-300">Log out</button></div></div><div className="mt-4 overflow-x-auto pb-3 scrollbar-hide"><div className="flex min-w-max gap-1">{TABS.map(item=><button key={item.key} onClick={()=>setTab(item.key)} className={`rounded-xl px-3 py-2 text-[10px] font-semibold ${tab===item.key?'bg-cyan-500 text-[#051018]':'text-[#74798B] hover:bg-white/[0.04] hover:text-white'}`}>{item.label}</button>)}</div></div></div></header>
    <main className="mx-auto max-w-7xl px-4 py-6 pb-24 lg:px-8 lg:py-8">{tab==='overview'&&<Overview profile={profile} onTab={setTab} onSetup={onGoToSetup}/>} {tab==='jobs'&&<Jobs profile={profile}/>} {tab==='schedule'&&<Schedule profile={profile}/>} {tab==='earnings'&&<WorkerWallet profile={profile}/>} {tab==='services'&&<Services profile={profile} onSetup={onGoToSetup}/>} {tab==='reviews'&&<Reviews profile={profile}/>} {tab==='verification'&&<Verification profile={profile} onNavigate={onNavigate}/>}</main>
  </div>;
}

function Overview({profile,onTab,onSetup}:{profile:Profile;onTab:(tab:WorkerTab)=>void;onSetup:()=>void}) {
 const [stats,setStats]=useState<Stats>({views:0,activeJobs:0,completedJobs:0,rating:0,reviewCount:0,availableBalance:0,pendingBalance:0}); const [available,setAvailable]=useState(Boolean(profile.available)); const [saving,setSaving]=useState(false); const status=STATUS[profile.worker_status||'pending']||STATUS.pending;
 useEffect(()=>{let active=true;void(async()=>{const [views,activeJobs,completed,reviews,wallet]=await Promise.all([supabase.from('worker_views').select('*',{count:'exact',head:true}).eq('worker_id',profile.user_id),supabase.from('worker_bookings').select('*',{count:'exact',head:true}).eq('worker_id',profile.user_id).not('status','in','(approved_released,cancelled,refunded)'),supabase.from('worker_bookings').select('*',{count:'exact',head:true}).eq('worker_id',profile.user_id).eq('status','approved_released'),supabase.from('reviews').select('rating').eq('reviewee_id',profile.user_id),supabase.from('wallets').select('available_balance,pending_balance').eq('owner_id',profile.user_id).eq('owner_type','worker').maybeSingle()]);if(!active)return;const rr=reviews.data||[];setStats({views:views.count||0,activeJobs:activeJobs.count||0,completedJobs:completed.count||0,reviewCount:rr.length,rating:rr.length?rr.reduce((s:number,r:any)=>s+Number(r.rating||0),0)/rr.length:0,availableBalance:Number(wallet.data?.available_balance||0),pendingBalance:Number(wallet.data?.pending_balance||0)})})();return()=>{active=false}},[profile.user_id]);
 async function toggle(){if(profile.worker_status!=='verified')return toast.error('Only verified workers can become publicly available');setSaving(true);const next=!available;const {error}=await setWorkerAvailability(profile.user_id,next);setSaving(false);if(error)return toast.error(error.message||'Unable to update availability');setAvailable(next);toast.success(next?'You are available for bookings':'You are unavailable for bookings')}
 return <div className="space-y-6"><section className="overflow-hidden rounded-3xl border border-cyan-500/15 bg-gradient-to-br from-cyan-500/[0.12] via-[#111722] to-[#0D1119] p-6 lg:p-8"><div className="grid gap-6 lg:grid-cols-[1.4fr_1fr] lg:items-end"><div><span className="rounded-full bg-cyan-400/10 px-3 py-1 text-[9px] font-semibold text-cyan-300">PROFESSIONAL PROFILE</span><h2 className="mt-4 text-2xl font-bold lg:text-3xl">{profile.full_name||profile.username||'Your worker workspace'}</h2><p className="mt-2 max-w-xl text-xs leading-relaxed text-[#9297AA]">New requests and customer conversations belong in Jobs. Scheduled work belongs in Schedule. Money belongs in Earnings & Wallet.</p></div><div className="flex flex-wrap gap-2 lg:justify-end"><button onClick={()=>onTab('jobs')} className="rounded-xl bg-cyan-500 px-4 py-3 text-xs font-semibold text-[#061016]">Open jobs</button><button onClick={onSetup} className="rounded-xl border border-white/[0.08] bg-white/[0.04] px-4 py-3 text-xs font-semibold text-[#C1C5D0]">Edit service profile</button></div></div></section><section className={`rounded-2xl border p-4 ${status.style}`}><p className="text-xs font-semibold">{status.label}</p><p className="mt-1 text-[10px] opacity-80">{status.text}</p></section><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Profile views" value={stats.views}/><Metric label="Active jobs" value={stats.activeJobs}/><Metric label="Completed" value={stats.completedJobs}/><Metric label="Rating" value={stats.reviewCount?`${stats.rating.toFixed(1)} / 5`:'No reviews'}/></section>{profile.worker_status==='verified'&&<section className={`flex items-center justify-between gap-4 rounded-2xl border p-4 ${available?'border-emerald-500/20 bg-emerald-500/[0.06]':'border-white/[0.06] bg-[#10141D]'}`}><div><p className={`text-xs font-semibold ${available?'text-emerald-300':'text-white'}`}>{available?'Available for bookings':'Unavailable for bookings'}</p><p className="mt-1 text-[10px] text-[#6D7284]">{available?'Your profile can appear in worker discovery.':'You are hidden from new booking requests.'}</p></div><button onClick={()=>void toggle()} disabled={saving} className={`relative h-7 w-12 rounded-full ${available?'bg-emerald-500':'bg-[#2A2E38]'} disabled:opacity-50`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${available?'left-6':'left-1'}`}/></button></section>}<section className="grid gap-3 md:grid-cols-2"><MoneyCard label="Available earnings" value={stats.availableBalance} onClick={()=>onTab('earnings')}/><MoneyCard label="Pending earnings" value={stats.pendingBalance} onClick={()=>onTab('earnings')}/></section></div>
}

function Jobs({profile}:{profile:Profile}){const [rows,setRows]=useState<any[]>([]),[filter,setFilter]=useState('all'),[active,setActive]=useState<{conversationId:string;bookingId:string}|null>(null),[loading,setLoading]=useState(true);async function load(){setLoading(true);const {conversations}=await getMyBookingConversations(profile.user_id);setRows(conversations||[]);setLoading(false)}useEffect(()=>{void load()},[profile.user_id]);if(active)return <BookingNegotiationChat conversationId={active.conversationId} bookingId={active.bookingId} profile={profile} isWorker onClose={()=>{setActive(null);void load()}}/>;const shown=filter==='all'?rows:rows.filter(r=>r.booking_status===filter);const filters=[['all','All'],['booking_requested','New requests'],['negotiating','Negotiating'],['waiting_payment','Awaiting payment'],['confirmed','Confirmed'],['in_progress','In progress'],['completed_pending_approval','Awaiting approval'],['approved_released','Paid']];return <div className="space-y-4"><div className="rounded-2xl border border-cyan-500/10 bg-cyan-500/[0.04] p-4"><p className="text-xs font-semibold text-cyan-200">Jobs is the home for customer work</p><p className="mt-1 text-[10px] text-[#7D8496]">Open a job to chat with the customer, negotiate the amount/date, accept work, update progress and complete it. There is no separate duplicate worker Messages area.</p></div><div className="flex gap-1 overflow-x-auto scrollbar-hide">{filters.map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-[10px] font-semibold ${filter===k?'bg-cyan-500 text-[#051018]':'bg-[#10141D] text-[#697083]'}`}>{l}</button>)}</div>{loading?<Loading/>:shown.length===0?<Empty title="No jobs in this stage" text="Customer requests and active work will appear here."/>:<div className="space-y-3">{shown.map(row=>{const status=BOOKING_STATUS_LABELS[row.booking_status];return <button key={row.conversation_id} onClick={()=>setActive({conversationId:row.conversation_id,bookingId:row.booking_id})} className="w-full rounded-2xl border border-white/[0.06] bg-[#10141D] p-4 text-left hover:border-cyan-500/25"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold">{row.service_type||'Service job'}</p><p className="mt-1 text-[10px] text-[#6D7284]">#{row.booking_code} · @{row.other_person_username||row.other_person_name||'customer'}</p></div>{status&&<span className={`rounded-full px-2 py-1 text-[8px] ${status.color}`}>{status.label}</span>}</div>{row.last_message&&<p className="mt-3 truncate text-[10px] text-[#858A9B]">{row.last_message}</p>}{Number(row.negotiated_amount||0)>0&&<p className="mt-3 text-xs font-semibold text-emerald-300">₦{Number(row.negotiated_amount).toLocaleString()}</p>}</button>})}</div>}</div>}
function Schedule({profile}:{profile:Profile}){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;void(async()=>{const {data}=await supabase.from('worker_bookings').select('id,booking_code,service_type,status,scheduled_date,address').eq('worker_id',profile.user_id).not('scheduled_date','is',null).order('scheduled_date',{ascending:true});if(active){setRows(data||[]);setLoading(false)}})();return()=>{active=false}},[profile.user_id]);return loading?<Loading/>:rows.length===0?<Empty title="No scheduled jobs" text="Confirmed jobs with agreed dates will appear here."/>:<div className="space-y-3">{rows.map(r=><section key={r.id} className="rounded-2xl border border-white/[0.06] bg-[#10141D] p-4"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold">{r.service_type||'Service job'}</p><p className="mt-1 text-[10px] text-[#6D7284]">{new Date(r.scheduled_date).toLocaleString()}</p><p className="mt-1 text-[9px] text-[#545A6B]">{r.address||'Address shared in the job conversation'}</p></div><Badge value={r.status}/></div></section>)}</div>}
function Services({profile,onSetup}:{profile:Profile;onSetup:()=>void}){const label=profile.worker_occupation?WORKER_OCCUPATION_LABELS[profile.worker_occupation]||profile.worker_occupation:'Not set';return <div className="space-y-5"><section className="rounded-3xl border border-cyan-500/15 bg-gradient-to-br from-cyan-500/[0.1] to-[#10141D] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.18em] text-cyan-300">Primary service</p><h2 className="mt-2 text-xl font-bold">{label}</h2><p className="mt-2 text-xs leading-relaxed text-[#858A9B]">{profile.worker_bio||'Add a clear description so customers understand your service and experience.'}</p></section><section className="grid gap-3 md:grid-cols-2"><Info label="State" value={profile.state||'Not set'}/><Info label="Local government" value={profile.local_government||profile.city||'Not set'}/><Info label="Experience" value={profile.worker_experience||'Not set'}/><Info label="Verification" value={(profile.worker_status||'pending').replace(/_/g,' ')}/></section><button onClick={onSetup} className="h-11 w-full rounded-xl bg-cyan-500 text-xs font-semibold text-[#051018]">Edit professional profile</button></div>}
function Reviews({profile}:{profile:Profile}){const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;void(async()=>{const {data}=await supabase.from('reviews').select('id,rating,comment,created_at').eq('reviewee_id',profile.user_id).order('created_at',{ascending:false});if(active){setRows(data||[]);setLoading(false)}})();return()=>{active=false}},[profile.user_id]);const avg=rows.length?rows.reduce((s,r)=>s+Number(r.rating||0),0)/rows.length:0;return <div className="space-y-4"><StatsBar label="Average rating" value={rows.length?`${avg.toFixed(1)} ★`:'—'} note={`${rows.length} review${rows.length===1?'':'s'}`}/>{loading?<Loading/>:rows.length===0?<Empty title="No reviews yet" text="Customers can review you after completed jobs."/>:<div className="space-y-3">{rows.map(r=><section key={r.id} className="rounded-2xl border border-white/[0.06] bg-[#10141D] p-4"><p className="text-amber-300">{'★'.repeat(Math.max(0,Math.min(5,Number(r.rating||0))))}</p>{r.comment&&<p className="mt-2 text-xs leading-relaxed text-[#9B9FAE]">{r.comment}</p>}<p className="mt-2 text-[9px] text-[#555B6C]">{new Date(r.created_at).toLocaleDateString()}</p></section>)}</div>}</div>}
function Verification({profile,onNavigate}:{profile:Profile;onNavigate?:(page:string)=>void}){const status=STATUS[profile.worker_status||'pending']||STATUS.pending;return <div className="space-y-4"><section className={`rounded-3xl border p-5 ${status.style}`}><p className="text-sm font-semibold">{status.label}</p><p className="mt-2 text-[11px] leading-relaxed opacity-80">{status.text}</p></section><section className="rounded-2xl border border-white/[0.06] bg-[#10141D] p-5"><h2 className="text-sm font-semibold">Professional verification</h2><p className="mt-2 text-[11px] leading-relaxed text-[#777D8E]">Identity documents and skill evidence stay in the dedicated verification flow. This tab shows progress and opens that single workflow instead of duplicating the form.</p><button onClick={()=>onNavigate?.('worker_verification')} disabled={profile.worker_status==='pending'} className="mt-5 h-11 w-full rounded-xl bg-cyan-500 text-xs font-semibold text-[#051018] disabled:opacity-40">{profile.worker_status==='pending'?'Awaiting verification access':'Open verification workflow'}</button></section></div>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/[0.06] bg-[#10141D] p-4"><p className="text-[9px] text-[#676D7E]">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>}
function MoneyCard({label,value,onClick}:{label:string;value:number;onClick:()=>void}){return <button onClick={onClick} className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[0.05] p-4 text-left hover:border-emerald-500/30"><p className="text-[9px] text-emerald-300/70">{label}</p><p className="mt-2 text-xl font-bold">₦{Number(value||0).toLocaleString('en-NG',{minimumFractionDigits:2})}</p></button>}
function Info({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/[0.06] bg-[#10141D] p-4"><p className="text-[9px] uppercase tracking-wide text-[#606678]">{label}</p><p className="mt-2 text-xs font-medium capitalize">{String(value)}</p></div>}
function StatsBar({label,value,note}:{label:string;value:string;note:string}){return <section className="rounded-2xl border border-white/[0.06] bg-[#10141D] p-5"><p className="text-[10px] text-[#676D7E]">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-1 text-[9px] text-[#555B6C]">{note}</p></section>}
function Badge({value}:{value:string}){const n=String(value||'unknown').replace(/_/g,' ');return <span className="rounded-full bg-cyan-500/10 px-2 py-1 text-[8px] capitalize text-cyan-300">{n}</span>}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-dashed border-white/[0.08] bg-white/[0.015] px-6 py-14 text-center"><p className="text-sm font-semibold">{title}</p><p className="mx-auto mt-2 max-w-md text-[10px] leading-relaxed text-[#666C7D]">{text}</p></div>}
function Loading(){return <div className="grid min-h-40 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-cyan-500 border-t-transparent"/></div>}
