import { useState } from 'react';
import { Toaster } from 'sonner';
import WorkerOverviewPanel from '@/components/WorkerOverviewPanel';
import WorkerJobsPanel from '@/components/WorkerJobsPanel';
import WorkerSchedulePanel from '@/components/WorkerSchedulePanel';
import WorkerWallet from './WorkerWallet';
import type { Profile } from '@/types';
import { WORKER_OCCUPATION_LABELS } from '@/types';

type Tab='overview'|'jobs'|'schedule'|'finance'|'profile';
type Props={profile:Profile;onGoToSetup:()=>void;onLogout:()=>void;onNavigate?:(page:string)=>void;onGoToChat?:(convId:string)=>void;onGoToMessages?:()=>void};
const TABS:Array<[Tab,string]>=[['overview','Overview'],['jobs','Jobs'],['schedule','Schedule'],['finance','Finance'],['profile','Professional Profile']];

export default function WorkerWorkspace({profile,onGoToSetup,onLogout,onNavigate}:Props){const[tab,setTab]=useState<Tab>('overview');const title=TABS.find(([id])=>id===tab)?.[1]||'Worker';return <div className="min-h-[100dvh] bg-[#080B11] text-white"><Toaster position="top-center" richColors/><header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#080B11]/95 backdrop-blur-xl"><div className="mx-auto max-w-7xl px-4 pt-4 sm:px-5 lg:px-8"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold tracking-[.22em] text-cyan-400">WORKER WORKSPACE</p><h1 className="mt-1 text-xl font-bold">{title}</h1></div><div className="flex gap-2">{onNavigate&&<button onClick={()=>onNavigate('profile')} className="rounded-xl border border-white/[.08] px-3 py-2 text-[10px] text-[#A3A8B7]">Account</button>}<button onClick={onLogout} className="rounded-xl border border-red-500/15 bg-red-500/[.05] px-3 py-2 text-[10px] text-red-300">Log out</button></div></div><div className="mt-4 overflow-x-auto pb-3 scrollbar-hide"><div className="flex min-w-max gap-1">{TABS.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-xl px-3 py-2 text-[10px] font-semibold ${tab===id?'bg-cyan-500 text-[#051018]':'text-[#74798B]'}`}>{label}</button>)}</div></div></div></header><main className="mx-auto max-w-7xl px-4 py-5 pb-24 sm:px-5 lg:px-8">{tab==='overview'&&<WorkerOverviewPanel profile={profile} onJobs={()=>setTab('jobs')} onSetup={onGoToSetup} onFinance={()=>setTab('finance')}/>} {tab==='jobs'&&<WorkerJobsPanel profile={profile}/>} {tab==='schedule'&&<WorkerSchedulePanel profile={profile}/>} {tab==='finance'&&<WorkerWallet profile={profile}/>} {tab==='profile'&&<ProfileSummary profile={profile} onSetup={onGoToSetup} onVerification={()=>onNavigate?.('worker_verification')}/>}</main></div>}
function ProfileSummary({profile,onSetup,onVerification}:{profile:Profile;onSetup:()=>void;onVerification:()=>void}){const occupation=profile.worker_occupation?WORKER_OCCUPATION_LABELS[profile.worker_occupation]||profile.worker_occupation:'Not set';return <div className="space-y-4"><section className="rounded-3xl border border-cyan-500/15 bg-[#10141D] p-5"><p className="text-[9px] uppercase tracking-wide text-cyan-300">Primary service</p><h2 className="mt-2 text-xl font-bold">{occupation}</h2><p className="mt-2 text-xs leading-relaxed text-[#858A9B]">{profile.worker_bio||'Add a clear description of your service and experience.'}</p><button onClick={onSetup} className="mt-4 rounded-xl bg-cyan-500 px-4 py-3 text-xs font-semibold text-[#051018]">Edit professional profile</button></section><section className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4"><p className="text-[9px] uppercase tracking-wide text-[#626778]">Verification</p><p className="mt-2 text-sm font-semibold capitalize">{String(profile.worker_status||'pending').replace(/_/g,' ')}</p>{profile.worker_status!=='pending'&&<button onClick={onVerification} className="mt-3 rounded-xl border border-cyan-500/20 px-4 py-2.5 text-[10px] text-cyan-300">Open verification</button>}</section></div>}
