import { useState, useEffect, useMemo } from 'react';
import { getWorkers, getCategoryWithSubcategories, supabase } from '@/lib/supabase';
import { WORKER_OCCUPATION_LABELS } from '@/types';
import type { Profile, ServiceCategory } from '@/types';
import { toast, Toaster } from 'sonner';
import { NIGERIA_STATES, getCitiesForState } from '@/data/nigeria-locations';
import { createBookingRequest, getUserActiveBookings } from '@/lib/supabase/worker-bookings';
import BookingNegotiationChat from '@/components/BookingNegotiationChat';

interface WorkerDiscoveryProps { userCity?: string | null; profile?: Profile | null; onNavigate?: (page: string) => void; preSelectedCategory?: string | null; }

export default function WorkerDiscovery({ userCity, profile, onNavigate, preSelectedCategory }: WorkerDiscoveryProps) {
  const [allWorkers,setAllWorkers]=useState<Profile[]>([]),[categories,setCategories]=useState<(ServiceCategory&{subcategories:any[]})[]>([]),[loading,setLoading]=useState(true),[fetchError,setFetchError]=useState<string|null>(null);
  const [searchQuery,setSearchQuery]=useState(''),[selectedState,setSelectedState]=useState(''),[selectedCity,setSelectedCity]=useState(''),[selectedCategory,setSelectedCategory]=useState<string|null>(null),[selectedSubcategory,setSelectedSubcategory]=useState<string|null>(null),[expandedBio,setExpandedBio]=useState<Set<string>>(new Set());
  const [bookingWorker,setBookingWorker]=useState<Profile|null>(null),[bookingForm,setBookingForm]=useState({description:'',address:'',message:''}),[bookingSubmitting,setBookingSubmitting]=useState(false),[activeBookingChat,setActiveBookingChat]=useState<{conversationId:string;bookingId:string;isWorker:boolean}|null>(null),[activeBookings,setActiveBookings]=useState<Map<string,{status:string;bookingId:string}>>(new Map());

  useEffect(()=>{const uid=profile?.user_id;if(!uid)return;void(async()=>{const{bookings}=await getUserActiveBookings(uid);const map=new Map<string,{status:string;bookingId:string}>();bookings.forEach((b:any)=>map.set(b.worker_id,{status:b.status,bookingId:b.id}));setActiveBookings(map)})()},[profile?.user_id]);
  useEffect(()=>{let cancelled=false;void(async()=>{setLoading(true);setFetchError(null);try{const[{workers,error:wErr},{categories:cats}]=await Promise.all([getWorkers(),getCategoryWithSubcategories().catch(()=>({categories:[]} as any))]);if(cancelled)return;if(wErr){setFetchError(wErr.message||'Failed to load workers');setAllWorkers([])}else setAllWorkers(workers||[]);setCategories(cats||[])}catch(err:any){if(!cancelled)setFetchError(err?.message||'Unexpected error loading workers')}if(!cancelled)setLoading(false)})();return()=>{cancelled=true}},[]);
  useEffect(()=>{if(!preSelectedCategory||!categories.length)return;const exact=categories.find(c=>c.name===preSelectedCategory);if(exact){setSelectedCategory(exact.name);setSelectedSubcategory(null);return}const parent=categories.find(c=>(c.subcategories||[]).some((s:any)=>s.name===preSelectedCategory));if(parent){setSelectedCategory(parent.name);setSelectedSubcategory(preSelectedCategory)}},[preSelectedCategory,categories]);

  const filteredWorkers=useMemo(()=>{let result=allWorkers.filter(w=>w.worker_status==='verified'&&w.available!==false);if(selectedState){const cities=getCitiesForState(selectedState);result=result.filter(w=>cities.includes(w.city||''))}if(selectedCity)result=result.filter(w=>(w.city||'').toLowerCase().trim()===selectedCity.toLowerCase().trim());if(selectedCategory){const q=selectedCategory.toLowerCase();result=result.filter(w=>(w.worker_occupation||'').toLowerCase().includes(q)||(w.worker_bio||'').toLowerCase().includes(q)||((w.worker_skills as string[])||[]).join(' ').toLowerCase().includes(q))}if(selectedSubcategory){const q=selectedSubcategory.toLowerCase();result=result.filter(w=>(w.worker_occupation||'').toLowerCase().includes(q)||((w.worker_skills as string[])||[]).join(' ').toLowerCase().includes(q)||(w.worker_bio||'').toLowerCase().includes(q))}if(searchQuery.trim()){const q=searchQuery.toLowerCase().trim();result=result.filter(w=>[(w.full_name||w.username||''),(w.worker_occupation||''),(WORKER_OCCUPATION_LABELS[w.worker_occupation||'']||''),(w.worker_bio||''),(w.city||''),...((w.worker_skills as string[])||[])].join(' ').toLowerCase().includes(q))}result.sort((a,b)=>{if(userCity){const aa=(a.city||'').toLowerCase().trim()===userCity.toLowerCase().trim(),bb=(b.city||'').toLowerCase().trim()===userCity.toLowerCase().trim();if(aa&&!bb)return-1;if(!aa&&bb)return 1}if(a.is_online&&!b.is_online)return-1;if(!a.is_online&&b.is_online)return 1;return(a.full_name||a.username||'').localeCompare(b.full_name||b.username||'')});return result},[allWorkers,searchQuery,selectedState,selectedCity,selectedCategory,selectedSubcategory,userCity]);
  const citiesForSelectedState=useMemo(()=>getCitiesForState(selectedState),[selectedState]);
  const selectedCategoryData=useMemo(()=>categories.find(c=>c.name===selectedCategory)||null,[categories,selectedCategory]);
  const hasActiveFilters=Boolean(selectedState||selectedCity||selectedCategory||selectedSubcategory||searchQuery.trim());
  const clearFilters=()=>{setSearchQuery('');setSelectedState('');setSelectedCity('');setSelectedCategory(null);setSelectedSubcategory(null)};

  function WorkerStats({workerId}:{workerId:string}){const[stats,setStats]=useState({completedJobs:0,avgRating:0});useEffect(()=>{void(async()=>{const[{count:jobs},{data:reviews}]=await Promise.all([supabase.from('worker_bookings').select('*',{count:'exact',head:true}).eq('worker_id',workerId).eq('status','approved_released'),supabase.from('reviews').select('rating').eq('reviewee_id',workerId)]);const avg=reviews?.length?reviews.reduce((s,r)=>s+r.rating,0)/reviews.length:0;setStats({completedJobs:jobs||0,avgRating:avg})})()},[workerId]);return <div className="mt-1 flex items-center gap-3 text-[9px] text-[#5C5E72]"><span>{stats.avgRating>0?`★ ${stats.avgRating.toFixed(1)}`:'No ratings'}</span><span>·</span><span>{stats.completedJobs} jobs done</span></div>}

  return <div className="min-h-[100dvh] overflow-x-hidden bg-[#0A0A0F] pb-24 text-white"><Toaster position="top-center" richColors/><header className="border-b border-white/[0.06] bg-gradient-to-b from-[#12121A] to-[#0A0A0F] px-4 py-5 sm:px-5"><div className="mx-auto max-w-5xl"><div className="flex items-center gap-3"><button onClick={()=>onNavigate?.('home')} className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white/[0.06] text-[#8A8B9C]">←</button><div className="min-w-0"><h1 className="text-lg font-bold">Find Workers</h1><p className="mt-1 text-[10px] text-[#5C5E72]">Choose the service you need, then compare verified available professionals.</p></div></div></div></header><main className="mx-auto max-w-5xl space-y-4 px-4 py-5 sm:px-5"><section className="rounded-2xl border border-white/[0.06] bg-[#11131B] p-4 sm:p-5"><div className="relative"><span className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-[#5C5E72]">⌕</span><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Search worker, skill or service" className="h-12 w-full rounded-xl border border-white/[0.08] bg-[#181A23] pl-10 pr-10 text-sm outline-none focus:border-blue-500/40"/>{searchQuery&&<button onClick={()=>setSearchQuery('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#707384]">×</button>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Select label="Service category" value={selectedCategory||''} onChange={v=>{setSelectedCategory(v||null);setSelectedSubcategory(null)}} options={categories.map(c=>({value:c.name,label:`${c.icon||''} ${c.name}`.trim()}))} placeholder="All services"/><Select label="Specific service" value={selectedSubcategory||''} onChange={v=>setSelectedSubcategory(v||null)} options={(selectedCategoryData?.subcategories||[]).map((s:any)=>({value:s.name,label:s.name}))} placeholder={selectedCategory?'All in this category':'Choose a category first'} disabled={!selectedCategory}/><Select label="State" value={selectedState} onChange={v=>{setSelectedState(v);setSelectedCity('')}} options={NIGERIA_STATES.map(s=>({value:s.state,label:s.state}))} placeholder="All Nigeria"/><Select label="Local Government" value={selectedCity} onChange={setSelectedCity} options={citiesForSelectedState.map(c=>({value:c,label:c}))} placeholder={selectedState?`All in ${selectedState}`:'Choose a state first'} disabled={!selectedState}/></div><div className="mt-4 flex items-center justify-between gap-3"><p className="text-[10px] text-[#686B7C]">{loading?'Loading…':`${filteredWorkers.length} verified worker${filteredWorkers.length===1?'':'s'} found`}</p>{hasActiveFilters&&<button onClick={clearFilters} className="text-[10px] font-medium text-blue-400">Clear filters</button>}</div></section>
  {fetchError&&<div className="rounded-2xl border border-red-500/20 bg-red-500/5 p-4 text-center"><p className="text-xs text-red-400">{fetchError}</p><button onClick={()=>window.location.reload()} className="mt-2 text-[10px] text-blue-400">Retry</button></div>}
  {loading&&!fetchError&&<div className="grid gap-3 sm:grid-cols-2">{[1,2,3,4].map(i=><div key={i} className="h-32 animate-pulse rounded-2xl bg-[#12121A]"/>)}</div>}
  {!loading&&!fetchError&&filteredWorkers.length===0&&<div className="rounded-2xl border border-dashed border-white/[0.08] px-5 py-14 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#1A1A24] text-2xl text-[#8A8B9C]">⌕</div><p className="mt-4 text-sm text-[#A4A6B2]">{allWorkers.length===0?'No verified workers available yet':'No workers match these filters'}</p><p className="mx-auto mt-2 max-w-sm text-xs leading-relaxed text-[#666979]">{allWorkers.length===0?'Verified and available professionals will appear here.':'Change a service or location filter to see more professionals.'}</p>{hasActiveFilters&&<button onClick={clearFilters} className="mt-4 rounded-xl bg-blue-500/10 px-4 py-2 text-xs font-medium text-blue-300">Show all workers</button>}</div>}
  {!loading&&!fetchError&&filteredWorkers.length>0&&<div className="grid gap-3 sm:grid-cols-2">{filteredWorkers.map(w=>{const skills=(w.worker_skills as string[])||[],nearby=userCity&&(w.city||'').toLowerCase().trim()===userCity.toLowerCase().trim();return <article key={w.user_id} className={`rounded-2xl border bg-[#12121A] p-4 ${w.is_online?'border-green-500/20':'border-[#1E1E2C]'}`}><div className="flex items-start gap-3"><div className="relative h-12 w-12 shrink-0 overflow-hidden rounded-2xl bg-gradient-to-br from-blue-500 to-blue-700">{w.avatar_url?<img src={w.avatar_url} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-lg font-bold">{(w.full_name||w.username||'W')[0].toUpperCase()}</div>}{w.is_online&&<span className="absolute bottom-0 right-0 h-3.5 w-3.5 rounded-full border-2 border-[#12121A] bg-green-400"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><p className="truncate text-sm font-semibold">{w.full_name||w.username||'Worker'}</p><span className="rounded-full border border-blue-500/20 bg-blue-500/10 px-1.5 py-0.5 text-[8px] font-bold text-blue-400">✓ Verified</span>{nearby&&<span className="rounded-full bg-blue-500/10 px-1.5 py-0.5 text-[8px] text-blue-300">In {w.city}</span>}</div><p className="mt-1 text-[10px] text-[#777A8B]">{WORKER_OCCUPATION_LABELS[w.worker_occupation||'']||w.worker_occupation||'Service professional'}{w.city?` · ${w.city}${w.state?`, ${w.state}`:''}`:''}</p><WorkerStats workerId={w.user_id}/></div></div>{skills.length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{skills.slice(0,4).map(s=><span key={s} className="rounded-lg border border-white/[0.06] bg-white/[0.025] px-2 py-1 text-[9px] text-[#8A8D9D]">{s}</span>)}{skills.length>4&&<span className="px-1 py-1 text-[9px] text-[#5C5E72]">+{skills.length-4}</span>}</div>}{w.worker_bio&&<div className="mt-3"><p className={`text-xs leading-relaxed text-[#858899] ${expandedBio.has(w.user_id)?'':'line-clamp-2'}`}>{w.worker_bio}</p>{w.worker_bio.length>80&&<button onClick={()=>setExpandedBio(prev=>{const next=new Set(prev);next.has(w.user_id)?next.delete(w.user_id):next.add(w.user_id);return next})} className="mt-1 text-[10px] text-blue-400">{expandedBio.has(w.user_id)?'Show less':'Read more'}</button>}</div>}<div className="mt-4">{profile&&activeBookings.has(w.user_id)?<button onClick={()=>onNavigate?.('my_bookings')} className="w-full rounded-xl border border-amber-500/15 bg-amber-500/[0.05] px-3 py-2.5 text-xs font-semibold text-amber-300">Booking in progress · View</button>:profile?<button onClick={()=>setBookingWorker(w)} className="w-full rounded-xl bg-blue-500 px-3 py-2.5 text-xs font-semibold">Book worker</button>:<button onClick={()=>toast.info('Please log in to book a worker')} className="w-full rounded-xl border border-white/[0.08] px-3 py-2.5 text-xs text-[#777A8B]">Log in to book</button>}</div></article>})}</div>}
  </main>
  {bookingWorker&&<div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-4" onClick={()=>setBookingWorker(null)}><div className="max-h-[90vh] w-full max-w-sm overflow-y-auto rounded-t-2xl border border-[#1E1E2C] bg-[#12121A] p-5 sm:rounded-2xl" onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold">Book {bookingWorker.full_name||bookingWorker.username||'Worker'}</h3><button onClick={()=>setBookingWorker(null)} className="grid h-8 w-8 place-items-center rounded-lg bg-[#1A1A24] text-[#5C5E72]">×</button></div><div className="space-y-3"><div className="rounded-xl border border-blue-500/10 bg-blue-500/5 p-3 text-[10px] leading-relaxed text-blue-300">Send the work request first. Price negotiation happens in the booking conversation before payment.</div><input value={bookingForm.description} onChange={e=>setBookingForm(f=>({...f,description:e.target.value}))} placeholder="Describe the work needed *" className="h-10 w-full rounded-xl border border-[#2A2A3A] bg-[#1A1A24] px-4 text-sm outline-none focus:border-blue-500"/><input value={bookingForm.address} onChange={e=>setBookingForm(f=>({...f,address:e.target.value}))} placeholder="Service address *" className="h-10 w-full rounded-xl border border-[#2A2A3A] bg-[#1A1A24] px-4 text-sm outline-none focus:border-blue-500"/><textarea value={bookingForm.message} onChange={e=>setBookingForm(f=>({...f,message:e.target.value}))} placeholder="Optional message" rows={2} className="w-full resize-none rounded-xl border border-[#2A2A3A] bg-[#1A1A24] px-4 py-2 text-sm outline-none focus:border-blue-500"/><button onClick={async()=>{if(!bookingForm.description||!bookingForm.address)return toast.error('Description and address required');if(!profile?.user_id)return toast.error('Please log in');setBookingSubmitting(true);const{booking,error}=await createBookingRequest(bookingWorker.user_id,WORKER_OCCUPATION_LABELS[bookingWorker.worker_occupation||'']||'Service',bookingForm.description,bookingForm.address,'',bookingForm.message);setBookingSubmitting(false);if(error)return toast.error('Failed: '+error.message);toast.success('Booking request sent');setBookingWorker(null);setBookingForm({description:'',address:'',message:''});if(booking?.conversation_id)setActiveBookingChat({conversationId:booking.conversation_id,bookingId:booking.booking_id,isWorker:false})}} disabled={bookingSubmitting} className="h-12 w-full rounded-xl bg-blue-500 font-semibold disabled:opacity-40">{bookingSubmitting?'Sending…':'Send booking request'}</button></div></div></div>}
  {activeBookingChat&&profile&&<BookingNegotiationChat conversationId={activeBookingChat.conversationId} bookingId={activeBookingChat.bookingId} profile={profile} isWorker={activeBookingChat.isWorker} onClose={()=>setActiveBookingChat(null)}/>}</div>;
}
function Select({label,value,onChange,options,placeholder,disabled}:{label:string;value:string;onChange:(v:string)=>void;options:Array<{value:string;label:string}>;placeholder:string;disabled?:boolean}){return <label className="block min-w-0"><span className="mb-1.5 block text-[9px] font-semibold uppercase tracking-wide text-[#626577]">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} className="h-11 w-full min-w-0 rounded-xl border border-white/[0.08] bg-[#181A23] px-3 text-xs outline-none disabled:opacity-40"><option value="">{placeholder}</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
