import { useEffect, useMemo, useState } from 'react';
import { Toaster, toast } from 'sonner';
import { getCategoryWithSubcategories, getWorkers, supabase } from '@/lib/supabase';
import { getUserActiveBookings } from '@/lib/supabase/worker-bookings';
import { NIGERIA_STATES, getCitiesForState } from '@/data/nigeria-locations';
import WorkerBookingRequestSheetV2 from '@/components/WorkerBookingRequestSheetV2';
import BookingNegotiationChat from '@/components/BookingNegotiationChat';
import WorkerPublicProfile from '@/components/WorkerPublicProfile';
import SearchableSelect from '@/components/SearchableSelect';
import DiscoveryShell, { DiscoveryEmpty, DiscoveryFilterSheet, DiscoveryToolbar } from '@/components/DiscoveryShell';
import { WORKER_OCCUPATION_LABELS } from '@/types';
import type { Profile, ServiceCategory } from '@/types';

type Category=ServiceCategory&{subcategories:any[]};
type Props={userCity?:string|null;profile?:Profile|null;onNavigate?:(page:string)=>void;preSelectedCategory?:string|null};
type WorkStatus={id:string;worker_id:string;media_type:'image'|'video';storage_path:string;caption:string|null;verified_job:boolean;expires_at:string;created_at:string;url?:string};

export default function WorkerDiscovery({userCity,profile,onNavigate=()=>{},preSelectedCategory}:Props){
 const savedState=profile?.state||'',savedCity=profile?.local_government||profile?.city||userCity||'';
 const[workers,setWorkers]=useState<Profile[]>([]),[categories,setCategories]=useState<Category[]>([]),[statuses,setStatuses]=useState<WorkStatus[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[specialty,setSpecialty]=useState(''),[state,setState]=useState(savedState),[city,setCity]=useState(savedCity),[filtersOpen,setFiltersOpen]=useState(false),[bookingWorker,setBookingWorker]=useState<Profile|null>(null),[viewWorker,setViewWorker]=useState<Profile|null>(null),[story,setStory]=useState<{status:WorkStatus;worker:Profile}|null>(null),[active,setActive]=useState<Set<string>>(new Set()),[chat,setChat]=useState<{conversationId:string;bookingId:string}|null>(null);
 useEffect(()=>{let live=true;void(async()=>{try{const[{workers:rows,error},{categories:cats}]=await Promise.all([getWorkers(),getCategoryWithSubcategories().catch(()=>({categories:[]} as any))]);if(!live)return;if(error)toast.error(error.message||'Unable to load home-service professionals');setWorkers(rows||[]);setCategories((cats||[]) as Category[])}catch(error:any){if(live){setWorkers([]);setCategories([]);toast.error(error?.message||'Unable to load home services')}}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 useEffect(()=>{let live=true;void(async()=>{const{data,error}=await supabase.from('worker_showcase_posts').select('id,worker_id,media_type,storage_path,caption,verified_job,expires_at,created_at').eq('kind','story').is('deleted_at',null).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(30);if(!live||error)return;const enriched=await Promise.all((data||[]).map(async(row:any)=>{const{data:signed}=await supabase.storage.from('worker-showcase').createSignedUrl(row.storage_path,3600);return{...row,url:signed?.signedUrl||''} as WorkStatus}));if(live)setStatuses(enriched)})();return()=>{live=false}},[]);
 useEffect(()=>{if(!profile?.user_id)return;void getUserActiveBookings(profile.user_id).then(({bookings})=>setActive(new Set((bookings||[]).map((row:any)=>row.worker_id))))},[profile?.user_id]);
 useEffect(()=>{if(!preSelectedCategory||!categories.length)return;const direct=categories.find(item=>item.name===preSelectedCategory);if(direct){setCategory(direct.name);setSpecialty('');return}const parent=categories.find(item=>(item.subcategories||[]).some((sub:any)=>sub.name===preSelectedCategory));if(parent){setCategory(parent.name);setSpecialty(preSelectedCategory)}},[preSelectedCategory,categories]);
 useEffect(()=>{if(!state&&savedState){setState(savedState);setCity(savedCity)}},[savedState,savedCity]);
 const selected=useMemo(()=>categories.find(item=>item.name===category)||null,[categories,category]);
 const cities=useMemo(()=>getCitiesForState(state),[state]);
 const categoryOptions=useMemo(()=>categories.map(item=>({value:item.name,label:item.name})),[categories]);
 const specialtyOptions=useMemo(()=>(selected?.subcategories||[]).map((sub:any)=>({value:sub.name,label:sub.name})),[selected]);
 const stateOptions=useMemo(()=>NIGERIA_STATES.map(item=>({value:item.state,label:item.state})),[]);
 const cityOptions=useMemo(()=>cities.map(item=>({value:item,label:item})),[cities]);
 const liveWorkers=useMemo(()=>workers.filter(worker=>worker.worker_status==='verified'&&worker.worker_verified===true&&worker.available!==false),[workers]);
 const latestStatusByWorker=useMemo(()=>{const map=new Map<string,WorkStatus>();statuses.forEach(status=>{if(!map.has(status.worker_id))map.set(status.worker_id,status)});return map},[statuses]);
 const statusWorkers=useMemo(()=>liveWorkers.map(worker=>({worker,status:latestStatusByWorker.get(worker.user_id)})).filter((entry):entry is{worker:Profile;status:WorkStatus}=>Boolean(entry.status)),[liveWorkers,latestStatusByWorker]);
 const shown=useMemo(()=>liveWorkers.filter(worker=>{const hay=[worker.full_name||worker.username||'',worker.worker_occupation||'',worker.worker_bio||'',worker.city||'',worker.local_government||'',worker.state||'',...((worker.worker_skills as string[])||[])].join(' ').toLowerCase(),needle=search.trim().toLowerCase();if(needle&&!hay.includes(needle))return false;if(category&&![(worker.worker_occupation||''),...((worker.worker_skills as string[])||[])].join(' ').toLowerCase().includes(category.toLowerCase()))return false;if(specialty&&!((worker.worker_skills as string[])||[]).some(skill=>skill.toLowerCase()===specialty.toLowerCase()))return false;if(state&&String(worker.state||'').toLowerCase()!==state.toLowerCase())return false;if(city&&String(worker.city||worker.local_government||'').toLowerCase()!==city.toLowerCase())return false;return true}).sort((a,b)=>{const aLocal=city&&String(a.city||a.local_government||'').toLowerCase()===city.toLowerCase(),bLocal=city&&String(b.city||b.local_government||'').toLowerCase()===city.toLowerCase();if(aLocal!==bLocal)return aLocal?-1:1;const rating=Number(b.rating||0)-Number(a.rating||0);return rating||String(a.full_name||a.username||'').localeCompare(String(b.full_name||b.username||''))}),[liveWorkers,search,category,specialty,state,city]);
 const filterCount=[category,specialty,state,city].filter(Boolean).length;
 function clear(){setSearch('');setCategory('');setSpecialty('');setState('');setCity('')}
 function resetStructured(){setCategory('');setSpecialty('');setState(savedState);setCity(savedCity)}
 function created(workerId:string,conversationId:string,bookingId:string){setBookingWorker(null);setActive(current=>new Set(current).add(workerId));setChat({conversationId,bookingId})}
 if(chat&&profile)return <BookingNegotiationChat conversationId={chat.conversationId} bookingId={chat.bookingId} profile={profile} isWorker={false} onClose={()=>setChat(null)}/>;
 if(viewWorker)return <><WorkerPublicProfile worker={viewWorker} onBack={()=>setViewWorker(null)} bookingActive={active.has(viewWorker.user_id)} onOpenBooking={()=>onNavigate('my_bookings')} onBook={()=>profile?setBookingWorker(viewWorker):toast.info('Please sign in to request a professional')}/>{bookingWorker&&profile&&<WorkerBookingRequestSheetV2 worker={bookingWorker} profile={profile} onClose={()=>setBookingWorker(null)} onCreated={(conversationId,bookingId)=>created(bookingWorker.user_id,conversationId,bookingId)}/>}</>;
 return <DiscoveryShell active="services" title="Find a service" description="Browse reviewed professionals across home, lifestyle and specialist service categories." onNavigate={onNavigate}>
  <Toaster position="top-center" richColors/>
  <main className="mx-auto max-w-7xl space-y-5 px-4 py-5 sm:px-6 lg:px-8">
   {statusWorkers.length>0&&<section><div className="mb-3 flex items-end justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-violet-400">WORK STATUS</p><h2 className="mt-1 text-sm font-bold">Recent work from professionals</h2></div><span className="text-[9px] text-[#666D7E]">24-hour updates</span></div><div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide">{statusWorkers.map(({worker,status})=><button key={worker.user_id} onClick={()=>setStory({worker,status})} className="w-24 shrink-0 text-left"><div className="rounded-[26px] bg-gradient-to-br from-violet-300 via-violet-500 to-indigo-500 p-[2px]"><StatusMedia status={status} className="h-32 w-full rounded-3xl bg-[#090C12] object-cover"/></div><p className="mt-1 truncate text-[9px] font-semibold text-[#C6CAD4]">{worker.full_name||worker.username||'Professional'}</p><p className="truncate text-[8px] text-[#686F80]">{status.caption||'Work Status'}</p></button>)}</div></section>}
   <DiscoveryToolbar value={search} onChange={setSearch} placeholder="Search service, skill or name" onFilters={()=>setFiltersOpen(true)} filterCount={filterCount}/>
   <div className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-semibold">{loading?'Finding professionals…':`${shown.length} ${shown.length===1?'professional':'professionals'}`}</p><p className="mt-1 text-[9px] text-[#666D7E]">{state?`Searching ${[city,state].filter(Boolean).join(', ')}`:'Choose State and LGA in filters.'}</p></div>{(search||filterCount)&&<button type="button" onClick={clear} className="text-[9px] font-semibold text-violet-300">Clear</button>}</div>
   {loading?<div className="grid min-h-56 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>:shown.length===0?<DiscoveryEmpty title="No professional matches this search" text="Try a broader service or location."/>:<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{shown.map(worker=><WorkerCard key={worker.user_id} worker={worker} status={latestStatusByWorker.get(worker.user_id)} active={active.has(worker.user_id)} onStatus={status=>setStory({worker,status})} onProfile={()=>setViewWorker(worker)} onBook={()=>profile?setBookingWorker(worker):toast.info('Please sign in to request a professional')} onOpen={()=>onNavigate('my_bookings')}/>)}</div>}
  </main>
  {filtersOpen&&<DiscoveryFilterSheet title="Filter services" onClose={()=>setFiltersOpen(false)} onClear={resetStructured}>
   <div className="grid grid-cols-2 gap-3">
    <SearchableSelect label="Service" value={category} onChange={value=>{setCategory(value);setSpecialty('')}} options={categoryOptions} placeholder="Any service" searchPlaceholder="Search service" />
    <SearchableSelect label="Specialty" value={specialty} onChange={setSpecialty} options={specialtyOptions} placeholder={category?'Any specialty':'Choose service'} searchPlaceholder="Search specialty" disabled={!category} />
   </div>
   <div className="grid grid-cols-2 gap-3">
    <SearchableSelect label="State" value={state} onChange={value=>{setState(value);setCity('')}} options={stateOptions} placeholder="Any State" searchPlaceholder="Search State" />
    <SearchableSelect label="LGA" value={city} onChange={setCity} options={cityOptions} placeholder={state?'Any LGA':'Choose State'} searchPlaceholder="Search LGA" disabled={!state} />
   </div>
   {(savedState||savedCity)&&<p className="rounded-xl border border-white/[.06] bg-white/[.02] px-3 py-2.5 text-[9px] text-[#737A89]">Your saved area is the default: {[savedCity,savedState].filter(Boolean).join(', ')}.</p>}
  </DiscoveryFilterSheet>}
  {story&&<div className="fixed inset-0 z-[95] bg-black/95" onClick={()=>setStory(null)}><div className="mx-auto flex h-full max-w-md flex-col justify-center p-4" onClick={event=>event.stopPropagation()}><div className="mb-3 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center overflow-hidden rounded-full bg-violet-500 text-xs font-bold">{story.worker.avatar_url?<img src={story.worker.avatar_url} alt="" className="h-full w-full object-cover"/>:(story.worker.full_name||story.worker.username||'W')[0].toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{story.worker.full_name||story.worker.username||'Professional'}</p><p className="mt-0.5 text-[9px] text-violet-300">Work Status · 24 hours</p></div><button onClick={()=>setStory(null)} className="grid h-10 w-10 place-items-center rounded-full bg-white/10">×</button></div><StatusMedia status={story.status} controls className="max-h-[68dvh] w-full rounded-3xl bg-black object-contain"/>{story.status.caption&&<p className="mt-3 rounded-2xl bg-white/[.06] p-4 text-[11px] leading-relaxed text-[#D0D3DA]">{story.status.caption}</p>}<button onClick={()=>{setViewWorker(story.worker);setStory(null)}} className="mt-3 h-12 w-full rounded-2xl bg-violet-500 text-xs font-semibold">View professional profile</button></div></div>}
  {bookingWorker&&profile&&<WorkerBookingRequestSheetV2 worker={bookingWorker} profile={profile} onClose={()=>setBookingWorker(null)} onCreated={(conversationId,bookingId)=>created(bookingWorker.user_id,conversationId,bookingId)}/>} 
 </DiscoveryShell>
}

function WorkerCard({worker,status,active,onStatus,onProfile,onBook,onOpen}:{worker:Profile;status?:WorkStatus;active:boolean;onStatus:(status:WorkStatus)=>void;onProfile:()=>void;onBook:()=>void;onOpen:()=>void}){const occupation=WORKER_OCCUPATION_LABELS[worker.worker_occupation||'']||worker.worker_occupation||'Service professional',skills=(worker.worker_skills as string[])||[];return <article className="rounded-3xl border border-white/[.07] bg-[#11141C] p-4"><div className="flex items-start gap-3"><button onClick={()=>status?onStatus(status):onProfile()} className={`shrink-0 rounded-[18px] ${status?'bg-gradient-to-br from-violet-300 via-violet-500 to-indigo-500 p-[2px]':''}`}><div className="grid h-14 w-14 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-violet-500 to-indigo-600 text-lg font-bold">{worker.avatar_url?<img src={worker.avatar_url} alt="" className="h-full w-full object-cover"/>:(worker.full_name||worker.username||'W')[0].toUpperCase()}</div></button><button onClick={onProfile} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-2"><h2 className="min-w-0 flex-1 truncate text-sm font-semibold">{worker.full_name||worker.username||'Professional'}</h2><span className="shrink-0 rounded-full border border-emerald-500/15 bg-emerald-500/[.06] px-2 py-1 text-[7px] font-bold text-emerald-300">REVIEWED</span></div><p className="mt-1 truncate text-[10px] text-[#8A8F9E]">{occupation}</p><p className="mt-1 truncate text-[9px] text-[#606575]">{[worker.city||worker.local_government,worker.state].filter(Boolean).join(', ')||'Location not shown'}</p>{Number(worker.rating||0)>0&&<p className="mt-2 text-[9px] font-semibold text-amber-300">★ {Number(worker.rating).toFixed(1)} · {Number(worker.review_count||0)} reviews</p>}</button></div>{status&&<button onClick={()=>onStatus(status)} className="mt-3 flex w-full items-center justify-between rounded-xl border border-violet-500/15 bg-violet-500/[.05] px-3 py-2 text-left"><span className="text-[9px] font-semibold text-violet-300">● Work Status live</span><span className="text-[9px] text-[#72798A]">Watch →</span></button>}{skills.length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{skills.slice(0,4).map(skill=><span key={skill} className="rounded-lg border border-white/[.06] px-2 py-1 text-[8px] text-[#858A99]">{skill}</span>)}</div>}<div className="mt-4 flex items-center justify-between gap-3"><p className="text-[10px] font-semibold text-[#DDE0E7]">{worker.worker_price?`From ₦${Number(worker.worker_price).toLocaleString()}`:'Discuss price'}</p>{active?<button onClick={onOpen} className="rounded-xl border border-amber-500/20 bg-amber-500/[.06] px-3 py-2 text-[9px] font-semibold text-amber-300">Open booking</button>:<button onClick={onBook} className="rounded-xl bg-violet-500 px-3 py-2 text-[9px] font-semibold text-white">Request</button>}</div></article>}
function StatusMedia({status,className,controls=false}:{status:WorkStatus;className:string;controls?:boolean}){return status.media_type==='video'?<video src={status.url} className={className} controls={controls} playsInline muted={!controls}/>:<img src={status.url} alt="Work Status" className={className}/>}
