import { useEffect,useState } from 'react';
import { Toaster,toast } from 'sonner';
import PayoutBankAccount from '@/components/PayoutBankAccount';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';

type WalletRow={id:string;available_balance:number;pending_balance:number;frozen_balance:number;total_withdrawn:number;is_frozen:boolean;frozen_reason:string|null};
type BankAccount={id:string;bank_name:string;account_number:string;account_name:string;verified_at:string|null};
type Tab='overview'|'withdraw'|'activity';
const money=(value:number)=>`₦${Number(value||0).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function WorkerWallet({profile}:{profile:Profile}){
 const[tab,setTab]=useState<Tab>('overview'),[wallet,setWallet]=useState<WalletRow|null>(null),[transactions,setTransactions]=useState<any[]>([]),[withdrawals,setWithdrawals]=useState<any[]>([]),[bank,setBank]=useState<BankAccount|null>(null),[amount,setAmount]=useState(''),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false);
 async function load(){setLoading(true);const[w,t,wd,b]=await Promise.all([
  supabase.from('wallets').select('id,available_balance,pending_balance,frozen_balance,total_withdrawn,is_frozen,frozen_reason').eq('owner_id',profile.user_id).eq('owner_type','worker').maybeSingle(),
  supabase.from('wallet_transactions').select('*').eq('user_id',profile.user_id).order('created_at',{ascending:false}).limit(30),
  supabase.from('withdrawals').select('id,amount,status,created_at,failed_reason,wallets!inner(owner_id)').eq('wallets.owner_id',profile.user_id).order('created_at',{ascending:false}).limit(20),
  supabase.from('bank_accounts').select('id,bank_name,account_number,account_name,verified_at').eq('user_id',profile.user_id).maybeSingle(),
 ]);if(w.error)toast.error('Unable to load worker wallet');setWallet((w.data||null) as WalletRow|null);setTransactions(t.data||[]);setWithdrawals(wd.data||[]);setBank((b.data||null) as BankAccount|null);setLoading(false)}
 useEffect(()=>{void load()},[profile.user_id]);
 async function withdraw(){if(!wallet)return;const n=Number(amount);if(!n||n<=0)return toast.error('Enter a valid amount');if(n>Number(wallet.available_balance||0))return toast.error('Insufficient available balance');if(!bank?.verified_at)return toast.error('Add and verify your payout account first');if(wallet.is_frozen)return toast.error(wallet.frozen_reason||'Your wallet is frozen');setSubmitting(true);const{data,error}=await supabase.rpc('request_worker_withdrawal',{p_amount:n,p_bank_account_id:bank.id});setSubmitting(false);if(error)return toast.error(error.message||'Withdrawal request failed');if(!data?.success)return toast.error(data?.error||'Withdrawal request failed');toast.success('Withdrawal request submitted');setAmount('');setTab('activity');await load()}
 if(loading)return <Loading/>;
 if(!wallet)return <section className="rounded-2xl border border-amber-500/20 bg-amber-500/[.06] p-5 text-xs text-amber-300">Your Worker wallet has not been created yet. Complete Worker verification or contact WeHouse Support.</section>;
 const tabs:Array<{key:Tab;label:string}>=[{key:'overview',label:'Overview'},{key:'withdraw',label:'Withdraw'},{key:'activity',label:'Activity'}];
 return <div className="min-h-[100dvh] bg-[#09090D] px-4 py-5 pb-24 text-white lg:px-8 lg:py-8"><Toaster position="top-center" richColors/><div className="mx-auto max-w-6xl space-y-5">
  <section className="overflow-hidden rounded-3xl border border-violet-500/15 bg-gradient-to-br from-violet-500/[.12] via-[#151520] to-[#101018] p-5 lg:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-violet-300">Worker wallet</p><p className="mt-2 text-3xl font-bold lg:text-4xl">{money(wallet.available_balance)}</p><p className="mt-2 text-[10px] text-[#85879A]">Available earnings ready for withdrawal.</p></div>{wallet.is_frozen&&<span className="rounded-full border border-red-500/20 bg-red-500/10 px-3 py-1 text-[10px] font-semibold text-red-300">Wallet frozen</span>}</div><div className="mt-6 grid grid-cols-3 gap-2"><Small label="Pending" value={money(wallet.pending_balance)}/><Small label="Held" value={money(wallet.frozen_balance)}/><Small label="Withdrawn" value={money(wallet.total_withdrawn)}/></div></section>
  <div className="flex gap-1 rounded-xl border border-white/[.05] bg-[#111119] p-1">{tabs.map(item=><button key={item.key} onClick={()=>setTab(item.key)} className={`flex-1 rounded-lg px-3 py-2.5 text-[11px] font-semibold ${tab===item.key?'bg-violet-500 text-white':'text-[#77798B]'}`}>{item.label}</button>)}</div>
  {tab==='overview'&&<div className="space-y-4"><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Card label="Available" value={wallet.available_balance}/><Card label="Pending" value={wallet.pending_balance}/><Card label="Held" value={wallet.frozen_balance}/><Card label="Withdrawn" value={wallet.total_withdrawn}/></section><PayoutBankAccount profile={profile} onChanged={load}/>{wallet.frozen_reason&&<section className="rounded-2xl border border-red-500/20 bg-red-500/[.06] p-4 text-[10px] text-red-300">{wallet.frozen_reason}</section>}<section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4 text-[10px] leading-relaxed text-[#797B8E]">Only completed and released job earnings become available. Pending, disputed or frozen funds cannot be withdrawn.</section></div>}
  {tab==='withdraw'&&<div className="space-y-4"><PayoutBankAccount profile={profile} onChanged={load} compact/><section className="rounded-2xl border border-white/[.06] bg-[#111119] p-5"><h2 className="text-sm font-semibold">Request withdrawal</h2><p className="mt-1 text-[10px] text-[#66687B]">Approved withdrawals go only to your current verified payout account.</p><div className="mt-5 space-y-3"><label className="block"><span className="mb-1.5 block text-[10px] text-[#77798B]">Amount</span><div className="flex h-12 items-center rounded-xl border border-white/[.08] bg-[#181822] px-3 focus-within:border-violet-500/40"><span className="mr-1 text-sm text-[#77798B]">₦</span><input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,''))} placeholder="0" className="min-w-0 flex-1 bg-transparent text-lg font-semibold outline-none"/></div></label>{bank?<div className="rounded-xl border border-white/[.06] bg-white/[.025] p-3"><p className="text-[9px] text-[#66687B]">Send to</p><p className="mt-1 text-xs font-medium">{bank.bank_name} · •••• {bank.account_number.slice(-4)}</p><p className="mt-1 truncate text-[9px] text-[#686B7C]">{bank.account_name}</p></div>:<div className="rounded-xl border border-amber-500/15 bg-amber-500/[.05] p-4 text-[10px] text-amber-300">Connect a payout account above before withdrawing.</div>}<button onClick={()=>void withdraw()} disabled={submitting||!amount||!bank?.verified_at} className="h-12 w-full rounded-xl bg-violet-500 text-xs font-semibold disabled:opacity-40">{submitting?'Submitting…':'Request withdrawal'}</button></div></section></div>}
  {tab==='activity'&&<div className="grid gap-4 lg:grid-cols-2"><List title="Transactions" empty="No wallet transactions yet." rows={transactions.map(row=>({id:row.id,title:row.description||row.transaction_type||'Transaction',note:new Date(row.created_at).toLocaleDateString(),amount:Number(row.amount||0),status:row.transaction_type}))}/><List title="Withdrawals" empty="No withdrawal requests yet." rows={withdrawals.map(row=>({id:row.id,title:`Withdrawal · ${row.status}`,note:new Date(row.created_at).toLocaleDateString(),amount:-Number(row.amount||0),status:row.status}))}/></div>}
 </div></div>
}
function Loading(){return <div className="grid min-h-56 place-items-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>}
function Small({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.06] bg-black/10 p-3"><p className="text-[8px] uppercase tracking-wide text-[#6C6E80]">{label}</p><p className="mt-1 truncate text-xs font-semibold">{value}</p></div>}
function Card({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><p className="text-[9px] text-[#66687B]">{label}</p><p className="mt-2 text-lg font-bold">{money(value)}</p></div>}
function List({title,empty,rows}:{title:string;empty:string;rows:Array<{id:string;title:string;note:string;amount:number;status:string}>}){return <section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><h2 className="text-sm font-semibold">{title}</h2>{rows.length===0?<p className="py-10 text-center text-[10px] text-[#5E6072]">{empty}</p>:<div className="mt-3 divide-y divide-white/[.05]">{rows.map(row=><div key={row.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-[11px] font-medium">{row.title}</p><p className="mt-1 text-[9px] text-[#5E6072]">{row.note} · {String(row.status||'').replace(/_/g,' ')}</p></div><p className={`text-xs font-semibold ${row.amount<0?'text-red-300':'text-emerald-300'}`}>{row.amount<0?'-':'+'}{money(Math.abs(row.amount))}</p></div>)}</div>}</section>}
