import { useState,useEffect,useRef } from 'react';
import {
  getBookingMessages,sendBookingMessage,uploadBookingChatImage,
  workerAcceptBooking,workerStartJob,workerMarkComplete,
  customerConfirmCompletion,customerRaiseDispute,cancelBooking,getBookingDetails,
  createWorkerBookingPayment,BOOKING_STATUS_LABELS,
} from '@/lib/supabase/worker-bookings';
import { initializePaystackPopup } from '@/lib/supabase/paystack';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';
import { toast } from 'sonner';

type Props={conversationId:string;bookingId:string;profile:Profile;isWorker:boolean;onClose:()=>void};
export default function BookingNegotiationChat({conversationId,bookingId,profile,isWorker,onClose}:Props){
 const[messages,setMessages]=useState<any[]>([]),[booking,setBooking]=useState<any>(null),[input,setInput]=useState(''),[loading,setLoading]=useState(true),[acceptAmount,setAcceptAmount]=useState(''),[acceptDate,setAcceptDate]=useState(''),[showAcceptForm,setShowAcceptForm]=useState(false),[disputeReason,setDisputeReason]=useState(''),[showDisputeForm,setShowDisputeForm]=useState(false),[cancelReason,setCancelReason]=useState(''),[showCancelForm,setShowCancelForm]=useState(false),[paying,setPaying]=useState(false),[sending,setSending]=useState(false);
 const bottomRef=useRef<HTMLDivElement>(null),fileInputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{void loadAll()},[]);useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 async function loadAll(){const[msgRes,bookingRes]=await Promise.all([getBookingMessages(conversationId),getBookingDetails(bookingId)]);setMessages(msgRes.messages||[]);setBooking(bookingRes.booking);setLoading(false)}
 function openSupport(){window.dispatchEvent(new CustomEvent('openSupportChat',{detail:{category:'worker_service',subject:`Worker booking ${booking?.booking_code||''}`.trim(),contextType:'worker_booking',contextId:bookingId,contextSnapshot:{booking_code:booking?.booking_code||null,service_type:booking?.service_type||null,status:booking?.status||null,scheduled_date:booking?.scheduled_date||null,agreed_amount:booking?.negotiated_amount||booking?.agreed_amount||null,address:booking?.address||null,worker_id:booking?.worker_id||null,customer_id:booking?.user_id||null}}}))}
 async function handleSend(){if(!input.trim()||sending)return;setSending(true);const{error}=await sendBookingMessage(conversationId,input.trim());setSending(false);if(error)return toast.error(error.message||'Message could not be sent');setInput('');void loadAll()}
 async function handleWorkerAccept(){const amount=parseInt(acceptAmount);if(!amount||amount<=0)return toast.error('Enter a valid amount');if(!acceptDate)return toast.error('Pick a schedule date');const{success,error}=await workerAcceptBooking(bookingId,amount,acceptDate);if(error||!success)return toast.error(error?.message||'Booking could not be accepted');toast.success('Booking accepted. The customer can now pay.');setShowAcceptForm(false);void loadAll()}
 async function handleWorkerStart(){const{success,error}=await workerStartJob(bookingId);if(error||!success)return toast.error(error?.message||'Job could not be started');toast.success('Job started');void loadAll()}
 async function handleWorkerComplete(){const{success,error}=await workerMarkComplete(bookingId);if(error||!success)return toast.error(error?.message||'Job could not be completed');toast.success('Marked complete. Waiting for customer confirmation.');void loadAll()}
 async function handleCustomerConfirm(){const{success,error}=await customerConfirmCompletion(bookingId);if(error||!success)return toast.error(error?.message||'Completion could not be confirmed');toast.success('Job confirmed. Payment can be released.');void loadAll()}
 async function handleCustomerDispute(){if(!disputeReason.trim())return toast.error('Enter a reason');const{success,error}=await customerRaiseDispute(bookingId,disputeReason.trim());if(error||!success)return toast.error(error?.message||'Dispute could not be raised');toast.success('Dispute raised for WeHouse review');setShowDisputeForm(false);void loadAll()}
 async function handleCancel(){if(!cancelReason.trim())return toast.error('Enter a reason');const{success,error}=await cancelBooking(bookingId,cancelReason.trim());if(error||!success)return toast.error(error?.message||'Booking could not be cancelled');toast.success('Booking cancelled');setShowCancelForm(false);void loadAll()}
 async function handleCustomerPay(){setPaying(true);try{const{result:bootstrap,error:bootstrapErr}=await createWorkerBookingPayment(bookingId);if(bootstrapErr||!bootstrap?.success){setPaying(false);return toast.error(bootstrap?.error||'Payment initialization failed')}const reference=bootstrap.reference as string,amount=bootstrap.amount as number;const{data:pk}=await supabase.rpc('get_setting_v2',{p_key:'paystack_public_key'});if(!pk){setPaying(false);return toast.error('Paystack not configured')}initializePaystackPopup({publicKey:pk,email:profile.email,amountKobo:Math.round(amount*100),reference,metadata:{payment_type:'worker_booking',expected_amount:amount,booking_id:bookingId},onSuccess:async()=>{const{verifyPaymentWithRetry}=await import('@/lib/supabase/payment-verify');const result=await verifyPaymentWithRetry(reference,{purpose:'worker_booking',expected_amount:amount});result.success?toast.success('Payment successful. The Worker can now start the job.'):toast.error(result.error||'Payment verification failed');setPaying(false);void loadAll()},onCancel:()=>{toast.info('Payment cancelled');setPaying(false)}})}catch(e:any){setPaying(false);toast.error(e?.message||'Payment failed')}}
 async function handlePhotoSelect(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setSending(true);toast.loading('Uploading photo…',{id:'photo-upload'});const{path,error}=await uploadBookingChatImage(file,conversationId);if(error||!path){toast.dismiss('photo-upload');setSending(false);e.target.value='';return toast.error(error?.message||'Photo upload failed')}const{error:sendErr}=await sendBookingMessage(conversationId,path);toast.dismiss('photo-upload');setSending(false);e.target.value='';if(sendErr)return toast.error(sendErr.message||'Photo could not be sent');void loadAll()}
 function isImageUrl(content:string){return Boolean(content)&&/\.(jpg|jpeg|png|gif|webp)(\?.*)?$/i.test(content)}
 const statusInfo=booking?.status?BOOKING_STATUS_LABELS[booking.status]:null;
 if(loading)return <div className="fixed inset-0 z-50 grid place-items-center bg-[#0A0A0F]"><div className="h-8 w-8 animate-spin rounded-full border-2 border-blue-500 border-t-transparent"/></div>;
 return <div className="fixed inset-0 z-50 flex h-[100dvh] flex-col bg-[#0A0A0F]">
  <header className="shrink-0 border-b border-white/[.06] bg-[#12121A] px-4 py-3"><div className="flex items-center gap-3"><button onClick={onClose} className="text-[#747889]">←</button><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold">{isWorker?(booking?.customer_username?`@${booking.customer_username}`:booking?.user_name||'Customer'):booking?.worker_name||'Worker'}</p>{statusInfo&&<span className={`rounded-full px-1.5 py-0.5 text-[8px] ${statusInfo.color}`}>{statusInfo.label}</span>}</div><p className="truncate text-[10px] text-[#686C7D]">{booking?.service_type} · #{booking?.booking_code}</p></div><button onClick={openSupport} className="shrink-0 rounded-xl border border-violet-500/20 bg-violet-500/[.08] px-3 py-2 text-[9px] font-semibold text-violet-300">Support</button></div>
  {booking&&<div className="mt-3 rounded-2xl border border-white/[.06] bg-white/[.025] p-3"><div className="mb-2 flex items-center justify-between"><p className="text-[9px] font-semibold uppercase tracking-wide text-[#656A7A]">Booking status</p>{Number(booking.negotiated_amount||0)>0&&<p className="text-xs font-bold">₦{Number(booking.negotiated_amount).toLocaleString()}</p>}</div><div className="h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-blue-500" style={{width:getProgressWidth(booking.status)}}/></div><p className="mt-1 text-[9px] leading-relaxed text-[#686C7D]">{statusInfo?.description}</p><div className="mt-2 flex flex-wrap gap-1.5">{isWorker&&booking.status==='booking_requested'&&<button onClick={()=>setShowAcceptForm(v=>!v)} className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-3 py-1.5 text-[9px] font-semibold text-emerald-300">Accept booking</button>}{isWorker&&booking.status==='confirmed'&&<button onClick={()=>void handleWorkerStart()} className="rounded-lg bg-blue-500/10 px-3 py-1.5 text-[9px] font-semibold text-blue-300">Start job</button>}{isWorker&&booking.status==='in_progress'&&<button onClick={()=>void handleWorkerComplete()} className="rounded-lg bg-violet-500/10 px-3 py-1.5 text-[9px] font-semibold text-violet-300">Mark complete</button>}{!isWorker&&booking.status==='waiting_payment'&&<button onClick={()=>void handleCustomerPay()} disabled={paying} className="rounded-lg bg-emerald-500 px-3 py-1.5 text-[9px] font-semibold disabled:opacity-50">{paying?'Processing…':`Pay ₦${Number(booking.negotiated_amount||0).toLocaleString()}`}</button>}{!isWorker&&booking.status==='completed_pending_approval'&&<><button onClick={()=>void handleCustomerConfirm()} className="rounded-lg bg-emerald-500 px-3 py-1.5 text-[9px] font-semibold">Confirm completion</button><button onClick={()=>setShowDisputeForm(v=>!v)} className="rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-1.5 text-[9px] font-semibold text-red-300">Raise dispute</button></>}{['booking_requested','negotiating','waiting_payment'].includes(booking.status)&&<button onClick={()=>setShowCancelForm(v=>!v)} className="rounded-lg bg-white/[.04] px-3 py-1.5 text-[9px] text-[#858999]">Cancel</button>}</div>
  {showAcceptForm&&<div className="mt-2 space-y-2 rounded-xl border border-emerald-500/15 bg-emerald-500/[.035] p-2"><input inputMode="numeric" value={acceptAmount} onChange={e=>setAcceptAmount(e.target.value)} placeholder="Agreed price (₦)" className="h-9 w-full rounded-lg border border-white/[.07] bg-[#181A23] px-3 text-xs outline-none"/><input type="date" value={acceptDate} onChange={e=>setAcceptDate(e.target.value)} className="h-9 w-full rounded-lg border border-white/[.07] bg-[#181A23] px-3 text-xs outline-none"/><button onClick={()=>void handleWorkerAccept()} className="h-9 w-full rounded-lg bg-emerald-500 text-[10px] font-semibold">Confirm & accept</button></div>}
  {showDisputeForm&&<div className="mt-2 space-y-2 rounded-xl border border-red-500/15 bg-red-500/[.035] p-2"><textarea value={disputeReason} onChange={e=>setDisputeReason(e.target.value)} rows={2} placeholder="What went wrong?" className="w-full resize-none rounded-lg border border-white/[.07] bg-[#181A23] p-2 text-xs outline-none"/><button onClick={()=>void handleCustomerDispute()} className="h-9 w-full rounded-lg bg-red-500 text-[10px] font-semibold">Submit dispute</button></div>}
  {showCancelForm&&<div className="mt-2 space-y-2 rounded-xl border border-white/[.07] bg-white/[.025] p-2"><textarea value={cancelReason} onChange={e=>setCancelReason(e.target.value)} rows={2} placeholder="Reason for cancellation" className="w-full resize-none rounded-lg border border-white/[.07] bg-[#181A23] p-2 text-xs outline-none"/><div className="grid grid-cols-2 gap-2"><button onClick={()=>setShowCancelForm(false)} className="h-9 rounded-lg bg-white/[.04] text-[10px]">Keep booking</button><button onClick={()=>void handleCancel()} className="h-9 rounded-lg bg-red-500/10 text-[10px] font-semibold text-red-300">Cancel booking</button></div></div>}</div>}</header>
  <div className="flex-1 space-y-3 overflow-y-auto px-4 py-4">{booking&&<div className="rounded-2xl border border-blue-500/10 bg-blue-500/[.04] p-3"><div className="flex items-center justify-between gap-3"><p className="text-[9px] font-semibold uppercase tracking-wide text-blue-300">Booking details</p><button onClick={openSupport} className="text-[9px] font-semibold text-violet-300">Need help?</button></div>{isWorker&&booking?.customer_username&&<p className="mt-2 text-[10px] font-medium text-blue-300">Booked by @{booking.customer_username}</p>}<p className="mt-2 text-xs leading-relaxed">{booking.description||'No description provided'}</p>{booking.address&&<p className="mt-1 text-[10px] text-[#626678]">{booking.address}</p>}{booking.scheduled_date&&<p className="mt-1 text-[10px] text-emerald-300">Scheduled · {new Date(booking.scheduled_date).toLocaleDateString()}</p>}</div>}
  {messages.map(msg=>{const mine=msg.sender_id===profile.user_id,image=isImageUrl(msg.content);return <div key={msg.id} className={`flex ${mine?'justify-end':'justify-start'}`}><div className={`max-w-[78%] overflow-hidden rounded-2xl ${mine?'rounded-br-md bg-blue-500':'rounded-bl-md bg-white/[.055]'} ${image?'p-1.5':'px-4 py-2.5'}`}>{image?<img src={msg.content} alt="Shared" className="max-w-full rounded-xl" onClick={()=>window.open(msg.content,'_blank')}/>:<><p className="text-xs leading-relaxed">{msg.content}</p><p className={`mt-1 text-[8px] ${mine?'text-blue-100/70':'text-[#5C6070]'}`}>{new Date(msg.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p></>}</div></div>})}<div ref={bottomRef}/></div>
  <footer className="chat-input-container shrink-0 border-t border-white/[.06] bg-[#12121A] px-4 pb-safe pt-3">{['booking_requested','negotiating','confirmed','in_progress','completed_pending_approval'].includes(booking?.status)?<div className="flex items-center gap-2"><button onClick={()=>fileInputRef.current?.click()} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/[.05] text-[#747889]">＋</button><input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={handlePhotoSelect}/><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void handleSend()}} placeholder="Message about this job…" className="h-10 min-w-0 flex-1 rounded-xl border border-white/[.07] bg-[#1A1A24] px-3 text-sm outline-none focus:border-blue-500/50"/><button onClick={()=>void handleSend()} disabled={sending||!input.trim()} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-500 disabled:opacity-40">➤</button></div>:<div className="flex items-center justify-between gap-3 py-2"><p className="text-[10px] text-[#656A7A]">This booking conversation is closed.</p><button onClick={openSupport} className="text-[10px] font-semibold text-violet-300">Contact Support</button></div>}</footer>
 </div>
}
function getProgressWidth(status:string){const progress:Record<string,string>={booking_requested:'15%',negotiating:'30%',waiting_payment:'45%',confirmed:'60%',in_progress:'75%',completed_pending_approval:'85%',approved_released:'100%',completed:'100%',disputed:'90%',cancelled:'0%',refunded:'0%'};return progress[status]||'0%'}
