import { useCallback, useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { reactivateUser, suspendUser } from '@/lib/supabase/admin';
import { supabase } from '@/lib/supabase';

type Worker={user_id:string;full_name?:string|null;username?:string|null;email?:string|null;worker_occupation?:string|null;worker_status?:string|null;worker_verified?:boolean;available?:boolean;suspended?:boolean;state?:string|null;local_government?:string|null;city?:string|null;rating?:number|null;review_count?:number|null};
type Checks={payment_confirmed?:boolean;identity_captured?:boolean;identity_passed?:boolean;readiness_passed?:boolean;readiness_percent?:number|null;evidence_saved?:boolean;submitted?:boolean;review_status?:string|null};
const FILTERS=[['all','All'],['onboarding','Onboarding'],['review','Awaiting review'],['live','Live'],['attention','Needs attention']] as const;

export default function CreatorWorkerOversight({actorLabel='Creator'}:{actorLabel?:'Creator'|'Admin'}){
 const[rows,setRows]=useState<Worker[]>([]),[selected,setSelected]=useState<Worker|null>(null),[checks,setChecks]=useState<Checks|null>(null),[loading,setLoading]=useState(true),[loadingChecks,setLoadingChecks]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[reason,setReason]=useState(''),[acting,setActing]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.rpc('admin_get_my_branch_profiles',{p_role:'worker'});if(error)toast.error(error.message);setRows(Array.isArray(data)?data:[]);setLoading(false)},[]);
 useEffect(()=>{void load()},[load]);
 async function open(worker:Worker){setSelected(worker);setReason('');setChecks(null);setLoadingChecks(true);const{data,error}=await supabase.rpc('admin_get_worker_review_trust_status',{p_worker_id:worker.user_id});if(error)toast.error(error.message);else setChecks((data||null) as Checks|null);setLoadingChecks(false)}
 async function changeAccess(){if(!selected)return;setActing(true);const result=selected.suspended?await reactivateUser(selected.user_id):await suspendUser(selected.user_id,reason.trim()||'Worker access paused by Creator oversight');setActing(false);if(result.error)return toast.error(result.error.message);toast.success(selected.suspended?'Worker access restored':'Worker access suspended');setSelected(null);await load()}
 const shown=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(worker=>{const status=worker.worker_status||'pending';const inFilter=filter==='all'||filter==='onboarding'&&['pending','verification_paid'].includes(status)||filter==='review'&&status==='profile_under_review'||filter==='live'&&status==='verified'&&!worker.suspended||filter==='attention'&&(['rejected','suspended'].includes(status)||worker.suspended);if(!inFilter)return false;if(!q)return true;return[worker.full_name,worker.username,worker.email,worker.worker_occupation,status,worker.state,worker.local_government,worker.city].filter(Boolean).join(' ').toLowerCase().includes(q)})},[rows,search,filter]);
 if(selected)return <div className="space-y-4">
  <button onClick={()=>setSelected(null)} className="text-[10px] font-semibold text-violet-400">← Worker oversight</button>
  <section className="rounded-3xl border border-white/[.06] bg-[#10131B] p-5"><div className="flex items-start gap-3"><Avatar worker={selected}/><div className="min-w-0 flex-1"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-violet-300">WEHOUSE SERVICE WORKER</p><h2 className="mt-1 truncate text-lg font-bold">{selected.full_name||selected.username||'Worker'}</h2><p className="mt-1 truncate text-[10px] text-[#707687]">{selected.worker_occupation||'Service not set'} · {[selected.local_government||selected.city,selected.state].filter(Boolean).join(', ')||'Location not set'}</p></div><Status value={selected.suspended?'suspended':selected.worker_status||'pending'}/></div>
   {loadingChecks?<Loading/>:<div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><Check label="Identity" value={checks?.identity_passed?'Current':checks?.identity_captured?'Captured':'Incomplete'} good={!!checks?.identity_passed}/><Check label="Payment" value={checks?.payment_confirmed?'Confirmed':'Incomplete'} good={!!checks?.payment_confirmed}/><Check label="Profile" value={checks?.readiness_passed?`Ready · ${checks.readiness_percent||100}%`:'Incomplete'} good={!!checks?.readiness_passed}/><Check label="Work evidence" value={checks?.evidence_saved?'Submitted':'Missing'} good={!!checks?.evidence_saved}/></div>}
   <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Info label="Marketplace" value={selected.worker_verified?'Published':'Private'}/><Info label="Bookings" value={selected.available?'Available':'Paused'}/><Info label="Rating" value={Number(selected.rating||0)?Number(selected.rating).toFixed(1):'New'}/><Info label="Reviews" value={Number(selected.review_count||0)}/></div>
  </section>
  <section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><h3 className="text-sm font-semibold">Creator oversight</h3><p className="mt-1 text-[9px] leading-5 text-[#737A8B]">Verification Staff review identity and professional evidence. {actorLabel} controls platform access and handles exceptions without duplicating their approval queue.</p>{!selected.suspended&&<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={2} placeholder="Reason for suspending access" className="mt-3 w-full rounded-xl border border-white/[.08] bg-black/20 p-3 text-xs outline-none"/>}<button onClick={()=>void changeAccess()} disabled={acting||(!selected.suspended&&!reason.trim())} className={`mt-3 h-11 w-full rounded-xl text-xs font-semibold disabled:opacity-35 ${selected.suspended?'bg-emerald-500 text-[#04120A]':'bg-red-500/15 text-red-300'}`}>{acting?'Updating access…':selected.suspended?'Restore Worker access':'Suspend Worker access'}</button></section>
 </div>;
 return <div className="space-y-4"><div><h2 className="text-lg font-bold">Worker oversight</h2><p className="mt-1 text-[10px] text-[#707687]">Lifecycle, marketplace access and exceptions. Verification Staff handle professional review.</p></div><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search Worker, service or location" className="h-11 w-full rounded-xl border border-white/[.08] bg-[#141720] px-3 text-xs outline-none"/><div className="flex gap-1 overflow-x-auto scrollbar-hide">{FILTERS.map(([id,label])=><button key={id} onClick={()=>setFilter(id)} className={`shrink-0 rounded-xl px-3 py-2 text-[9px] font-semibold ${filter===id?'bg-violet-500 text-white':'border border-white/[.06] text-[#777D8D]'}`}>{label}</button>)}</div>{loading?<Loading/>:shown.length===0?<Empty/>:<div className="divide-y divide-white/[.06] border-y border-white/[.06]">{shown.map(worker=><button key={worker.user_id} onClick={()=>void open(worker)} className="flex w-full items-center gap-3 py-4 text-left"><Avatar worker={worker}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{worker.full_name||worker.username||'Worker'}</p><p className="mt-1 truncate text-[9px] text-[#686F7F]">{worker.worker_occupation||'Service not set'} · {[worker.local_government||worker.city,worker.state].filter(Boolean).join(', ')||'Location not set'}</p></div><Status value={worker.suspended?'suspended':worker.worker_status||'pending'}/><span className="text-[#555C6D]">›</span></button>)}</div>}</div>
}
function Avatar({worker}:{worker:Worker}){return <div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-violet-500/12 text-sm font-bold text-violet-300">{String(worker.full_name||worker.username||'W')[0].toUpperCase()}</div>}
function Check({label,value,good}:{label:string;value:string;good:boolean}){return <div className={`rounded-xl border p-3 ${good?'border-emerald-500/12 bg-emerald-500/[.035]':'border-white/[.06] bg-black/10'}`}><p className="text-[8px] uppercase text-[#62697A]">{label}</p><p className={`mt-1 text-[10px] font-semibold ${good?'text-emerald-300':'text-[#A0A6B4]'}`}>{value}</p></div>}
function Info({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-white/[.06] bg-black/10 p-3"><p className="text-[8px] uppercase text-[#62697A]">{label}</p><p className="mt-1 text-[10px] font-semibold text-[#A0A6B4]">{value}</p></div>}
function Status({value}:{value:string}){const good=value==='verified',bad=['rejected','suspended'].includes(value);return <span className={`shrink-0 rounded-full px-2 py-1 text-[8px] font-semibold capitalize ${good?'bg-emerald-500/10 text-emerald-300':bad?'bg-red-500/10 text-red-300':'bg-amber-500/10 text-amber-300'}`}>{value.replace(/_/g,' ')}</span>}
function Loading(){return <div className="grid min-h-32 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>}
function Empty(){return <div className="border-y border-dashed border-white/[.08] px-5 py-12 text-center text-[10px] text-[#666C7D]">No Workers match this view.</div>}
