import { useCallback,useEffect,useRef,useState } from 'react';

interface DualRangeSliderProps{min:number;max:number;floor:number;ceiling:number;step:number;onChange:(min:number,max:number)=>void}
function short(v:number){if(v>=1000000)return `₦${(v/1000000).toFixed(v%1000000?1:0)}M`;if(v>=1000)return `₦${Math.round(v/1000)}k`;return `₦${v}`}

export default function DualRangeSlider({min,max,floor,ceiling,step,onChange}:DualRangeSliderProps){
 const trackRef=useRef<HTMLDivElement>(null);const[dragging,setDragging]=useState<'min'|'max'|null>(null),[editing,setEditing]=useState<'min'|'max'|null>(null),[minDraft,setMinDraft]=useState(String(min)),[maxDraft,setMaxDraft]=useState(String(max));
 const safeMin=Math.max(floor,Math.min(min,max-step)),safeMax=Math.max(safeMin+step,Math.min(max,ceiling)),range=ceiling-floor,minPercent=((safeMin-floor)/range)*100,maxPercent=((safeMax-floor)/range)*100;
 useEffect(()=>{if(editing!=='min')setMinDraft(String(safeMin))},[safeMin,editing]);useEffect(()=>{if(editing!=='max')setMaxDraft(String(safeMax))},[safeMax,editing]);
 const fromPosition=useCallback((clientX:number)=>{if(!trackRef.current)return floor;const rect=trackRef.current.getBoundingClientRect(),x=Math.max(0,Math.min(clientX-rect.left,rect.width)),raw=floor+(x/rect.width)*range;return Math.round(raw/step)*step},[floor,range,step]);
 const move=useCallback((clientX:number)=>{if(!dragging)return;const val=fromPosition(clientX);if(dragging==='min')onChange(Math.max(floor,Math.min(val,safeMax-step)),safeMax);else onChange(safeMin,Math.max(safeMin+step,Math.min(val,ceiling)))},[dragging,fromPosition,onChange,floor,ceiling,step,safeMin,safeMax]);
 useEffect(()=>{if(!dragging)return;const mouse=(e:MouseEvent)=>move(e.clientX),up=()=>setDragging(null),touch=(e:TouchEvent)=>{if(e.touches[0])move(e.touches[0].clientX)};window.addEventListener('mousemove',mouse);window.addEventListener('mouseup',up);window.addEventListener('touchmove',touch,{passive:true});window.addEventListener('touchend',up);return()=>{window.removeEventListener('mousemove',mouse);window.removeEventListener('mouseup',up);window.removeEventListener('touchmove',touch);window.removeEventListener('touchend',up)}},[dragging,move]);
 function track(e:React.MouseEvent<HTMLDivElement>){const val=fromPosition(e.clientX);if(Math.abs(val-safeMin)<Math.abs(val-safeMax))onChange(Math.max(floor,Math.min(val,safeMax-step)),safeMax);else onChange(safeMin,Math.max(safeMin+step,Math.min(val,ceiling)))}
 function digits(value:string){return value.replace(/[^0-9]/g,'')}
 function live(which:'min'|'max',raw:string){const draft=digits(raw);if(which==='min')setMinDraft(draft);else setMaxDraft(draft);if(!draft)return;const parsed=Number(draft);if(which==='min'&&parsed>=floor&&parsed<=safeMax-step)onChange(parsed,safeMax);if(which==='max'&&parsed>=safeMin+step&&parsed<=ceiling)onChange(safeMin,parsed)}
 function commit(which:'min'|'max'){if(which==='min'){const parsed=Number(minDraft),wanted=Number.isFinite(parsed)&&minDraft!==''?parsed:safeMin,next=Math.max(floor,Math.min(Math.round(wanted/step)*step,safeMax-step));onChange(next,safeMax);setMinDraft(String(next))}else{const parsed=Number(maxDraft),wanted=Number.isFinite(parsed)&&maxDraft!==''?parsed:safeMax,next=Math.min(ceiling,Math.max(Math.round(wanted/step)*step,safeMin+step));onChange(safeMin,next);setMaxDraft(String(next))}setEditing(null)}
 return <div className="w-full select-none">
  <div className="grid grid-cols-2 gap-2"><ValueBox label="From" value={minDraft} active={editing==='min'} onFocus={()=>setEditing('min')} onChange={v=>live('min',v)} onBlur={()=>commit('min')}/><ValueBox label="To" value={maxDraft} active={editing==='max'} onFocus={()=>setEditing('max')} onChange={v=>live('max',v)} onBlur={()=>commit('max')}/></div>
  <div ref={trackRef} onClick={track} className="relative mt-2 flex h-9 touch-none cursor-pointer items-center"><div className="absolute inset-x-1 h-1 rounded-full bg-[#272B35]"/><div className="absolute h-1 rounded-full bg-violet-500" style={{left:`${minPercent}%`,width:`${maxPercent-minPercent}%`}}/><Handle percent={minPercent} active={dragging==='min'} onMouse={e=>{e.stopPropagation();setDragging('min')}} onTouch={e=>{e.stopPropagation();setDragging('min')}}/><Handle percent={maxPercent} active={dragging==='max'} onMouse={e=>{e.stopPropagation();setDragging('max')}} onTouch={e=>{e.stopPropagation();setDragging('max')}}/></div>
  <div className="flex justify-between px-0.5 text-[7px] font-medium text-[#535A6A]"><span>{short(floor)}</span><span>{short(ceiling)}</span></div>
 </div>
}
function Handle({percent,active,onMouse,onTouch}:{percent:number;active:boolean;onMouse:(e:React.MouseEvent)=>void;onTouch:(e:React.TouchEvent)=>void}){return <div onMouseDown={onMouse} onTouchStart={onTouch} className={`absolute z-10 h-5 w-5 cursor-grab rounded-full border-[3px] border-[#0F1218] bg-violet-500 shadow-md ${active?'scale-110 ring-2 ring-violet-400/20':''}`} style={{left:`${percent}%`,transform:'translateX(-50%)'}}/>}
function ValueBox({label,value,active,onFocus,onChange,onBlur}:{label:string;value:string;active:boolean;onFocus:()=>void;onChange:(v:string)=>void;onBlur:()=>void}){return <label className={`flex h-10 items-center gap-2 rounded-xl border px-3 ${active?'border-violet-500/35 bg-violet-500/[.055]':'border-white/[.07] bg-[#171A21]'}`}><span className="shrink-0 text-[8px] font-medium text-[#697080]">{label}</span><span className="text-[10px] text-[#737A8B]">₦</span><input inputMode="numeric" value={value} onFocus={onFocus} onChange={e=>onChange(e.target.value)} onBlur={onBlur} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}} className="min-w-0 flex-1 bg-transparent text-right text-[11px] font-semibold text-white outline-none"/></label>}
