import type { Listing, ListingStatus } from '@/types';
import { LISTING_STATUS_LABELS, LISTING_STATUS_COLORS } from '@/types';

interface ListingCardProps { listing:Listing;onClick:()=>void;isSaved?:boolean;onToggleSave?:(e:React.MouseEvent)=>void;distanceKm?:number|null; }
export default function ListingCard({listing,onClick,isSaved,onToggleSave,distanceKm}:ListingCardProps){
 const imageUrl=listing.images?.[0]||'https://placehold.co/600x400/1A1A24/5C5E72?text=No+Image';const listingStatus:ListingStatus=listing.status||'available';const rawStatus=String(listing.status||'available');const statusColor=LISTING_STATUS_COLORS[listingStatus]||LISTING_STATUS_COLORS.available;const statusLabel=listing.sub_type==='short_let'&&rawStatus==='occupied'?'Booked now':LISTING_STATUS_LABELS[listingStatus]||'Available';const price=listing.price||0;const priceDisplay=price>=1000000?`₦${(price/1000000).toFixed(1)}M`:price>=1000?`₦${(price/1000).toFixed(0)}k`:`₦${price}`;const priceUnit=listing.sub_type==='short_let'?'/night':'/year';
 const statusBg=statusColor.includes('green')?'bg-green-500/15':statusColor.includes('amber')?'bg-amber-500/15':statusColor.includes('blue')?'bg-violet-500/15':statusColor.includes('red')?'bg-red-500/15':'bg-gray-500/15';const statusText=statusColor.includes('green')?'text-green-400':statusColor.includes('amber')?'text-amber-400':statusColor.includes('blue')?'text-violet-400':statusColor.includes('red')?'text-red-400':'text-gray-400';const statusBorder=statusColor.includes('green')?'border-green-500/20':statusColor.includes('amber')?'border-amber-500/20':statusColor.includes('blue')?'border-violet-500/20':statusColor.includes('red')?'border-red-500/20':'border-gray-500/20';
 const media=(listing.images||[]).filter(Boolean),primary=media[0]||imageUrl;
 return <article onClick={onClick} className="group cursor-pointer border-b border-white/[.07] pb-5"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl bg-[#141720]"><img src={primary} alt={listing.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.02]" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-black/10"/><div className="absolute left-2.5 top-2.5 z-10"><span className={`rounded-full border px-2.5 py-1 text-[8px] font-bold uppercase backdrop-blur-md ${statusBg} ${statusText} ${statusBorder}`}>{statusLabel}</span></div>{onToggleSave&&<button onClick={onToggleSave} aria-label={isSaved?'Remove from saved properties':'Save property'} aria-pressed={isSaved} className="absolute right-2.5 top-2.5 z-10 grid h-10 w-10 place-items-center rounded-full bg-black/45 backdrop-blur-md"><svg width="17" height="17" viewBox="0 0 24 24" fill={isSaved?'#A78BFA':'none'} stroke={isSaved?'#A78BFA':'white'} strokeWidth="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg></button>}<div className="absolute bottom-2.5 left-2.5 z-10"><span className="text-base font-bold">{priceDisplay}</span><span className="ml-1 text-[9px] text-white/65">{priceUnit}</span></div>{(media.length+Number(listing.videos?.length||0))>1&&<span className="absolute bottom-2.5 right-2.5 z-10 rounded-full bg-black/55 px-2 py-1 text-[8px] font-semibold">{media.length} photos{listing.videos?.length?` · ${listing.videos.length} video${listing.videos.length===1?'':'s'}`:''}</span>}</div><div className="px-1 pt-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[8px] font-bold uppercase tracking-[.14em] text-violet-300">{listing.sub_type==='short_let'?'Short Let':'Long Let'}</p><h3 className="mt-1 truncate text-[15px] font-bold">{listing.title}</h3><p className="mt-1 truncate text-[10px] text-[#686F80]">{[listing.city,listing.state].filter(Boolean).join(', ')||'Location unavailable'}</p></div><div className="shrink-0 text-right text-[9px] text-[#9BA0AF]">{listing.bedrooms>0&&<p>{listing.bedrooms} bed · {listing.bathrooms||0} bath</p>}{distanceKm!=null&&Number.isFinite(distanceKm)&&<p className="mt-1 text-violet-300">{distanceKm<1?`${Math.max(1,Math.round(distanceKm*1000))} m`:`${distanceKm.toFixed(distanceKm<10?1:0)} km`} away</p>}</div></div><div className="mt-3 flex items-center gap-2 text-[8px]">{rawStatus==='available'&&<span className="text-emerald-300">● Verified and available</span>}{listing.videos?.length>0&&<span className="text-[#747B8C]">▶ Video preview</span>}</div></div></article>
}
