import { useState } from 'react';

type Props={latitude:number;longitude:number;label?:string;height?:number;approximate?:boolean;showDirections?:boolean};
type Point={latitude:number;longitude:number};

export default function LocationMap({latitude,longitude,label='Property location',height=220,approximate=false,showDirections=false}:Props){
 const target=approximate?{latitude:Math.round(latitude*100)/100,longitude:Math.round(longitude*100)/100}:{latitude,longitude};
 const[user,setUser]=useState<Point|null>(null),[locating,setLocating]=useState(false),[locationError,setLocationError]=useState('');
 const delta=approximate?0.025:0.006,left=target.longitude-delta,right=target.longitude+delta,bottom=target.latitude-delta,top=target.latitude+delta;
 const src=`https://www.openstreetmap.org/export/embed.html?bbox=${left}%2C${bottom}%2C${right}%2C${top}&layer=mapnik&marker=${target.latitude}%2C${target.longitude}`;
 const distance=user?distanceKm(user.latitude,user.longitude,target.latitude,target.longitude):null;
 function locate(){if(!navigator.geolocation){setLocationError('Location is unavailable on this device');return}setLocating(true);setLocationError('');navigator.geolocation.getCurrentPosition(position=>{setUser({latitude:position.coords.latitude,longitude:position.coords.longitude});setLocating(false)},error=>{setLocating(false);setLocationError(error.code===1?'Allow location access to calculate your route':'Current location could not be found')},{enableHighAccuracy:true,timeout:20000,maximumAge:15000})}
 const directions=`https://www.google.com/maps/dir/?api=1&destination=${target.latitude}%2C${target.longitude}${user?`&origin=${user.latitude}%2C${user.longitude}`:''}&travelmode=driving`;
 return <div className="overflow-hidden rounded-2xl border border-white/[0.08] bg-[#10131B]"><iframe title={label} src={src} style={{height}} className="w-full border-0" loading="lazy"/><div className="space-y-3 px-3 py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold text-white">{label}</p><p className="mt-1 text-[9px] text-[#6D7182]">{approximate?'Exact address stays private until reservation':'Verified property pin'}{distance!==null?` · about ${distance<1?`${Math.max(1,Math.round(distance*1000))} m`:`${distance.toFixed(1)} km`} away`:''}</p></div>{showDirections&&!user&&<button type="button" onClick={locate} disabled={locating} className="shrink-0 rounded-lg border border-violet-500/20 px-3 py-2 text-[9px] font-semibold text-violet-300 disabled:opacity-50">{locating?'Locating…':'Use my location'}</button>}</div>{locationError&&<p className="text-[9px] text-amber-300">{locationError}</p>}<div className="grid grid-cols-2 gap-2"><a href={`https://www.openstreetmap.org/?mlat=${target.latitude}&mlon=${target.longitude}#map=16/${target.latitude}/${target.longitude}`} target="_blank" rel="noreferrer" className="grid min-h-10 place-items-center rounded-xl border border-white/[0.08] text-[9px] font-semibold text-[#B7BBC7]">Open map</a>{showDirections&&<a href={directions} target="_blank" rel="noreferrer" className="grid min-h-10 place-items-center rounded-xl bg-violet-500 text-[9px] font-semibold text-white">Get directions</a>}</div></div></div>
}

export function distanceKm(aLat:number,aLon:number,bLat:number,bLon:number){const r=6371;const rad=(v:number)=>v*Math.PI/180;const dLat=rad(bLat-aLat),dLon=rad(bLon-aLon);const x=Math.sin(dLat/2)**2+Math.cos(rad(aLat))*Math.cos(rad(bLat))*Math.sin(dLon/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
