import { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';

type Props={latitude:number;longitude:number;label?:string;height?:number;approximate?:boolean;showDirections?:boolean};
type Point={latitude:number;longitude:number};

export default function LocationMap({latitude,longitude,label='Property location',height=220,approximate=false,showDirections=false}:Props){
 const target=approximate?{latitude:Math.round(latitude*100)/100,longitude:Math.round(longitude*100)/100}:{latitude,longitude};
 const[user,setUser]=useState<Point|null>(null),[locating,setLocating]=useState(false),[locationError,setLocationError]=useState('');
 const host=useRef<HTMLDivElement|null>(null),mapRef=useRef<L.Map|null>(null),layersRef=useRef<L.LayerGroup|null>(null);
 const distance=user?distanceKm(user.latitude,user.longitude,target.latitude,target.longitude):null;
 useEffect(()=>{if(!host.current||mapRef.current)return;const map=L.map(host.current,{zoomControl:false});mapRef.current=map;L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'© OpenStreetMap © CARTO'}).addTo(map);layersRef.current=L.layerGroup().addTo(map);map.setView([target.latitude,target.longitude],approximate?14:17);window.setTimeout(()=>map.invalidateSize(),100);return()=>{map.remove();mapRef.current=null;layersRef.current=null}},[]);
 useEffect(()=>{const layer=layersRef.current,map=mapRef.current;if(!layer||!map)return;layer.clearLayers();L.circleMarker([target.latitude,target.longitude],{radius:10,color:'#DDD6FE',weight:3,fillColor:'#7C3AED',fillOpacity:.95}).bindTooltip(approximate?'Approximate property area':'Property').addTo(layer);if(approximate)L.circle([target.latitude,target.longitude],{radius:1100,color:'#8B5CF6',weight:1,fillColor:'#8B5CF6',fillOpacity:.09}).addTo(layer);if(user){L.circleMarker([user.latitude,user.longitude],{radius:8,color:'#fff',weight:3,fillColor:'#22C55E',fillOpacity:1}).bindTooltip('You').addTo(layer);L.polyline([[user.latitude,user.longitude],[target.latitude,target.longitude]],{color:'#A78BFA',weight:3,dashArray:'7 8'}).addTo(layer);map.fitBounds([[user.latitude,user.longitude],[target.latitude,target.longitude]],{padding:[35,35],maxZoom:15})}else map.setView([target.latitude,target.longitude],approximate?14:17)},[target.latitude,target.longitude,approximate,user]);
 function locate(){if(!navigator.geolocation){setLocationError('This browser cannot share your location. Open WeHouse in Chrome or Safari with Location enabled.');return}setLocating(true);setLocationError('');navigator.geolocation.getCurrentPosition(position=>{setUser({latitude:position.coords.latitude,longitude:position.coords.longitude});setLocating(false)},error=>{setLocating(false);setLocationError(error.code===error.PERMISSION_DENIED?'Location is off for WeHouse. Tap the site controls beside the web address, allow Location, turn on Precise location or GPS, then try again.':error.code===error.TIMEOUT?'We could not get your location in time. Turn on Location and GPS, then try again.':'Your location could not be read. Turn on Location and GPS, then try again.')},{enableHighAccuracy:true,timeout:20000,maximumAge:15000})}
 return <div className="overflow-hidden rounded-2xl border border-white/[0.08] bg-[#10131B]"><div ref={host} style={{height}} className="w-full" role="img" aria-label={label}/><div className="space-y-3 px-3 py-3"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold text-white">{label}</p><p className="mt-1 text-[9px] text-[#6D7182]">{approximate?'Purple area: approximate property vicinity':'Purple pin: property location'}{distance!==null?` · about ${distance<1?`${Math.max(1,Math.round(distance*1000))} m`:`${distance.toFixed(1)} km`} from you`:''}</p></div>{showDirections&&<button type="button" onClick={locate} disabled={locating} className="shrink-0 rounded-lg border border-violet-500/20 px-3 py-2 text-[9px] font-semibold text-violet-300 disabled:opacity-50">{locating?'Finding you…':user?'Update my position':'Show my position'}</button>}</div>{user&&<p className="text-[9px] text-[#8D93A3]"><span className="text-emerald-300">● You</span> · <span className="text-violet-300">● Property</span> · approximate direction and distance are shown together on this map</p>}{locationError&&<p className="rounded-xl bg-amber-500/10 px-3 py-2 text-[9px] leading-5 text-amber-200" role="alert">{locationError}</p>}</div></div>
}

export function distanceKm(aLat:number,aLon:number,bLat:number,bLon:number){const r=6371;const rad=(v:number)=>v*Math.PI/180;const dLat=rad(bLat-aLat),dLon=rad(bLon-aLon);const x=Math.sin(dLat/2)**2+Math.cos(rad(aLat))*Math.cos(rad(bLat))*Math.sin(dLon/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
