import { useEffect,useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';

export default function ManageListing({listingId,done}:{listingId:string;done:()=>void}){
 const[listing,setListing]=useState<any|null>(null),[editing,setEditing]=useState(false),[preview,setPreview]=useState(false),[confirming,setConfirming]=useState(false),[busy,setBusy]=useState(false),[form,setForm]=useState({title:'',description:'',price:''});
 async function load(){const{data,error}=await supabase.from('listings').select('*').eq('id',listingId).maybeSingle();if(error)return toast.error(error.message);setListing(data);if(data)setForm({title:data.title||'',description:data.description||'',price:String(data.price||'')})}
 useEffect(()=>{void load()},[listingId]);
 async function save(){if(!form.title.trim()||!Number(form.price))return toast.error('Title and a valid price are required');setBusy(true);try{const{data,error}=await supabase.rpc('creator_update_listing',{p_listing_id:listingId,p_changes:{title:form.title.trim(),description:form.description.trim(),price:Number(form.price)}});if(error)throw error;setListing(data);setEditing(false);setPreview(false);toast.success(listing?.status==='draft'?'Draft details saved':'Property details updated')}catch(error:any){toast.error(error.message||'Could not update property')}finally{setBusy(false)}}
 async function remove(){setBusy(true);const{error}=await supabase.rpc('creator_remove_listing',{p_listing_id:listingId,p_reason:'Removed from property management'});setBusy(false);if(error)return toast.error(error.message);toast.success('Property removed from the marketplace');done()}
 if(!listing)return null;
 const photos=listing.images||[];
 if(preview)return <section className="border-t border-white/[.07] pt-5"><button onClick={()=>setPreview(false)} className="text-[10px] font-semibold text-violet-300">← Back to editing</button><div className="mt-3 overflow-hidden rounded-3xl bg-[#11141C]"><div className="aspect-[4/3]">{photos[0]?<img src={photos[0]} alt="Property preview" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-xs text-[#666D7E]">No image</div>}</div><div className="p-4"><p className="text-lg font-bold">{form.title}</p><p className="mt-1 text-sm font-bold text-violet-300">₦{Number(form.price||0).toLocaleString()} / year</p><p className="mt-3 text-[10px] leading-5 text-[#8A90A0]">{form.description||'No description'}</p></div></div><button disabled={busy} onClick={()=>void save()} className="mt-3 min-h-12 w-full rounded-xl bg-violet-500 text-xs font-semibold disabled:opacity-40">{busy?'Saving…':'Save corrected listing'}</button></section>;
 return <section className="border-t border-white/[.07] pt-5"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">Listing details</h3><p className="mt-1 text-[9px] text-[#73798A]">Correct the public text and price. Gallery choices come only from submitted partner and Field Operations photos above.</p></div><button onClick={()=>setEditing(value=>!value)} className="rounded-xl border border-white/[.08] px-3 py-2 text-[9px] font-semibold">{editing?'Close':'Edit'}</button></div>{editing&&<div className="mt-4 space-y-3"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Property title" className="h-11 w-full border-b border-white/[.08] bg-transparent text-sm outline-none"/><input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Annual rent" className="h-11 w-full border-b border-white/[.08] bg-transparent text-sm outline-none"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4} placeholder="Description" className="w-full resize-none border-b border-white/[.08] bg-transparent py-2 text-sm outline-none"/><div className="grid grid-cols-2 gap-2"><button onClick={()=>setPreview(true)} className="min-h-11 rounded-xl bg-violet-500 text-xs font-semibold">Preview changes</button><button onClick={()=>setConfirming(true)} className="min-h-11 rounded-xl border border-red-500/20 text-xs font-semibold text-red-300">Remove property</button></div></div>}{confirming&&<div className="mt-4 rounded-2xl border border-red-500/20 bg-red-500/[.05] p-4"><p className="text-sm font-semibold">Remove this property?</p><p className="mt-1 text-[10px] leading-5 text-[#8E8290]">It disappears from discovery. WeHouse keeps reservation and payment history. Active reservations block removal.</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setConfirming(false)} className="min-h-10 rounded-xl border border-white/[.08] text-xs">Keep</button><button disabled={busy} onClick={()=>void remove()} className="min-h-10 rounded-xl bg-red-500 text-xs font-semibold disabled:opacity-40">{busy?'Removing…':'Remove'}</button></div></div>}</section>
}
