import { useCallback,useEffect,useState } from 'react';
import { getAnnouncementsForUser,supabase } from '@/lib/supabase';
import VerifiedBadge from './VerifiedBadge';
import type { Profile } from '@/types';

type Props={profile:Profile;onOpen:()=>void;compact?:boolean};

export default function OfficialEntryCard({profile,onOpen,compact=false}:Props){
 const[title,setTitle]=useState('Official announcements'),[preview,setPreview]=useState('Updates from WeHouse will appear here.'),[unread,setUnread]=useState(0),[time,setTime]=useState<string|null>(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{const{messages}=await getAnnouncementsForUser(profile.user_id);const rows=(messages||[]) as any[];setUnread(rows.filter(row=>!row.read_status).length);const latest=rows[0]?.announcements||rows[0]?.announcement;setTitle(latest?.title||'Official announcements');setPreview(latest?.content||'Updates from WeHouse will appear here.');setTime(latest?.created_at||rows[0]?.delivered_at||null);setLoading(false)},[profile.user_id]);
 useEffect(()=>{void load();const channel=supabase.channel(`official-entry:${profile.user_id}`).on('postgres_changes',{event:'*',schema:'public',table:'announcement_recipients',filter:`user_id=eq.${profile.user_id}`},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[profile.user_id,load]);
 const inner=<><div className="relative grid h-12 w-12 shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-violet-600 font-bold text-white shadow-lg shadow-violet-500/10">W<span className="absolute -bottom-0.5 -right-0.5 grid h-4 w-4 place-items-center rounded-full border-2 border-[#11141C] bg-violet-400"><VerifiedBadge size={8}/></span></div><div className="min-w-0 flex-1"><div className="flex min-w-0 items-center gap-1.5"><p className="truncate text-[13px] font-semibold text-white">WeHouse Official</p><VerifiedBadge size={11}/></div><p className={`mt-1 truncate text-[11px] ${unread?'font-medium text-[#E3E5EB]':'text-[#777C8D]'}`}>{loading?'Checking updates…':title}</p><p className="mt-0.5 truncate text-[9px] text-[#5F6474]">{loading?'':preview}</p></div><div className="shrink-0 self-start pt-0.5 text-right">{time&&<p className={`text-[8px] ${unread?'text-violet-300':'text-[#555A6B]'}`}>{formatTime(time)}</p>}{unread>0&&<span className="ml-auto mt-2 grid h-5 min-w-5 place-items-center rounded-full bg-violet-500 px-1 text-[8px] font-bold text-white">{unread>99?'99+':unread}</span>}</div></>;
 return <button onClick={onOpen} className={compact?'flex w-full items-center gap-3 px-4 py-3.5 text-left transition hover:bg-white/[.025]':'flex w-full items-center gap-3 rounded-2xl border border-white/[.06] bg-[#11141C] p-4 text-left transition hover:border-violet-500/20'}>{inner}</button>
}
function formatTime(value:string){const d=new Date(value),now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const days=Math.floor((now.getTime()-d.getTime())/86400000);if(days===1)return'Yesterday';if(days<7)return d.toLocaleDateString([],{weekday:'short'});return d.toLocaleDateString([],{month:'short',day:'numeric'})}
