import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";
import PropertyMediaCarousel from "@/components/PropertyMediaCarousel";
import HotelBookingChat from "@/components/HotelBookingChat";
import { getMyHotelConversations, type HotelConversation } from "@/lib/supabase/hotel-chat";
import type { Profile } from "@/types";
import WeHouseSelect from "@/components/WeHouseSelect";

type HotelAccessRole="owner"|"manager"|"staff";
type Props={hotel:any;accessRole:HotelAccessRole;onBack:()=>void;profile?:Profile};
type Room={room_id:number;hotel_id:number;room_type:string;description:string|null;price_per_night:number;max_guests:number;bed_type:string|null;images:string[];amenities:string[];total_rooms:number};
type Booking={booking_id:number;room_id:number;check_in:string;check_out:string;guest_count:number;guest_name:string|null;booking_code:string|null;status:string;payment_status:string;total_price:number;special_requests:string|null;profiles?:{username?:string|null}|null;hotel_rooms?:{room_type?:string|null}|null};
type ActiveHotelChat={booking_id:number;conversation_id?:string|null;guest_name?:string|null;booking_code?:string|null};
type Inventory={room_id:number;inventory_date:string;available_quantity:number;rate_override:number|null;closed:boolean};
const today=()=>new Date().toISOString().slice(0,10);
const money=(value:number)=>`₦${Number(value||0).toLocaleString("en-NG")}`;
const HOTEL_STATUS:Record<string,string>={pending:"Awaiting payment",confirmed:"Stay confirmed",checked_in:"Checked in",checked_out:"Checked out",completed:"Stay completed",cancelled:"Cancelled",refunded:"Refunded",expired:"Payment expired",payment_conflict:"Payment review"};

export default function PartnerHotelOperations({hotel,accessRole,onBack,profile}:Props){
 const[rooms,setRooms]=useState<Room[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[hotelChats,setHotelChats]=useState<HotelConversation[]>([]),[activeChat,setActiveChat]=useState<ActiveHotelChat|null>(null),[loading,setLoading]=useState(true),[section,setSection]=useState<"today"|"availability"|"rooms"|"reservations"|"team">("today"),[reservationQuery,setReservationQuery]=useState(""),[reservationFilter,setReservationFilter]=useState("all"),[editing,setEditing]=useState<Room|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const date=today();const canHandleGuests=accessRole!=="manager";const [roomResult,bookingResult,inventoryResult,chatResult]=await Promise.all([
	  supabase.from("hotel_rooms").select("*").eq("hotel_id",hotel.hotel_id).order("price_per_night"),
	  canHandleGuests?supabase.from("hotel_bookings").select("booking_id,room_id,check_in,check_out,guest_count,guest_name,booking_code,status,payment_status,total_price,special_requests,profiles(username),hotel_rooms(room_type)").eq("hotel_id",hotel.hotel_id).order("created_at",{ascending:false}).limit(200):Promise.resolve({data:[],error:null}),
	  supabase.from("hotel_inventory_daily").select("room_id,inventory_date,available_quantity,rate_override,closed").eq("hotel_id",hotel.hotel_id).gte("inventory_date",date).lte("inventory_date",date),
	  canHandleGuests?getMyHotelConversations():Promise.resolve({conversations:[],error:null}),
	 ]);if(roomResult.error||bookingResult.error||inventoryResult.error)toast.error(roomResult.error?.message||bookingResult.error?.message||inventoryResult.error?.message||"Hotel operation could not be loaded");setRooms((roomResult.data||[]) as Room[]);setBookings((bookingResult.data||[]) as unknown as Booking[]);setInventory((inventoryResult.data||[]) as Inventory[]);setHotelChats((chatResult.conversations||[]).filter(row=>Number(row.hotel_id)===Number(hotel.hotel_id)));setLoading(false)},[accessRole,hotel.hotel_id]);
 useEffect(()=>{void load()},[load]);
 const date=today(),activeBookings=bookings.filter(row=>["pending","confirmed","checked_in"].includes(row.status));
 const metrics=useMemo(()=>({arrivals:bookings.filter(row=>row.check_in===date&&row.status==="confirmed").length,staying:bookings.filter(row=>row.status==="checked_in").length,departures:bookings.filter(row=>row.check_out===date&&row.status==="checked_in").length,attention:bookings.filter(row=>row.status==="payment_conflict"||(row.check_in<=date&&row.status==="confirmed")).length}),[bookings,date]);
 const available=rooms.reduce((sum,room)=>{const override=inventory.find(row=>row.room_id===room.room_id);const reserved=activeBookings.filter(row=>row.room_id===room.room_id&&row.check_in<=date&&row.check_out>date).length;return sum+Math.max(0,(override?.closed?0:override?.available_quantity??room.total_rooms)-reserved)},0);
 const metricRows=([["Rooms available",available],["Arriving today",metrics.arrivals],["Guests staying",metrics.staying],["Leaving today",metrics.departures],["Needs attention",metrics.attention]] as Array<[string,number]>).filter(([label,value])=>label==="Rooms available"||value>0);
 const filteredBookings=bookings.filter(row=>{if(reservationFilter!=="all"&&row.status!==reservationFilter)return false;const query=reservationQuery.trim().toLowerCase();return !query||[row.guest_name,row.profiles?.username,row.booking_code,row.hotel_rooms?.room_type,row.status].filter(Boolean).join(" ").toLowerCase().includes(query)});
 async function transition(booking:Booking,status:"checked_in"|"checked_out"){setBusy(true);const{error}=await supabase.rpc("partner_transition_hotel_booking",{p_booking_id:booking.booking_id,p_status:status});setBusy(false);if(error){toast.error(error.message);return}toast.success(status==="checked_in"?"Guest checked in":"Checkout completed");await load()}
 function messageWeHouse(booking?:Booking){window.dispatchEvent(new CustomEvent("openSupportChat",{detail:{category:"hotel_operations",subject:booking?`${hotel.name} · ${booking.booking_code||"Hotel reservation"}`:hotel.name||"Hotel operations",contextType:"hotel_operations",contextId:String(booking?.booking_id||hotel.hotel_id),contextSnapshot:{source_type:"hotel_operations",source_id:String(booking?.booking_id||hotel.hotel_id),hotel_id:hotel.hotel_id,hotel_name:hotel.name,booking_id:booking?.booking_id||null,booking_code:booking?.booking_code||null,room_name:booking?.hotel_rooms?.room_type||null,status:booking?.status||hotel.status}}}))}
 const tabs:[typeof section,string][]=accessRole==="owner"?[["today","Today"],["availability","Availability"],["rooms","Rooms"],["reservations","Reservations"],["team","Team"]]:accessRole==="manager"?[["today","Today"],["availability","Availability"],["rooms","Rooms"]]:[["today","Today"],["reservations","Reservations"]];
 return <div className="space-y-5"><header className="flex items-center gap-3 border-b border-white/[.07] pb-4"><button onClick={onBack} aria-label="Back to hotels" className="grid h-11 w-11 place-items-center rounded-full text-xl text-[#A0A5B4]">‹</button><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-bold">{hotel.name}</h2><p className="mt-0.5 truncate text-[9px] text-[#6F7586]">{[hotel.address,hotel.city,hotel.state].filter(Boolean).join(", ")} · {hotel.status==="active"?"Live":"Not public"}</p></div>{accessRole==="owner"?<button type="button" onClick={()=>messageWeHouse()} className="shrink-0 rounded-full border border-white/[.09] px-3 py-2 text-[9px] font-semibold text-[#B9BECA]">Message WeHouse</button>:null}</header>
 <div className="flex border-b border-white/[.07]" aria-label="Hotel workspace sections">{tabs.map(([id,label])=><button key={id} onClick={()=>{setSection(id);window.scrollTo({top:0,behavior:"smooth"})}} className={`relative min-h-12 flex-1 px-1 text-[9px] font-semibold ${section===id?'text-violet-300':'text-[#747A8A]'}`}>{label}{section===id&&<span className="absolute inset-x-4 bottom-0 h-0.5 rounded-full bg-violet-400"/>}</button>)}</div>
 {loading?<div className="min-h-44" role="status" aria-label="Loading hotel operation"/>:<>
 {section==="today"&&<><section className="border-b border-white/[.06] pb-4"><p className="text-[9px] font-bold uppercase tracking-[.16em] text-violet-300">TODAY</p><h3 className="mt-2 text-lg font-bold">What needs attention</h3><p className="mt-1 text-[10px] leading-5 text-[#747A8B]">Arrivals, current guests and departures stay on the same paid reservation. Open Reservations for guest action or Availability to update room sales.</p><div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setSection("reservations")} className="min-h-12 rounded-xl bg-violet-500 px-3 text-[10px] font-semibold">Open reservations</button>{accessRole!=="staff"&&<button type="button" onClick={()=>setSection("availability")} className="min-h-12 rounded-xl border border-white/[.08] px-3 text-[10px] font-semibold text-[#B9BECA]">Update availability</button>}</div></section><section className="grid grid-cols-2 gap-px overflow-hidden border-y border-white/[.06] bg-white/[.06] sm:grid-cols-5">{metricRows.map(([label,value])=><div key={label} className="bg-[#0A0A0F] p-4"><p className="text-xl font-bold">{value}</p><p className="mt-1 text-[8px] text-[#72798A]">{label}</p></div>)}</section><Today rooms={rooms} bookings={bookings} inventory={inventory}/></>}
 {section==="availability"&&<section><div className="mb-4"><h3 className="text-sm font-semibold">Room availability</h3><p className="mt-1 text-[9px] leading-5 text-[#707687]">Choose a date range, how many rooms can be sold and whether sales are closed.</p></div><div className="divide-y divide-white/[.07] border-y border-white/[.07]">{rooms.map(room=><AvailabilityRow key={room.room_id} room={room} inventory={inventory.find(row=>row.room_id===room.room_id)} onSaved={load}/>)}{rooms.length===0&&<Empty text="No room types have been prepared for this hotel."/></div></section>}
 {section==="rooms"&&<section><div className="mb-4"><h3 className="text-sm font-semibold">Room types</h3><p className="mt-1 text-[9px] leading-5 text-[#707687]">Manage the gallery, guest capacity, units and nightly price for each room type.</p></div><div className="divide-y divide-white/[.07] border-y border-white/[.07]">{rooms.map(room=><RoomRow key={room.room_id} room={room} onEdit={()=>setEditing(room)}/>)}{rooms.length===0&&<Empty text="No room types have been prepared for this hotel."/></div></section>}
 {section==="reservations"&&<section><div className="mb-4"><h3 className="text-sm font-semibold">Reservations</h3><p className="mt-1 text-[9px] leading-5 text-[#707687]">Search the guest or booking code. Status stays on each reservation; it does not become navigation.</p></div><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><input value={reservationQuery} onChange={event=>setReservationQuery(event.target.value)} placeholder="Search guest or booking code" className="h-11 rounded-xl border border-white/[.08] bg-[#171B24] px-3 text-xs outline-none focus:border-violet-500/35"/><WeHouseSelect value={reservationFilter} options={[{value:"all",label:"All reservations"},{value:"pending",label:"Awaiting payment"},{value:"confirmed",label:"Stay confirmed"},{value:"checked_in",label:"Checked in"},{value:"completed",label:"Completed"},{value:"cancelled",label:"Cancelled"}]} onChange={setReservationFilter} eyebrow="Reservations" title="Filter reservations" ariaLabel="Filter hotel reservations"/></div><div className="mt-4 divide-y divide-white/[.06] border-y border-white/[.06]">{filteredBookings.map(row=><ReservationRow key={row.booking_id} row={row} busy={busy} chat={hotelChats.find(item=>Number(item.booking_id)===Number(row.booking_id))} onChat={setActiveChat} onWeHouse={accessRole==="owner"?()=>messageWeHouse(row):undefined} transition={transition}/>)}{filteredBookings.length===0&&<Empty text={bookings.length?"No reservations match this filter.":"No hotel reservations yet."}/>}</div></section>}
 {section==="team"&&accessRole==="owner"&&<HotelTeam hotelId={hotel.hotel_id}/>}
 </>}
 {editing&&<RoomEditor room={editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load()}}/>}
 {activeChat&&profile&&<HotelBookingChat bookingId={activeChat.booking_id} conversationId={activeChat.conversation_id} profile={profile} title={activeChat.guest_name||"Guest"} subtitle={`${hotel.name} · ${activeChat.booking_code||"Paid stay"}`} onClose={()=>setActiveChat(null)} onUpdated={()=>void load()}/>}
 </div>
}

function Today({rooms,bookings,inventory}:{rooms:Room[];bookings:Booking[];inventory:Inventory[]}){const date=today();return <div className="space-y-5"><section><h3 className="text-sm font-semibold">Today’s rooms</h3><div className="mt-2 divide-y divide-white/[.06] border-y border-white/[.06]">{rooms.map(room=>{const override=inventory.find(row=>row.room_id===room.room_id);const used=bookings.filter(row=>row.room_id===room.room_id&&["confirmed","checked_in"].includes(row.status)&&row.check_in<=date&&row.check_out>date).length;const capacity=override?.closed?0:override?.available_quantity??room.total_rooms;return <div key={room.room_id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-xs font-semibold">{room.room_type}</p><p className="mt-1 text-[9px] text-[#686F80]">{used} occupied/reserved · {room.total_rooms} total</p></div><div className="text-right"><p className="text-sm font-bold">{Math.max(0,capacity-used)} available</p>{override?.closed&&<p className="text-[8px] text-amber-300">Closed today</p>}</div></div>})}</div></section><section><h3 className="text-sm font-semibold">Today’s guest movement</h3><div className="mt-2 divide-y divide-white/[.06] border-y border-white/[.06]">{bookings.filter(row=>row.check_in===date||row.check_out===date||row.status==="checked_in").slice(0,8).map(row=><div key={row.booking_id} className="py-3"><div className="flex justify-between gap-3"><p className="text-xs font-semibold">{row.guest_name||row.profiles?.username||"Guest"}</p><Status value={row.status}/></div><p className="mt-1 text-[9px] text-[#6C7282]">{row.hotel_rooms?.room_type||"Room"} · {row.booking_code}</p></div>)}{!bookings.some(row=>row.check_in===date||row.check_out===date||row.status==="checked_in")&&<Empty text="No arrivals, current stays or departures today."/>}</div></section></div>}

function RoomRow({room,onEdit}:{room:Room;onEdit:()=>void}){return <article className="py-5"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-semibold">{room.room_type}</p><p className="mt-1 text-[10px] text-[#777D8D]">{money(room.price_per_night)} / night</p></div><button onClick={onEdit} className="rounded-full border border-violet-500/20 px-3 py-2 text-[9px] font-semibold text-violet-300">Edit room</button></div>{room.images?.length>0?<div className="-mx-4 mt-4 sm:mx-0"><PropertyMediaCarousel images={room.images} title={room.room_type}/></div>:<div className="mt-4 grid aspect-[16/9] place-items-center rounded-2xl bg-white/[.025] text-[9px] text-[#666D7E]">No room gallery</div>}<div className="mt-4 grid grid-cols-3 divide-x divide-white/[.06] border-y border-white/[.06] py-3 text-center"><RoomFact label="Units" value={room.total_rooms}/><RoomFact label="Guests" value={room.max_guests}/><RoomFact label="Bed" value={room.bed_type||"—"}/></div>{room.description&&<p className="mt-4 text-[10px] leading-5 text-[#8C92A1]">{room.description}</p>}{room.amenities?.length?<div className="mt-3 flex flex-wrap gap-2">{room.amenities.map(item=><span key={item} className="rounded-full border border-white/[.07] px-2.5 py-1 text-[8px] text-[#A0A5B3]">{item}</span>)}</div>:null}</article>}

function AvailabilityRow({room,inventory,onSaved}:{room:Room;inventory?:Inventory;onSaved:()=>Promise<void>}){const[start,setStart]=useState(today()),[end,setEnd]=useState(today()),[quantity,setQuantity]=useState(String(inventory?.available_quantity??room.total_rooms)),[closed,setClosed]=useState(Boolean(inventory?.closed)),[saving,setSaving]=useState(false);useEffect(()=>{setQuantity(String(inventory?.available_quantity??room.total_rooms));setClosed(Boolean(inventory?.closed))},[room.total_rooms,inventory?.available_quantity,inventory?.closed]);async function save(){const available=Number(quantity);if(!Number.isInteger(available)||available<0||available>room.total_rooms)return toast.error(`Available rooms must be between 0 and ${room.total_rooms}`);if(!start||!end||end<start)return toast.error("Choose a valid date range");setSaving(true);const{error}=await supabase.rpc("partner_set_hotel_inventory_range",{p_room_id:room.room_id,p_start_date:start,p_end_date:end,p_available_quantity:available,p_closed:closed,p_rate_override:null,p_note:null});setSaving(false);if(error)return toast.error(error.message);toast.success("Availability updated");await onSaved()}return <article className="py-5"><div><p className="text-sm font-semibold">{room.room_type}</p><p className="mt-1 text-[9px] text-[#707687]">{room.total_rooms} rooms total · {inventory?.closed?"Sales closed today":`${inventory?.available_quantity??room.total_rooms} available today`}</p></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Field label="From" value={start} set={setStart} type="date"/><Field label="To" value={end} set={setEnd} type="date"/><Field label="Rooms available" value={quantity} set={setQuantity} type="number"/><label className="flex min-h-11 items-center gap-2 rounded-xl border border-white/[.07] px-3 text-[9px]"><input type="checkbox" checked={closed} onChange={e=>setClosed(e.target.checked)} className="accent-violet-500"/>Close room sales</label></div><button onClick={()=>void save()} disabled={saving} className="mt-2 min-h-11 w-full rounded-xl border border-violet-500/20 text-[10px] font-semibold text-violet-300 disabled:opacity-40">{saving?"Updating…":"Save availability"}</button></article>}

function RoomEditor({room,close,saved}:{room:Room;close:()=>void;saved:()=>Promise<void>}){const[form,setForm]=useState({name:room.room_type,description:room.description||"",price:String(room.price_per_night),guests:String(room.max_guests),bed:room.bed_type||"",quantity:String(room.total_rooms)}),[busy,setBusy]=useState(false);async function save(){setBusy(true);const{error}=await supabase.rpc("partner_update_hotel_room",{p_room_id:room.room_id,p_room_type:form.name,p_description:form.description||null,p_price_per_night:Number(form.price),p_max_guests:Number(form.guests),p_bed_type:form.bed||null,p_total_rooms:Number(form.quantity),p_amenities:room.amenities,p_images:room.images});setBusy(false);if(error)return toast.error(error.message);toast.success("Room type updated");await saved()}return <div className="fixed inset-0 z-[100030] flex items-end bg-black/75" onClick={close}><section className="max-h-[90dvh] w-full overflow-y-auto rounded-t-[28px] bg-[#11151D] p-5 pb-[max(1.5rem,env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><div className="mx-auto max-w-2xl"><div className="flex justify-between"><div><h3 className="text-base font-bold">Edit room type</h3><p className="mt-1 text-[9px] text-[#707687]">Update the room information guests use to choose and book.</p></div><button onClick={close} className="h-10 w-10">×</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Room type" value={form.name} set={value=>setForm({...form,name:value})}/><Field label="Nightly rate" value={form.price} set={value=>setForm({...form,price:value})} type="number"/><Field label="Guest capacity" value={form.guests} set={value=>setForm({...form,guests:value})} type="number"/><Field label="Total units" value={form.quantity} set={value=>setForm({...form,quantity:value})} type="number"/><Field label="Bed configuration" value={form.bed} set={value=>setForm({...form,bed:value})}/><label className="sm:col-span-2"><span className="mb-1 block text-[8px] text-[#686E7E]">Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} className="w-full rounded-xl border border-white/[.08] bg-[#171B24] p-3 text-xs outline-none"/></label></div><button onClick={()=>void save()} disabled={busy} className="mt-4 h-12 w-full rounded-xl bg-violet-500 text-xs font-semibold disabled:opacity-40">{busy?"Saving…":"Save room type"}</button></div></section></div>}

function ReservationRow({row,busy,chat,onChat,onWeHouse,transition}:{row:Booking;busy:boolean;chat?:HotelConversation;onChat:(chat:ActiveHotelChat)=>void;onWeHouse?:()=>void;transition:(row:Booking,status:"checked_in"|"checked_out")=>Promise<void>}){const next=row.status==="pending"?"Waiting for secure payment":row.status==="confirmed"?"Ready for front-desk check-in":row.status==="checked_in"?"Guest is staying · complete after checkout":row.status==="completed"||row.status==="checked_out"?"Stay finished · guest can leave a verified review":"No action required";const code=row.booking_code||"Code appears after verified payment";const guestChatAllowed=row.payment_status==="paid"&&["confirmed","checked_in","checked_out","completed"].includes(row.status);return <article className="py-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{row.guest_name||row.profiles?.username||"Guest"}</p><p className="mt-1 text-[9px] text-[#6C7282]">{row.hotel_rooms?.room_type||"Room"} · {code} · {row.guest_count} guest(s)</p><p className="mt-1 text-[9px] text-[#6C7282]">{new Date(row.check_in).toLocaleDateString()} → {new Date(row.check_out).toLocaleDateString()}</p></div><div className="text-right"><Status value={row.status}/><p className="mt-2 text-xs font-bold">{money(row.total_price)}</p></div></div><p className="mt-3 text-[9px] text-[#858B9A]">{next}</p>{row.special_requests&&<p className="mt-3 rounded-xl bg-white/[.025] p-3 text-[9px] text-[#858B9A]">{row.special_requests}</p>}<div className="mt-3 flex flex-wrap gap-2">{guestChatAllowed&&<button onClick={()=>onChat(chat||{booking_id:row.booking_id,guest_name:row.guest_name||row.profiles?.username||"Guest",booking_code:row.booking_code})} className="h-10 flex-1 rounded-xl border border-violet-500/20 bg-violet-500/[.07] px-3 text-[10px] font-semibold text-violet-200">{chat?`Guest messages${chat.unread_count>0?` · ${chat.unread_count} new`:""}`:"Message guest"}</button>}{onWeHouse?<button type="button" onClick={onWeHouse} className="h-10 flex-1 rounded-xl border border-white/[.08] px-3 text-[10px] font-semibold text-[#AEB4C1]">Message WeHouse</button>:null}{row.status==="confirmed"&&row.booking_code&&<button disabled={busy} onClick={()=>void transition(row,"checked_in")} className="h-10 flex-1 rounded-xl bg-violet-500 text-[10px] font-semibold disabled:opacity-40">Check in guest</button>}{row.status==="checked_in"&&<button disabled={busy} onClick={()=>void transition(row,"checked_out")} className="h-10 flex-1 rounded-xl bg-violet-500 text-[10px] font-semibold disabled:opacity-40">Complete checkout</button>}</div></article>}
function RoomFact({label,value}:{label:string;value:string|number}){return <div className="px-2"><p className="text-sm font-bold">{value}</p><p className="mt-1 text-[8px] text-[#666D7E]">{label}</p></div>}
type HotelTeamRow={id:string;member_user_id:string;hotel_role:"manager"|"staff";status:"invited"|"active";name:string;username?:string|null};
function HotelTeam({hotelId}:{hotelId:number}){
 const[rows,setRows]=useState<HotelTeamRow[]>([]),[identifier,setIdentifier]=useState(""),[role,setRole]=useState<"manager"|"staff">("staff"),[saving,setSaving]=useState(false),[removing,setRemoving]=useState<string|null>(null);
 const load=useCallback(async()=>{const{data,error}=await supabase.rpc("get_my_hotel_team",{p_hotel_id:hotelId});if(error)return toast.error(error.message);setRows(Array.isArray(data)?data:[])},[hotelId]);
 useEffect(()=>{void load()},[load]);
 async function invite(){if(!identifier.trim())return toast.error("Enter a WeHouse username or user ID");setSaving(true);const{error}=await supabase.rpc("owner_invite_hotel_team_member",{p_hotel_id:hotelId,p_identifier:identifier.trim(),p_role:role});setSaving(false);if(error)return toast.error(error.message);setIdentifier("");toast.success("Invitation sent. Access starts only after acceptance.");await load()}
 async function remove(row:HotelTeamRow){setRemoving(row.id);const{error}=await supabase.rpc("owner_revoke_hotel_team_member",{p_membership_id:row.id});setRemoving(null);if(error)return toast.error(error.message);toast.success(row.status==="invited"?"Invitation cancelled":"Hotel access removed");await load()}
 return <div className="space-y-5"><section className="rounded-2xl border border-white/[.06] bg-[#11141C] p-4"><h3 className="text-sm font-semibold">Invite a team member</h3><p className="mt-1 text-[9px] leading-relaxed text-[#6D7485]">Use their exact WeHouse username or user ID. They must accept before any hotel access is granted.</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_150px_auto]"><input value={identifier} onChange={event=>setIdentifier(event.target.value)} placeholder="@username or WH user ID" autoCapitalize="none" autoCorrect="off" className="h-11 rounded-xl border border-white/[.08] bg-[#171B24] px-3 text-xs outline-none focus:border-violet-500/35"/><select value={role} onChange={event=>setRole(event.target.value as "manager"|"staff")} className="h-11 rounded-xl border border-white/[.08] bg-[#171B24] px-3 text-xs"><option value="manager">Manager</option><option value="staff">Front desk</option></select><button disabled={saving} onClick={()=>void invite()} className="h-11 rounded-xl bg-violet-500 px-5 text-xs font-semibold disabled:opacity-40">{saving?"Sending…":"Send invite"}</button></div><div className="mt-3 grid grid-cols-2 gap-2 text-[8px] leading-4 text-[#73798A]"><p className="rounded-xl bg-white/[.025] p-2.5"><strong className="block text-[#B7BCC8]">Manager</strong>Rooms and availability only</p><p className="rounded-xl bg-white/[.025] p-2.5"><strong className="block text-[#B7BCC8]">Front desk</strong>Arrivals and guest support only</p></div></section><section><h3 className="mb-2 text-sm font-semibold">Hotel team</h3>{rows.length===0?<Empty text="No pending invitations or active team members."/>:<div className="divide-y divide-white/[.06] border-y border-white/[.06]">{rows.map(row=><div key={row.id} className="flex items-center gap-3 py-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-violet-500/10 text-xs font-bold text-violet-200">{(row.name||row.username||"W").slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{row.name}</p><p className="mt-1 truncate text-[9px] text-[#687080]">{row.username?`@${row.username}`:row.member_user_id}</p></div><div className="text-right"><span className={`rounded-full px-2 py-1 text-[8px] font-semibold ${row.status==="active"?"bg-emerald-500/10 text-emerald-300":"bg-amber-500/10 text-amber-200"}`}>{row.status==="active"?(row.hotel_role==="manager"?"Manager":"Front desk"):"Awaiting acceptance"}</span><button disabled={removing===row.id} onClick={()=>void remove(row)} className="mt-2 block w-full text-[8px] font-semibold text-red-300 disabled:opacity-40">{removing===row.id?"Updating…":row.status==="invited"?"Cancel":"Remove"}</button></div></div>)}</div>}</section></div>
}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(value:string)=>void;type?:string}){return <label><span className="mb-1 block text-[8px] text-[#686E7E]">{label}</span><input type={type} min={type==="date"?today():undefined} value={value} onChange={e=>set(e.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#171B24] px-3 text-xs outline-none"/></label>}
function Status({value}:{value:string}){return <span className="inline-flex rounded-full bg-violet-500/10 px-2 py-1 text-[8px] font-semibold text-violet-300">{HOTEL_STATUS[String(value)]||"Status unavailable"}</span>}
function Empty({text}:{text:string}){return <p className="py-10 text-center text-[10px] text-[#686F80]">{text}</p>}
