import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";

type Props={hotel:any;onBack:()=>void};
type Room={room_id:number;hotel_id:number;room_type:string;description:string|null;price_per_night:number;max_guests:number;bed_type:string|null;images:string[];amenities:string[];total_rooms:number};
type Booking={booking_id:number;room_id:number;check_in:string;check_out:string;guest_count:number;guest_name:string|null;booking_code:string;status:string;payment_status:string;total_price:number;special_requests:string|null;profiles?:{username?:string|null}|null;hotel_rooms?:{room_type?:string|null}|null};
type Inventory={room_id:number;inventory_date:string;available_quantity:number;rate_override:number|null;closed:boolean};
const today=()=>new Date().toISOString().slice(0,10);
const money=(value:number)=>`₦${Number(value||0).toLocaleString("en-NG")}`;

export default function PartnerHotelOperations({hotel,onBack}:Props){
 const[rooms,setRooms]=useState<Room[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[loading,setLoading]=useState(true),[section,setSection]=useState<"today"|"rooms"|"reservations">("today"),[editing,setEditing]=useState<Room|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const date=today();const [roomResult,bookingResult,inventoryResult]=await Promise.all([
  supabase.from("hotel_rooms").select("*").eq("hotel_id",hotel.hotel_id).order("price_per_night"),
  supabase.from("hotel_bookings").select("booking_id,room_id,check_in,check_out,guest_count,guest_name,booking_code,status,payment_status,total_price,special_requests,profiles(username),hotel_rooms(room_type)").eq("hotel_id",hotel.hotel_id).gte("check_out",date).order("check_in"),
  supabase.from("hotel_inventory_daily").select("room_id,inventory_date,available_quantity,rate_override,closed").eq("hotel_id",hotel.hotel_id).gte("inventory_date",date).lte("inventory_date",date),
 ]);if(roomResult.error||bookingResult.error||inventoryResult.error)toast.error(roomResult.error?.message||bookingResult.error?.message||inventoryResult.error?.message||"Hotel operation could not be loaded");setRooms((roomResult.data||[]) as Room[]);setBookings((bookingResult.data||[]) as unknown as Booking[]);setInventory((inventoryResult.data||[]) as Inventory[]);setLoading(false)},[hotel.hotel_id]);
 useEffect(()=>{void load()},[load]);
 const date=today(),activeBookings=bookings.filter(row=>["pending","confirmed","checked_in"].includes(row.status));
 const metrics=useMemo(()=>({arrivals:bookings.filter(row=>row.check_in===date&&row.status==="confirmed").length,staying:bookings.filter(row=>row.status==="checked_in").length,departures:bookings.filter(row=>row.check_out===date&&row.status==="checked_in").length,attention:bookings.filter(row=>row.status==="payment_conflict"||(row.check_in<=date&&row.status==="confirmed")).length}),[bookings,date]);
 const available=rooms.reduce((sum,room)=>{const override=inventory.find(row=>row.room_id===room.room_id);const reserved=activeBookings.filter(row=>row.room_id===room.room_id&&row.check_in<=date&&row.check_out>date).length;return sum+Math.max(0,(override?.closed?0:override?.available_quantity??room.total_rooms)-reserved)},0);
 async function transition(booking:Booking,status:"checked_in"|"checked_out"){setBusy(true);const{error}=await supabase.rpc("partner_transition_hotel_booking",{p_booking_id:booking.booking_id,p_status:status});setBusy(false);if(error)return toast.error(error.message);toast.success(status==="checked_in"?"Guest checked in":"Stay checked out");await load()}
 return <div className="space-y-5"><header className="flex items-center gap-3 border-b border-white/[.07] pb-4"><button onClick={onBack} aria-label="Back to properties" className="grid h-11 w-11 place-items-center rounded-full text-xl text-[#A0A5B4]">‹</button><div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-violet-300">Hotel operation</p><h2 className="truncate text-lg font-bold">{hotel.name}</h2><p className="mt-0.5 truncate text-[9px] text-[#6F7586]">{[hotel.city,hotel.state].filter(Boolean).join(", ")} · {hotel.status==="active"?"Live":"Not public"}</p></div></header>
 {loading?<div className="min-h-44" role="status" aria-label="Loading hotel operation"/>:<>
 <section className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/[.06] bg-white/[.06] sm:grid-cols-5">{[["Available today",available],["Arriving",metrics.arrivals],["Staying",metrics.staying],["Leaving",metrics.departures],["Needs attention",metrics.attention]].map(([label,value])=><div key={String(label)} className="bg-[#11141C] p-4"><p className="text-xl font-bold">{value}</p><p className="mt-1 text-[8px] text-[#72798A]">{label}</p></div>)}</section>
 <div className="grid grid-cols-3 border-b border-white/[.07]" aria-label="Hotel workspace sections">{([['today','Today'],['rooms','Rooms & availability'],['reservations','Reservations']] as const).map(([id,label])=><button key={id} onClick={()=>setSection(id)} className={`relative min-h-12 px-1 text-[9px] font-semibold ${section===id?'text-violet-300':'text-[#747A8A]'}`}>{label}{section===id&&<span className="absolute inset-x-4 bottom-0 h-0.5 rounded-full bg-violet-400"/>}</button>)}</div>
 {section==="today"&&<Today rooms={rooms} bookings={bookings} inventory={inventory}/>} 
 {section==="rooms"&&<div className="space-y-3">{rooms.map(room=><RoomRow key={room.room_id} room={room} inventory={inventory.find(row=>row.room_id===room.room_id)} onEdit={()=>setEditing(room)} onSaved={load}/>)}{rooms.length===0&&<Empty text="No room types have been prepared for this hotel."/>}</div>}
 {section==="reservations"&&<div className="divide-y divide-white/[.06] border-y border-white/[.06]">{bookings.map(row=><ReservationRow key={row.booking_id} row={row} busy={busy} transition={transition}/>)}{bookings.length===0&&<Empty text="No upcoming or current reservations."/>}</div>}
 </>}
 {editing&&<RoomEditor room={editing} close={()=>setEditing(null)} saved={async()=>{setEditing(null);await load()}}/>}
 </div>
}

function Today({rooms,bookings,inventory}:{rooms:Room[];bookings:Booking[];inventory:Inventory[]}){const date=today();return <div className="space-y-5"><section><h3 className="text-sm font-semibold">Today’s rooms</h3><div className="mt-2 divide-y divide-white/[.06] border-y border-white/[.06]">{rooms.map(room=>{const override=inventory.find(row=>row.room_id===room.room_id);const used=bookings.filter(row=>row.room_id===room.room_id&&["confirmed","checked_in"].includes(row.status)&&row.check_in<=date&&row.check_out>date).length;const capacity=override?.closed?0:override?.available_quantity??room.total_rooms;return <div key={room.room_id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-xs font-semibold">{room.room_type}</p><p className="mt-1 text-[9px] text-[#686F80]">{used} occupied/reserved · {room.total_rooms} total</p></div><div className="text-right"><p className="text-sm font-bold">{Math.max(0,capacity-used)} available</p>{override?.closed&&<p className="text-[8px] text-amber-300">Closed today</p>}</div></div>})}</div></section><section><h3 className="text-sm font-semibold">Today’s guest movement</h3><div className="mt-2 divide-y divide-white/[.06] border-y border-white/[.06]">{bookings.filter(row=>row.check_in===date||row.check_out===date||row.status==="checked_in").slice(0,8).map(row=><div key={row.booking_id} className="py-3"><div className="flex justify-between gap-3"><p className="text-xs font-semibold">{row.guest_name||row.profiles?.username||"Guest"}</p><Status value={row.status}/></div><p className="mt-1 text-[9px] text-[#6C7282]">{row.hotel_rooms?.room_type||"Room"} · {row.booking_code}</p></div>)}{!bookings.some(row=>row.check_in===date||row.check_out===date||row.status==="checked_in")&&<Empty text="No arrivals, current stays or departures today."/>}</div></section></div>}

function RoomRow({room,inventory,onEdit,onSaved}:{room:Room;inventory?:Inventory;onEdit:()=>void;onSaved:()=>Promise<void>}){const[start,setStart]=useState(today()),[end,setEnd]=useState(today()),[quantity,setQuantity]=useState(String(room.total_rooms)),[closed,setClosed]=useState(false),[saving,setSaving]=useState(false);async function save(){setSaving(true);const{error}=await supabase.rpc("partner_set_hotel_inventory_range",{p_room_id:room.room_id,p_start_date:start,p_end_date:end,p_available_quantity:Number(quantity),p_closed:closed,p_rate_override:null,p_note:null});setSaving(false);if(error)return toast.error(error.message);toast.success("Availability updated");await onSaved()}return <article className="rounded-2xl border border-white/[.06] bg-[#11141C] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{room.room_type}</p><p className="mt-1 text-[9px] text-[#707687]">{room.total_rooms} units · up to {room.max_guests} guests · {money(room.price_per_night)}/night</p></div><button onClick={onEdit} className="text-[9px] font-semibold text-violet-300">Edit room</button></div>{room.images?.length>0&&<div className="mt-3 grid grid-cols-4 gap-1">{room.images.slice(0,4).map((src,index)=><img key={`${src}-${index}`} src={src} alt="" className="aspect-[3/4] w-full rounded-lg object-cover"/>)}</div>}<div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Field label="From" value={start} set={setStart} type="date"/><Field label="To" value={end} set={setEnd} type="date"/><Field label="Available units" value={quantity} set={setQuantity} type="number"/><label className="flex min-h-11 items-center gap-2 rounded-xl border border-white/[.07] px-3 text-[9px]"><input type="checkbox" checked={closed} onChange={e=>setClosed(e.target.checked)} className="accent-violet-500"/>Close inventory</label></div><button onClick={()=>void save()} disabled={saving} className="mt-2 min-h-10 w-full rounded-xl border border-violet-500/20 text-[10px] font-semibold text-violet-300 disabled:opacity-40">{saving?"Updating…":inventory?.closed?"Update closure":"Update date range"}</button></article>}

function RoomEditor({room,close,saved}:{room:Room;close:()=>void;saved:()=>Promise<void>}){const[form,setForm]=useState({name:room.room_type,description:room.description||"",price:String(room.price_per_night),guests:String(room.max_guests),bed:room.bed_type||"",quantity:String(room.total_rooms)}),[busy,setBusy]=useState(false);async function save(){setBusy(true);const{error}=await supabase.rpc("partner_update_hotel_room",{p_room_id:room.room_id,p_room_type:form.name,p_description:form.description||null,p_price_per_night:Number(form.price),p_max_guests:Number(form.guests),p_bed_type:form.bed||null,p_total_rooms:Number(form.quantity),p_amenities:room.amenities,p_images:room.images});setBusy(false);if(error)return toast.error(error.message);toast.success("Room type updated");await saved()}return <div className="fixed inset-0 z-[100030] flex items-end bg-black/75" onClick={close}><section className="max-h-[90dvh] w-full overflow-y-auto rounded-t-[28px] bg-[#11151D] p-5 pb-[max(1.5rem,env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><div className="mx-auto max-w-2xl"><div className="flex justify-between"><div><h3 className="text-base font-bold">Edit room type</h3><p className="mt-1 text-[9px] text-[#707687]">Update the shared details for this inventory type.</p></div><button onClick={close} className="h-10 w-10">×</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Room type" value={form.name} set={value=>setForm({...form,name:value})}/><Field label="Nightly rate" value={form.price} set={value=>setForm({...form,price:value})} type="number"/><Field label="Guest capacity" value={form.guests} set={value=>setForm({...form,guests:value})} type="number"/><Field label="Total units" value={form.quantity} set={value=>setForm({...form,quantity:value})} type="number"/><Field label="Bed configuration" value={form.bed} set={value=>setForm({...form,bed:value})}/><label className="sm:col-span-2"><span className="mb-1 block text-[8px] text-[#686E7E]">Description</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} className="w-full rounded-xl border border-white/[.08] bg-[#171B24] p-3 text-xs outline-none"/></label></div><button onClick={()=>void save()} disabled={busy} className="mt-4 h-12 w-full rounded-xl bg-violet-500 text-xs font-semibold disabled:opacity-40">{busy?"Saving…":"Save room type"}</button></div></section></div>}

function ReservationRow({row,busy,transition}:{row:Booking;busy:boolean;transition:(row:Booking,status:"checked_in"|"checked_out")=>Promise<void>}){return <article className="py-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{row.guest_name||row.profiles?.username||"Guest"}</p><p className="mt-1 text-[9px] text-[#6C7282]">{row.hotel_rooms?.room_type||"Room"} · {row.booking_code} · {row.guest_count} guest(s)</p><p className="mt-1 text-[9px] text-[#6C7282]">{new Date(row.check_in).toLocaleDateString()} → {new Date(row.check_out).toLocaleDateString()}</p></div><div className="text-right"><Status value={row.status}/><p className="mt-2 text-xs font-bold">{money(row.total_price)}</p></div></div>{row.special_requests&&<p className="mt-3 rounded-xl bg-white/[.025] p-3 text-[9px] text-[#858B9A]">{row.special_requests}</p>}<div className="mt-3 flex gap-2">{row.status==="confirmed"&&<button disabled={busy} onClick={()=>void transition(row,"checked_in")} className="h-10 flex-1 rounded-xl bg-violet-500 text-[10px] font-semibold disabled:opacity-40">Check in</button>}{row.status==="checked_in"&&<button disabled={busy} onClick={()=>void transition(row,"checked_out")} className="h-10 flex-1 rounded-xl bg-violet-500 text-[10px] font-semibold disabled:opacity-40">Check out</button>}</div></article>}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(value:string)=>void;type?:string}){return <label><span className="mb-1 block text-[8px] text-[#686E7E]">{label}</span><input type={type} min={type==="date"?today():undefined} value={value} onChange={e=>set(e.target.value)} className="h-11 w-full rounded-xl border border-white/[.08] bg-[#171B24] px-3 text-xs outline-none"/></label>}
function Status({value}:{value:string}){return <span className="inline-flex rounded-full bg-violet-500/10 px-2 py-1 text-[8px] font-semibold capitalize text-violet-300">{String(value).replace(/_/g," ")}</span>}
function Empty({text}:{text:string}){return <p className="py-10 text-center text-[10px] text-[#686F80]">{text}</p>}
