import { useEffect,useMemo,useState } from 'react';
import { toast } from 'sonner';
import SearchableSelect from '@/components/SearchableSelect';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';

type Bank={code:string;name:string};
type Saved={id:string;bank_name:string;bank_code:string|null;account_number:string;account_name:string;verified_at:string|null;is_default:boolean};
type Resolved={bank:{code:string;name:string};account_number:string;account_name:string;first_account:boolean;additional_account:boolean;additional_allowed:boolean;matched_names:number;needs_full_name:boolean};

export default function PayoutAccountManager({profile,onChanged}:{profile:Profile;onChanged?:()=>void}){
 const[accounts,setAccounts]=useState<Saved[]>([]),[adding,setAdding]=useState(false),[banks,setBanks]=useState<Bank[]>([]),[bankCode,setBankCode]=useState(''),[number,setNumber]=useState(''),[resolved,setResolved]=useState<Resolved|null>(null),[loading,setLoading]=useState(true),[loadingBanks,setLoadingBanks]=useState(false),[verifying,setVerifying]=useState(false),[saving,setSaving]=useState(false);
 const options=useMemo(()=>banks.map(bank=>({value:bank.code,label:bank.name})),[banks]);
 const firstAccount=accounts.length===0;
 async function loadAccounts(){setLoading(true);const{data,error}=await supabase.from('bank_accounts').select('id,bank_name,bank_code,account_number,account_name,verified_at,is_default').eq('user_id',profile.user_id).order('is_default',{ascending:false}).order('created_at',{ascending:true});if(error)toast.error('Unable to load payout accounts');setAccounts((data||[]) as Saved[]);setLoading(false)}
 useEffect(()=>{void loadAccounts()},[profile.user_id]);
 async function loadBanks(){if(banks.length)return;setLoadingBanks(true);const{data,error}=await supabase.functions.invoke('payout-account',{body:{action:'banks'}});setLoadingBanks(false);if(error||!data?.success)return toast.error(data?.error||error?.message||'Unable to load banks');setBanks(data.banks||[])}
 function begin(){setAdding(true);setBankCode('');setNumber('');setResolved(null);void loadBanks()}
 function cancel(){setAdding(false);setResolved(null);setBankCode('');setNumber('')}
 async function verify(){if(!bankCode)return toast.error('Choose a bank');if(!/^\d{10}$/.test(number))return toast.error('Enter a valid 10-digit account number');setVerifying(true);const{data,error}=await supabase.functions.invoke('payout-account',{body:{action:'resolve',bank_code:bankCode,account_number:number}});setVerifying(false);if(error||!data?.success){setResolved(null);return toast.error(data?.error||error?.message||'Unable to verify account')}setResolved(data as Resolved)}
 async function save(){if(!resolved||!resolved.additional_allowed)return;setSaving(true);const{data,error}=await supabase.functions.invoke('payout-account',{body:{action:'save',bank_code:resolved.bank.code,account_number:resolved.account_number}});setSaving(false);if(error||!data?.success)return toast.error(data?.error||error?.message||'Unable to save payout account');toast.success('Payout account added');cancel();await loadAccounts();onChanged?.()}
 if(loading)return <section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><div className="h-16 animate-pulse rounded-xl bg-white/[.03]"/></section>;
 return <section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold">Payout accounts</p><p className="mt-1 text-[9px] leading-relaxed text-[#676A7B]">Choose any saved verified account when you withdraw.</p></div>{!adding&&<button onClick={begin} className="shrink-0 rounded-xl border border-violet-500/20 bg-violet-500/[.07] px-3 py-2 text-[9px] font-semibold text-violet-300">Add account</button>}</div>
 {!adding&&accounts.length===0&&<div className="mt-4 rounded-xl border border-dashed border-white/[.08] p-4 text-[10px] leading-relaxed text-[#6C6F80]">No payout account connected. Your first account can be any valid account that Paystack can verify.</div>}
 {!adding&&accounts.length>0&&<div className="mt-4 space-y-2">{accounts.map(account=><div key={account.id} className="flex items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.025] p-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-500/10 text-[10px] font-bold text-violet-200">{account.bank_name.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{account.bank_name}</p><p className="mt-1 truncate text-[9px] text-[#6D7081]">•••• {account.account_number.slice(-4)} · {account.account_name}</p></div><div className="flex shrink-0 items-center gap-1">{account.is_default&&<span className="rounded-full bg-violet-500/10 px-2 py-1 text-[8px] text-violet-300">First</span>}<span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[8px] text-emerald-300">Verified</span></div></div>)}</div>}
 {adding&&<div className="mt-4 space-y-3"><div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3 text-[9px] leading-relaxed text-[#777B8C]">{firstAccount?'Your first payout account has no profile-name restriction. WeHouse still verifies the account directly with Paystack.':'You can keep every account already saved. To add another one, at least two names on the bank account must match your saved WeHouse full name.'}</div><SearchableSelect label="Bank" value={bankCode} onChange={value=>{setBankCode(value);setResolved(null)}} options={options} placeholder={loadingBanks?'Loading banks…':'Choose bank'} searchPlaceholder="Search bank" disabled={loadingBanks}/><label className="block"><span className="mb-1.5 block text-[10px] font-medium text-[#7B8190]">Account number</span><input inputMode="numeric" maxLength={10} value={number} onChange={event=>{setNumber(event.target.value.replace(/\D/g,'').slice(0,10));setResolved(null)}} placeholder="10-digit account number" className="h-11 w-full rounded-xl border border-white/[.08] bg-[#181B24] px-3 text-xs outline-none focus:border-violet-500/45"/></label><button onClick={()=>void verify()} disabled={verifying||!bankCode||number.length!==10} className="h-11 w-full rounded-xl border border-violet-500/20 bg-violet-500/[.08] text-[10px] font-semibold text-violet-200 disabled:opacity-40">{verifying?'Checking account…':'Verify account'}</button>
 {resolved&&<div className={`rounded-xl border p-3 ${resolved.additional_allowed?'border-emerald-500/20 bg-emerald-500/[.05]':'border-red-500/20 bg-red-500/[.05]'}`}><p className="text-[9px] uppercase tracking-wide text-[#777B8C]">Bank verified name</p><p className="mt-1 text-sm font-semibold">{resolved.account_name}</p>{!resolved.additional_allowed&&<p className="mt-2 text-[9px] leading-relaxed text-red-300">{resolved.needs_full_name?'Complete your full name in Personal Details before adding another account.':'This additional account does not match at least two names from your saved WeHouse full name.'}</p>}</div>}
 <div className="grid grid-cols-2 gap-2"><button onClick={cancel} className="h-11 rounded-xl border border-white/[.08] text-[10px] font-semibold text-[#9093A3]">Cancel</button><button onClick={()=>void save()} disabled={saving||!resolved||!resolved.additional_allowed} className="h-11 rounded-xl bg-violet-500 text-[10px] font-semibold disabled:opacity-40">{saving?'Saving…':'Add account'}</button></div></div>}
 </section>
}
