import { useEffect,useMemo,useState } from 'react';
import { toast } from 'sonner';
import SearchableSelect from '@/components/SearchableSelect';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';

type Bank={name:string;code:string};
type Account={id:string;bank_name:string;bank_code:string;account_number:string;account_name:string;verified_at:string|null};
type Resolution={bank_name:string;bank_code:string;account_number:string;account_name:string;replacement:boolean;replacement_allowed:boolean;name_match_count:number};

type Props={profile:Profile;onChanged?:()=>void;compact?:boolean};

export default function PayoutBankAccount({profile,onChanged,compact=false}:Props){
 const[current,setCurrent]=useState<Account|null>(null),[banks,setBanks]=useState<Bank[]>([]),[editing,setEditing]=useState(false),[bankCode,setBankCode]=useState(''),[number,setNumber]=useState(''),[resolution,setResolution]=useState<Resolution|null>(null),[loading,setLoading]=useState(true),[loadingBanks,setLoadingBanks]=useState(false),[resolving,setResolving]=useState(false),[saving,setSaving]=useState(false);
 const options=useMemo(()=>banks.map(bank=>({value:bank.code,label:bank.name})),[banks]);
 async function load(){setLoading(true);const{data,error}=await supabase.from('bank_accounts').select('id,bank_name,bank_code,account_number,account_name,verified_at').eq('user_id',profile.user_id).maybeSingle();if(error)toast.error('Unable to load payout account');setCurrent((data||null) as Account|null);setLoading(false)}
 useEffect(()=>{void load()},[profile.user_id]);
 async function loadBanks(){if(banks.length)return;setLoadingBanks(true);const{data,error}=await supabase.functions.invoke('payout-bank-account',{body:{action:'banks'}});setLoadingBanks(false);if(error||!data?.success)return toast.error(data?.error||error?.message||'Unable to load banks');setBanks(Array.isArray(data.banks)?data.banks:[])}
 function begin(){setEditing(true);setBankCode('');setNumber('');setResolution(null);void loadBanks()}
 function cancel(){setEditing(false);setBankCode('');setNumber('');setResolution(null)}
 async function resolve(){if(!bankCode)return toast.error('Choose your bank');if(!/^\d{10}$/.test(number))return toast.error('Enter a 10-digit account number');setResolving(true);const{data,error}=await supabase.functions.invoke('payout-bank-account',{body:{action:'resolve',bank_code:bankCode,account_number:number}});setResolving(false);if(error||!data?.success){setResolution(null);return toast.error(data?.error||error?.message||'Account could not be verified')}setResolution(data as Resolution)}
 async function save(){if(!resolution||!resolution.replacement_allowed)return;setSaving(true);const{data,error}=await supabase.functions.invoke('payout-bank-account',{body:{action:'save',bank_code:resolution.bank_code,account_number:resolution.account_number}});setSaving(false);if(error||!data?.success)return toast.error(data?.error||error?.message||'Payout account could not be saved');toast.success(current?'Payout account changed':'Payout account connected');cancel();await load();onChanged?.()}
 if(loading)return <div className="h-24 animate-pulse rounded-2xl border border-white/[.06] bg-white/[.025]"/>;
 if(editing)return <section className={`rounded-2xl border border-violet-500/15 bg-[#11141C] ${compact?'p-4':'p-5'} text-white`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{current?'Change payout account':'Add payout account'}</p><p className="mt-1 text-[10px] leading-relaxed text-[#747A8B]">Account holder name is verified automatically with the selected bank.</p></div><button type="button" onClick={cancel} className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-white/[.04] text-[#8B90A0]">×</button></div>{current&&<div className="mt-3 rounded-xl border border-amber-500/15 bg-amber-500/[.05] p-3 text-[9px] leading-relaxed text-amber-200/80">When changing your payout account, at least two names on the new bank account must match your WeHouse full name.</div>}<div className="mt-4 space-y-3"><SearchableSelect label="Bank" value={bankCode} onChange={value=>{setBankCode(value);setResolution(null)}} options={options} placeholder={loadingBanks?'Loading banks…':'Choose bank'} searchPlaceholder="Search bank" disabled={loadingBanks}/><label className="block"><span className="mb-1.5 block text-[10px] font-medium text-[#7B8190]">Account number</span><input inputMode="numeric" maxLength={10} value={number} onChange={event=>{setNumber(event.target.value.replace(/\D/g,'').slice(0,10));setResolution(null)}} placeholder="10-digit account number" className="h-11 w-full rounded-xl border border-white/[.08] bg-[#181B24] px-3 text-xs outline-none focus:border-violet-500/45"/></label><button type="button" onClick={()=>void resolve()} disabled={resolving||!bankCode||number.length!==10} className="h-11 w-full rounded-xl border border-violet-500/25 bg-violet-500/[.08] text-xs font-semibold text-violet-200 disabled:opacity-40">{resolving?'Verifying…':'Verify account'}</button>{resolution&&<div className={`rounded-xl border p-3 ${resolution.replacement_allowed?'border-emerald-500/15 bg-emerald-500/[.05]':'border-red-500/20 bg-red-500/[.05]'}`}><p className={`text-[9px] font-semibold ${resolution.replacement_allowed?'text-emerald-300':'text-red-300'}`}>{resolution.replacement_allowed?'Account verified':'This account cannot replace your current payout account'}</p><p className="mt-1 text-xs font-semibold">{resolution.account_name}</p><p className="mt-1 text-[9px] text-[#747A8B]">{resolution.bank_name} · •••• {resolution.account_number.slice(-4)}</p>{!resolution.replacement_allowed&&<p className="mt-2 text-[9px] leading-relaxed text-red-200/70">At least two names must match your WeHouse full name.</p>}</div>}{resolution?.replacement_allowed&&<button type="button" onClick={()=>void save()} disabled={saving} className="h-12 w-full rounded-xl bg-violet-500 text-xs font-semibold disabled:opacity-40">{saving?'Saving…':current?'Confirm account change':'Connect payout account'}</button>}</div></section>;
 return <section className={`rounded-2xl border border-white/[.06] bg-[#111119] ${compact?'p-4':'p-5'} text-white`}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold">Payout account</p><p className="mt-1 text-[9px] text-[#666B7B]">WeHouse sends approved withdrawals here.</p></div><button type="button" onClick={begin} className="rounded-xl border border-violet-500/20 bg-violet-500/[.07] px-3 py-2 text-[9px] font-semibold text-violet-300">{current?'Change':'Add account'}</button></div>{current?<div className="mt-4 flex items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.025] p-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-500/10 text-xs font-bold text-violet-200">{current.bank_name.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{current.bank_name}</p><p className="mt-1 truncate text-[9px] text-[#696E7E]">•••• {current.account_number.slice(-4)} · {current.account_name}</p></div><span className="rounded-full bg-emerald-500/10 px-2 py-1 text-[8px] text-emerald-300">Verified</span></div>:<div className="mt-4 rounded-xl border border-dashed border-white/[.08] p-4 text-[10px] leading-relaxed text-[#666B7B]">No payout account connected. Your first account can be any valid bank account that Paystack can resolve.</div>}</section>;
}
