import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import LocationMap from './LocationMap';

export type PreciseLocation={latitude:number;longitude:number;accuracy:number|null;address:string;city?:string;state?:string};
type Props={value:PreciseLocation|null;onChange:(value:PreciseLocation|null)=>void;title?:string;description?:string};

export default function PreciseLocationPicker({value,onChange,title='Confirm property address',description='Use your phone location at the property, then check the street address before continuing.'}:Props){
 const[locating,setLocating]=useState(false),[message,setMessage]=useState('');
 const requestRef=useRef(0);
 useEffect(()=>()=>{requestRef.current+=1},[]);
 async function finish(position:GeolocationPosition,request:number){if(request!==requestRef.current)return;setLocating(false);const latitude=position.coords.latitude,longitude=position.coords.longitude,accuracy=position.coords.accuracy;const pin={latitude,longitude,accuracy,address:value?.address||'',city:value?.city,state:value?.state};onChange(pin);setMessage(`Pin found · accuracy about ${Math.round(accuracy)} m`);try{const result=await Promise.race([supabase.functions.invoke('reverse-geocode',{body:{latitude,longitude}}),new Promise<never>((_,reject)=>window.setTimeout(()=>reject(new Error('Address lookup timed out')),8000))]);if(request!==requestRef.current)return;if(!result.error&&result.data?.address){const address=String(result.data.address);onChange({...pin,address,city:String(result.data.city||''),state:String(result.data.state||'')});setMessage('Address found from the pin. Check it before continuing.')}else setMessage('Pin found. Enter the exact street address below.')}catch{if(request===requestRef.current)setMessage('Pin found. Enter the exact street address below.')}}
 function fail(error:GeolocationPositionError){setLocating(false);const denied=error.code===error.PERMISSION_DENIED;const text=denied?'Location permission is blocked. Open the site controls beside the WeHouse address, set Location to Allow, then tap again.':error.code===error.TIMEOUT?'No location arrived from this phone. Turn on Location, return to WeHouse and tap again.':'This phone could not provide a location. Check that Location is on, then tap again.';setMessage(text);toast.error(denied?'Allow WeHouse to use your location':'No location received')}
 function locate(){if(!navigator.geolocation){setMessage('This browser cannot share location. Open WeHouse in Chrome or Safari on a phone with Location enabled.');return}const request=++requestRef.current;setLocating(true);setMessage('Getting your property location…');navigator.geolocation.getCurrentPosition(position=>{if(request!==requestRef.current)return;void finish(position,request);const watch=navigator.geolocation.watchPosition(better=>{if(request!==requestRef.current)return navigator.geolocation.clearWatch(watch);if(better.coords.accuracy<position.coords.accuracy)void finish(better,request)},()=>undefined,{enableHighAccuracy:true,maximumAge:0,timeout:15000});window.setTimeout(()=>navigator.geolocation.clearWatch(watch),15000)},fail,{enableHighAccuracy:false,maximumAge:600000,timeout:15000})}
 return <section className="border-y border-white/[.07] py-4"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold">{title}</p><p className="mt-1 text-[9px] leading-5 text-[#787D8F]">{description}</p></div>{value&&<span className={`shrink-0 text-[8px] font-bold uppercase tracking-wide ${value.address.trim()?'text-emerald-300':'text-amber-300'}`}>{value.address.trim()?'Address ready':'Address needed'}</span>}</div><div className="mt-3 grid grid-cols-3 gap-1.5 text-center text-[8px]"><span className={`border-b pb-2 ${value?'border-emerald-400 text-emerald-300':'border-violet-400 text-violet-300'}`}>1 · Locate</span><span className={`border-b pb-2 ${value?'border-violet-400 text-violet-300':'border-white/10 text-[#626879]'}`}>2 · Check pin</span><span className={`border-b pb-2 ${value?.address.trim()?'border-emerald-400 text-emerald-300':'border-white/10 text-[#626879]'}`}>3 · Confirm address</span></div><button type="button" onClick={locate} disabled={locating} className="mt-3 min-h-11 w-full rounded-xl bg-violet-500 px-4 text-[10px] font-semibold text-white disabled:opacity-50">{locating?'Finding this phone…':value?'Update from my location':'Use my current location'}</button>{message&&<p className={`mt-2 rounded-xl px-3 py-2 text-[9px] leading-5 ${/off|could not|unavailable|No location|cannot/i.test(message)?'bg-amber-500/10 text-amber-200':'text-[#9AA0AF]'}`} role={/off|could not|unavailable|No location|cannot/i.test(message)?'alert':'status'}>{message}</p>}{value&&<div className="mt-3 space-y-3"><LocationMap latitude={value.latitude} longitude={value.longitude} label="Property pin"/><label className="block"><span className="mb-1 block text-[9px] font-semibold text-[#A4A9B7]">Exact street address</span><textarea rows={2} value={value.address} placeholder="House number, street, area" onChange={event=>onChange({...value,address:event.target.value})} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#181A23] p-3 text-xs outline-none focus:border-violet-500/40"/><span className="mt-1 block text-[8px] leading-4 text-[#656B7B]">The map suggestion may be approximate. Correct the address so WeHouse Operations can find the property.</span></label><button type="button" onClick={()=>{requestRef.current+=1;onChange(null);setMessage('')}} className="text-[9px] font-semibold text-red-300">Clear location</button></div>}</section>
}
