import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import LocationMap from './LocationMap';

export type PreciseLocation={latitude:number;longitude:number;accuracy:number|null;address:string};
type Props={value:PreciseLocation|null;onChange:(value:PreciseLocation|null)=>void;title?:string;description?:string};

export default function PreciseLocationPicker({value,onChange,title='Precise location (optional)',description='Use your device location, check the map pin, and let WeHouse find the nearest street address.'}:Props){
 const[locating,setLocating]=useState(false),[message,setMessage]=useState('');
 const watchRef=useRef<number|null>(null),bestRef=useRef<GeolocationPosition|null>(null),timeoutRef=useRef<number|null>(null),requestRef=useRef(0);
 function clear(){if(watchRef.current!==null)navigator.geolocation.clearWatch(watchRef.current);if(timeoutRef.current!==null)window.clearTimeout(timeoutRef.current);watchRef.current=null;timeoutRef.current=null}
 useEffect(()=>()=>{requestRef.current+=1;clear()},[]);
 async function finish(position:GeolocationPosition,request:number){if(request!==requestRef.current)return;clear();setLocating(false);const latitude=position.coords.latitude,longitude=position.coords.longitude,accuracy=position.coords.accuracy;const pin={latitude,longitude,accuracy,address:value?.address||''};onChange(pin);setMessage(`Pin found · GPS accuracy ±${Math.round(accuracy)}m · finding the nearest address…`);try{const result=await Promise.race([supabase.functions.invoke('reverse-geocode',{body:{latitude,longitude}}),new Promise<never>((_,reject)=>window.setTimeout(()=>reject(new Error('Address lookup timed out')),8000))]);if(request!==requestRef.current)return;if(!result.error&&result.data?.address){const address=String(result.data.address);onChange({...pin,address});setMessage(`Address found · GPS accuracy ±${Math.round(accuracy)}m`)}else setMessage(`Pin saved · GPS accuracy ±${Math.round(accuracy)}m. You can enter the street address below.`)}catch{if(request===requestRef.current)setMessage(`Pin saved · GPS accuracy ±${Math.round(accuracy)}m. Address lookup is unavailable, so enter it below.`)}}
 function fail(error:GeolocationPositionError){clear();setLocating(false);const denied=error.code===error.PERMISSION_DENIED;const text=denied?'Location is off for WeHouse. Tap the site controls beside the web address, allow Location, turn on Precise location or GPS, then try again.':error.code===error.TIMEOUT?'We could not get a GPS reading in time. Turn on Location, move near a window, and try again.':'Your location could not be read. Turn on Location and GPS, then try again.';setMessage(text);toast.error(denied?'Location permission is off':'Location could not be captured')}
 function locate(){if(!navigator.geolocation){setMessage('This browser cannot share location. Open WeHouse in Chrome or Safari on a device with Location enabled.');return}clear();const request=++requestRef.current;bestRef.current=null;setLocating(true);setMessage('Waiting for your device location. If prompted, choose Allow and enable precise location.');watchRef.current=navigator.geolocation.watchPosition(position=>{if(request!==requestRef.current)return;if(!bestRef.current||position.coords.accuracy<bestRef.current.coords.accuracy)bestRef.current=position;setMessage(`Location received · improving GPS accuracy ±${Math.round(bestRef.current.coords.accuracy)}m`);if(position.coords.accuracy<=35)void finish(position,request)},fail,{enableHighAccuracy:true,maximumAge:3000,timeout:20000});timeoutRef.current=window.setTimeout(()=>{if(request!==requestRef.current)return;const best=bestRef.current;if(best)void finish(best,request);else{clear();setLocating(false);setMessage('No location was received. Turn on Location and GPS, allow WeHouse to use it, then try again.')}},18000)}
 return <section className="rounded-2xl border border-violet-500/15 bg-violet-500/[.04] p-4"><p className="text-xs font-semibold">{title}</p><p className="mt-1 text-[9px] leading-5 text-[#787D8F]">{description}</p><button type="button" onClick={locate} disabled={locating} className="mt-3 min-h-11 w-full rounded-xl border border-violet-500/20 bg-violet-500/10 px-4 text-[10px] font-semibold text-violet-300 disabled:opacity-50">{locating?'Finding your location…':value?'Update map pin':'Use map & current location'}</button>{message&&<p className={`mt-2 rounded-xl px-3 py-2 text-[9px] leading-5 ${/off|could not|unavailable|No location|cannot/i.test(message)?'bg-amber-500/10 text-amber-200':'text-[#9AA0AF]'}`} role={/off|could not|unavailable|No location|cannot/i.test(message)?'alert':'status'}>{message}</p>}{value&&<div className="mt-3 space-y-3"><LocationMap latitude={value.latitude} longitude={value.longitude} label={value.address||`GPS accuracy ±${Math.round(value.accuracy||0)}m`}/><label className="block"><span className="mb-1 block text-[9px] text-[#777E8E]">Nearest street address (you can correct it)</span><textarea rows={2} value={value.address} onChange={event=>onChange({...value,address:event.target.value})} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#181A23] p-3 text-xs outline-none focus:border-violet-500/40"/></label><button type="button" onClick={()=>{requestRef.current+=1;clear();onChange(null);setMessage('')}} className="text-[9px] font-semibold text-red-300">Remove map pin</button></div>}</section>
}
