import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import LocationMap from './LocationMap';

export type PreciseLocation={latitude:number;longitude:number;accuracy:number|null;address:string};
type Props={value:PreciseLocation|null;onChange:(value:PreciseLocation|null)=>void;title?:string;description?:string};

export default function PreciseLocationPicker({value,onChange,title='Precise location (optional)',description='Use your device location, check the map pin, and let WeHouse find the nearest street address.'}:Props){
 const[locating,setLocating]=useState(false),[message,setMessage]=useState('');
 const requestRef=useRef(0);
 useEffect(()=>()=>{requestRef.current+=1},[]);
 async function finish(position:GeolocationPosition,request:number){if(request!==requestRef.current)return;setLocating(false);const latitude=position.coords.latitude,longitude=position.coords.longitude,accuracy=position.coords.accuracy;const pin={latitude,longitude,accuracy,address:value?.address||''};onChange(pin);setMessage(`Property location saved · GPS accuracy ±${Math.round(accuracy)}m`);try{const result=await Promise.race([supabase.functions.invoke('reverse-geocode',{body:{latitude,longitude}}),new Promise<never>((_,reject)=>window.setTimeout(()=>reject(new Error('Address lookup timed out')),8000))]);if(request!==requestRef.current)return;if(!result.error&&result.data?.address){const address=String(result.data.address);onChange({...pin,address});setMessage(`Property location and nearest address saved · GPS accuracy ±${Math.round(accuracy)}m`)}else setMessage(`Property location saved · GPS accuracy ±${Math.round(accuracy)}m`)}catch{if(request===requestRef.current)setMessage(`Property location saved · GPS accuracy ±${Math.round(accuracy)}m`)}}
 function fail(error:GeolocationPositionError){setLocating(false);const denied=error.code===error.PERMISSION_DENIED;const text=denied?'Location permission is blocked. Open the site controls beside the WeHouse address, set Location to Allow, then tap again.':error.code===error.TIMEOUT?'No location arrived from this phone. Turn on Location, return to WeHouse and tap again.':'This phone could not provide a location. Check that Location is on, then tap again.';setMessage(text);toast.error(denied?'Allow WeHouse to use your location':'No location received')}
 function locate(){if(!navigator.geolocation){setMessage('This browser cannot share location. Open WeHouse in Chrome or Safari on a phone with Location enabled.');return}const request=++requestRef.current;setLocating(true);setMessage('Getting your property location…');navigator.geolocation.getCurrentPosition(position=>{if(request!==requestRef.current)return;void finish(position,request);const watch=navigator.geolocation.watchPosition(better=>{if(request!==requestRef.current)return navigator.geolocation.clearWatch(watch);if(better.coords.accuracy<position.coords.accuracy)void finish(better,request)},()=>undefined,{enableHighAccuracy:true,maximumAge:0,timeout:15000});window.setTimeout(()=>navigator.geolocation.clearWatch(watch),15000)},fail,{enableHighAccuracy:false,maximumAge:600000,timeout:15000})}
 return <section className="rounded-2xl border border-violet-500/15 bg-violet-500/[.04] p-4"><p className="text-xs font-semibold">{title}</p><p className="mt-1 text-[9px] leading-5 text-[#787D8F]">{description}</p><button type="button" onClick={locate} disabled={locating} className="mt-3 min-h-11 w-full rounded-xl border border-violet-500/20 bg-violet-500/10 px-4 text-[10px] font-semibold text-violet-300 disabled:opacity-50">{locating?'Getting property location…':value?'Update property location':'Use current property location'}</button>{message&&<p className={`mt-2 rounded-xl px-3 py-2 text-[9px] leading-5 ${/off|could not|unavailable|No location|cannot/i.test(message)?'bg-amber-500/10 text-amber-200':'text-[#9AA0AF]'}`} role={/off|could not|unavailable|No location|cannot/i.test(message)?'alert':'status'}>{message}</p>}{value&&<div className="mt-3 space-y-3"><LocationMap latitude={value.latitude} longitude={value.longitude} label={value.address||`GPS accuracy ±${Math.round(value.accuracy||0)}m`}/><label className="block"><span className="mb-1 block text-[9px] text-[#777E8E]">Nearest street address</span><textarea rows={2} value={value.address} onChange={event=>onChange({...value,address:event.target.value})} className="w-full resize-none rounded-xl border border-white/[.08] bg-[#181A23] p-3 text-xs outline-none focus:border-violet-500/40"/></label><button type="button" onClick={()=>{requestRef.current+=1;onChange(null);setMessage('')}} className="text-[9px] font-semibold text-red-300">Remove property location</button></div>}</section>
}
