import { useCallback,useEffect,useRef,useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import { endPrivateCall,getActiveCalls,getCallDetails,listCallSignals,respondPrivateCall,sendCallSignal,startPrivateCall,type PrivateCall,type PrivateCallContext,type PrivateCallType,type CallSignal } from '@/lib/private-calls';

type Me={user_id:string;role:string;full_name:string|null;username:string|null;avatar_url:string|null};
type StartDetail={contextType:PrivateCallContext;contextId:string;callType:PrivateCallType};
const TERMINAL=new Set(['declined','missed','ended','failed']);

export default function PrivateCallCenterStable(){
 const[me,setMe]=useState<Me|null>(null),[call,setCall]=useState<PrivateCall|null>(null),[loading,setLoading]=useState(false);
 const loadCall=useCallback(async(id:string)=>{const{call:row}=await getCallDetails(id);if(row)setCall(row)},[]);
 useEffect(()=>{let live=true;void(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from('profiles').select('user_id,role,full_name,username,avatar_url').eq('auth_id',user.id).maybeSingle();if(!live||!data||!['user','worker'].includes(String(data.role)))return;setMe(data as Me);const active=await getActiveCalls();if(active.calls?.length)setCall(active.calls.find(row=>row.status==='accepted')||active.calls[0])})();return()=>{live=false}},[]);
 useEffect(()=>{if(!me)return;const uid=me.user_id;const channel=supabase.channel(`private-calls:${uid}`)
  .on('postgres_changes',{event:'INSERT',schema:'public',table:'private_calls',filter:`callee_id=eq.${uid}`},payload=>void loadCall(String((payload.new as any).id)))
  .on('postgres_changes',{event:'UPDATE',schema:'public',table:'private_calls',filter:`callee_id=eq.${uid}`},payload=>void loadCall(String((payload.new as any).id)))
  .on('postgres_changes',{event:'UPDATE',schema:'public',table:'private_calls',filter:`caller_id=eq.${uid}`},payload=>void loadCall(String((payload.new as any).id)))
  .subscribe();return()=>{void supabase.removeChannel(channel)}},[me?.user_id,loadCall]);
 useEffect(()=>{if(!me)return;const handler=(event:Event)=>{const detail=(event as CustomEvent<StartDetail>).detail;if(!detail?.contextId||!detail?.contextType||!detail?.callType)return;void begin(detail)};window.addEventListener('wehouse:start-private-call',handler as EventListener);return()=>window.removeEventListener('wehouse:start-private-call',handler as EventListener)},[me?.user_id,call?.id,loading]);
 useEffect(()=>{if(!call||!me||call.status!=='ringing'||call.caller_id!==me.user_id)return;const timer=window.setTimeout(()=>void hangup(true),45000);return()=>window.clearTimeout(timer)},[call?.id,call?.status,me?.user_id]);
 useEffect(()=>{if(!call||!TERMINAL.has(call.status))return;const timer=window.setTimeout(()=>setCall(null),1100);return()=>window.clearTimeout(timer)},[call?.status]);
 async function begin(detail:StartDetail){if(!me||loading)return;if(call&&['ringing','accepted'].includes(call.status))return toast.info('Finish the current call first');setLoading(true);const result=await startPrivateCall(detail.contextType,detail.contextId,detail.callType);setLoading(false);if(result.error||!result.call)return toast.error(result.error?.message||'Call could not start');setCall(result.call)}
 async function accept(){if(!call)return;const result=await respondPrivateCall(call.id,true);if(result.error||!result.call)return toast.error(result.error?.message||'Call could not be answered');setCall(result.call)}
 async function decline(){if(!call)return;const result=await respondPrivateCall(call.id,false);if(result.error)return toast.error(result.error.message);if(result.call)setCall(result.call);else setCall(null)}
 async function hangup(silent=false){if(!call)return;const result=await endPrivateCall(call.id);if(result.error&&!silent)toast.error(result.error.message);if(result.call)setCall(result.call);else setCall(null)}
 if(!me||!call)return null;
 if(call.status==='ringing'&&call.callee_id===me.user_id)return <IncomingCall call={call} onAccept={()=>void accept()} onDecline={()=>void decline()}/>;
 if(TERMINAL.has(call.status))return <CallEnded call={call}/>;
 return <RtcRoom call={call} me={me} onHangup={()=>void hangup()}/>;
}

function IncomingCall({call,onAccept,onDecline}:{call:PrivateCall;onAccept:()=>void;onDecline:()=>void}){
 return <div className="fixed inset-0 z-[190] grid place-items-end bg-black/70 p-3 backdrop-blur-md sm:place-items-center"><section className="w-full overflow-hidden rounded-[30px] border border-white/10 bg-[#10131B] p-5 text-white shadow-2xl sm:max-w-sm"><div className="text-center"><Avatar call={call} large/><p className="mt-4 text-lg font-bold">{call.peer_name||'WeHouse member'}</p><p className="mt-1 text-[10px] text-[#7D8495]">Incoming {call.call_type==='video'?'video':'audio'} call</p><div className="mx-auto mt-3 flex w-fit items-center gap-1.5"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400"/><span className="text-[8px] uppercase tracking-[.14em] text-emerald-300">Private WeHouse conversation</span></div></div><div className="mt-7 grid grid-cols-2 gap-3"><button onClick={onDecline} className="h-14 rounded-2xl bg-red-500/14 text-xs font-semibold text-red-200">Decline</button><button onClick={onAccept} className="h-14 rounded-2xl bg-emerald-500 text-xs font-semibold text-white">Answer</button></div></section></div>
}
function CallEnded({call}:{call:PrivateCall}){const label=call.status==='declined'?'Call declined':call.status==='missed'?'No answer':call.status==='failed'?'Call failed':'Call ended';return <div className="fixed inset-0 z-[190] grid place-items-center bg-[#080A0E]/96 p-5 text-white"><div className="text-center"><Avatar call={call} large/><p className="mt-4 text-lg font-bold">{label}</p><p className="mt-1 text-[10px] text-[#6D7485]">{call.peer_name||'WeHouse member'}</p></div></div>}

function RtcRoom({call,me,onHangup}:{call:PrivateCall;me:Me;onHangup:()=>void}){
 const localVideo=useRef<HTMLVideoElement>(null),remoteVideo=useRef<HTMLVideoElement>(null),remoteAudio=useRef<HTMLAudioElement>(null),pcRef=useRef<RTCPeerConnection|null>(null),localStream=useRef<MediaStream|null>(null),signalChannel=useRef<any>(null),processed=useRef(new Set<string>()),pendingIce=useRef<RTCIceCandidateInit[]>([]),offerSent=useRef(false);
 const[connected,setConnected]=useState(false),[muted,setMuted]=useState(false),[cameraOn,setCameraOn]=useState(call.call_type==='video'),[seconds,setSeconds]=useState(0),[mediaError,setMediaError]=useState('');
 const caller=call.caller_id===me.user_id;
 useEffect(()=>{let alive=true;processed.current.clear();pendingIce.current=[];offerSent.current=false;void setup();return()=>{alive=false;if(signalChannel.current){void supabase.removeChannel(signalChannel.current);signalChannel.current=null}localStream.current?.getTracks().forEach(track=>track.stop());localStream.current=null;pcRef.current?.close();pcRef.current=null;if(remoteVideo.current)remoteVideo.current.srcObject=null;if(remoteAudio.current)remoteAudio.current.srcObject=null};
  async function setup(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1},video:call.call_type==='video'?{facingMode:'user',width:{ideal:1280,max:1920},height:{ideal:720,max:1080},frameRate:{ideal:30,max:30}}:false});if(!alive){stream.getTracks().forEach(track=>track.stop());return}localStream.current=stream;if(localVideo.current)localVideo.current.srcObject=stream;const pc=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}]});pcRef.current=pc;stream.getTracks().forEach(track=>pc.addTrack(track,stream));pc.onicecandidate=event=>{if(event.candidate)void sendCallSignal(call.id,me.user_id,'ice',event.candidate.toJSON())};pc.ontrack=event=>{const remote=event.streams[0]||new MediaStream([event.track]);if(call.call_type==='video'&&remoteVideo.current)remoteVideo.current.srcObject=remote;if(remoteAudio.current)remoteAudio.current.srcObject=remote};pc.onconnectionstatechange=()=>{const state=pc.connectionState;setConnected(state==='connected');if(state==='failed'||state==='disconnected')setMediaError('The call lost its media connection. Try again or use audio.')};const existing=await listCallSignals(call.id);for(const signal of existing.signals||[])await process(signal,pc);const channel=supabase.channel(`call-signals:${call.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'private_call_signals',filter:`call_id=eq.${call.id}`},payload=>void process(payload.new as CallSignal,pc)).subscribe();signalChannel.current=channel;if(caller&&!offerSent.current){offerSent.current=true;const offer=await pc.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:call.call_type==='video'});await pc.setLocalDescription(offer);await sendCallSignal(call.id,me.user_id,'offer',offer)}}catch(error:any){setMediaError(error?.name==='NotAllowedError'?'Allow microphone and camera access for calls.':error?.message||'Media could not start')}}
  async function process(signal:CallSignal,pc:RTCPeerConnection){if(!signal?.id||processed.current.has(signal.id)||signal.sender_id===me.user_id)return;processed.current.add(signal.id);try{if(signal.signal_type==='offer'&&!pc.currentRemoteDescription){await pc.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);await flush(pc);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await sendCallSignal(call.id,me.user_id,'answer',answer)}else if(signal.signal_type==='answer'&&pc.signalingState==='have-local-offer'){await pc.setRemoteDescription(signal.payload as RTCSessionDescriptionInit);await flush(pc)}else if(signal.signal_type==='ice'){if(pc.remoteDescription)await pc.addIceCandidate(signal.payload as RTCIceCandidateInit);else pendingIce.current.push(signal.payload as RTCIceCandidateInit)}}catch{}}
  async function flush(pc:RTCPeerConnection){while(pendingIce.current.length){const candidate=pendingIce.current.shift();if(candidate)try{await pc.addIceCandidate(candidate)}catch{}}}
 },[call.id,call.call_type,caller,me.user_id]);
 useEffect(()=>{if(!connected){setSeconds(0);return}const timer=window.setInterval(()=>setSeconds(value=>value+1),1000);return()=>window.clearInterval(timer)},[connected]);
 function toggleMute(){const next=!muted;localStream.current?.getAudioTracks().forEach(track=>track.enabled=!next);setMuted(next)}
 function toggleCamera(){const next=!cameraOn;localStream.current?.getVideoTracks().forEach(track=>track.enabled=next);setCameraOn(next)}
 const status=mediaError||(!connected?(caller?'Calling…':'Connecting…'):formatDuration(seconds));
 return <div className="fixed inset-0 z-[190] flex h-[100dvh] flex-col overflow-hidden bg-black text-white">
  <div className="relative min-h-0 flex-1 overflow-hidden">{call.call_type==='video'?<><video ref={remoteVideo} autoPlay muted playsInline className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-b from-black/45 via-transparent to-black/60"/>{!connected&&<div className="absolute inset-0 grid place-items-center"><div className="text-center"><Avatar call={call} large/><p className="mt-4 text-lg font-bold">{call.peer_name||'WeHouse member'}</p><p className="mt-1 text-[10px] text-white/60">{status}</p></div></div>}<div className="absolute right-3 top-[max(.75rem,env(safe-area-inset-top))] h-40 w-28 overflow-hidden rounded-2xl border border-white/15 bg-[#111] shadow-2xl sm:h-48 sm:w-36"><video ref={localVideo} autoPlay muted playsInline className={`h-full w-full scale-x-[-1] object-cover ${cameraOn?'':'opacity-0'}`}/>{!cameraOn&&<div className="absolute inset-0 grid place-items-center text-[9px] text-white/50">Camera off</div>}</div></>:<div className="grid h-full place-items-center bg-[radial-gradient(circle_at_50%_35%,rgba(124,58,237,.24),transparent_38%),#090A0F]"><div className="text-center"><Avatar call={call} large/><p className="mt-5 text-2xl font-bold">{call.peer_name||'WeHouse member'}</p><p className="mt-2 text-[11px] text-[#8A91A2]">{status}</p>{connected&&<div className="mx-auto mt-6 flex w-28 items-end justify-center gap-1">{[18,30,22,36,25,32,19].map((height,index)=><span key={index} className="w-1.5 animate-pulse rounded-full bg-violet-400/80" style={{height}}/>)}</div>}</div></div>}<audio ref={remoteAudio} autoPlay/>{mediaError&&<div className="absolute inset-x-4 top-20 rounded-2xl border border-red-500/20 bg-red-500/10 p-3 text-center text-[10px] text-red-100 backdrop-blur-xl">{mediaError}</div>}</div>
  <footer className="shrink-0 border-t border-white/10 bg-[#0D0F14]/98 px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-4"><div className="mx-auto flex max-w-md items-center justify-center gap-4"><Control active={!muted} label={muted?'Unmute':'Mute'} onClick={toggleMute} icon={<Mic muted={muted}/>}/>{call.call_type==='video'&&<Control active={cameraOn} label={cameraOn?'Camera':'Camera off'} onClick={toggleCamera} icon={<Camera off={!cameraOn}/>}/>}<button onClick={onHangup} className="grid h-14 w-14 place-items-center rounded-full bg-red-500 shadow-lg shadow-red-950/30" aria-label="End call"><PhoneEnd/></button></div><p className="mt-3 text-center text-[8px] text-[#555D6D]">Adaptive WebRTC media · 720p target with higher resolution when the connection allows it.</p></footer>
 </div>
}
function Avatar({call,large=false}:{call:PrivateCall;large?:boolean}){const size=large?'h-28 w-28 text-3xl':'h-12 w-12 text-sm';return <div className={`mx-auto grid ${size} place-items-center overflow-hidden rounded-full border border-white/10 bg-gradient-to-br from-violet-500 to-indigo-600 font-bold shadow-2xl`}>{call.peer_avatar?<img src={call.peer_avatar} alt="" className="h-full w-full object-cover"/>:(call.peer_name||'W')[0].toUpperCase()}</div>}
function Control({active,label,onClick,icon}:{active:boolean;label:string;onClick:()=>void;icon:React.ReactNode}){return <button onClick={onClick} className="flex w-16 flex-col items-center gap-1.5"><span className={`grid h-12 w-12 place-items-center rounded-full ${active?'bg-white/12':'bg-red-500/16 text-red-200'}`}>{icon}</span><span className="text-[8px] text-white/65">{label}</span></button>}
function formatDuration(total:number){const minutes=Math.floor(total/60),seconds=total%60;return`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}
function Mic({muted}:{muted:boolean}){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 10a7 7 0 0 0 12 4.9M12 18v3M8 21h8"/>{muted&&<path d="M4 4l16 16"/>}</svg>}
function Camera({off}:{off:boolean}){return <svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/>{off&&<path d="M3 3l18 18"/>}</svg>}
function PhoneEnd(){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 14c5-4 11-4 16 0"/><path d="M7 12l-2 4M17 12l2 4"/></svg>}
