import { useEffect,useState } from 'react';
import { toast } from 'sonner';
import PayoutBankAccount from '@/components/PayoutBankAccount';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';

type Finance={available_balance:number;pending_balance:number;frozen_balance:number;total_withdrawn:number;total_earnings:number;apartment_commission_rate:number;hotel_commission_rate:number;minimum_withdrawal:number;is_frozen:boolean};
type BankAccount={id:string;bank_name:string;bank_code:string;account_number:string;account_name:string;verified_at:string|null};
type View='wallet'|'withdraw'|'activity';
type Props={profile:Profile;showAmounts?:boolean;onToggleAmounts?:()=>void};
const money=(value:number)=>`₦${Number(value||0).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const hidden='₦••••••';

export default function PropertyPartnerFinancePanel({profile,showAmounts=true,onToggleAmounts}:Props){
 const[view,setView]=useState<View>('wallet'),[finance,setFinance]=useState<Finance|null>(null),[transactions,setTransactions]=useState<any[]>([]),[withdrawals,setWithdrawals]=useState<any[]>([]),[bank,setBank]=useState<BankAccount|null>(null),[amount,setAmount]=useState(''),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false);
 async function load(){setLoading(true);const[f,t,w,b]=await Promise.all([
  supabase.rpc('get_my_property_partner_finance'),
  supabase.from('wallet_transactions').select('*').eq('user_id',profile.user_id).order('created_at',{ascending:false}).limit(30),
  supabase.from('withdrawals').select('id,amount,status,created_at,failed_reason,wallets!inner(owner_id)').eq('wallets.owner_id',profile.user_id).order('created_at',{ascending:false}).limit(20),
  supabase.from('bank_accounts').select('id,bank_name,bank_code,account_number,account_name,verified_at').eq('user_id',profile.user_id).maybeSingle(),
 ]);if(f.error)toast.error('Unable to load your wallet');setFinance((f.data||null) as Finance|null);setTransactions(t.data||[]);setWithdrawals(w.data||[]);setBank((b.data||null) as BankAccount|null);setLoading(false)}
 useEffect(()=>{void load()},[profile.user_id]);
 async function requestWithdrawal(){if(!finance)return;const n=Number(amount);if(!n||n<=0)return toast.error('Enter a valid amount');if(n<Number(finance.minimum_withdrawal||0))return toast.error(`Minimum withdrawal is ${money(finance.minimum_withdrawal)}`);if(n>Number(finance.available_balance||0))return toast.error('Insufficient available balance');if(!bank?.verified_at)return toast.error('Add and verify your payout account first');if(finance.is_frozen)return toast.error('Your wallet is currently unavailable. Contact WeHouse Support.');setSubmitting(true);const{error}=await supabase.rpc('request_my_property_partner_withdrawal',{p_amount:n,p_bank_account_number:bank.account_number,p_bank_code:bank.bank_code,p_bank_name:bank.bank_name,p_account_name:bank.account_name});setSubmitting(false);if(error)return toast.error(error.message||'Withdrawal request failed');toast.success('Withdrawal request submitted');setAmount('');setView('activity');await load()}
 if(loading)return <Loading/>;if(!finance)return <section className="rounded-2xl border border-red-500/20 bg-red-500/[.06] p-5 text-xs text-red-300">Unable to load your wallet.</section>;
 const recent=[...transactions.map(row=>({id:`t-${row.id}`,title:row.description||friendly(row.transaction_type)||'Transaction',date:row.created_at,amount:Number(row.amount||0),status:row.transaction_type})),...withdrawals.map(row=>({id:`w-${row.id}`,title:'Withdrawal',date:row.created_at,amount:-Number(row.amount||0),status:row.status}))].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
 if(view==='withdraw')return <div className="space-y-4"><Back title="Withdraw" onBack={()=>setView('wallet')}/><PayoutBankAccount profile={profile} onChanged={load} compact/><section className="rounded-3xl border border-violet-500/15 bg-gradient-to-br from-violet-500/[.08] to-[#111119] p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-[9px] uppercase tracking-[.16em] text-[#707286]">Available to withdraw</p><p className="mt-2 text-2xl font-bold">{showAmounts?money(finance.available_balance):hidden}</p></div>{onToggleAmounts&&<PrivacyButton show={showAmounts} onClick={onToggleAmounts}/>}</div><p className="mt-1 text-[10px] text-[#626477]">Minimum withdrawal {showAmounts?money(finance.minimum_withdrawal):'••••'}</p><div className="mt-5 space-y-3"><label className="block"><span className="mb-1 block text-[10px] text-[#77798B]">Amount</span><div className="flex h-12 items-center rounded-xl border border-white/[.08] bg-[#181822] px-3 focus-within:border-violet-500/40"><span className="mr-1 text-sm text-[#77798B]">₦</span><input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9]/g,''))} placeholder="0" className="min-w-0 flex-1 bg-transparent text-lg font-semibold outline-none"/></div></label>{bank?<div className="rounded-xl border border-white/[.06] bg-white/[.025] p-3"><p className="text-[9px] text-[#66687B]">Send to</p><p className="mt-1 text-xs font-medium">{bank.bank_name} · •••• {bank.account_number.slice(-4)}</p><p className="mt-1 truncate text-[9px] text-[#686B7C]">{bank.account_name}</p></div>:<div className="rounded-xl border border-amber-500/15 bg-amber-500/[.05] p-4 text-[10px] text-amber-300">Connect a payout account above before withdrawing.</div>}<button onClick={()=>void requestWithdrawal()} disabled={submitting||!amount||!bank?.verified_at} className="h-12 w-full rounded-xl bg-violet-500 text-xs font-semibold disabled:opacity-40">{submitting?'Submitting…':'Request withdrawal'}</button></div></section></div>;
 if(view==='activity')return <div className="space-y-4"><Back title="Wallet activity" onBack={()=>setView('wallet')}/><Activity rows={recent} showAmounts={showAmounts}/></div>;
 return <div className="space-y-4"><section className="overflow-hidden rounded-3xl border border-violet-500/20 bg-gradient-to-br from-violet-600/30 via-violet-500/10 to-[#101018] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-violet-200/70">Available balance</p><p className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{showAmounts?money(finance.available_balance):hidden}</p><p className="mt-2 text-[9px] text-violet-100/55">Ready for withdrawal</p></div>{onToggleAmounts&&<PrivacyButton show={showAmounts} onClick={onToggleAmounts}/>}</div>{finance.is_frozen&&<div className="mt-4 rounded-xl border border-red-500/20 bg-red-500/10 px-3 py-2 text-[10px] text-red-200">Wallet temporarily unavailable · contact WeHouse Support</div>}<div className="mt-6 grid grid-cols-3 gap-2"><Mini label="Pending" value={showAmounts?money(finance.pending_balance):'••••'}/><Mini label="Held" value={showAmounts?money(finance.frozen_balance):'••••'}/><Mini label="Withdrawn" value={showAmounts?money(finance.total_withdrawn):'••••'}/></div></section><section className="grid grid-cols-2 gap-3"><Action label="Withdraw" text="Send available funds" onClick={()=>setView('withdraw')} icon="↓"/><Action label="Activity" text="See money movement" onClick={()=>setView('activity')} icon="↗"/></section><PayoutBankAccount profile={profile} onChanged={load}/><section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold">Recent activity</p><p className="mt-1 text-[9px] text-[#66687B]">Latest wallet movement</p></div>{recent.length>3&&<button onClick={()=>setView('activity')} className="text-[10px] font-medium text-violet-300">View all</button>}</div>{recent.length===0?<p className="py-8 text-center text-[10px] text-[#5E6072]">No wallet activity yet.</p>:<div className="mt-3 divide-y divide-white/[.05]">{recent.slice(0,3).map(row=><ActivityRow key={row.id} row={row} showAmounts={showAmounts}/>)}</div>}</section><section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4"><p className="text-xs font-semibold">Your property income</p><p className="mt-2 text-[10px] leading-relaxed text-[#77798B]">Eligible income becomes available after the required property payment milestone. Reservation fees are not Property Partner earnings.</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-white/[.04] px-2.5 py-1 text-[9px] text-[#9092A2]">Apartment commission {finance.apartment_commission_rate}%</span><span className="rounded-full bg-white/[.04] px-2.5 py-1 text-[9px] text-[#9092A2]">Hotel commission {finance.hotel_commission_rate}%</span></div></section></div>
}
function Back({title,onBack}:{title:string;onBack:()=>void}){return <div className="flex items-center gap-3"><button onClick={onBack} className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.07] text-[#9A9CAD]">←</button><h2 className="text-sm font-semibold">{title}</h2></div>}
function PrivacyButton({show,onClick}:{show:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} aria-label={show?'Hide amounts':'Show amounts'} className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-white/10 bg-black/10 text-[#D7D8E2]">{show?'◉':'○'}</button>}
function Mini({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl border border-white/[.07] bg-black/10 p-3"><p className="text-[8px] uppercase tracking-wide text-violet-100/50">{label}</p><p className="mt-1 truncate text-[11px] font-semibold">{value}</p></div>}
function Action({label,text,onClick,icon}:{label:string;text:string;onClick:()=>void;icon:string}){return <button onClick={onClick} className="flex min-h-20 items-center gap-3 rounded-2xl border border-white/[.06] bg-[#111119] p-4 text-left"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-500/10 text-lg text-violet-300">{icon}</span><span className="min-w-0"><span className="block text-xs font-semibold">{label}</span><span className="mt-1 block text-[9px] text-[#626477]">{text}</span></span></button>}
function Activity({rows,showAmounts}:{rows:any[];showAmounts:boolean}){return <section className="rounded-2xl border border-white/[.06] bg-[#111119] p-4">{rows.length===0?<p className="py-10 text-center text-[10px] text-[#5E6072]">No wallet activity yet.</p>:<div className="divide-y divide-white/[.05]">{rows.map(row=><ActivityRow key={row.id} row={row} showAmounts={showAmounts}/>)}</div>}</section>}
function ActivityRow({row,showAmounts}:{row:any;showAmounts:boolean}){const n=Number(row.amount||0);return <div className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-[11px] font-medium">{row.title}</p><p className="mt-1 text-[9px] capitalize text-[#5E6072]">{new Date(row.date).toLocaleDateString()} · {friendly(row.status)}</p></div><p className={`shrink-0 text-xs font-semibold ${n<0?'text-red-300':'text-emerald-300'}`}>{showAmounts?`${n<0?'-':'+'}${money(Math.abs(n))}`:'••••'}</p></div>}
function Loading(){return <div className="grid min-h-52 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>}
function friendly(value:any){return String(value||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
