import { useEffect,useMemo,useRef,useState } from 'react';
import type { Listing } from '@/types';

type UserLocation={lat:number;lng:number};
type Item={listing:Listing;distance:number|null};
type Props={items:Item[];userLocation:UserLocation|null;radius:number|'';onOpen:(listing:Listing)=>void};

type Point={lat:number;lng:number};
function rawCoords(listing:Listing):Point|null{const row=listing as Listing&{gps_latitude?:number|null;gps_longitude?:number|null};const lat=Number(row.gps_latitude),lng=Number(row.gps_longitude);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null}
function hash(text:string){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function publicCoords(listing:Listing):Point|null{const point=rawCoords(listing);if(!point)return null;const h=hash(String(listing.id));const angle=(h%360)*Math.PI/180;const metres=55+(h%70);const dLat=(metres/111320)*Math.sin(angle);const cos=Math.max(.2,Math.cos(point.lat*Math.PI/180));const dLng=(metres/(111320*cos))*Math.cos(angle);return{lat:point.lat+dLat,lng:point.lng+dLng}}
function money(value:number){if(value>=1000000)return `₦${(value/1000000).toFixed(value%1000000?1:0)}m`;if(value>=1000)return `₦${Math.round(value/1000)}k`;return `₦${value.toLocaleString()}`}

export default function PropertyMapExplorer({items,userLocation,radius,onOpen}:Props){
 const host=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),layerRef=useRef<any>(null),locationLayerRef=useRef<any>(null);
 const[selectedId,setSelectedId]=useState<string|null>(null);
 const mapped=useMemo(()=>items.map(item=>({...item,point:publicCoords(item.listing)})).filter(item=>item.point),[items]);
 const selected=useMemo(()=>items.find(item=>item.listing.id===selectedId)||null,[items,selectedId]);
 useEffect(()=>{if(selectedId&&!items.some(item=>item.listing.id===selectedId))setSelectedId(null)},[items,selectedId]);
 useEffect(()=>{const L=(window as any).L;if(!L||!host.current||mapRef.current)return;const map=L.map(host.current,{zoomControl:false,attributionControl:true,minZoom:5,maxZoom:18});mapRef.current=map;L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);layerRef.current=L.layerGroup().addTo(map);locationLayerRef.current=L.layerGroup().addTo(map);map.setView([9.082,8.6753],6);setTimeout(()=>map.invalidateSize(),100);return()=>{map.remove();mapRef.current=null;layerRef.current=null;locationLayerRef.current=null}},[]);
 useEffect(()=>{const L=(window as any).L,map=mapRef.current,layer=layerRef.current,locationLayer=locationLayerRef.current;if(!L||!map||!layer||!locationLayer)return;layer.clearLayers();locationLayer.clearLayers();const bounds:any[]=[];mapped.forEach(item=>{const p=item.point!;bounds.push([p.lat,p.lng]);const selectedNow=item.listing.id===selectedId;const price=money(Number(item.listing.price||0));const icon=L.divIcon({className:'wehouse-map-pin',html:`<div style="transform:translate(-50%,-50%);white-space:nowrap;border-radius:999px;padding:${selectedNow?'7px 11px':'6px 9px'};font-size:${selectedNow?'11px':'10px'};font-weight:800;background:${selectedNow?'#7c3aed':'#111827'};color:white;border:1px solid ${selectedNow?'#a78bfa':'rgba(255,255,255,.18)'};box-shadow:0 7px 20px rgba(0,0,0,.35)">${price}</div>`,iconSize:[1,1],iconAnchor:[0,0]});const marker=L.marker([p.lat,p.lng],{icon}).addTo(layer);marker.on('click',()=>setSelectedId(String(item.listing.id)))});if(userLocation){bounds.push([userLocation.lat,userLocation.lng]);L.circleMarker([userLocation.lat,userLocation.lng],{radius:7,weight:3,color:'#ffffff',fillColor:'#3b82f6',fillOpacity:1}).addTo(locationLayer).bindTooltip('Your location');if(radius)L.circle([userLocation.lat,userLocation.lng],{radius:Number(radius)*1000,weight:1,color:'#60a5fa',fillColor:'#3b82f6',fillOpacity:.06}).addTo(locationLayer)}if(bounds.length===1)map.setView(bounds[0],14);else if(bounds.length>1)map.fitBounds(bounds,{padding:[38,38],maxZoom:15});else map.setView([9.082,8.6753],6);setTimeout(()=>map.invalidateSize(),50)},[mapped,userLocation,radius,selectedId]);
 return <div className="relative overflow-hidden rounded-3xl border border-white/[.07] bg-[#11141C]">
  <div ref={host} className="h-[58dvh] min-h-[430px] w-full lg:h-[calc(100dvh-245px)]"/>
  <div className="pointer-events-none absolute left-3 top-3 rounded-xl border border-white/10 bg-[#0B0D14]/90 px-3 py-2 backdrop-blur-xl"><p className="text-[10px] font-semibold text-white">{mapped.length} on map</p><p className="mt-0.5 text-[8px] text-[#8D92A3]">Home pins are approximate for privacy</p></div>
  {selected&&<div className="absolute inset-x-3 bottom-3 rounded-2xl border border-white/[.09] bg-[#0B0D14]/95 p-3 shadow-2xl backdrop-blur-xl sm:left-auto sm:w-[360px]"><div className="flex gap-3"><div className="h-16 w-20 shrink-0 overflow-hidden rounded-xl bg-[#191C26]">{selected.listing.images?.[0]?<img src={selected.listing.images[0]} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-[9px] text-[#606576]">No image</div>}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-white">{selected.listing.title||'Property'}</p><p className="mt-1 truncate text-[9px] text-[#777C8D]">{[selected.listing.city,selected.listing.state].filter(Boolean).join(', ')}</p><div className="mt-2 flex items-center justify-between gap-2"><p className="text-sm font-bold text-white">{money(Number(selected.listing.price||0))}</p>{selected.distance!=null&&<p className="text-[9px] text-blue-300">{selected.distance<1?`${Math.round(selected.distance*1000)} m`:`${selected.distance.toFixed(1)} km`}</p>}</div></div></div><button onClick={()=>onOpen(selected.listing)} className="mt-3 h-10 w-full rounded-xl bg-violet-500 text-[10px] font-semibold text-white">View property</button></div>}
  {mapped.length===0&&<div className="absolute inset-0 grid place-items-center bg-[#0E1118]/80 p-6 text-center"><div><p className="text-sm font-semibold text-white">No mapped properties in this search</p><p className="mx-auto mt-2 max-w-xs text-[10px] leading-relaxed text-[#74798A]">Properties with verified location data will appear here. You can switch back to List to see every result.</p></div></div>}
 </div>
}
