import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import {
  getMySharedHousingGroups,
  initializeSharedHousingPayment,
  respondToSharedHousingInvite,
  startSharedHousingContractSplit,
} from "@/lib/supabase/shared-housing";

type Member={user_id:string;name:string;invitation_status:string;share_amount:number;payment_status:string;paid_at?:string|null};
type Group={id:string;created_by:string;conversation_id?:string|null;listing_id:string;status:string;payment_phase:string;expires_at:string;reservation_id?:string|null;listing:{id:string;title:string;image?:string|null;address?:string;city?:string;state?:string};members:Member[]};

export default function SharedHomeLifecyclePanel({profileId,onOpenConversation,onOpenListing}:{profileId:string;onOpenConversation?:(id:string)=>void;onOpenListing?:(id:string)=>void}){
  const[groups,setGroups]=useState<Group[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState("");
  const load=useCallback(async()=>{const{groups:rows,error}=await getMySharedHousingGroups();if(error)toast.error(error.message||"Shared homes could not be loaded");setGroups((rows||[]) as Group[]);setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  async function respond(group:Group,accept:boolean){setBusy(group.id);const{error}=await respondToSharedHousingInvite(group.id,accept);setBusy("");if(error)return toast.error(error.message);toast.success(accept?"Shared home accepted":"Shared home declined");await load()}
  async function pay(group:Group){setBusy(group.id);const{result,error}=await initializeSharedHousingPayment(group.id);if(error){setBusy("");return toast.error(error.message)}if(result?.already_paid){setBusy("");await load();return toast.success("Your share is already paid")}if(!result?.authorization_url){setBusy("");return toast.error(result?.error||"Checkout could not open")}window.location.assign(result.authorization_url)}
  async function startRent(group:Group){setBusy(group.id);const{error}=await startSharedHousingContractSplit(group.id);setBusy("");if(error)return toast.error(error.message);toast.success("The rent has been divided equally. Each roommate can now pay their share.");await load()}
  if(loading)return <div className="h-20 animate-pulse rounded-2xl bg-white/[.035]"/>;
  if(!groups.length)return null;
  return <section className="space-y-3"><div><h2 className="text-sm font-semibold">Shared homes</h2><p className="mt-1 text-[9px] text-[#707687]">Invitations, equal payment shares and the shared reservation stay together.</p></div><div className="divide-y divide-white/[.06] border-y border-white/[.07]">{groups.map(group=><SharedHomeRow key={group.id} group={group} profileId={profileId} busy={busy===group.id} onRespond={respond} onPay={pay} onStartRent={startRent} onOpenConversation={onOpenConversation} onOpenListing={onOpenListing}/>)}</div></section>
}

function SharedHomeRow({group,profileId,busy,onRespond,onPay,onStartRent,onOpenConversation,onOpenListing}:{group:Group;profileId:string;busy:boolean;onRespond:(g:Group,a:boolean)=>void;onPay:(g:Group)=>void;onStartRent:(g:Group)=>void;onOpenConversation?:(id:string)=>void;onOpenListing?:(id:string)=>void}){
  const mine=group.members.find(m=>m.user_id===profileId),peer=group.members.find(m=>m.user_id!==profileId),invited=mine?.invitation_status==='invited',canPay=mine?.invitation_status==='accepted'&&mine.payment_status!=='paid'&&['ready','payment_pending'].includes(group.status),allReservationPaid=group.payment_phase==='reservation_fee'&&group.status==='paid'&&Boolean(group.reservation_id),label=stage(group,mine);
  return <article className="py-4"><div className="flex gap-3">{group.listing.image?<img src={group.listing.image} alt="" className="h-20 w-20 shrink-0 rounded-2xl object-cover"/>:<div className="h-20 w-20 shrink-0 rounded-2xl bg-violet-500/10"/>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><button onClick={()=>onOpenListing?.(group.listing_id)} className="min-w-0 text-left"><p className="truncate text-sm font-semibold">{group.listing.title||"Shared home"}</p><p className="mt-1 truncate text-[9px] text-[#707687]">With {peer?.name||"your roommate"} · {[group.listing.city,group.listing.state].filter(Boolean).join(", ")}</p></button><span className="shrink-0 rounded-full bg-violet-500/10 px-2 py-1 text-[8px] font-semibold text-violet-300">{label}</span></div><p className="mt-3 text-[10px] text-[#959AAA]">Your share: ₦{Number(mine?.share_amount||0).toLocaleString()} · {mine?.payment_status==='paid'?"Paid":"Not paid"}</p></div></div><div className="mt-3 flex flex-wrap gap-2">{invited&&<><Action disabled={busy} primary onClick={()=>onRespond(group,true)}>Accept invitation</Action><Action disabled={busy} onClick={()=>onRespond(group,false)}>Decline</Action></>}{canPay&&<Action disabled={busy} primary onClick={()=>onPay(group)}>{busy?"Opening…":"Pay my share"}</Action>}{allReservationPaid&&group.created_by===profileId&&<Action disabled={busy} primary onClick={()=>onStartRent(group)}>Split rent equally</Action>}{group.conversation_id&&<Action onClick={()=>onOpenConversation?.(group.conversation_id!)}>Message roommate</Action>}{onOpenListing&&<Action onClick={()=>onOpenListing(group.listing_id)}>View property</Action>}</div></article>
}
function stage(group:Group,mine?:Member){if(mine?.invitation_status==='invited')return"Invitation";if(group.status==='cancelled')return"Cancelled";if(group.status==='expired')return"Expired";if(group.payment_phase==='complete')return"Paid";if(group.status==='paid'&&group.payment_phase==='reservation_fee')return"Reserved";if(group.payment_phase==='contract_rent')return"Rent split";if(group.status==='payment_pending')return"Paying shares";return"Agreeing"}
function Action({children,onClick,disabled,primary=false}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean;primary?:boolean}){return <button disabled={disabled} onClick={onClick} className={`min-h-10 rounded-xl px-4 text-[9px] font-semibold disabled:opacity-40 ${primary?"bg-violet-500 text-white":"border border-white/[.08] text-[#C1C5D0]"}`}>{children}</button>}
