import { useEffect,useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';

const STATUSES=['verification_paid','profile_under_review','verified','rejected','suspended'];
export default function StaffVerificationPanel(){const[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true);async function load(){setLoading(true);const batches=await Promise.all(STATUSES.map(status=>supabase.rpc('get_my_staff_worker_reviews',{p_status:status})));const failure=batches.find(result=>result.error)?.error;if(failure)toast.error(failure.message);setRows(batches.flatMap(result=>result.data||[]));setLoading(false)}useEffect(()=>{void load()},[]);async function change(status:string){if(!selected)return;const{error}=await supabase.rpc('review_my_staff_worker',{p_worker_id:selected.user_id,p_status:status});if(error)return toast.error(error.message);toast.success('Worker review updated');setSelected(null);void load()}if(loading)return <Empty text="Loading worker reviews…"/>;if(selected)return <div className="space-y-4"><button onClick={()=>setSelected(null)} className="text-[10px] font-semibold text-violet-400">← Back to workers</button><section className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4"><Head worker={selected}/><div className="mt-4 grid gap-3 sm:grid-cols-2"><Evidence label="Government ID" url={selected.worker_gov_id_url}/><Evidence label="Skill video" url={selected.worker_video_url}/></div><div className="mt-4 flex flex-wrap gap-2">{selected.worker_status==='verification_paid'&&<Action onClick={()=>void change('profile_under_review')}>Start review</Action>}{['verification_paid','profile_under_review'].includes(selected.worker_status)&&<><Action onClick={()=>void change('verified')}>Verify</Action><Action danger onClick={()=>void change('rejected')}>Reject</Action></>}{selected.worker_status==='verified'&&<Action danger onClick={()=>void change('suspended')}>Suspend</Action>}</div></section></div>;const queue=rows.filter(row=>['verification_paid','profile_under_review'].includes(row.worker_status)).length;return <div className="space-y-4"><div className="grid grid-cols-3 gap-3"><Metric label="Workers" value={rows.length}/><Metric label="Needs review" value={queue}/><Metric label="Verified" value={rows.filter(row=>row.worker_status==='verified').length}/></div>{rows.length?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map(worker=><button key={worker.user_id} onClick={()=>setSelected(worker)} className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4 text-left hover:border-violet-500/30"><Head worker={worker}/><p className="mt-3 text-[9px] font-semibold text-violet-400">Open evidence →</p></button>)}</div>:<Empty text="No worker review records yet."/>}</div>}
function Head({worker}:{worker:any}){return <div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold">{worker.full_name||worker.username||'Worker'}</p><span className="rounded-full bg-violet-500/10 px-2 py-1 text-[8px] capitalize text-violet-300">{String(worker.worker_status||'unknown').replace(/_/g,' ')}</span></div>}
function Evidence({label,url}:{label:string;url?:string}){return <div className="rounded-xl border border-white/[.06] p-3"><p className="text-[9px] font-semibold">{label}</p>{url?<a href={url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-[10px] text-violet-400">Open evidence →</a>:<p className="mt-2 text-[10px] text-red-300">Not supplied</p>}</div>}
function Action({children,onClick,danger=false}:{children:React.ReactNode;onClick:()=>void;danger?:boolean}){return <button onClick={onClick} className={`rounded-xl px-3 py-2 text-[10px] font-semibold ${danger?'bg-red-500/15 text-red-300':'bg-violet-500 text-white'}`}>{children}</button>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4"><p className="text-[9px] uppercase text-[#656B7D]">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] p-10 text-center text-[10px] text-[#6D7284]">{text}</div>}
