import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import { getMySupportConversations, type SupportThread } from "@/lib/supabase/support";
import type { Profile } from "@/types";

type Props = { profile: Profile; compact?: boolean };

export default function SupportEntryCard({ compact = false }: Props) {
  const [threads,setThreads]=useState<SupportThread[]>([]),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{const{conversations}=await getMySupportConversations();setThreads(conversations||[]);setLoading(false)},[]);
  useEffect(()=>{const initial=window.setTimeout(()=>void load(),0),timer=window.setInterval(()=>void load(),15000);return()=>{window.clearTimeout(initial);window.clearInterval(timer)}},[load]);
  useEffect(()=>{const channel=supabase.channel('support-entry-all').on('postgres_changes',{event:'*',schema:'public',table:'partner_support_messages'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'partner_support_conversations'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load]);
  const ordered=useMemo(()=>[...threads].sort((a,b)=>new Date(b.last_message_time||b.created_at||0).getTime()-new Date(a.last_message_time||a.created_at||0).getTime()),[threads]);
  function open(thread?:SupportThread){window.dispatchEvent(new CustomEvent('openSupportChat',{detail:thread?{conversationId:thread.conversation_id,contextType:thread.context_type,contextId:thread.context_id}:undefined}))}
  if(loading&&compact)return <div className="px-4 py-4 text-[10px] text-[#666C7C]">Loading help conversations…</div>;
  if(!ordered.length)return <SupportRow compact={compact} title="WeHouse Help" preview="Message a real WeHouse support team member." meta="A case starts only after you send" unread={0} time={null} onOpen={()=>open()}/>;
  return <div>{ordered.map((thread,index)=><div key={thread.conversation_id}>{index>0&&<div className="ml-[4.5rem] h-px bg-white/[.05]"/>}<SupportRow compact={compact} title={deskTitle(thread)} preview={thread.last_message||'Open this help case'} meta={`${friendly(thread.context_type)} · ${thread.status==='open'?'Open case':friendly(thread.status)}`} unread={Number(thread.unread_count||0)} time={thread.last_message_time||thread.created_at} onOpen={()=>open(thread)}/></div>)}<button type="button" onClick={()=>open()} className="flex min-h-11 w-full items-center justify-center border-t border-white/[.05] px-4 text-[9px] font-semibold text-violet-300">Start a different help case</button></div>;
}

function SupportRow({compact,title,preview,meta,unread,time,onOpen}:{compact:boolean;title:string;preview:string;meta:string;unread:number;time:string|null;onOpen:()=>void}){return <button onClick={onOpen} className={compact?'flex w-full items-center gap-3 px-4 py-3.5 text-left transition hover:bg-white/[.025]':'flex w-full items-center gap-3 rounded-2xl border border-white/[.06] bg-[#11141C] p-4 text-left transition hover:border-violet-500/20'}><div className="relative grid h-12 w-12 shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-600 font-bold text-white shadow-lg shadow-violet-500/10">S<span className="absolute bottom-0 right-0 h-3.5 w-3.5 rounded-full border-2 border-[#11141C] bg-emerald-400"/></div><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-white">{title}</p><p className={`mt-1 truncate text-[11px] ${unread?'font-medium text-[#E3E5EB]':'text-[#777C8D]'}`}>{preview}</p><p className="mt-0.5 truncate text-[9px] text-[#5F6474]">{meta}</p></div><div className="shrink-0 self-start pt-0.5 text-right">{time&&<p className={`text-[8px] ${unread?'text-violet-300':'text-[#555A6B]'}`}>{formatTime(time)}</p>}{unread>0&&<span className="ml-auto mt-2 grid h-5 min-w-5 place-items-center rounded-full bg-violet-500 px-1 text-[8px] font-bold text-white">{unread>99?'99+':unread}</span>}</div></button>}
function deskTitle(thread:SupportThread){return ['apartment_reservation','reservation','hotel_booking'].includes(thread.context_type)?'Reservation Help':thread.context_type==='worker_booking'?'Worker Booking Help':thread.context_type==='property_inspection'?'Property Help':'WeHouse Help'}
function friendly(value:string){return String(value||'general').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function formatTime(value:string){const d=new Date(value),now=new Date();if(d.toDateString()===now.toDateString())return d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const days=Math.floor((now.getTime()-d.getTime())/86400000);if(days===1)return'Yesterday';if(days<7)return d.toLocaleDateString([],{weekday:'short'});return d.toLocaleDateString([],{month:'short',day:'numeric'})}
