import { useCallback,useEffect,useRef,useState } from 'react';
import { toast } from 'sonner';
import SecureSupportAttachment from '@/components/SecureSupportAttachment';
import WeHouseGuide from '@/components/WeHouseGuide';
import { supabase } from '@/lib/supabase';
import {
  deleteSupportAttachment,
  ensureSupportConversation,
  getMySupportConversations,
  getSupportMessages,
  markSupportMessagesRead,
  sendSupportMessage,
  uploadSupportAttachment,
  type SupportOpenContext,
  type SupportThread,
} from '@/lib/supabase/support';

interface ChatProfile{user_id:string;username:string|null;email:string;role?:string}
interface Props{profile:ChatProfile|null}
const MAX_FILES=6,MAX_FILE_SIZE=25*1024*1024;

export default function SupportChat({profile}:Props){
 const[open,setOpen]=useState(false),[thread,setThread]=useState<SupportThread|null>(null),[messages,setMessages]=useState<any[]>([]),[loading,setLoading]=useState(false),[input,setInput]=useState(''),[sending,setSending]=useState(false),[files,setFiles]=useState<File[]>([]),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[pendingContext,setPendingContext]=useState<SupportOpenContext|null>(null);
 const fileRef=useRef<HTMLInputElement>(null),mediaRef=useRef<MediaRecorder|null>(null),chunksRef=useRef<Blob[]>([]),bottomRef=useRef<HTMLDivElement>(null),inputRef=useRef<HTMLTextAreaElement>(null);

 const loadMessages=useCallback(async(id:string,quiet=false)=>{if(!quiet)setLoading(true);const{messages:data,error}=await getSupportMessages(id);if(error&&!quiet)toast.error(error.message||'Unable to load support messages');if(!error)setMessages(data||[]);await markSupportMessagesRead(id);if(!quiet)setLoading(false)},[]);
 const refreshThread=useCallback(async()=>{const{conversations}=await getMySupportConversations();const current=conversations?.[0]||null;setThread(current);return current},[]);
 const openConversation=useCallback(async(context?:SupportOpenContext)=>{if(!profile)return;setOpen(true);setPendingContext(context&&hasContext(context)?context:null);setLoading(true);const{conversationId,error}=await ensureSupportConversation(context||{});if(error||!conversationId){setLoading(false);toast.error(error?.message||'Unable to open WeHouse Support');return}const current=await refreshThread();setThread(current||null);await loadMessages(conversationId,true);setLoading(false);requestAnimationFrame(()=>inputRef.current?.focus())},[profile?.user_id,loadMessages,refreshThread]);

 useEffect(()=>{const handler=(event:Event)=>{const detail=((event as CustomEvent<SupportOpenContext>).detail||{});void openConversation(detail)};window.addEventListener('openSupportChat',handler as EventListener);return()=>window.removeEventListener('openSupportChat',handler as EventListener)},[openConversation]);
 useEffect(()=>{if(!thread?.conversation_id||!open)return;const id=thread.conversation_id;const channel=supabase.channel(`human-support:${id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'partner_support_messages',filter:`conversation_id=eq.${id}`},()=>{void loadMessages(id,true);void refreshThread()}).subscribe();return()=>{void supabase.removeChannel(channel)}},[thread?.conversation_id,open,loadMessages,refreshThread]);
 useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length,open]);
 useEffect(()=>{if(!recording){setSeconds(0);return}const timer=window.setInterval(()=>setSeconds(v=>v+1),1000);return()=>window.clearInterval(timer)},[recording]);

 function addFiles(list:FileList|null){if(!list)return;const valid=Array.from(list).filter(file=>{if(file.size>MAX_FILE_SIZE){toast.error(`${file.name} is larger than 25MB`);return false}return true});setFiles(current=>{const next=[...current,...valid].slice(0,MAX_FILES);if(current.length+valid.length>MAX_FILES)toast.error('A maximum of 6 files can be sent at once');return next});if(fileRef.current)fileRef.current.value=''}
 async function send(){if(!thread||sending||(!input.trim()&&!files.length))return;setSending(true);const paths:string[]=[],types:string[]=[];for(const file of files){const uploaded=await uploadSupportAttachment(thread.conversation_id,file);if(uploaded.error||!uploaded.path){for(const path of paths)await deleteSupportAttachment(path);setSending(false);return toast.error(uploaded.error?.message||`Could not upload ${file.name}`)}paths.push(uploaded.path);types.push(file.type||'application/octet-stream')}const{error}=await sendSupportMessage(thread.conversation_id,input.trim(),paths,types,pendingContext);if(error){for(const path of paths)await deleteSupportAttachment(path);setSending(false);return toast.error(error.message||'Message failed')}setInput('');setFiles([]);setPendingContext(null);setSending(false);await loadMessages(thread.conversation_id,true);void refreshThread()}
 async function toggleVoice(){if(recording){mediaRef.current?.stop();return}if(files.length>=MAX_FILES)return toast.error('Remove a file before recording a voice note');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunksRef.current=[];recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data)};recorder.onstop=()=>{const type=recorder.mimeType||'audio/webm';const blob=new Blob(chunksRef.current,{type});const ext=type.includes('mp4')?'m4a':'webm';setFiles(current=>[...current,new File([blob],`voice-${Date.now()}.${ext}`,{type})].slice(0,MAX_FILES));stream.getTracks().forEach(t=>t.stop());setRecording(false)};mediaRef.current=recorder;recorder.start();setRecording(true)}catch{toast.error('Microphone permission is required for voice messages')}}
 if(!profile)return null;
 if(!open)return <WeHouseGuide profile={profile}/>;

 return <div className="fixed inset-0 z-[100] flex h-[100dvh] flex-col overflow-hidden bg-[#090C11] text-white"><header className="shrink-0 border-b border-white/[.06] bg-[#10141B]/95 px-3 py-2.5 backdrop-blur-xl sm:px-4"><div className="mx-auto flex max-w-4xl items-center gap-3"><button onClick={()=>{setOpen(false);setFiles([]);setPendingContext(null)}} aria-label="Close support" className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-[#9DA3B2] hover:bg-white/[.05]">←</button><div className="relative grid h-11 w-11 shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-600 font-bold">S<span className="absolute bottom-0 right-0 h-3.5 w-3.5 rounded-full border-2 border-[#10141B] bg-emerald-400"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><p className="truncate text-[14px] font-semibold">WeHouse Support</p><span className="grid h-4 w-4 place-items-center rounded-full bg-blue-400 text-[9px] font-bold">✓</span></div><p className="mt-0.5 truncate text-[9px] text-[#747A8B]">{thread?.assigned_staff_name?`Human support · ${thread.assigned_staff_name}`:'Human support · a team member will reply here'}</p></div></div></header>

 <main className="min-h-0 flex-1 overflow-y-auto bg-[radial-gradient(circle_at_top,rgba(124,58,237,.05),transparent_34%)] px-3 py-4 sm:px-5"><div className="mx-auto max-w-4xl">{loading?<div className="grid min-h-[55vh] place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>:messages.length===0?<Welcome/>:<div className="space-y-2.5">{messages.map(msg=><MessageBubble key={msg.id} msg={msg} mine={msg.sender_id===profile.user_id}/>)}</div>}<div ref={bottomRef}/></div></main>

 <footer className="shrink-0 border-t border-white/[.06] bg-[#10141B]/98 px-2.5 pb-[max(.65rem,env(safe-area-inset-bottom))] pt-2.5 sm:px-4"><div className="mx-auto max-w-4xl">{pendingContext&&hasContext(pendingContext)&&<PendingContext context={pendingContext} onRemove={()=>setPendingContext(null)}/>} {files.length>0&&<div className="mb-2 flex gap-2 overflow-x-auto pb-1">{files.map((file,index)=><div key={`${file.name}-${index}`} className="flex shrink-0 items-center gap-2 rounded-xl border border-violet-500/15 bg-violet-500/[.06] px-3 py-2"><p className="max-w-40 truncate text-[9px] text-violet-200">{file.type.startsWith('audio/')?'🎤 ':''}{file.name}</p><button onClick={()=>setFiles(current=>current.filter((_,i)=>i!==index))} className="text-[#8D91A1]">×</button></div>)}</div>}{recording&&<div className="mb-2 flex items-center gap-2 rounded-xl bg-red-500/[.08] px-3 py-2 text-[10px] text-red-200"><span className="h-2 w-2 animate-pulse rounded-full bg-red-400"/>Recording voice <span className="font-mono">{duration(seconds)}</span><span className="ml-auto text-[9px] text-red-300/70">Tap mic to finish</span></div>}<div className="flex items-end gap-2"><button onClick={()=>fileRef.current?.click()} className="grid h-11 w-11 shrink-0 place-items-center rounded-full text-[#9AA0B1] hover:bg-white/[.05]" aria-label="Attach file">＋</button><input ref={fileRef} type="file" multiple accept="image/*,application/pdf,text/plain,.doc,.docx,audio/*" onChange={e=>addFiles(e.target.files)} className="hidden"/><div className="flex min-h-11 flex-1 items-end rounded-[22px] border border-white/[.07] bg-[#1A1F28] px-3 py-1.5 focus-within:border-violet-500/35"><textarea ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} rows={1} placeholder="Message WeHouse Support" className="max-h-28 min-h-8 flex-1 resize-none bg-transparent py-1.5 text-[13px] leading-5 outline-none placeholder:text-[#62697A]"/></div>{input.trim()||files.length?<button onClick={()=>void send()} disabled={sending} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-violet-500 text-white disabled:opacity-40" aria-label="Send">➤</button>:<button onClick={()=>void toggleVoice()} className={`grid h-11 w-11 shrink-0 place-items-center rounded-full ${recording?'bg-red-500':'bg-violet-500'} text-white`} aria-label={recording?'Stop recording':'Record voice'}><MicIcon/></button>}</div></div></footer></div>
}

function MessageBubble({msg,mine}:{msg:any;mine:boolean}){const meta=msg.action_metadata||{};return <div className={`flex ${mine?'justify-end':'justify-start'}`}><div className={`max-w-[88%] sm:max-w-[72%] ${mine?'items-end':'items-start'} flex flex-col`}>{meta&&Object.keys(meta).length>0&&<MessageContext meta={meta} type={msg.action_type}/>}<div className={`rounded-[19px] px-3.5 py-2.5 ${mine?'rounded-br-md bg-violet-500 text-white':'rounded-bl-md border border-white/[.06] bg-[#171B24] text-[#E4E6EC]'}`}>{!mine&&<p className="mb-1 text-[9px] font-semibold text-violet-300">{msg.sender_name||'WeHouse Support'}</p>}{(msg.attachments||[]).map((path:string,i:number)=><SecureSupportAttachment key={`${msg.id}-${path}`} path={path} type={msg.attachment_types?.[i]||''}/>)}{msg.content&&<p className="whitespace-pre-wrap text-[12px] leading-5">{msg.content}</p>}<p className={`mt-1 text-[8px] ${mine?'text-violet-100/65':'text-[#606677]'}`}>{formatTime(msg.created_at)}</p></div></div></div>}
function MessageContext({meta,type}:{meta:any;type?:string}){const snap=meta.context_snapshot||{};const ref=meta.context_id;const label=String(meta.subject||type||meta.context_type||'Linked WeHouse item').replace(/_/g,' ');return <div className="mb-1.5 w-full max-w-sm rounded-2xl border border-blue-500/15 bg-blue-500/[.055] p-3 text-left"><div className="flex items-center justify-between gap-3"><p className="truncate text-[10px] font-semibold capitalize text-blue-200">{label}</p>{ref&&<span className="shrink-0 rounded-full bg-blue-500/10 px-2 py-1 text-[8px] text-blue-300">Ref {String(ref).slice(0,18)}</span>}</div>{Object.keys(snap).length>0&&<div className="mt-2 grid gap-1 text-[9px] text-[#8FA0B9] sm:grid-cols-2">{Object.entries(snap).slice(0,6).map(([k,v])=><p key={k} className="truncate"><span className="capitalize text-[#66758C]">{k.replace(/_/g,' ')}:</span> {String(v??'')}</p>)}</div>}</div>}
function PendingContext({context,onRemove}:{context:SupportOpenContext;onRemove:()=>void}){return <div className="mb-2 flex items-start gap-3 rounded-2xl border border-blue-500/15 bg-blue-500/[.055] p-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-blue-500/10 text-blue-300">↗</div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-semibold text-blue-200">{context.subject||String(context.contextType||'Linked WeHouse item').replace(/_/g,' ')}</p><p className="mt-1 truncate text-[9px] text-[#6F7F97]">This reference will be attached to your next message{context.contextId?` · ${context.contextId}`:''}.</p></div><button onClick={onRemove} className="text-[#758096]">×</button></div>}
function Welcome(){return <div className="grid min-h-[55vh] place-items-center px-5 text-center"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-violet-500/10 text-xl font-bold text-violet-300">S</div><h2 className="mt-4 text-base font-semibold">Message WeHouse Support</h2><p className="mx-auto mt-2 max-w-sm text-[11px] leading-5 text-[#747A8B]">This is one continuous conversation with the human support team. Send text, photos, documents or voice notes. When you open Support from a booking, inspection or payment, that item is attached to the message automatically.</p></div></div>}
function hasContext(value:SupportOpenContext){return Boolean(value.contextId||value.contextType&&value.contextType!=='general'||value.contextSnapshot&&Object.keys(value.contextSnapshot).length)}
function formatTime(value:string){return new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function duration(value:number){return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`}
function MicIcon(){return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v5M8 22h8"/></svg>}
