import { useCallback, useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';

type Row={id:string;full_name:string|null;email:string|null;phone:string|null;interest:string;city:string|null;budget:number|null;status:string;notified:boolean;created_at:string};
const STATUSES=['waiting','contacted','invited','joined','archived'] as const;
const STATUS_COPY:Record<(typeof STATUSES)[number],{label:string;description:string}>={waiting:{label:'Waiting',description:'Signup received; no outreach yet.'},contacted:{label:'Contacted',description:'WeHouse has spoken with this person.'},invited:{label:'Early-access invite sent',description:'They were invited to create an account.'},joined:{label:'Became a member',description:'They created their WeHouse account.'},archived:{label:'Archived',description:'No further follow-up is planned.'}};
const INTERESTS=['all','housing','roommate','worker'] as const;

export default function WaitlistManagement(){
 const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[interest,setInterest]=useState('all'),[status,setStatus]=useState('all'),[updatingId,setUpdatingId]=useState<string|null>(null),[statusMenu,setStatusMenu]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.rpc('get_waitlist_signups',{p_search:search.trim()||null,p_interest:interest==='all'?null:interest,p_status:status==='all'?null:status});if(error)toast.error(error.message);setRows(Array.isArray(data)?data:[]);setLoading(false)},[search,interest,status]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(timer)},[load]);
 async function update(row:Row,nextStatus=row.status,nextNotified=row.notified){
  if(updatingId===row.id||(nextStatus===row.status&&nextNotified===row.notified))return;
  const previous=row;setUpdatingId(row.id);setStatusMenu(null);
  setRows(current=>current.map(item=>item.id===row.id?{...item,status:nextStatus,notified:nextNotified}:item));
  const{data,error}=await supabase.rpc('update_waitlist_signup',{p_id:row.id,p_status:nextStatus,p_notified:nextNotified});
  setUpdatingId(null);
  if(error){setRows(current=>current.map(item=>item.id===row.id?previous:item));return void toast.error(error.message,{id:'waitlist-'+row.id})}
  setRows(current=>current.map(item=>item.id===row.id?data as Row:item));
  toast.success('Waitlist updated',{id:'waitlist-'+row.id});
 }
 const summary=useMemo(()=>({total:rows.length,housing:rows.filter(r=>r.interest==='housing').length,roommate:rows.filter(r=>r.interest==='roommate').length,worker:rows.filter(r=>r.interest==='worker').length}),[rows]);
 return <div className="space-y-5">
  <section><p className="text-[9px] font-bold uppercase tracking-[.18em] text-violet-300">PRE-LAUNCH DEMAND</p><h2 className="mt-2 text-xl font-bold">Waitlist</h2><p className="mt-1 text-[10px] text-[#707687]">See what people need, where they need it and whether they have been contacted.</p></section>
  <section className="grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(summary).map(([label,value])=><div key={label} className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-[9px] capitalize text-[#676D7D]">{label}</p></div>)}</section>
  <section className="grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, contact or location" className="h-11 rounded-xl border border-white/[.08] bg-[#12151D] px-3 text-xs outline-none"/><select value={interest} onChange={e=>setInterest(e.target.value)} className="h-11 rounded-xl border border-white/[.08] bg-[#12151D] px-3 text-xs">{INTERESTS.map(value=><option key={value} value={value}>{value==='all'?'All needs':friendly(value)}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="h-11 rounded-xl border border-white/[.08] bg-[#12151D] px-3 text-xs"><option value="all">All follow-up stages</option>{STATUSES.map(value=><option key={value} value={value}>{STATUS_COPY[value].label}</option>)}</select></section>
  {loading?<Loading/>:rows.length===0?<Empty/>:<div className="grid gap-3 xl:grid-cols-2">{rows.map(row=><article key={row.id} className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{row.full_name||'Unnamed signup'}</p><p className="mt-1 truncate text-[9px] text-[#707687]">{row.email||row.phone||'No contact'} · {row.city||'Location not supplied'}</p></div><span className="rounded-full bg-violet-500/10 px-2 py-1 text-[8px] font-semibold text-violet-300">{friendly(row.interest)}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Info label="Budget" value={row.budget?`₦${Number(row.budget).toLocaleString('en-NG')}`:'Not supplied'}/><Info label="Waitlisted" value={new Date(row.created_at).toLocaleDateString()}/></div><div className="relative mt-3 flex gap-2"><button disabled={updatingId===row.id} onClick={()=>setStatusMenu(current=>current===row.id?null:row.id)} className="flex min-h-11 min-w-0 flex-1 items-center justify-between rounded-xl border border-white/[.08] bg-[#151923] px-3 text-left text-[10px] disabled:opacity-40"><span><span className="block font-semibold">{updatingId===row.id?'Updating…':statusLabel(row.status)}</span><span className="mt-0.5 block truncate text-[8px] text-[#686E7E]">{statusDescription(row.status)}</span></span><span>⌄</span></button><button disabled={updatingId===row.id} onClick={()=>void update(row,row.status,!row.notified)} className={`h-11 rounded-xl px-3 text-[10px] font-semibold disabled:opacity-40 ${row.notified?'bg-emerald-500/10 text-emerald-300':'border border-white/[.08] text-[#8B91A1]'}`}>{row.notified?'Notification sent':'Mark notified'}</button>{statusMenu===row.id&&<div className="absolute bottom-14 left-0 z-20 w-64 overflow-hidden rounded-2xl border border-white/[.1] bg-[#191C25] p-1 shadow-2xl">{STATUSES.map(value=><button key={value} onClick={()=>void update(row,value,row.notified)} className={`flex min-h-14 w-full items-center justify-between rounded-xl px-3 text-left ${row.status===value?'bg-violet-500/15 text-violet-200':'text-[#A5AAB7]'}`}><span><span className="block text-[10px] font-semibold">{STATUS_COPY[value].label}</span><span className="mt-0.5 block text-[8px] text-[#747A8A]">{STATUS_COPY[value].description}</span></span>{row.status===value&&<span>✓</span>}</button>)}</div>}</div></article>)}</div>}
 </div>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.05] bg-black/10 p-3"><p className="text-[8px] uppercase tracking-wide text-[#5F6575]">{label}</p><p className="mt-1 truncate text-[10px] font-semibold">{value}</p></div>}
function Loading(){return <div className="grid min-h-40 place-items-center"><div className="h-7 w-7 animate-spin rounded-full border-2 border-violet-500 border-t-transparent"/></div>}
function Empty(){return <div className="rounded-2xl border border-dashed border-white/[.08] px-5 py-12 text-center"><p className="text-sm font-semibold">No waitlist signups found</p><p className="mt-1 text-[9px] text-[#666D7E]">Try another search or filter.</p></div>}
function friendly(value:string){return value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function statusLabel(value:string){return STATUS_COPY[value as keyof typeof STATUS_COPY]?.label||friendly(value)}
function statusDescription(value:string){return STATUS_COPY[value as keyof typeof STATUS_COPY]?.description||'Follow-up stage for this signup.'}
