import { useEffect,useMemo,useRef,useState } from 'react';
import { supabase } from '@/lib/supabase';

type Props={profile:{role?:string};onBack:()=>void};
type Msg={id:number;side:'assistant'|'me';text:string};
const QUICK=['Help me find a home','How do I book a Worker?','How does Roommate matching work?','When should I contact Human Support?'];

export default function WeHouseAssistantScreen({profile,onBack}:Props){
 const[input,setInput]=useState(''),[sending,setSending]=useState(false),[messages,setMessages]=useState<Msg[]>([{id:1,side:'assistant',text:'Hi — I’m the WeHouse Assistant. I can guide you around WeHouse, explain features and help you find the right next step.'}]);
 const bottomRef=useRef<HTMLDivElement>(null),nextId=useRef(2);const role=profile.role||'user';
 const context=useMemo(()=>role==='worker'?'Ask about your Worker profile, jobs, verification, payments or WeHouse features.':role==='property_partner'?'Ask about properties, inspections, publication, finance or WeHouse features.':'Ask about homes, Short Stay, Long Stay, Workers, Roommates, reservations or WeHouse features.',[role]);
 useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length,sending]);
 async function ask(raw?:string){const question=(raw??input).trim();if(!question||sending)return;const history=messages.filter(m=>m.id!==1).slice(-10).map(m=>({role:m.side==='me'?'user':'assistant',content:m.text}));setMessages(current=>[...current,{id:nextId.current++,side:'me',text:question}]);setInput('');setSending(true);try{const{data,error}=await supabase.functions.invoke('wehouse-assistant',{body:{message:question,messages:history}});const text=String(data?.message||'').trim();setMessages(current=>[...current,{id:nextId.current++,side:'assistant',text:error||!text?'WeHouse Assistant is unavailable right now. Human Support can still help with account-specific issues.':text}])}catch{setMessages(current=>[...current,{id:nextId.current++,side:'assistant',text:'WeHouse Assistant is unavailable right now. Human Support can still help with account-specific issues.'}])}finally{setSending(false)}}
 function humanSupport(){window.dispatchEvent(new CustomEvent('openSupportChat',{detail:{category:'general',contextType:'general'}}))}
 return <div className="flex h-[100dvh] min-h-0 flex-col overflow-hidden bg-[#090B10] text-white">
  <header className="shrink-0 border-b border-white/[.06] bg-[#0D1016]/96 px-2.5 pb-2 pt-[max(.6rem,env(safe-area-inset-top))] backdrop-blur-xl sm:px-4"><div className="mx-auto flex max-w-3xl items-center gap-2"><button onClick={onBack} className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-xl text-[#A2A7B5] active:bg-white/[.05]">‹</button><div className="relative grid h-10 w-10 shrink-0 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-indigo-600"><AssistantIcon/><span className="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[#0D1016] bg-emerald-400"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><h1 className="truncate text-[14px] font-semibold">WeHouse Assistant</h1><span className="rounded-full bg-blue-500/10 px-1.5 py-0.5 text-[7px] font-semibold text-blue-300">AI</span></div><p className="mt-0.5 truncate text-[8px] text-[#6F7586]">Product guidance · not Human Support</p></div><button onClick={humanSupport} className="rounded-full border border-violet-500/20 bg-violet-500/[.07] px-3 py-2 text-[9px] font-semibold text-violet-300">Support</button></div></header>
  <main className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-3 py-4 sm:px-4"><div className="mx-auto max-w-3xl"><div className="mb-5 text-center"><p className="text-[9px] text-[#676E80]">{context}</p></div><div className="space-y-1.5">{messages.map((msg,index)=>{const previous=messages[index-1];const grouped=previous?.side===msg.side;return <div key={msg.id} className={`flex ${msg.side==='me'?'justify-end':'justify-start'} ${grouped?'mt-1':'mt-3'}`}><div className={`max-w-[82%] rounded-[20px] px-3.5 py-2.5 text-[12px] leading-[1.45] sm:max-w-[72%] ${msg.side==='me'?'rounded-br-[6px] bg-violet-500 text-white':'rounded-bl-[6px] bg-[#171B23] text-[#E5E7ED]'}`}>{msg.text}</div></div>})}{sending&&<div className="mt-2 flex justify-start"><div className="flex gap-1 rounded-[20px] rounded-bl-[6px] bg-[#171B23] px-4 py-3"><Dot/><Dot delay="120ms"/><Dot delay="240ms"/></div></div>}<div ref={bottomRef}/></div></div></main>
  <footer className="shrink-0 border-t border-white/[.06] bg-[#0D1016]/98 px-2.5 pb-[max(.55rem,env(safe-area-inset-bottom))] pt-2 sm:px-4"><div className="mx-auto max-w-3xl">{messages.length<=2&&<div className="mb-2 flex gap-2 overflow-x-auto pb-1 scrollbar-hide">{QUICK.map(item=><button key={item} onClick={()=>void ask(item)} className="shrink-0 rounded-full border border-white/[.07] bg-white/[.035] px-3 py-2 text-[9px] text-[#B7BBC6]">{item}</button>)}</div>}<div className="flex items-end gap-2"><div className="min-h-11 flex-1 rounded-[22px] border border-white/[.08] bg-[#181C24] px-3 py-1.5 focus-within:border-violet-500/35"><textarea rows={1} value={input} disabled={sending} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask()}}} placeholder="Ask WeHouse Assistant" className="max-h-28 min-h-8 w-full resize-none bg-transparent py-1.5 text-[13px] leading-5 outline-none placeholder:text-[#5D6475]"/></div><button onClick={()=>void ask()} disabled={sending||!input.trim()} aria-label="Send" className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-violet-500 text-white disabled:bg-white/[.06] disabled:text-[#565C6C]"><SendIcon/></button></div></div></footer>
 </div>
}
function Dot({delay='0ms'}:{delay?:string}){return <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#868D9D]" style={{animationDelay:delay}}/>}
function AssistantIcon(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/><circle cx="12" cy="12" r="4"/></svg>}
function SendIcon(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m4 4 16 8-16 8 3-8-3-8Z"/><path d="M7 12h13"/></svg>}
