import { useEffect,useMemo,useRef,useState } from 'react';

type Props={profile:{role?:string};onBack:()=>void};
type Msg={id:number;side:'assistant'|'me';text:string};
const QUICK=['Help me find a home','How do I book a Worker?','How does Roommate matching work?','Explain Short Let and Long Let'];

export default function WeHouseAssistantScreen({profile,onBack}:Props){
 const[input,setInput]=useState(''),[sending,setSending]=useState(false),[messages,setMessages]=useState<Msg[]>([{id:1,side:'assistant',text:'Ask me anything about WeHouse. I can explain Homes, Short Let, Long Let, Roommates, Local Service Workers, bookings, verification, payments and other WeHouse features.'}]);
 const bottomRef=useRef<HTMLDivElement>(null),nextId=useRef(2);const role=profile.role||'user';
 const context=useMemo(()=>role==='worker'?'WeHouse questions only · Worker profile, jobs, verification, payments and platform features':role==='property_partner'?'WeHouse questions only · properties, inspections, publication, finance and platform features':'WeHouse questions only · homes, stays, Roommates, Workers, reservations and platform features',[role]);
 useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length,sending]);
 async function ask(raw?:string){const question=(raw??input).trim();if(!question||sending)return;setMessages(current=>[...current,{id:nextId.current++,side:'me',text:question}]);setInput('');setSending(true);await Promise.resolve();setMessages(current=>[...current,{id:nextId.current++,side:'assistant',text:weHouseAnswer(question,role)}]);setSending(false)}
 return <div className="flex h-[100dvh] min-h-0 flex-col overflow-hidden bg-[#090B10] text-white">
  <header className="shrink-0 border-b border-white/[.06] bg-[#0D1016]/96 px-2.5 pb-2 pt-[max(.6rem,env(safe-area-inset-top))] backdrop-blur-xl sm:px-4"><div className="mx-auto flex max-w-3xl items-center gap-2"><button onClick={onBack} className="grid h-10 w-10 shrink-0 place-items-center rounded-full text-xl text-[#A2A7B5] active:bg-white/[.05]">‹</button><div className="relative grid h-10 w-10 shrink-0 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-indigo-600"><AssistantIcon/><span className="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[#0D1016] bg-emerald-400"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><h1 className="truncate text-[14px] font-semibold">WeHouse Assistant</h1><span className="rounded-full bg-blue-500/10 px-1.5 py-0.5 text-[7px] font-semibold text-blue-300">AI</span></div><p className="mt-0.5 truncate text-[8px] text-[#6F7586]">WeHouse questions only</p></div></div></header>
  <main className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-3 py-4 sm:px-4"><div className="mx-auto max-w-3xl"><div className="mb-5 rounded-2xl border border-blue-500/10 bg-blue-500/[.035] px-4 py-3 text-center"><p className="text-[9px] leading-relaxed text-[#788094]">{context}</p><p className="mt-1 text-[8px] text-[#596173]">Human Support is a separate conversation in Messages for account-specific help.</p></div><div className="space-y-1.5">{messages.map((msg,index)=>{const previous=messages[index-1];const grouped=previous?.side===msg.side;return <div key={msg.id} className={`flex ${msg.side==='me'?'justify-end':'justify-start'} ${grouped?'mt-1':'mt-3'}`}><div className={`max-w-[82%] rounded-[20px] px-3.5 py-2.5 text-[12px] leading-[1.45] sm:max-w-[72%] ${msg.side==='me'?'rounded-br-[6px] bg-violet-500 text-white':'rounded-bl-[6px] bg-[#171B23] text-[#E5E7ED]'}`}>{msg.text}</div></div>})}{sending&&<div className="mt-2 flex justify-start"><div className="flex gap-1 rounded-[20px] rounded-bl-[6px] bg-[#171B23] px-4 py-3"><Dot/><Dot delay="120ms"/><Dot delay="240ms"/></div></div>}<div ref={bottomRef}/></div></div></main>
  <footer className="shrink-0 border-t border-white/[.06] bg-[#0D1016]/98 px-2.5 pb-[max(.55rem,env(safe-area-inset-bottom))] pt-2 sm:px-4"><div className="mx-auto max-w-3xl">{messages.length<=2&&<div className="mb-2 flex gap-2 overflow-x-auto pb-1 scrollbar-hide">{QUICK.map(item=><button key={item} onClick={()=>void ask(item)} className="shrink-0 rounded-full border border-white/[.07] bg-white/[.035] px-3 py-2 text-[9px] text-[#B7BBC6]">{item}</button>)}</div>}<label className="mb-1.5 block px-1 text-[8px] font-semibold uppercase tracking-[.12em] text-[#62697A]">Ask your own WeHouse question</label><div className="flex items-end gap-2"><div className="min-h-11 flex-1 rounded-[22px] border border-white/[.08] bg-[#181C24] px-3 py-1.5 focus-within:border-violet-500/35"><textarea rows={1} value={input} disabled={sending} autoFocus onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask()}}} placeholder="Type a question about WeHouse…" className="max-h-28 min-h-8 w-full resize-none bg-transparent py-1.5 text-[13px] leading-5 outline-none placeholder:text-[#5D6475]"/></div><button onClick={()=>void ask()} disabled={sending||!input.trim()} aria-label="Send question" className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-violet-500 text-white disabled:bg-white/[.06] disabled:text-[#565C6C]"><SendIcon/></button></div></div></footer>
 </div>
}
function weHouseAnswer(question:string,role:string){const q=question.toLowerCase();if(/save|favourite|favorite/.test(q))return 'Tap the heart on a property to add it to Saved. Open Saved from the main navigation to find it again.';if(/reservation|reserved|book/.test(q)&&/home|house|property|rent/.test(q))return 'Open a property, choose the rental details and complete the reservation step. Your booking remains available under Account → My reservations.';if(/worker/.test(q)&&/book|hire|find/.test(q))return 'Open Explore → Professionals, choose a reviewed Worker and send a job request. Each job keeps its own status in your bookings.';if(/worker/.test(q)&&/(onboard|fee|verify|identity)/.test(q))return 'Worker onboarding has four separate parts: professional profile, private face check, one-time onboarding fee, and work evidence review. Payment never guarantees approval.';if(/roommate/.test(q))return 'Roommate matching uses your location, budget, gender preference, school option and living preferences. Chat opens only after the matching rules allow the connection.';if(/short/.test(q)&&/let|stay|rent/.test(q))return 'Short Let is furnished accommodation priced by night. Dates and any refundable property deposit are shown before payment.';if(/long/.test(q)&&/let|stay|rent/.test(q))return 'Long Let uses annual rent and a tenancy period. Your active reservation and payment steps remain under Account → My reservations.';if(/support|help/.test(q))return 'For an account-specific booking, payment or inspection problem, open WeHouse Support in Messages. The Assistant does not access private account records.';if(/property partner|listing|publish/.test(q))return role==='property_partner'?'Submit the property details and media from Property Requests. WeHouse inspection and preparation happen before Admin or Creator publication.':'Properties move through submission, inspection, preparation and authorized publication before users can reserve them.';return 'I can answer questions about WeHouse homes, Short Let, Long Let, Roommates, Workers, reservations, payments, Saved, listings and support. Please ask about one of those WeHouse features.'}
function Dot({delay='0ms'}:{delay?:string}){return <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-[#868D9D]" style={{animationDelay:delay}}/>}
function AssistantIcon(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/><circle cx="12" cy="12" r="4"/></svg>}
function SendIcon(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m4 4 16 8-16 8 3-8-3-8Z"/><path d="M7 12h13"/></svg>}
