import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';

type Props={profile:Profile;status?:string|null;rejectionReason?:string|null;onSaved:()=>Promise<void>|void};
type Stage='intro'|'loading'|'checking'|'failed'|'success';
type Step='center_start'|'side_one'|'side_two'|'center_end';
type Sample={similarity:number;live:number;real:number;yaw:number;pitch:number};
type RefData={has_reference?:boolean;photo_path?:string|null};
const MODULE='https://cdn.jsdelivr.net/npm/@vladmandic/human@3.3.6/dist/human.esm.js';
const MODELS='https://vladmandic.github.io/human-models/models/';
const LABEL:Record<Step,string>={center_start:'Look straight at the camera',side_one:'Slowly turn your head to one side',side_two:'Now turn to the other side',center_end:'Look straight again'};
const CENTER=.2,PITCH=.28,TURN=.27,POSE_MATCH=.45,FINAL_MATCH=.55,LIVE=.5,REAL=.5;

export default function WorkerIdentityCheckPhase10Live({profile,status,rejectionReason,onSaved}:Props){
 const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),humanRef=useRef<any>(null),embeddingRef=useRef<number[]|null>(null),photoRef=useRef<Blob|null>(null),pathRef=useRef<string|null>(null),cancelled=useRef(false);
 const[stage,setStage]=useState<Stage>('intro'),[consent,setConsent]=useState(false),[prompt,setPrompt]=useState(''),[hint,setHint]=useState(''),[step,setStep]=useState(0),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false),[renewal,setRenewal]=useState(status==='expired');
 useEffect(()=>()=>{cancelled.current=true;stopCamera()},[]);
 function stopCamera(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null}
 function currentCanvas(){const v=videoRef.current;if(!v||v.readyState<2)return null;const w=v.videoWidth||720,h=v.videoHeight||720,s=Math.min(w,h),c=document.createElement('canvas'),x=c.getContext('2d');c.width=s;c.height=s;if(!x)return null;x.drawImage(v,Math.max(0,(w-s)/2),Math.max(0,(h-s)/2),s,s,0,0,s,s);return c}
 async function human(){if(humanRef.current)return humanRef.current;setStage('loading');setPrompt('Preparing secure face check…');const mod:any=await import(/* @vite-ignore */ MODULE),Human=mod.default||mod.Human;if(!Human)throw new Error('Face-check engine could not load');const h=new Human({debug:false,backend:'webgl',modelBasePath:MODELS,filter:{enabled:true,equalization:false,flip:false},face:{enabled:true,detector:{enabled:true,rotation:true,maxDetected:1,minConfidence:.7},mesh:{enabled:true},iris:{enabled:false},description:{enabled:true},emotion:{enabled:false},antispoof:{enabled:true},liveness:{enabled:true}},body:{enabled:false},hand:{enabled:false},object:{enabled:false},gesture:{enabled:false},segmentation:{enabled:false}});await h.load();humanRef.current=h;return h}
 async function loadBaseline(){const{data,error}=await supabase.rpc('get_my_worker_identity_reference');if(error)throw error;const r=(data||{}) as RefData;if(!r.has_reference||!r.photo_path)return false;const signed=await supabase.storage.from('worker-identity-private').createSignedUrl(r.photo_path,300);if(signed.error||!signed.data?.signedUrl)throw new Error('Your enrolled Worker face could not be loaded');const c=await imageCanvas(signed.data.signedUrl),res=await humanRef.current.detect(c),face=res.face?.[0];if(res.face?.length!==1||!face?.embedding?.length)throw new Error('Your enrolled Worker face could not be read');embeddingRef.current=[...face.embedding];pathRef.current=r.photo_path;photoRef.current=null;setRenewal(true);return true}
 async function openCamera(){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera is not supported on this device');const s=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:1280},height:{ideal:1280},frameRate:{ideal:30,max:30}}});stopCamera();streamRef.current=s;setStage('checking');await frames();const v=videoRef.current;if(!v)throw new Error('Camera view could not open');v.srcObject=s;await v.play().catch(()=>undefined);await videoReady(v)}
 async function start(){if(!consent)return toast.error('Confirm the privacy notice first');if(busy)return;cancelled.current=false;setBusy(true);setFailure('');setHint('');setStep(0);try{await human();const existing=await loadBaseline();await openCamera();if(!existing)await enroll();await challenge()}catch(e:any){stopCamera();setFailure(e?.name==='NotAllowedError'?'Allow camera access to continue.':e?.message||'Face check could not start.');setStage('failed')}finally{setBusy(false)}}
 async function enroll(){setPrompt('Center your face in the oval');setHint('Good lighting. Keep the phone steady.');const began=Date.now();while(Date.now()-began<18000&&!cancelled.current){const c=currentCanvas();if(!c){await sleep(180);continue}const r=await humanRef.current.detect(c),f=r.face?.[0];if(r.face?.length!==1){setHint('Keep only your face in the frame.');await sleep(220);continue}const yaw=Math.abs(Number(f?.rotation?.angle?.yaw??99)),pitch=Math.abs(Number(f?.rotation?.angle?.pitch??99));if(!f?.embedding?.length||yaw>CENTER||pitch>PITCH||Number(f.score||0)<.7){setHint('Face forward and move into brighter light.');await sleep(220);continue}const blob=await new Promise<Blob|null>(resolve=>c.toBlob(resolve,'image/jpeg',.92));if(!blob)throw new Error('Could not prepare your private Worker selfie');embeddingRef.current=[...f.embedding];photoRef.current=blob;pathRef.current=null;setRenewal(false);setHint('Face captured. Follow the movement prompts.');await sleep(400);return}throw new Error('We could not get a clear centered face. Improve the lighting and try again.')}
 async function sample():Promise<Sample>{const v=videoRef.current,h=humanRef.current,ref=embeddingRef.current;if(!v||!h||!ref)throw new Error('Face reference is not ready');const r=await h.detect(v),f=r.face?.[0];if(r.face?.length!==1)throw new Error('Keep only your face in the frame');if(!f?.embedding?.length||!f.rotation)throw new Error('Keep your full face visible');return{similarity:Number(h.match.similarity(ref,f.embedding)),live:Number(f.live??0),real:Number(f.real??0),yaw:Number(f.rotation.angle.yaw??0),pitch:Number(f.rotation.angle.pitch??0)}}
 async function challenge(){const steps:Step[]=['center_start','side_one','side_two','center_end'],all:Sample[]=[],security:Sample[]=[];let current=0,stable=0,sideSign=0;const began=Date.now();while(current<steps.length&&!cancelled.current){if(Date.now()-began>42000)throw new Error('The face check timed out. Follow each movement slowly and try again.');const s=steps[current];setPrompt(LABEL[s]);setStep(current);let v:Sample;try{v=await sample()}catch{stable=0;setHint('Keep your full face inside the oval.');await sleep(210);continue}if(v.similarity<POSE_MATCH){stable=0;setHint('Keep the same face clearly visible.');await sleep(210);continue}const ay=Math.abs(v.yaw),ap=Math.abs(v.pitch);let ok=false;if(s==='center_start'||s==='center_end')ok=ay<=CENTER&&ap<=PITCH;if(s==='side_one')ok=ay>=TURN;if(s==='side_two')ok=ay>=TURN&&sideSign!==0&&Math.sign(v.yaw)===-sideSign;if(!ok){stable=0;setHint(s.includes('center')?'Face forward and hold still.':'Turn a little farther, slowly.');await sleep(180);continue}stable++;all.push(v);if(s==='center_start'||s==='center_end')security.push(v);if(stable>=2){if(s==='side_one')sideSign=Math.sign(v.yaw)||1;current++;stable=0;setHint(current<steps.length?'Good. Next movement…':'Checking…');await sleep(350)}await sleep(180)}if(cancelled.current)return;if(all.length<6||security.length<4)throw new Error('We could not collect enough clear face frames. Try again.');const match=median(all.map(v=>v.similarity)),live=median(security.map(v=>v.live)),real=median(security.map(v=>v.real));if(match<FINAL_MATCH)throw new Error('Your live face did not match the enrolled Worker closely enough.');if(live<LIVE||real<REAL)throw new Error('We could not confirm a live, real face. Use brighter light, remove screen glare and try again.');await save(match,live,real)}
 async function save(match:number,live:number,real:number){let path=pathRef.current,uploaded=false;if(!path){if(!photoRef.current)throw new Error('Private Worker face is missing');path=`${profile.user_id}/identity-enrollment-${Date.now()}.jpg`;const up=await supabase.storage.from('worker-identity-private').upload(path,photoRef.current,{contentType:'image/jpeg',upsert:false});if(up.error)throw up.error;uploaded=true}const{error}=await supabase.rpc('complete_my_worker_identity_check',{p_photo_path:path,p_face_match_score:match,p_liveness_score:live,p_anti_spoof_score:real,p_challenge_result:{center_start:true,side_one:true,side_two:true,center_end:true,automatic:true,recorded_video:false,renewal,original_face_reference:renewal},p_consent:true});if(error){if(uploaded)await supabase.storage.from('worker-identity-private').remove([path]);throw error}stopCamera();setPrompt('Identity confirmed');setHint('Your Worker verification is saved securely.');setStage('success');toast.success(renewal?'Identity re-check complete':'Private face check complete');await onSaved()}
 function retry(){stopCamera();embeddingRef.current=null;photoRef.current=null;pathRef.current=null;setFailure('');setPrompt('');setHint('');setStep(0);setStage('intro')}
 if(status==='passed')return <section className="rounded-2xl border border-emerald-500/15 bg-emerald-500/[.04] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-500/12 text-emerald-300">✓</span><div><p className="text-xs font-semibold text-emerald-300">Worker identity confirmed</p><p className="mt-1 text-[9px] text-[#747B8B]">The live check passed. No liveness video was stored.</p></div></div></section>;
 return <section className="overflow-hidden rounded-3xl border border-white/[.07] bg-[#0F131B] shadow-2xl shadow-black/20"><div className="border-b border-white/[.055] p-4 sm:p-5"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-violet-500/10 text-violet-300"><FaceIcon/></div><div><p className="text-[8px] font-bold uppercase tracking-[.18em] text-violet-300">PRIVATE IDENTITY CHECK</p><h3 className="mt-1 text-lg font-bold">{renewal?'Confirm it is still you':'Confirm your Worker identity'}</h3><p className="mt-1 text-[10px] leading-5 text-[#747C8E]">{renewal?'Your live face is compared with the original Worker face enrolled on this account.':'One guided camera session creates your private Worker face reference and checks that you are live.'}</p></div></div></div>
 {(stage==='checking'||stage==='loading')&&<div className="p-4 sm:p-5"><div className="relative mx-auto aspect-[3/4] max-h-[62dvh] w-full max-w-sm overflow-hidden rounded-[32px] bg-black"><video ref={videoRef} autoPlay muted playsInline className="h-full w-full scale-x-[-1] object-cover"/><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_42%_38%_at_50%_43%,transparent_0%,transparent_66%,rgba(0,0,0,.66)_67%,rgba(0,0,0,.86)_100%)]"/><div className="pointer-events-none absolute left-1/2 top-[43%] h-[52%] w-[62%] -translate-x-1/2 -translate-y-1/2 rounded-[50%] border-2 border-violet-300/80 shadow-[0_0_30px_rgba(167,139,250,.22)]"/><div className="absolute inset-x-4 bottom-4 rounded-2xl border border-white/10 bg-black/45 p-3 text-center backdrop-blur-xl"><p className="text-sm font-semibold">{prompt||'Preparing camera…'}</p><p className="mt-1 text-[9px] text-white/65">{hint||'Keep your face inside the oval.'}</p></div></div><div className="mx-auto mt-4 flex max-w-sm gap-2">{[0,1,2,3].map(i=><div key={i} className={`h-1.5 flex-1 rounded-full ${i<step?'bg-emerald-400':i===step?'bg-violet-400':'bg-white/[.08]'}`}/>)}</div><p className="mt-2 text-center text-[8px] uppercase tracking-[.15em] text-[#616879]">{stage==='loading'?'Loading secure camera check':`Movement ${step+1} of 4`}</p></div>}
 {stage==='intro'&&<div className="space-y-4 p-4 sm:p-5">{rejectionReason&&<div className="rounded-2xl border border-amber-500/15 bg-amber-500/[.05] p-3 text-[9px] text-amber-100">{rejectionReason}</div>}<div className="grid gap-2 sm:grid-cols-3"><Info icon="◉" title="Center your face" text="Good light, one person only."/><Info icon="↔" title="Follow the turns" text="Move slowly when prompted."/><Info icon="⌁" title="Nothing public" text="No liveness video is stored."/></div><label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-white/[.06] bg-black/10 p-3"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-0.5 h-4 w-4 accent-violet-500"/><span className="text-[9px] leading-5 text-[#818899]">I agree to a private automated face, liveness and anti-spoof check for Worker account protection. The enrollment selfie stays private.</span></label><button onClick={()=>void start()} disabled={!consent||busy} className="h-12 w-full rounded-2xl bg-violet-500 text-xs font-semibold disabled:bg-white/[.06] disabled:text-[#62697A]">{busy?'Starting…':renewal?'Start identity re-check':'Start face check'}</button><p className="text-center text-[8px] text-[#555D6D]">Front camera only. Uploaded photos cannot replace the liveness check.</p></div>}
 {stage==='failed'&&<div className="space-y-4 p-5 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-red-500/10 text-xl text-red-300">!</div><h4 className="text-base font-bold">We could not complete the check</h4><p className="mx-auto max-w-sm text-[10px] leading-5 text-[#858C9D]">{failure}</p><button onClick={retry} className="h-12 w-full rounded-2xl bg-violet-500 text-xs font-semibold">Try again</button></div>}
 {stage==='success'&&<div className="space-y-3 p-6 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-500/12 text-2xl text-emerald-300">✓</div><h4 className="text-lg font-bold">Identity confirmed</h4><p className="text-[10px] text-[#7B8394]">The result is saved. WeHouse is unlocking the next step.</p></div>}</section>
}
async function imageCanvas(url:string){const img=new Image();img.crossOrigin='anonymous';img.src=url;await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('Private identity image could not load'))});const w=img.naturalWidth||720,h=img.naturalHeight||720,s=Math.min(w,h),c=document.createElement('canvas'),x=c.getContext('2d');c.width=s;c.height=s;if(!x)throw new Error('Image could not be prepared');x.drawImage(img,Math.max(0,(w-s)/2),Math.max(0,(h-s)/2),s,s,0,0,s,s);return c}
function median(values:number[]){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}
function frames(){return new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())))}
function videoReady(v:HTMLVideoElement){return new Promise<void>((resolve,reject)=>{if(v.readyState>=2&&v.videoWidth>0)return resolve();const t=window.setTimeout(()=>{off();reject(new Error('Camera took too long to start'))},8000),ok=()=>{if(v.videoWidth>0){off();resolve()}},off=()=>{clearTimeout(t);v.removeEventListener('loadeddata',ok);v.removeEventListener('canplay',ok)};v.addEventListener('loadeddata',ok);v.addEventListener('canplay',ok)})}
function Info({icon,title,text}:{icon:string;title:string;text:string}){return <div className="rounded-2xl border border-white/[.055] bg-white/[.018] p-3"><span className="text-lg text-violet-300">{icon}</span><p className="mt-2 text-[10px] font-semibold">{title}</p><p className="mt-1 text-[8px] leading-4 text-[#6C7485]">{text}</p></div>}
function FaceIcon(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M8 3H6a3 3 0 0 0-3 3v2M16 3h2a3 3 0 0 1 3 3v2M8 21H6a3 3 0 0 1-3-3v-2M16 21h2a3 3 0 0 0 3-3v-2"/><circle cx="9" cy="10" r="1"/><circle cx="15" cy="10" r="1"/><path d="M8.5 15c2.2 1.6 4.8 1.6 7 0"/></svg>}
