import { useEffect, useMemo, useState } from 'react';
import GoldTickBadge from '@/components/GoldTickBadge';
import { supabase } from '@/lib/supabase';
import type { Profile } from '@/types';
import { workerOccupation, workerServiceNames } from '@/lib/workerTaxonomy';

type Props={profile:Profile;onEdit:()=>void;onVerification:()=>void};
type Trust={reviewed?:boolean;trusted?:boolean;trusted_enabled?:boolean;completed_jobs?:number;rating?:number;review_count?:number;worker_cancel_rate?:number;open_disputes?:number;label?:string};
type Coverage={state:string|null;lga:string|null;areas:string[]|null};
type Review={id:string;rating:number;comment?:string|null;reviewer_name:string;service_name:string;created_at:string};

export default function WorkerProfilePanelV3({profile,onEdit,onVerification}:Props){
 const[coverage,setCoverage]=useState<Coverage|null>(null),[trust,setTrust]=useState<Trust|null>(null),[reviews,setReviews]=useState<Review[]>([]),[loading,setLoading]=useState(true),[aboutOpen,setAboutOpen]=useState(false);
 useEffect(()=>{let active=true;void(async()=>{const[cov,trustResult,reviewResult]=await Promise.all([supabase.from('worker_service_coverage').select('state,lga,areas').eq('worker_id',profile.user_id).maybeSingle(),supabase.rpc('get_worker_marketplace_trust',{p_worker_id:profile.user_id}),supabase.rpc('get_public_worker_reviews',{p_worker_id:profile.user_id,p_limit:20})]);if(active){setCoverage((cov.data||null) as Coverage|null);setTrust((trustResult.data||null) as Trust|null);setReviews((reviewResult.data||[]) as Review[]);setLoading(false)}})();return()=>{active=false}},[profile.user_id]);
 const occupation=workerOccupation(profile),skills=workerServiceNames(profile),status=String(profile.worker_status||'pending'),live=status==='verified'&&profile.worker_verified===true,paymentConfirmedVisual=['verification_paid','profile_under_review','verified'].includes(status),location=[coverage?.lga||profile.local_government||profile.city,coverage?.state||profile.state].filter(Boolean).join(', ')||'Work location not set',cleanAbout=useMemo(()=>cleanWorkerBio(profile.worker_bio||''),[profile.worker_bio]),aboutIsLong=cleanAbout.length>320,trusted=trust?.trusted===true;
 return <div className="space-y-4"><section className="overflow-hidden rounded-3xl border border-white/[.07] bg-[#10131B]"><div className="h-20 bg-gradient-to-r from-violet-600/35 via-violet-500/15 to-transparent"/><div className="px-4 pb-4 sm:px-5 sm:pb-5"><div className="-mt-9 flex items-end justify-between gap-3"><div className="grid h-[72px] w-[72px] shrink-0 place-items-center overflow-hidden rounded-2xl border-4 border-[#10131B] bg-gradient-to-br from-violet-500 to-violet-600 text-2xl font-bold">{profile.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:(profile.full_name||profile.username||'W')[0].toUpperCase()}</div><StatusBadge status={status} live={live} trusted={trusted}/></div><div className="mt-3"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate text-xl font-bold sm:text-2xl">{profile.full_name||profile.username||'Your profile'}</h2>{paymentConfirmedVisual&&<GoldTickBadge title="Gold Tick · verification payment confirmed"/>}</div><p className="mt-1 text-xs font-medium text-[#AEB3C1]">{occupation}</p><p className="mt-1 text-[10px] text-[#6F7585]">{location}</p></div><div className="mt-4 flex gap-2"><button onClick={onEdit} className="h-11 flex-1 rounded-xl bg-violet-500 px-4 text-[11px] font-semibold">Edit profile</button>{!live?<button onClick={onVerification} className="h-11 flex-1 rounded-xl border border-white/[.08] bg-white/[.025] px-4 text-[11px] font-semibold">Continue verification</button>:null}</div></div></section>
 <section className="grid grid-cols-3 overflow-hidden rounded-2xl border border-white/[.06] bg-[#0F1219]"><Fact label="Starting from" value={profile.worker_price?`₦${Number(profile.worker_price).toLocaleString()}`:'Discuss'}/><Fact label="Completed" value={String(Number(trust?.completed_jobs||0))}/><Fact label="Reputation" value={Number(trust?.review_count||0)>0?`${Number(trust?.rating||0).toFixed(1)} ★`:'New'}/></section>
 <section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><Heading title="Services & specialties"/><div className="mt-3 flex flex-wrap gap-2">{skills.length?skills.map(skill=><span key={skill} className="rounded-full border border-violet-500/15 bg-violet-500/[.06] px-3 py-1.5 text-[10px] font-medium text-violet-200">{skill}</span>):<button onClick={onEdit} className="text-[10px] text-[#666D7E]">Add your service →</button>}</div>{(coverage?.areas?.length||0)>0&&<p className="mt-3 text-[10px] text-[#717888]">Also serving: {coverage?.areas?.join(' · ')}</p>}</section>
 <section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><Heading title="About" action={<button onClick={onEdit} className="text-[9px] font-semibold text-violet-300">Edit</button>}/>{cleanAbout?<><p className={`mt-3 whitespace-pre-line text-[11px] leading-5 text-[#969CAA] ${aboutOpen?'':'line-clamp-4'}`}>{cleanAbout}</p>{aboutIsLong&&<button onClick={()=>setAboutOpen(v=>!v)} className="mt-2 text-[9px] font-semibold text-violet-300">{aboutOpen?'Show less':'Read more'}</button>}</>:<button onClick={onEdit} className="mt-3 text-left text-[10px] text-[#6B7181]">Add a short introduction about your work →</button>}</section>
 <section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><div className="flex items-end justify-between gap-3"><div><Heading title="Customer reviews"/><p className="mt-1 text-[9px] text-[#666D7E]">Only completed WeHouse jobs can appear here.</p></div>{Number(trust?.review_count||0)>0&&<p className="shrink-0 text-[10px] font-semibold text-amber-300">★ {Number(trust?.rating||0).toFixed(1)} · {Number(trust?.review_count||0)}</p>}</div>{reviews.length?<div className="mt-3 divide-y divide-white/[.06] border-t border-white/[.06]">{reviews.map(review=><article key={review.id} className="py-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold">{review.reviewer_name}</p><p className="mt-1 text-[9px] text-[#686F80]">{review.service_name} · {new Date(review.created_at).toLocaleDateString()}</p></div><p className="text-[10px] font-semibold text-amber-300">{'★'.repeat(Number(review.rating))}</p></div>{review.comment&&<p className="mt-2 text-[10px] leading-5 text-[#A5AAB7]">{review.comment}</p>}</article>)}</div>:!loading?<p className="mt-4 border-t border-white/[.06] pt-4 text-[10px] text-[#73798A]">No customer reviews yet.</p>:null}</section>
 {loading&&<div className="rounded-2xl border border-dashed border-white/[.07] px-4 py-6 text-center text-[10px] text-[#666D7E]">Loading professional profile…</div>}</div>;
}
function Fact({label,value}:{label:string;value:string}){return <div className="min-w-0 border-b border-r border-white/[.05] p-3 last:border-r-0 sm:border-b-0"><p className="text-[8px] uppercase tracking-wide text-[#5F6676]">{label}</p><p className="mt-1 truncate text-[11px] font-semibold text-[#DDE0E7]">{value}</p></div>}
function Heading({title,action}:{title:string;action?:React.ReactNode}){return <div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">{title}</h3>{action}</div>}
function StatusBadge({status,live,trusted}:{status:string;live:boolean;trusted:boolean}){const label=live?(trusted?'WeHouse Trusted':'WeHouse Reviewed'):status==='profile_under_review'?'Under review':status==='rejected'?'Needs changes':'Not live yet';const cls=live?'border-emerald-500/20 bg-emerald-500/[.08] text-emerald-300':status==='rejected'?'border-red-500/20 bg-red-500/[.08] text-red-300':'border-amber-500/20 bg-amber-500/[.08] text-amber-300';return <span className={`rounded-full border px-2.5 py-1 text-[8px] font-bold ${cls}`}>{label}</span>}
function cleanWorkerBio(value:string){let text=value.trim();if(!text)return'';text=text.split(/\n\s*Services\s+Offered\s*:/i)[0].trim();const lines=text.split('\n').map(line=>line.trim()).filter(Boolean);if(lines.length>1&&/^professional\s+/i.test(lines[0])&&lines[0].length<80)lines.shift();return lines.join('\n\n')}
