import { useEffect, useMemo, useState } from 'react';
import GoldTickBadge from '@/components/GoldTickBadge';
import { supabase } from '@/lib/supabase';
import { WORKER_OCCUPATION_LABELS } from '@/types';
import type { Profile } from '@/types';

type Props={profile:Profile;onEdit:()=>void;onVerification:()=>void;onShowcase?:()=>void};
type Post={id:string;kind:'story'|'portfolio';media_type:'image'|'video';storage_path:string;caption:string|null;verified_job:boolean;expires_at:string|null;created_at:string;url?:string};
type Trust={reviewed?:boolean;trusted?:boolean;trusted_enabled?:boolean;face_check_passed?:boolean;completed_jobs?:number;rating?:number;review_count?:number;worker_cancel_rate?:number;open_disputes?:number;label?:string};

export default function WorkerProfilePanelV3({profile,onEdit,onVerification,onShowcase}:Props){
 const[coverage,setCoverage]=useState<any>(null),[posts,setPosts]=useState<Post[]>([]),[trust,setTrust]=useState<Trust|null>(null),[loading,setLoading]=useState(true),[aboutOpen,setAboutOpen]=useState(false);
 useEffect(()=>{let active=true;void(async()=>{const[cov,showcase,trustResult]=await Promise.all([supabase.from('worker_service_coverage').select('state,lga,areas').eq('worker_id',profile.user_id).maybeSingle(),supabase.from('worker_showcase_posts').select('id,kind,media_type,storage_path,caption,verified_job,expires_at,created_at').eq('worker_id',profile.user_id).is('deleted_at',null).order('created_at',{ascending:false}).limit(8),supabase.rpc('get_worker_marketplace_trust',{p_worker_id:profile.user_id})]);const enriched=await Promise.all((showcase.data||[]).map(async(row:any)=>{const{data}=await supabase.storage.from('worker-showcase').createSignedUrl(row.storage_path,3600);return{...row,url:data?.signedUrl||''} as Post}));if(active){setCoverage(cov.data||null);setPosts(enriched);setTrust((trustResult.data||null) as Trust|null);setLoading(false)}})();return()=>{active=false}},[profile.user_id]);
 const occupation=profile.worker_occupation?WORKER_OCCUPATION_LABELS[profile.worker_occupation]||profile.worker_occupation:'Service not set',skills=(profile.worker_skills as string[])||[],status=String(profile.worker_status||'pending'),live=status==='verified'&&profile.worker_verified===true,paymentConfirmedVisual=['verification_paid','profile_under_review','verified'].includes(status),location=[coverage?.lga||profile.local_government||profile.city,coverage?.state||profile.state].filter(Boolean).join(', ')||'Work location not set',cleanAbout=useMemo(()=>cleanWorkerBio(profile.worker_bio||''),[profile.worker_bio]),aboutIsLong=cleanAbout.length>320,activeStatus=posts.filter(post=>post.kind==='story'&&(!post.expires_at||new Date(post.expires_at)>new Date())),portfolio=posts.filter(post=>post.kind==='portfolio'),preview=portfolio.slice(0,4),trusted=trust?.trusted===true,facePassed=trust?.face_check_passed===true;
 return <div className="space-y-4"><section className="overflow-hidden rounded-3xl border border-white/[.07] bg-[#10131B]"><div className="h-20 bg-gradient-to-r from-violet-600/35 via-indigo-500/15 to-transparent"/><div className="px-4 pb-4 sm:px-5 sm:pb-5"><div className="-mt-9 flex items-end justify-between gap-3"><div className="grid h-[72px] w-[72px] shrink-0 place-items-center overflow-hidden rounded-2xl border-4 border-[#10131B] bg-gradient-to-br from-violet-500 to-indigo-600 text-2xl font-bold">{profile.avatar_url?<img src={profile.avatar_url} alt="" className="h-full w-full object-cover"/>:(profile.full_name||profile.username||'W')[0].toUpperCase()}</div><StatusBadge status={status} live={live} trusted={trusted}/></div><div className="mt-3"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate text-xl font-bold sm:text-2xl">{profile.full_name||profile.username||'Your professional profile'}</h2>{paymentConfirmedVisual&&<GoldTickBadge title="Gold Tick · verification payment confirmed"/>}</div><p className="mt-1 text-xs font-medium text-[#AEB3C1]">{occupation}</p><p className="mt-1 text-[10px] text-[#6F7585]">{location}</p></div><div className="mt-4 flex gap-2"><button onClick={onEdit} className="h-11 flex-1 rounded-xl bg-violet-500 px-4 text-[11px] font-semibold">Edit professional profile</button>{!live?<button onClick={onVerification} className="h-11 flex-1 rounded-xl border border-white/[.08] bg-white/[.025] px-4 text-[11px] font-semibold">Continue verification</button>:onShowcase?<button onClick={onShowcase} className="h-11 flex-1 rounded-xl border border-white/[.08] bg-white/[.025] px-4 text-[11px] font-semibold">Manage showcase</button>:null}</div></div></section>
 <section className="grid grid-cols-2 overflow-hidden rounded-2xl border border-white/[.06] bg-[#0F1219] sm:grid-cols-4"><Fact label="Starting from" value={profile.worker_price?`₦${Number(profile.worker_price).toLocaleString()}`:'Discuss'}/><Fact label="Experience" value={shortExperience(profile.worker_experience)}/><Fact label="Reputation" value={Number(profile.rating||0)>0?`${Number(profile.rating).toFixed(1)} ★`:'New'}/><Fact label="Work status" value={activeStatus.length?`${activeStatus.length} live`:'None'}/></section>
 <section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><Heading title="Skills & service"/><div className="mt-3 flex flex-wrap gap-2">{skills.length?skills.map(skill=><span key={skill} className="rounded-full border border-violet-500/15 bg-violet-500/[.06] px-3 py-1.5 text-[10px] font-medium text-violet-200">{skill}</span>):<button onClick={onEdit} className="text-[10px] text-[#666D7E]">Add your specialty →</button>}</div>{coverage?.areas?.length>0&&<p className="mt-3 text-[10px] text-[#717888]">Also serving: {coverage.areas.join(' · ')}</p>}</section>
 <section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><Heading title="About" action={<button onClick={onEdit} className="text-[9px] font-semibold text-violet-300">Edit</button>}/>{cleanAbout?<><p className={`mt-3 whitespace-pre-line text-[11px] leading-5 text-[#969CAA] ${aboutOpen?'':'line-clamp-4'}`}>{cleanAbout}</p>{aboutIsLong&&<button onClick={()=>setAboutOpen(v=>!v)} className="mt-2 text-[9px] font-semibold text-violet-300">{aboutOpen?'Show less':'Read more'}</button>}</>:<button onClick={onEdit} className="mt-3 text-left text-[10px] text-[#6B7181]">Add a short introduction about your work →</button>}</section>
 {live&&<section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><Heading title="Your work" action={onShowcase?<button onClick={onShowcase} className="text-[9px] font-semibold text-violet-300">Manage showcase</button>:undefined}/><div className="mt-1 flex gap-3 text-[9px] text-[#6C7282]"><span>{activeStatus.length} Work Status</span><span>·</span><span>{portfolio.length} Portfolio</span></div>{preview.length?<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{preview.map(post=><WorkPreview key={post.id} post={post}/>)}</div>:<button onClick={onShowcase} className="mt-3 w-full rounded-xl border border-dashed border-white/[.08] px-4 py-7 text-center text-[10px] text-[#686F7F]">Add your first Portfolio photo or video →</button>}</section>}
 {live&&<section className="rounded-2xl border border-white/[.06] bg-[#10131B] p-4"><Heading title={trusted?'WeHouse Trusted':'WeHouse Reviewed'} meta={trusted?'Earned marketplace trust':'Initial review passed'}/><p className="mt-2 text-[10px] leading-relaxed text-[#747B8B]">{trusted?'You have passed WeHouse review and earned additional trust from marketplace performance.':'Your private face check and professional work review were approved. Marketplace trust is earned later from real WeHouse performance.'}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Fact label="Face check" value={facePassed?'Completed':'Private'}/><Fact label="WeHouse jobs" value={String(trust?.completed_jobs??0)}/><Fact label="Rating" value={Number(profile.rating||0)>0?Number(profile.rating).toFixed(1):'New'}/><Fact label="Reviews" value={String(profile.review_count||0)}/></div>{!trusted&&trust?.trusted_enabled===false&&<p className="mt-3 rounded-xl bg-white/[.03] p-3 text-[9px] text-[#666D7E]">WeHouse Trusted is not enabled yet. Your Reviewed status is still your public approval status.</p>}</section>}
 {loading&&<div className="rounded-2xl border border-dashed border-white/[.07] px-4 py-6 text-center text-[10px] text-[#666D7E]">Loading professional profile…</div>}</div>;
}
function Fact({label,value}:{label:string;value:string}){return <div className="min-w-0 border-b border-r border-white/[.05] p-3 last:border-r-0 sm:border-b-0"><p className="text-[8px] uppercase tracking-wide text-[#5F6676]">{label}</p><p className="mt-1 truncate text-[11px] font-semibold text-[#DDE0E7]">{value}</p></div>}
function Heading({title,action,meta}:{title:string;action?:React.ReactNode;meta?:string}){return <div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">{title}</h3>{action||(meta?<span className="text-[9px] text-[#6A7180]">{meta}</span>:null)}</div>}
function StatusBadge({status,live,trusted}:{status:string;live:boolean;trusted:boolean}){const label=live?(trusted?'WeHouse Trusted':'WeHouse Reviewed'):status==='profile_under_review'?'Under review':status==='rejected'?'Needs changes':'Not live yet';const cls=live?'border-emerald-500/20 bg-emerald-500/[.08] text-emerald-300':status==='rejected'?'border-red-500/20 bg-red-500/[.08] text-red-300':'border-amber-500/20 bg-amber-500/[.08] text-amber-300';return <span className={`rounded-full border px-2.5 py-1 text-[8px] font-bold ${cls}`}>{label}</span>}
function WorkPreview({post}:{post:Post}){if(!post.url)return <div className="aspect-[4/3] rounded-xl bg-white/[.03]"/>;return <div className="relative overflow-hidden rounded-xl border border-white/[.05] bg-black/20">{post.media_type==='video'?<video src={post.url} muted playsInline className="aspect-[4/3] w-full object-cover"/>:<img src={post.url} alt="Portfolio work" className="aspect-[4/3] w-full object-cover"/>}{post.verified_job&&<span className="absolute left-1.5 top-1.5 rounded-full bg-emerald-500 px-1.5 py-0.5 text-[6px] font-bold text-[#04100B]">WEHOUSE JOB ✓</span>}</div>}
function cleanWorkerBio(value:string){let text=value.trim();if(!text)return'';text=text.split(/\n\s*Services\s+Offered\s*:/i)[0].trim();const lines=text.split('\n').map(line=>line.trim()).filter(Boolean);if(lines.length>1&&/^professional\s+/i.test(lines[0])&&lines[0].length<80)lines.shift();return lines.join('\n\n')}
function shortExperience(value?:string|null){const text=String(value||'').trim();if(!text)return'Not added';return text.length>28?`${text.slice(0,25).trim()}…`:text}
