import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import { WORKER_OCCUPATION_LABELS } from '@/types';
import type { Profile } from '@/types';

type Post = { id:string;kind:'story'|'portfolio';media_type:'image'|'video';storage_path:string;caption:string|null;verified_job:boolean;expires_at:string|null;created_at:string;url?:string };
type Trust = { level?:'reviewed'|'trusted'|'unavailable';identity_check_completed?:boolean;completed_jobs?:number;rating?:number;review_count?:number;worker_cancel_rate?:number;clean_record?:boolean;trusted_enabled?:boolean };
type Props={worker:Profile;onBack:()=>void;onBook:()=>void;bookingActive?:boolean;onOpenBooking?:()=>void};

export default function WorkerPublicProfileV2({worker,onBack,onBook,bookingActive=false,onOpenBooking}:Props){
 const[posts,setPosts]=useState<Post[]>([]),[viewer,setViewer]=useState<Post|null>(null),[loading,setLoading]=useState(true),[trust,setTrust]=useState<Trust|null>(null),[trustOpen,setTrustOpen]=useState(false);
 useEffect(()=>{let active=true;void(async()=>{const[{data:rows},{data:trustData}]=await Promise.all([supabase.from('worker_showcase_posts').select('id,kind,media_type,storage_path,caption,verified_job,expires_at,created_at').eq('worker_id',worker.user_id).is('deleted_at',null).order('created_at',{ascending:false}),supabase.rpc('get_worker_marketplace_trust',{p_worker_id:worker.user_id})]);const enriched=await Promise.all((rows||[]).map(async(row:any)=>{const{data}=await supabase.storage.from('worker-showcase').createSignedUrl(row.storage_path,3600);return{...row,url:data?.signedUrl||''} as Post}));if(active){setPosts(enriched);setTrust((trustData||null) as Trust|null);setLoading(false)}})();return()=>{active=false}},[worker.user_id]);
 const occupation=WORKER_OCCUPATION_LABELS[worker.worker_occupation||'']||worker.worker_occupation||'Service professional',skills=(worker.worker_skills as string[])||[],stories=posts.filter(post=>post.kind==='story'&&(!post.expires_at||new Date(post.expires_at)>new Date())),portfolio=posts.filter(post=>post.kind==='portfolio'),rating=Number(worker.rating||0)||0,reviewCount=Number(worker.review_count||0)||0,trusted=trust?.level==='trusted';
 return <div className="min-h-[100dvh] bg-[#0A0A0F] pb-24 text-white"><header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#0A0A0F]/95 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-4xl items-center gap-3"><button onClick={onBack} className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.07] bg-white/[.03]">←</button><div className="min-w-0 flex-1"><p className="text-[9px] font-bold tracking-[.18em] text-violet-300">WEHOUSE PROFESSIONAL</p><p className="truncate text-sm font-semibold">{worker.full_name||worker.username||'Professional'}</p></div><button onClick={()=>setTrustOpen(true)} className={`rounded-full border px-2.5 py-1 text-[8px] font-bold ${trusted?'border-violet-400/25 bg-violet-500/[.1] text-violet-200':'border-emerald-500/20 bg-emerald-500/[.08] text-emerald-300'}`}>{trusted?'WEHOUSE TRUSTED':'WEHOUSE REVIEWED'}</button></div></header>
 <main className="mx-auto max-w-4xl space-y-5 px-4 py-5 sm:px-5"><section className="rounded-3xl border border-violet-500/15 bg-gradient-to-br from-violet-500/[.1] via-[#111720] to-[#0D1118] p-5"><div className="flex items-start gap-4"><button type="button" onClick={()=>stories[0]&&setViewer(stories[0])} disabled={!stories.length} className={`shrink-0 rounded-[26px] ${stories.length?'bg-gradient-to-br from-violet-400 via-blue-500 to-cyan-400 p-[2px]':''}`}><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-3xl bg-gradient-to-br from-violet-500 to-blue-600 text-2xl font-bold">{worker.avatar_url?<img src={worker.avatar_url} alt="" className="h-full w-full object-cover"/>:(worker.full_name||worker.username||'W')[0].toUpperCase()}</div></button><div className="min-w-0 flex-1"><h1 className="text-xl font-bold">{worker.full_name||worker.username||'Professional'}</h1><p className="mt-1 text-xs text-[#A5ABB8]">{occupation}</p><p className="mt-1 text-[10px] text-[#72798A]">{[worker.city||worker.local_government,worker.state].filter(Boolean).join(', ')||'Location not shown'}</p><div className="mt-3 flex flex-wrap gap-2">{stories.length>0&&<span className="rounded-full bg-violet-500/10 px-2.5 py-1 text-[9px] font-semibold text-violet-300">● Work Status live</span>}{rating>0&&<span className="rounded-full bg-amber-500/10 px-2.5 py-1 text-[9px] font-semibold text-amber-300">★ {rating.toFixed(1)} · {reviewCount} review{reviewCount===1?'':'s'}</span>}{worker.worker_price&&<span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-[9px] font-semibold text-emerald-300">From ₦{Number(worker.worker_price).toLocaleString()}</span>}</div></div></div>{worker.worker_bio&&<p className="mt-4 line-clamp-5 whitespace-pre-line text-xs leading-relaxed text-[#858C9B]">{cleanBio(worker.worker_bio)}</p>}{skills.length>0&&<div className="mt-4 flex flex-wrap gap-2">{skills.map(skill=><span key={skill} className="rounded-full border border-white/[.07] px-2.5 py-1 text-[9px] text-[#A9AEBA]">{skill}</span>)}</div>}</section>
 {stories.length>0&&<section><div className="mb-2"><h2 className="text-sm font-bold">Work Status</h2><p className="mt-1 text-[9px] text-[#666D7E]">Recent work updates · available for 24 hours</p></div><div className="flex gap-3 overflow-x-auto pb-2">{stories.map(post=><button key={post.id} onClick={()=>setViewer(post)} className="w-24 shrink-0 text-left"><div className="rounded-3xl bg-gradient-to-br from-violet-300 via-blue-500 to-cyan-500 p-[2px]"><Media post={post} className="h-32 w-full rounded-[22px] bg-[#090C12] object-cover"/></div><p className="mt-1 truncate text-[9px] text-[#878D9C]">{post.caption||'Work Status'}</p></button>)}</div></section>}
 <section><div className="mb-3"><h2 className="text-sm font-bold">Portfolio</h2><p className="mt-1 text-[9px] text-[#666D7E]">Permanent examples of this professional’s work</p></div>{loading?<Empty text="Loading professional work…"/>:portfolio.length===0?<Empty text="No Portfolio work has been published yet."/>:<div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{portfolio.map(post=><button key={post.id} onClick={()=>setViewer(post)} className="relative overflow-hidden rounded-2xl border border-white/[.06] bg-[#0D1118] text-left"><Media post={post} className="aspect-[4/3] w-full object-cover"/>{post.verified_job&&<span className="absolute left-2 top-2 rounded-full bg-emerald-500 px-2 py-1 text-[7px] font-bold text-[#04100B]">WEHOUSE JOB ✓</span>}<p className="line-clamp-2 p-2 text-[9px] text-[#A0A5B2]">{post.caption||'Professional work'}</p></button>)}</div>}</section>
 <section className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-bold">Customer reputation</h2><p className="mt-1 text-[9px] text-[#666D7E]">Aggregate marketplace reputation from WeHouse records</p></div>{rating>0&&<span className="text-sm font-bold text-amber-300">★ {rating.toFixed(1)}</span>}</div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Fact label="Reviews" value={String(reviewCount)}/><Fact label="WeHouse jobs" value={String(trust?.completed_jobs??0)}/><Fact label="Identity check" value={trust?.identity_check_completed?'Completed':'Reviewed privately'}/><Fact label="Record" value={trust?.clean_record===false?'Needs attention':'Clear'}/></div>{reviewCount===0&&<p className="mt-3 text-[9px] text-[#666D7E]">Individual Worker reviews will appear after the canonical booking-review system is enabled.</p>}</section></main>
 <div className="fixed inset-x-0 bottom-0 z-40 border-t border-white/[.08] bg-[#090B12]/96 p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] backdrop-blur-xl"><div className="mx-auto max-w-4xl"><button onClick={bookingActive?onOpenBooking:onBook} className={`h-12 w-full rounded-2xl text-xs font-semibold ${bookingActive?'border border-amber-500/20 bg-amber-500/[.07] text-amber-300':'bg-violet-500 text-white'}`}>{bookingActive?'Open current booking':'Request this professional'}</button></div></div>
 {trustOpen&&<div className="fixed inset-0 z-[95] bg-black/75 p-4 backdrop-blur-sm" onClick={()=>setTrustOpen(false)}><div className="mx-auto mt-[15dvh] max-w-md rounded-3xl border border-white/[.08] bg-[#11151D] p-5" onClick={event=>event.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><p className="text-[8px] font-bold uppercase tracking-[.16em] text-violet-300">MARKETPLACE TRUST</p><h3 className="mt-2 text-lg font-bold">{trusted?'WeHouse Trusted':'WeHouse Reviewed'}</h3></div><button onClick={()=>setTrustOpen(false)} className="grid h-9 w-9 place-items-center rounded-full bg-white/[.05]">×</button></div><p className="mt-3 text-[10px] leading-relaxed text-[#7D8392]">{trusted?'This professional has passed WeHouse review and earned additional trust from marketplace performance.':'This professional passed WeHouse’s private identity/liveness and professional review before becoming public. Payment alone does not create this status.'}</p><div className="mt-4 space-y-2"><TrustRow label="Private face/liveness check" good={!!trust?.identity_check_completed}/><TrustRow label="Professional review" good/><TrustRow label={`${trust?.completed_jobs??0} completed WeHouse jobs`} good={(trust?.completed_jobs??0)>0}/>{rating>0&&<TrustRow label={`${rating.toFixed(1)} marketplace rating`} good/>}<TrustRow label="No unresolved Worker-booking dispute" good={trust?.clean_record!==false}/></div>{!trusted&&trust?.trusted_enabled===false&&<p className="mt-4 rounded-xl bg-white/[.03] p-3 text-[9px] text-[#666D7E]">WeHouse Trusted is not enabled yet. Reviewed professionals remain fully searchable and bookable.</p>}</div></div>}
 {viewer&&<div className="fixed inset-0 z-[90] bg-black/95" onClick={()=>setViewer(null)}><div className="mx-auto flex h-full max-w-lg flex-col justify-center p-4" onClick={event=>event.stopPropagation()}><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-semibold">{viewer.kind==='story'?'Work Status':'Portfolio work'}</p>{viewer.verified_job&&<p className="mt-1 text-[9px] text-emerald-300">Completed through WeHouse ✓</p>}</div><button onClick={()=>setViewer(null)} className="grid h-10 w-10 place-items-center rounded-full bg-white/10">×</button></div><Media post={viewer} className="max-h-[72dvh] w-full rounded-3xl bg-black object-contain" controls/>{viewer.caption&&<p className="mt-3 rounded-2xl bg-white/[.06] p-4 text-[11px] leading-relaxed text-[#D0D3DA]">{viewer.caption}</p>}</div></div>}
 </div>;
}
function Media({post,className,controls=false}:{post:Post;className:string;controls?:boolean}){return post.media_type==='video'?<video src={post.url} className={className} controls={controls} playsInline muted={!controls}/>:<img src={post.url} alt="Worker work" className={className}/>}
function Fact({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.05] bg-black/10 p-3"><p className="text-[8px] uppercase text-[#5F6676]">{label}</p><p className="mt-1 text-[10px] font-semibold text-[#DDE0E7]">{value}</p></div>}
function TrustRow({label,good}:{label:string;good:boolean}){return <div className="flex items-center gap-2 rounded-xl border border-white/[.05] bg-black/10 px-3 py-2.5"><span className={`grid h-5 w-5 place-items-center rounded-full text-[8px] ${good?'bg-emerald-500 text-[#03120A]':'bg-white/[.06] text-[#6D7484]'}`}>{good?'✓':'•'}</span><span className="text-[9px] text-[#A0A6B4]">{label}</span></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] px-5 py-8 text-center text-[10px] text-[#666D7E]">{text}</div>}
function cleanBio(value:string){return String(value||'').split(/\n\s*Services\s+Offered\s*:/i)[0].trim()}
