import { useEffect,useMemo,useState } from 'react';
import { toast } from 'sonner';
import { BOOKING_STATUS_LABELS,getMyBookingConversations } from '@/lib/supabase/worker-bookings';
import BookingNegotiationChat from '@/components/BookingNegotiationChat';
import type { Profile } from '@/types';

type View='all'|'attention'|'active'|'history';
const HISTORY=new Set(['approved_released','cancelled','refunded']);
const ATTENTION=new Set(['booking_requested','disputed']);
const ACTIVE=new Set(['negotiating','waiting_payment','confirmed','in_progress','completed_pending_approval']);

export default function WorkerJobsPanelV2({profile}:{profile:Profile}){
 const[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[view,setView]=useState<View>('all');
 async function load(){setLoading(true);const{conversations,error}=await getMyBookingConversations(profile.user_id);if(error)toast.error(error.message);setRows(conversations||[]);setLoading(false)}
 useEffect(()=>{void load()},[profile.user_id]);
 const counts=useMemo(()=>({all:rows.length,attention:rows.filter(row=>ATTENTION.has(row.booking_status)).length,active:rows.filter(row=>ACTIVE.has(row.booking_status)).length,history:rows.filter(row=>HISTORY.has(row.booking_status)).length}),[rows]);
 const shown=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(row=>{const inView=view==='all'||view==='attention'&&ATTENTION.has(row.booking_status)||view==='active'&&ACTIVE.has(row.booking_status)||view==='history'&&HISTORY.has(row.booking_status);if(!inView)return false;if(!q)return true;return[row.service_type,row.booking_code,row.other_person_name,row.booking_status].filter(Boolean).join(' ').toLowerCase().includes(q)}).sort((a,b)=>new Date(b.updated_at||0).getTime()-new Date(a.updated_at||0).getTime())},[rows,search,view]);
 if(selected)return <BookingNegotiationChat conversationId={selected.conversation_id} bookingId={selected.booking_id} profile={profile} isWorker onClose={()=>{setSelected(null);void load()}}/>;
 return <div className="space-y-4"><section><h2 className="text-lg font-bold">Jobs</h2><p className="mt-1 max-w-2xl text-[10px] leading-relaxed text-[#707687]">One work list from customer request to completion. Every job carries its own current status.</p></section><div className="grid grid-cols-4 gap-1 rounded-2xl border border-white/[.06] bg-[#0D1017] p-1">{([['all','All'],['attention','Attention'],['active','Active'],['history','History']] as const).map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`min-h-11 rounded-xl px-1 text-[9px] font-semibold ${view===id?'bg-violet-500 text-white':'text-[#73798A]'}`}>{label}<span className={`ml-1 ${view===id?'text-violet-100':'text-[#4F5667]'}`}>{counts[id]}</span></button>)}</div><div className="relative"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#5E6575]">⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, service or booking code" className="h-11 w-full rounded-2xl border border-white/[.07] bg-[#11151E] pl-9 pr-4 text-xs outline-none focus:border-violet-500/35"/></div>{loading?<Empty text="Loading jobs…"/>:shown.length===0?<Empty text={rows.length?'Nothing in this view.':'Customer booking requests will appear here.'}/>:<div className="space-y-2.5">{shown.map(row=><JobCard key={row.booking_id||row.conversation_id} row={row} onOpen={()=>setSelected(row)}/>)}</div>}</div>
}

function JobCard({row,onOpen}:{row:any;onOpen:()=>void}){const status=BOOKING_STATUS_LABELS[row.booking_status],amount=Number(row.negotiated_amount||0),attention=ATTENTION.has(row.booking_status);return <button onClick={onOpen} className={`w-full rounded-2xl border bg-[#10141D] p-4 text-left transition hover:border-violet-500/25 ${attention?'border-amber-500/15':'border-white/[.06]'}`}><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{row.service_type||'Service job'}</p>{Number(row.unread_count||0)>0&&<span className="rounded-full bg-violet-500 px-2 py-0.5 text-[8px] font-bold">{row.unread_count} new</span>}</div><p className="mt-1 truncate text-[10px] text-[#6D7284]">#{row.booking_code} · {row.other_person_name||'Customer'}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[8px] font-semibold ${status?.color||'bg-white/[.05] text-[#8A8F9E]'}`}>{status?.label||String(row.booking_status||'unknown').replace(/_/g,' ')}</span></div><div className="mt-3 flex items-end justify-between gap-3 border-t border-white/[.05] pt-3"><div>{amount>0&&<p className="text-xs font-semibold text-emerald-300">₦{amount.toLocaleString('en-NG')}</p>}<p className="mt-1 text-[9px] text-[#555C6D]">{workerHint(row.booking_status)}</p></div><p className="text-[9px] font-semibold text-violet-300">Open job →</p></div></button>}
function workerHint(status:string){const hints:Record<string,string>={booking_requested:'New request · respond to the customer',negotiating:'Agree the job, date and price',waiting_payment:'Waiting for customer payment',confirmed:'Paid · ready to start',in_progress:'Work in progress',completed_pending_approval:'Waiting for customer confirmation',approved_released:'Completed · earnings released',disputed:'WeHouse review in progress',cancelled:'Cancelled',refunded:'Refunded'};return hints[status]||'Open for details'}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] px-5 py-12 text-center text-[10px] text-[#666C7D]">{text}</div>}
