import { useEffect, useState } from 'react';
import GoldTickBadge from '@/components/GoldTickBadge';
import { supabase } from '@/lib/supabase';
import { WORKER_OCCUPATION_LABELS } from '@/types';
import type { Profile } from '@/types';

type Post = { id:string;kind:'story'|'portfolio';media_type:'image'|'video';storage_path:string;caption:string|null;verified_job:boolean;expires_at:string|null;created_at:string;url?:string };
type Trust = { reviewed?:boolean;trusted?:boolean;trusted_enabled?:boolean;completed_jobs?:number;rating?:number;review_count?:number;worker_cancel_rate?:number;open_disputes?:number;label?:string };
type Props={worker:Profile;onBack:()=>void;onBook:()=>void;bookingActive?:boolean;onOpenBooking?:()=>void};

export default function WorkerPublicProfileV2({worker,onBack,onBook,bookingActive=false,onOpenBooking}:Props){
 const[posts,setPosts]=useState<Post[]>([]),[viewer,setViewer]=useState<Post|null>(null),[loading,setLoading]=useState(true),[trust,setTrust]=useState<Trust|null>(null);
 useEffect(()=>{let active=true;void(async()=>{const[{data:rows},{data:trustData}]=await Promise.all([supabase.from('worker_showcase_posts').select('id,kind,media_type,storage_path,caption,verified_job,expires_at,created_at').eq('worker_id',worker.user_id).is('deleted_at',null).order('created_at',{ascending:false}),supabase.rpc('get_worker_marketplace_trust',{p_worker_id:worker.user_id})]);const enriched=await Promise.all(((rows||[]) as Post[]).map(async row=>{const{data}=await supabase.storage.from('worker-showcase').createSignedUrl(row.storage_path,3600);return{...row,url:data?.signedUrl||''} as Post}));if(active){setPosts(enriched);setTrust((trustData||null) as Trust|null);setLoading(false)}})();return()=>{active=false}},[worker.user_id]);
 const occupation=WORKER_OCCUPATION_LABELS[worker.worker_occupation||'']||worker.worker_occupation||'Service professional',skills=(worker.worker_skills as string[])||[],stories=posts.filter(post=>post.kind==='story'&&(!post.expires_at||new Date(post.expires_at)>new Date())),portfolio=posts.filter(post=>post.kind==='portfolio'),rating=Number(worker.rating||0)||0,reviewCount=Number(worker.review_count||0)||0,trusted=trust?.trusted===true;
 return <div className="min-h-[100dvh] bg-[#0A0A0F] pb-24 text-white"><header className="sticky top-0 z-30 border-b border-white/[.06] bg-[#0A0A0F]/95 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-4xl items-center gap-3"><button onClick={onBack} className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.07] bg-white/[.03]">←</button><div className="min-w-0 flex-1"><p className="text-[9px] font-bold tracking-[.18em] text-violet-300">WEHOUSE PROFESSIONAL</p><p className="truncate text-sm font-semibold">{worker.full_name||worker.username||'Professional'}</p></div><span className={`rounded-full border px-2.5 py-1 text-[8px] font-bold ${trusted?'border-violet-400/25 bg-violet-500/[.1] text-violet-200':'border-emerald-500/20 bg-emerald-500/[.08] text-emerald-300'}`}>{trusted?'WEHOUSE TRUSTED':'WEHOUSE REVIEWED'}</span></div></header>
 <main className="mx-auto max-w-4xl space-y-5 px-4 py-5 sm:px-5"><section className="rounded-3xl border border-violet-500/15 bg-gradient-to-br from-violet-500/[.1] via-[#111720] to-[#0D1118] p-5"><div className="flex items-start gap-4"><button type="button" onClick={()=>stories[0]&&setViewer(stories[0])} disabled={!stories.length} className={`shrink-0 rounded-[26px] ${stories.length?'bg-gradient-to-br from-violet-400 via-violet-500 to-cyan-400 p-[2px]':''}`}><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-3xl bg-gradient-to-br from-violet-500 to-violet-600 text-2xl font-bold">{worker.avatar_url?<img src={worker.avatar_url} alt="" className="h-full w-full object-cover"/>:(worker.full_name||worker.username||'W')[0].toUpperCase()}</div></button><div className="min-w-0 flex-1"><div className="flex min-w-0 items-center gap-2"><h1 className="truncate text-xl font-bold">{worker.full_name||worker.username||'Professional'}</h1><GoldTickBadge title="Gold Tick · verification payment confirmed"/></div><p className="mt-1 text-xs text-[#A5ABB8]">{occupation}</p><p className="mt-1 text-[10px] text-[#72798A]">{[worker.city||worker.local_government,worker.state].filter(Boolean).join(', ')||'Location not shown'}</p><div className="mt-3 flex flex-wrap gap-2">{stories.length>0&&<span className="rounded-full bg-violet-500/10 px-2.5 py-1 text-[9px] font-semibold text-violet-300">● Work Status live</span>}{rating>0&&<span className="rounded-full bg-amber-500/10 px-2.5 py-1 text-[9px] font-semibold text-amber-300">★ {rating.toFixed(1)} · {reviewCount} review{reviewCount===1?'':'s'}</span>}{worker.worker_price&&<span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-[9px] font-semibold text-emerald-300">From ₦{Number(worker.worker_price).toLocaleString()}</span>}</div></div></div>{worker.worker_bio&&<p className="mt-4 line-clamp-5 whitespace-pre-line text-xs leading-relaxed text-[#858C9B]">{cleanBio(worker.worker_bio)}</p>}{skills.length>0&&<div className="mt-4 flex flex-wrap gap-2">{skills.map(skill=><span key={skill} className="rounded-full border border-white/[.07] px-2.5 py-1 text-[9px] text-[#A9AEBA]">{skill}</span>)}</div>}</section>
 {stories.length>0&&<section><div className="mb-2"><h2 className="text-sm font-bold">Work Status</h2><p className="mt-1 text-[9px] text-[#666D7E]">Recent work updates · available for 24 hours</p></div><div className="flex gap-3 overflow-x-auto pb-2">{stories.map(post=><button key={post.id} onClick={()=>setViewer(post)} className="w-24 shrink-0 text-left"><div className="rounded-3xl bg-gradient-to-br from-violet-300 via-violet-500 to-cyan-500 p-[2px]"><Media post={post} className="h-32 w-full rounded-[22px] bg-[#090C12] object-cover"/></div><p className="mt-1 truncate text-[9px] text-[#878D9C]">{post.caption||'Work Status'}</p></button>)}</div></section>}
 <section><div className="mb-3"><h2 className="text-sm font-bold">Portfolio</h2><p className="mt-1 text-[9px] text-[#666D7E]">Permanent examples of this professional’s work</p></div>{loading?<Empty text="Loading professional work…"/>:portfolio.length===0?<Empty text="No Portfolio work has been published yet."/>:<div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{portfolio.map(post=><button key={post.id} onClick={()=>setViewer(post)} className="relative overflow-hidden rounded-2xl border border-white/[.06] bg-[#0D1118] text-left"><Media post={post} className="aspect-[4/3] w-full object-cover"/>{post.verified_job&&<span className="absolute left-2 top-2 rounded-full bg-emerald-500 px-2 py-1 text-[7px] font-bold text-[#04100B]">WEHOUSE JOB ✓</span>}<p className="line-clamp-2 p-2 text-[9px] text-[#A0A5B2]">{post.caption||'Professional work'}</p></button>)}</div>}</section>
 {(rating>0||Number(trust?.completed_jobs||0)>0)&&<section className="flex items-center gap-6 border-y border-white/[.06] py-4"><div><p className="text-lg font-bold">{rating>0?rating.toFixed(1):'New'}</p><p className="text-[9px] text-[#666D7E]">Rating · {reviewCount} reviews</p></div><div><p className="text-lg font-bold">{Number(trust?.completed_jobs||0)}</p><p className="text-[9px] text-[#666D7E]">Completed WeHouse jobs</p></div></section>}</main>
 <div className="fixed inset-x-0 bottom-0 z-40 border-t border-white/[.08] bg-[#090B12]/96 p-3 pb-[max(.75rem,env(safe-area-inset-bottom))] backdrop-blur-xl"><div className="mx-auto max-w-4xl"><button onClick={bookingActive?onOpenBooking:onBook} className={`h-12 w-full rounded-2xl text-xs font-semibold ${bookingActive?'border border-amber-500/20 bg-amber-500/[.07] text-amber-300':'bg-violet-500 text-white'}`}>{bookingActive?'Open current booking':'Request this professional'}</button></div></div>
 {viewer&&<div className="fixed inset-0 z-[90] bg-black/95" onClick={()=>setViewer(null)}><div className="mx-auto flex h-full max-w-lg flex-col justify-center p-4" onClick={event=>event.stopPropagation()}><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-semibold">{viewer.kind==='story'?'Work Status':'Portfolio work'}</p>{viewer.verified_job&&<p className="mt-1 text-[9px] text-emerald-300">Completed through WeHouse ✓</p>}</div><button onClick={()=>setViewer(null)} className="grid h-10 w-10 place-items-center rounded-full bg-white/10">×</button></div><Media post={viewer} className="max-h-[72dvh] w-full rounded-3xl bg-black object-contain" controls/>{viewer.caption&&<p className="mt-3 rounded-2xl bg-white/[.06] p-4 text-[11px] leading-relaxed text-[#D0D3DA]">{viewer.caption}</p>}</div></div>}
 </div>;
}
function Media({post,className,controls=false}:{post:Post;className:string;controls?:boolean}){return post.media_type==='video'?<video src={post.url} className={className} controls={controls} playsInline muted={!controls}/>:<img src={post.url} alt="Worker work" className={className}/>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] px-5 py-8 text-center text-[10px] text-[#666D7E]">{text}</div>}
function cleanBio(value:string){return String(value||'').split(/\n\s*Services\s+Offered\s*:/i)[0].trim()}
