import { useEffect,useState } from 'react';
import { supabase } from '@/lib/supabase';
import { WORKER_OCCUPATION_LABELS } from '@/types';
import type { Profile } from '@/types';

type Props={profile:Profile;onEdit:()=>void;onVerification:()=>void};
export default function WorkerProfilePanelV2({profile,onEdit,onVerification}:Props){
 const[coverage,setCoverage]=useState<any>(null),[reviews,setReviews]=useState<any[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;void(async()=>{const[c,r]=await Promise.all([supabase.from('worker_service_coverage').select('state,lga,areas').eq('worker_id',profile.user_id).maybeSingle(),supabase.from('reviews').select('id,rating,comment,created_at').eq('reviewee_id',profile.user_id).order('created_at',{ascending:false}).limit(10)]);if(!active)return;setCoverage(c.data||null);setReviews(r.data||[]);setLoading(false)})();return()=>{active=false}},[profile.user_id]);
 const occupation=profile.worker_occupation?WORKER_OCCUPATION_LABELS[profile.worker_occupation]||profile.worker_occupation:'Service not set';
 const skills=(profile.worker_skills as string[])||[];const average=reviews.length?reviews.reduce((sum,row)=>sum+Number(row.rating||0),0)/reviews.length:0;
 const status=String(profile.worker_status||'pending');const verified=status==='verified';
 return <div className="space-y-5">
  <section className="overflow-hidden rounded-3xl border border-cyan-500/15 bg-gradient-to-br from-cyan-500/[.12] via-[#101721] to-[#0C1118] p-5 sm:p-6 lg:p-7">
   <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-cyan-300">PUBLIC PROFESSIONAL PROFILE</p><h2 className="mt-3 text-2xl font-bold">{profile.full_name||profile.username||'Your professional profile'}</h2><p className="mt-1 text-sm font-medium text-[#B8BCC8]">{occupation}</p><p className="mt-3 max-w-2xl text-xs leading-relaxed text-[#7E8495]">{profile.worker_bio||'Add a clear description of your experience, the work you handle and what customers can expect.'}</p></div><div className="flex shrink-0 gap-2"><button onClick={onEdit} className="rounded-xl bg-cyan-500 px-4 py-3 text-xs font-semibold text-[#051018]">Edit profile</button></div></div>
   {skills.length>0&&<div className="mt-4 flex flex-wrap gap-2">{skills.map(skill=><span key={skill} className="rounded-full border border-white/[.07] bg-white/[.035] px-3 py-1.5 text-[10px] text-[#BEC2CE]">{skill}</span>)}</div>}
  </section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Service State" value={coverage?.state||profile.state||'Not set'}/><Info label="Service LGA" value={coverage?.lga||profile.local_government||profile.city||'Not set'}/><Info label="Experience" value={profile.worker_experience||'Not set'}/><Info label="Starting price" value={profile.worker_price?`₦${Number(profile.worker_price).toLocaleString()}`:'Discuss per job'}/></section>
  {coverage?.areas?.length>0&&<section className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4"><p className="text-[9px] uppercase tracking-wide text-[#636A7B]">Other service areas</p><p className="mt-2 text-xs text-[#B2B6C2]">{coverage.areas.join(' · ')}</p></section>}
  <section className={`rounded-2xl border p-4 ${verified?'border-emerald-500/20 bg-emerald-500/[.05]':'border-amber-500/20 bg-amber-500/[.05]'}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className={`text-xs font-semibold ${verified?'text-emerald-300':'text-amber-300'}`}>{verified?'Verified professional':status.replace(/_/g,' ')}</p><p className="mt-1 text-[10px] leading-relaxed text-[#7A8090]">{verified?'Your approved profile can appear in Local Services while availability is on.':'Verification controls whether your professional profile can be public and accept new customers.'}</p></div><button onClick={onVerification} className="rounded-xl border border-white/[.08] px-4 py-2.5 text-[10px] font-semibold text-white">Open verification</button></div></section>
  <section><div className="mb-3 flex items-end justify-between gap-3"><div><h3 className="text-base font-bold">Customer reputation</h3><p className="mt-1 text-[10px] text-[#666D7E]">Reviews from completed WeHouse jobs.</p></div><div className="text-right"><p className="text-xl font-bold">{reviews.length?average.toFixed(1):'—'}</p><p className="text-[9px] text-[#626879]">{reviews.length} review{reviews.length===1?'':'s'}</p></div></div>{loading?<Empty text="Loading reviews…"/>:reviews.length===0?<Empty text="Completed customers can leave reviews here."/>:<div className="space-y-3">{reviews.map(review=><article key={review.id} className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4"><p className="text-xs text-amber-300">{'★'.repeat(Math.max(0,Math.min(5,Number(review.rating||0))))}</p>{review.comment&&<p className="mt-2 text-xs leading-relaxed text-[#9B9FAC]">{review.comment}</p>}<p className="mt-2 text-[9px] text-[#555C6D]">{new Date(review.created_at).toLocaleDateString()}</p></article>)}</div>}</section>
 </div>
}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[.06] bg-[#10141D] p-4"><p className="text-[9px] uppercase tracking-wide text-[#62697A]">{label}</p><p className="mt-2 break-words text-xs font-semibold text-[#E2E4EA]">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-white/[.08] px-5 py-9 text-center text-[10px] text-[#666D7E]">{text}</div>}
