-- Explicit pre-launch reset approved on 2026-09-03.
-- Preserve accounts, roles, staff permissions, platform configuration,
-- marketplace categories, institutions, security identities and secrets.

drop function if exists public.get_waitlist_signups(text,text,text);
drop function if exists public.update_waitlist_signup(uuid,text,boolean);
drop table if exists public.waitlist_signups cascade;

truncate table
  public.listings,
  public.inspection_requests,
  public.property_submission_batches,
  public.property_submission_items,
  public.property_access_challenges,
  public.inspection_status_history,
  public.listing_image_hashes,
  public.listing_reports,
  public.saved_listings,
  public.saved_searches,
  public.hotels,
  public.hotel_rooms,
  public.hotel_inventory_daily,
  public.hotel_bookings,
  public.hotel_reviews,
  public.hotel_team_members,
  public.reservations,
  public.user_inspection_requests,
  public.reservation_refunds,
  public.rent_plans,
  public.rent_plan_contributions,
  public.rent_plan_cancellations,
  public.shared_housing_groups,
  public.shared_housing_members,
  public.roommate_matches,
  public.roommate_search_results,
  public.conversations,
  public.messages,
  public.chat_rooms,
  public.message_requests,
  public.chat_usage,
  public.chat_photo_usage,
  public.conversation_key_envelopes,
  public.partner_support_conversations,
  public.partner_support_messages,
  public.worker_bookings,
  public.booking_conversations,
  public.booking_messages,
  public.booking_payments,
  public.booking_status_history,
  public.booking_code_registry,
  public.worker_booking_reviews,
  public.worker_showcase_posts,
  public.payments,
  public.verified_paystack_references,
  public.payment_reversals,
  public.escrow_transactions,
  public.commission_ledger,
  public.property_partner_earning_releases,
  public.withdrawals,
  public.withdrawal_requests,
  public.wallet_transactions,
  public.wallet_balances,
  public.financial_audit_logs,
  public.financial_audit_log,
  public.bank_accounts,
  public.bank_account_history,
  public.reviews,
  public.staff_reviews,
  public.notifications,
  public.announcements,
  public.announcement_recipients,
  public.private_calls,
  public.private_call_signals,
  public.activity_logs,
  public.user_activity,
  public.admin_logs,
  public.admin_audit_log,
  public.audit_logs,
  public.role_change_history
restart identity cascade;

-- Wallet containers are account infrastructure, but all test balances must
-- start at zero after their transactions and earnings are removed.
update public.wallets
set available_balance=0,
    pending_balance=0,
    frozen_balance=0,
    total_withdrawn=0,
    bank_name=null,
    bank_account_number=null,
    bank_account_name=null,
    paystack_recipient_code=null,
    is_frozen=false,
    frozen_reason=null,
    frozen_by=null,
    frozen_at=null,
    updated_at=now();
